delete from public.watch_items
where lower(trim(title)) in (
  'accueil',
  'particuliers',
  'professionnels',
  'entreprises',
  'associations',
  'vie associative',
  'être informé',
  'etre informe',
  'accéder à la rubrique',
  'acceder a la rubrique',
  'actualités et communiqués',
  'actualites et communiques',
  'actualités',
  'actualites',
  'communiqués',
  'communiques',
  'agenda et événements',
  'agenda et evenements',
  'agenda',
  'événements',
  'evenements',
  'les publications',
  'publications',
  'les prises de parole',
  'prises de parole',
  'le post, la newsletter mensuelle',
  'newsletter',
  'quels sont mes droits ?',
  'quels sont mes droits',
  'achats et publicité',
  'achats et publicite',
  'banque/assurance',
  'banque assurance',
  'les pratiques numériques des français',
  'les pratiques numeriques des francais',
  'auditions devant le parlement',
  'les auditions devant le parlement'
);
