import {NextResponse} from "next/server";
import {evidenceExcerptIsGrounded,normalizeRadarText,verifyOfficialContactValues} from "@/lib/radarAudit";

export const runtime="nodejs";
export const maxDuration=30;

type Dossier={id:string;client:string;title:string;objective:string;context?:string;sector?:string|null;activity?:string|null;strategic_issues?:string[];risks_to_avoid?:string[];opportunities?:string[];client_position?:string|null;key_actors?:string[];watch_topics?:string[];watch_subtopics?:string[];reference_texts?:string[];key_deadlines?:string[]};
type WatchItem={id:string;title:string;nature:string;source_url?:string;source_name?:string|null;urgency?:string;created_at?:string;published_at?:string|null;source_text?:string};
type ActorEvidence={source_index:number;source_title:string;source_url:string;excerpt:string;confidence:number;verified:boolean};
type Actor={id:string;name:string;role:string;orbit:1|2|3;position:"favorable"|"inconnue"|"reserve"|"opposition";influence:number;why:string;window:string;action:string;certainty:"confirme"|"probable"|"a_confirmer";evidence:ActorEvidence;contact_email?:string;contact_phone?:string;contact_url?:string;contact_verified?:boolean};
type Extraction={url:string;resolved_url?:string;content:string;status:"fetched"|"unavailable"|"unsupported";read_chars:number;origin?:"live"|"stored"};
type CorpusRow={reference_id?:string;title?:string;role?:string;source_url?:string;source_text?:string;confidence?:number|string;published_at?:string|null};

const OFFICIAL_HOSTS=["assemblee-nationale.fr","senat.fr","legifrance.gouv.fr","vie-publique.fr","gouvernement.fr","elysee.fr","service-public.fr","conseil-constitutionnel.fr","conseil-etat.fr","courdecassation.fr","cnil.fr","arcep.fr","economie.gouv.fr","ecologie.gouv.fr","tresor.economie.gouv.fr","ademe.fr","eur-lex.europa.eu","europarl.europa.eu","commission.europa.eu"];
const RADAR_FORMAT={type:"json_schema",name:"myvor_radar_v3",strict:true,schema:{type:"object",additionalProperties:false,properties:{actors:{type:"array",maxItems:6,items:{type:"object",additionalProperties:false,properties:{id:{type:"string"},name:{type:"string"},role:{type:"string"},orbit:{type:"integer",enum:[1,2,3]},position:{type:"string",enum:["favorable","inconnue","reserve","opposition"]},influence:{type:"integer",minimum:1,maximum:5},why:{type:"string"},window:{type:"string"},action:{type:"string"},certainty:{type:"string",enum:["confirme","probable","a_confirmer"]},evidence:{type:"object",additionalProperties:false,properties:{source_index:{type:"integer",minimum:0,maximum:6},source_title:{type:"string"},source_url:{type:"string"},excerpt:{type:"string"},confidence:{type:"number",minimum:0,maximum:1}},required:["source_index","source_title","source_url","excerpt","confidence"]}},required:["id","name","role","orbit","position","influence","why","window","action","certainty","evidence"]}}},required:["actors"]}} as const;
const CONTACT_FORMAT={type:"json_schema",name:"myvor_radar_contacts_v3",strict:true,schema:{type:"object",additionalProperties:false,properties:{contacts:{type:"array",maxItems:3,items:{type:"object",additionalProperties:false,properties:{id:{type:"string"},email:{type:"string"},phone:{type:"string"},url:{type:"string"}},required:["id","email","phone","url"]}}},required:["contacts"]}} as const;

function asText(value:unknown){return typeof value==="string"?value.trim():"";}
function asList(value:unknown){return Array.isArray(value)?value.map(asText).filter(Boolean):[];}
function decodeHtml(value:string){return value.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">");}
function htmlToText(html:string){return decodeHtml(html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<!--([\s\S]*?)-->/g," ").replace(/<br\s*\/?>/gi,"\n").replace(/<\/p>/gi,"\n").replace(/<\/li>/gi,"\n").replace(/<\/h[1-6]>/gi,"\n").replace(/<[^>]+>/g," ").replace(/[ \t]+/g," ").replace(/\n\s*\n+/g,"\n").trim());}
function official(raw:string){try{const url=new URL(raw);const host=url.hostname.toLowerCase();return url.protocol==="https:"&&(OFFICIAL_HOSTS.some(base=>host===base||host.endsWith(`.${base}`))||host==="gouv.fr"||host.endsWith(".gouv.fr")||host==="europa.eu"||host.endsWith(".europa.eu"));}catch{return false;}}
function officialContact(raw:string){return official(raw);}
function outputText(payload:any){if(typeof payload?.output_text==="string")return payload.output_text.trim();return(payload?.output||[]).flatMap((item:any)=>item?.content||[]).filter((part:any)=>part?.type==="output_text").map((part:any)=>part?.text||"").join("").trim();}
function comparable(value:unknown){return normalizeRadarText(value).replace(/[^a-z0-9]+/g," ").trim();}
function urgency(value:unknown){const key=asText(value).toLowerCase();return key==="absolument urgent"?4:key==="fort"?3:key==="moyen"?2:1;}
function validEmail(value:unknown){const valueText=asText(value);return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(valueText)?valueText:"";}
function validPhone(value:unknown){const valueText=asText(value).replace(/[^+0-9(). -]/g,"").trim();return valueText.replace(/\D/g,"").length>=8?valueText:"";}
function supabaseConfig(){return{url:(process.env.NEXT_PUBLIC_SUPABASE_URL||"").replace(/\/$/,""),key:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||""};}

async function verifySession(request:Request){const authorization=request.headers.get("authorization")||"";if(!authorization.toLowerCase().startsWith("bearer "))return false;const{url,key}=supabaseConfig();if(!url||!key)return false;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),3200);try{const response=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:authorization},signal:controller.signal,cache:"no-store"});return response.ok;}catch{return false;}finally{clearTimeout(timer);}}
async function fetchText(rawUrl:string,maxChars:number,contact=false):Promise<Extraction>{const allowed=contact?officialContact:official;if(!rawUrl||!allowed(rawUrl))return{url:rawUrl,content:"",status:"unsupported",read_chars:0};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4500);try{const response=await fetch(rawUrl,{headers:{"User-Agent":"Mozilla/5.0 (compatible; Myvor/3.2; +https://myvor.app)","Accept":"text/html,text/plain;q=0.9,*/*;q=0.4","Accept-Language":"fr-FR,fr;q=0.9,en;q=0.6"},redirect:"follow",cache:"no-store",signal:controller.signal});if(!response.ok)return{url:rawUrl,resolved_url:response.url||rawUrl,content:"",status:"unavailable",read_chars:0};const resolved=response.url||rawUrl;if(!allowed(resolved))return{url:rawUrl,resolved_url:resolved,content:"",status:"unsupported",read_chars:0};const contentType=(response.headers.get("content-type")||"").toLowerCase();if(!contentType.includes("text/html")&&!contentType.includes("text/plain"))return{url:rawUrl,resolved_url:resolved,content:"",status:"unsupported",read_chars:0};const raw=(await response.text()).slice(0,1_000_000);const content=(contentType.includes("text/html")?htmlToText(raw):raw.trim()).slice(0,maxChars);return{url:rawUrl,resolved_url:resolved,content,status:content?"fetched":"unavailable",read_chars:content.length,origin:"live"};}catch{return{url:rawUrl,content:"",status:"unavailable",read_chars:0};}finally{clearTimeout(timer);}}
async function fetchCorpusEvidence(request:Request,dossierId:string):Promise<WatchItem[]>{const authorization=request.headers.get("authorization")||"";const{url,key}=supabaseConfig();if(!authorization||!url||!key)return[];const query=new URLSearchParams({select:"reference_id,title,role,source_url,source_text,confidence,published_at",dossier_id:`eq.${dossierId}`,order:"confidence.desc",limit:"12"});const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),3500);try{const response=await fetch(`${url}/rest/v1/dossier_corpus?${query.toString()}`,{headers:{apikey:key,Authorization:authorization},cache:"no-store",signal:controller.signal});if(!response.ok)return[];const rows=(await response.json().catch(()=>[])) as CorpusRow[];return rows.map((row,index)=>({id:`corpus:${asText(row.reference_id)||index}`,title:asText(row.title),nature:asText(row.role)||"Corpus applicable",source_url:asText(row.source_url),source_name:"Corpus juridique Myvor",urgency:"faible",published_at:asText(row.published_at)||null,source_text:asText(row.source_text).slice(0,16000)})).filter(item=>Boolean(item.title&&item.source_url&&official(item.source_url)));}catch{return[];}finally{clearTimeout(timer);}}
function actorEvidencePriority(item:WatchItem){const url=asText(item.source_url);let host="";try{host=new URL(url).hostname.toLowerCase();}catch{}let score=0;if(/senat\.fr|assemblee-nationale\.fr/.test(host))score+=120;else if(/ecologie\.gouv\.fr|economie\.gouv\.fr|ademe\.fr|gouvernement\.fr/.test(host))score+=110;else if(/commission\.europa\.eu|europarl\.europa\.eu/.test(host))score+=100;else if(/eur-lex\.europa\.eu/.test(host))score+=80;else if(/legifrance\.gouv\.fr/.test(host))score+=50;if(asText(item.source_text).length>500)score+=30;return score;}
function mergeEvidenceItems(incoming:WatchItem[],corpus:WatchItem[],limit:number){const merged=new Map<string,WatchItem>();const add=(item:WatchItem)=>{const key=asText(item.source_url)||comparable(item.title);if(!key)return;const existing=merged.get(key);if(existing){merged.set(key,{...item,...existing,source_text:asText(existing.source_text)||asText(item.source_text),source_name:asText(existing.source_name)||asText(item.source_name)});return;}merged.set(key,item);};incoming.forEach(add);[...corpus].sort((a,b)=>actorEvidencePriority(b)-actorEvidencePriority(a)).forEach(add);const primary=[...incoming].map(item=>asText(item.source_url)||comparable(item.title));const all=[...merged.entries()];all.sort((a,b)=>{const ai=primary.indexOf(a[0]),bi=primary.indexOf(b[0]);if(ai>=0&&bi>=0)return ai-bi;if(ai>=0)return-1;if(bi>=0)return 1;return actorEvidencePriority(b[1])-actorEvidencePriority(a[1]);});const primaryCount=Math.min(3,primary.length);const selected=all.slice(0,primaryCount);for(const entry of all){if(selected.some(([key])=>key===entry[0]))continue;selected.push(entry);if(selected.length>=limit)break;}return selected.map(([,item])=>item).slice(0,limit);}
async function extractionForItem(item:WatchItem,maxChars:number):Promise<Extraction>{const stored=asText(item.source_text);if(stored.length>=180&&official(asText(item.source_url)))return{url:asText(item.source_url),resolved_url:asText(item.source_url),content:stored.slice(0,maxChars),status:"fetched",read_chars:Math.min(stored.length,maxChars),origin:"stored"};return fetchText(asText(item.source_url),maxChars);}
function dossierProfile(dossier:Dossier){return[["Secteur",asText(dossier.sector)],["Activité",asText(dossier.activity)],["Enjeux stratégiques",asList(dossier.strategic_issues).join(" ; ")],["Risques à éviter",asList(dossier.risks_to_avoid).join(" ; ")],["Opportunités",asList(dossier.opportunities).join(" ; ")],["Position client",asText(dossier.client_position)],["Acteurs suivis",asList(dossier.key_actors).join(" ; ")],["Thèmes de veille",[...asList(dossier.watch_topics),...asList(dossier.watch_subtopics)].join(" ; ")],["Textes de référence",asList(dossier.reference_texts).join(" ; ")],["Échéances",asList(dossier.key_deadlines).join(" ; ")]].filter(([,value])=>value).map(([label,value])=>`${label} : ${value}`).join("\n").slice(0,3600);}
function normalizeActor(raw:any,index:number):Actor{return{id:asText(raw?.id)||`actor-${index+1}`,name:asText(raw?.name),role:asText(raw?.role),orbit:[1,2,3].includes(Number(raw?.orbit))?Number(raw.orbit) as 1|2|3:3,position:["favorable","inconnue","reserve","opposition"].includes(raw?.position)?raw.position:"inconnue",influence:Math.max(1,Math.min(5,Math.round(Number(raw?.influence)||1))),why:asText(raw?.why),window:asText(raw?.window),action:asText(raw?.action),certainty:["confirme","probable","a_confirmer"].includes(raw?.certainty)?raw.certainty:"a_confirmer",evidence:{source_index:Math.max(0,Math.min(6,Math.round(Number(raw?.evidence?.source_index)||0))),source_title:asText(raw?.evidence?.source_title),source_url:asText(raw?.evidence?.source_url),excerpt:asText(raw?.evidence?.excerpt).slice(0,300),confidence:Math.max(0,Math.min(1,Number(raw?.evidence?.confidence)||0)),verified:false}};}
function mentioned(actor:Actor,content:string){const source=normalizeRadarText(content);return[actor.name,actor.role].map(normalizeRadarText).filter(value=>value.length>=8).some(value=>source.includes(value));}
function ground(actor:Actor,items:WatchItem[],byUrl:Map<string,Extraction>):Actor|null{const index=actor.evidence.source_index;const item=index>=1&&index<=items.length?items[index-1]:null;const source=item?.source_url?byUrl.get(item.source_url):undefined;if(!item||!source||source.status!=="fetched"||!evidenceExcerptIsGrounded(source.content,actor.evidence.excerpt)||!mentioned(actor,source.content))return null;return{...actor,evidence:{...actor.evidence,source_index:index,source_title:item.title,source_url:item.source_url||"",verified:true}};}
function cleanActors(actors:Actor[],client:string){const seen=new Set<string>();const clientKey=comparable(client);return actors.filter(actor=>{const key=comparable(actor.name);if(!key||key===clientKey||seen.has(key))return false;seen.add(key);return true;});}

async function callRadarModel(apiKey:string,model:string,prompt:string,maxTokens:number,timeoutMs:number){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:prompt,text:{format:RADAR_FORMAT},max_output_tokens:maxTokens,store:false}),signal:controller.signal});const raw=await response.text();let payload:any=null;try{payload=raw?JSON.parse(raw):null;}catch{}if(!response.ok){const error:any=new Error(payload?.error?.message||`Le moteur Radar a échoué (${response.status}).`);error.status=response.status;throw error;}const output=outputText(payload);if(!output)throw new Error("Le moteur Radar n’a retourné aucun résultat.");try{return JSON.parse(output);}catch{throw new Error("Le moteur Radar a retourné une réponse invalide.");}}finally{clearTimeout(timer);}}
async function enrichContacts(apiKey:string,model:string,actors:Actor[]){const targets=actors.filter(actor=>(actor.influence>=4||actor.orbit===1)&&actor.certainty!=="a_confirmer").slice(0,3);if(!targets.length)return actors;const prompt=`Recherche uniquement des coordonnées professionnelles publiques pour ces acteurs :\n${targets.map(actor=>`${actor.id} | ${actor.name} | ${actor.role}`).join("\n")}\nUtilise uniquement une page institutionnelle officielle. Ne déduis jamais un e-mail ou un téléphone. Si rien n'est publié, laisse les champs vides.`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),4200);try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:prompt,tools:[{type:"web_search"}],text:{format:CONTACT_FORMAT},max_output_tokens:700,store:false}),signal:controller.signal});if(!response.ok)return actors;const payload=await response.json();const output=outputText(payload);if(!output)return actors;let parsed:any=null;try{parsed=JSON.parse(output);}catch{return actors;}const contacts=Array.isArray(parsed?.contacts)?parsed.contacts:[];const verified=new Map<string,{email:string;phone:string;url:string}>();await Promise.all(contacts.map(async(raw:any)=>{const id=asText(raw?.id),url=asText(raw?.url);if(!id||!targets.some(actor=>actor.id===id)||!url||!officialContact(url))return;const page=await fetchText(url,14000,true);if(page.status!=="fetched")return;const values=verifyOfficialContactValues(page.content,validEmail(raw?.email),validPhone(raw?.phone));verified.set(id,{email:validEmail(values.email),phone:validPhone(values.phone),url:page.resolved_url||url});}));return actors.map(actor=>{const contact=verified.get(actor.id);return contact?{...actor,contact_email:contact.email||undefined,contact_phone:contact.phone||undefined,contact_url:contact.url,contact_verified:true}:actor;});}catch{return actors;}finally{clearTimeout(timer);}}

export async function POST(request:Request){
  try{
    if(!(await verifySession(request)))return NextResponse.json({error:"Session Myvor requise."},{status:401});
    const body=await request.json().catch(()=>null);const dossier:Dossier|null=body?.dossier||null;const incoming:WatchItem[]=Array.isArray(body?.items)?body.items:[];
    if(!dossier)return NextResponse.json({error:"Sélectionne un dossier client."},{status:400});if(!incoming.length)return NextResponse.json({error:"Aucun texte n’est rattaché à ce dossier."},{status:400});
    const apiKey=asText(process.env.OPENAI_API_KEY);if(!apiKey)return NextResponse.json({error:"Moteur Radar non configuré."},{status:503});const model=asText(process.env.OPENAI_RADAR_MODEL)||"gpt-4.1-mini";
    const actorLimit=incoming.length<=1?4:incoming.length===2?5:6;const corpus=await fetchCorpusEvidence(request,dossier.id);const items=mergeEvidenceItems(incoming,corpus,Math.min(6,Math.max(3,incoming.length+3)));const extractions=await Promise.all(items.map(item=>extractionForItem(item,6000)));const byUrl=new Map(extractions.map(source=>[source.url,source]));
    const sourceText=items.map((item,index)=>{const source=item.source_url?byUrl.get(item.source_url):undefined;return[`SOURCE ${index+1}`,`Titre : ${item.title}`,`Nature : ${item.nature}`,`Urgence : ${item.urgency||"non renseignée"}`,item.source_name?`Origine : ${item.source_name}`:"",item.source_url?`URL officielle : ${item.source_url}`:"",source?.status==="fetched"?`CONTENU OFFICIEL :\n${source.content}`:""].filter(Boolean).join("\n");}).join("\n\n====================\n\n");
    const basePrompt=`MYVOR — Radar d'influence professionnel, prudent et vérifiable.\nCLIENT : ${dossier.client}\nDOSSIER : ${dossier.title}\nOBJECTIF CLIENT : ${dossier.objective}\nCONTEXTE : ${asText(dossier.context).slice(0,1500)}\n${dossierProfile(dossier)?`MÉMOIRE STRATÉGIQUE (contexte uniquement, jamais preuve) :\n${dossierProfile(dossier)}\n`:""}\nSOURCES OFFICIELLES :\n${sourceText}\n\nRÈGLES : le client n'est jamais un acteur ; n'invente aucun nom, rôle, position, déclaration ou relation ; privilégie les institutions, autorités, commissions, rapporteurs, responsables publics et organismes explicitement nommés dans les sources ; chaque acteur doit être réellement nommé dans une source fournie ; cite un extrait exact de 18 à 240 caractères et son numéro de source ; la position par rapport à l'objectif client reste inconnue si elle n'est pas explicitement établie ; la mémoire dossier ne constitue jamais une preuve. Maximum ${actorLimit} acteurs. Retourne uniquement le JSON du schéma.`;
    let parsed:any;let continuity=false;
    try{parsed=await callRadarModel(apiKey,model,basePrompt,1500,12000);}catch(error:any){const transient=error?.name==="AbortError"||Number(error?.status)>=500||Number(error?.status)===429||String(error?.message||"").toLowerCase().includes("fetch");if(!transient)throw error;continuity=true;const compactSources=items.map((item,index)=>{const source=item.source_url?byUrl.get(item.source_url):undefined;return`SOURCE ${index+1} — ${item.title}\n${source?.content.slice(0,2400)||""}`;}).join("\n\n");const compactPrompt=`MYVOR Radar d'influence — mode rapide. CLIENT : ${dossier.client}. DOSSIER : ${dossier.title}. OBJECTIF : ${dossier.objective}.\n${compactSources}\nIdentifie au maximum 3 acteurs institutionnels ou publics réellement nommés. Pour chacun, copie un extrait exact de 18 à 180 caractères de la source numérotée. N'invente rien. Retourne uniquement le JSON du schéma.`;parsed=await callRadarModel(apiKey,model,compactPrompt,900,6500);}
    const grounded:Actor[]=(Array.isArray(parsed?.actors)?parsed.actors:[]).slice(0,actorLimit).map((raw:any,index:number)=>normalizeActor(raw,index)).map((actor:Actor)=>ground(actor,items,byUrl)).filter((actor:Actor|null):actor is Actor=>Boolean(actor));const relevant=cleanActors(grounded,dossier.client);if(!relevant.length){const fetchedSources=extractions.filter(source=>source.status==="fetched").length;return NextResponse.json({error:fetchedSources?"Aucun acteur clairement nommé n’a été identifié dans le corpus officiel de ce dossier.":"Myvor n’a pas pu lire le corpus officiel lié à ce dossier. Vérifie le dossier ou relance le Radar."},{status:422});}const actors=continuity?relevant:await enrichContacts(apiKey,model,relevant);const verifiedContacts=actors.filter(actor=>actor.contact_verified).length;const fetchedSources=extractions.filter(source=>source.status==="fetched").length;
    return NextResponse.json({actors,engine:continuity?"openai-radar-grounded-v4-corpus-fast":"openai-radar-grounded-v4-corpus",model,quality:{status:"grounded",client_excluded:true,generic_unsubstantiated_filtered:true,structured_output:true,grounded_actors:actors.length,total_actors:actors.length,grounding_rate:1,official_contact_lookup:!continuity,verified_contact_pages:verifiedContacts,canonical_corpus_used:corpus.length>0},grounding:{official_sources_requested:items.length,official_sources_fetched:fetchedSources,max_official_sources:6,statuses:extractions.map(source=>({url:source.url,resolved_url:source.resolved_url||source.url,status:source.status,read_chars:source.read_chars,origin:source.origin||"live"}))}});
  }catch(error:any){if(error?.name==="AbortError")return NextResponse.json({error:"Le Radar n’a pas pu terminer cette analyse."},{status:504});return NextResponse.json({error:error?.message||"Impossible de générer le Radar d’influence."},{status:502});}
}
