import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";
const PATH="/functions/v1/legal-catalog-fr-backfill",DILA="https://echanges.dila.gouv.fr/OPENDATA/JORFSIMPLE/";const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const MAX_GZ=6500000,MAX_TAR=65000000,MAX_XML=1000000,MAX_TEXT=40000;
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H});}function clip(x:unknown,n:number){return String(x??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g,"").slice(0,n).trim();}
function key(){const m=Deno.env.get("SUPABASE_SECRET_KEYS");if(m){try{const o=JSON.parse(m),v=o?.default||Object.values(o||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function auth(req:Request,s:any){const ts=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const{data,error}=await s.rpc("verify_veille_internal_request",{p_path:PATH,p_timestamp:Number(ts),p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function ent(x:string){const map:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",laquo:"«",raquo:"»",eacute:"é",egrave:"è",ecirc:"ê",agrave:"à",ccedil:"ç",ocirc:"ô",ugrave:"ù"};return x.replace(/&#(x[0-9a-f]+|\d+);?/gi,(_,r)=>{const n=String(r).toLowerCase().startsWith("x")?parseInt(String(r).slice(1),16):parseInt(String(r),10);try{return Number.isFinite(n)?String.fromCodePoint(n):_;}catch{return _;}}).replace(/&([a-z][a-z0-9]+);/gi,(a,n)=>map[String(n).toLowerCase()]??a);}
function clean(x:string,max=MAX_TEXT){return clip(ent(x.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]+>/g," ")).replace(/\s+/g," "),max);}function tag(xml:string,name:string){const m=xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,`i`));return clean(m?.[1]||"",1200);}function decode(b:Uint8Array){let x=new TextDecoder("utf-8").decode(b);if(x.includes("�")){const y=new TextDecoder("windows-1252").decode(b);if((y.match(/�/g)||[]).length<(x.match(/�/g)||[]).length)x=y;}return x;}
function nature(raw:string,title:string){const x=`${raw} ${title}`.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();if(/ORDONNANCE/.test(x))return"Ordonnance";if(/DECRET/.test(x))return"Décret";if(/ARRETE/.test(x))return"Arrêté";if(/\bLOI\b/.test(x))return"Loi";if(/DECISION|DELIBERATION/.test(x))return"Décision / jurisprudence";if(/CIRCULAIRE|INSTRUCTION/.test(x))return"Circulaire / instruction";if(/\bAVIS\b/.test(x))return"Avis";return"Texte réglementaire";}
async function html(url:string){const c=new AbortController(),tm=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{signal:c.signal,redirect:"error",headers:{"User-Agent":"Myvor-Legal-Catalog/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text();}finally{clearTimeout(tm);}}async function bytes(url:string){const c=new AbortController(),tm=setTimeout(()=>c.abort(),25000);try{const r=await fetch(url,{signal:c.signal,redirect:"error",headers:{"User-Agent":"Myvor-Legal-Catalog/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=new Uint8Array(await r.arrayBuffer());if(b.length>MAX_GZ)throw new Error("archive too large");return b;}finally{clearTimeout(tm);}}
async function gunzip(b:Uint8Array){const reader=new Blob([b]).stream().pipeThrough(new DecompressionStream("gzip")).getReader(),chunks:Uint8Array[]=[];let total=0;try{for(;;){const{value,done}=await reader.read();if(done)break;if(!value)continue;total+=value.length;if(total>MAX_TAR){await reader.cancel();throw new Error("tar too large");}chunks.push(value);}}finally{reader.releaseLock();}const o=new Uint8Array(total);let p=0;for(const c of chunks){o.set(c,p);p+=c.length;}return o;}
function parseTar(tar:Uint8Array){const dec=new TextDecoder("utf-8"),items:any[]=[];let p=0,guard=0;while(p+512<=tar.length&&guard++<30000){const h=tar.subarray(p,p+512);if(h.every(x=>x===0))break;const size=parseInt(dec.decode(h.subarray(124,136)).replace(/\0/g,"").trim()||"0",8),type=h[156],start=p+512,end=start+size;if(!Number.isFinite(size)||size<0||end>tar.length)break;if((type===0||type===48)&&size>20&&size<=MAX_XML){const xml=decode(tar.subarray(start,end)),id=xml.match(/<ID(?:\s[^>]*)?>\s*(JORFTEXT\d+)\s*<\/ID>/i)?.[1];if(id){const title=tag(xml,"TITREFULL")||tag(xml,"TITRE"),text=clean(xml);if(title.length>=5&&text.length>=80&&text.includes(id))items.push({document_id:id,title:clip(title,900),nature:nature(tag(xml,"NATURE"),title),source_url:`https://www.legifrance.gouv.fr/jorf/id/${id}`,source_name:"DILA / Légifrance",published_at:tag(xml,"DATE_PUBLI")||tag(xml,"DATE_PUBLICATION")||null,source_text:text,source_text_chars:text.length});}}p=start+Math.ceil(size/512)*512;}return items;}
function ymd(d:Date){return`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,"0")}${String(d.getUTCDate()).padStart(2,"0")}`;}function iso(d:Date){return d.toISOString().slice(0,10);}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=key();if(!url||!secret)return out({error:"Configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await auth(req,s))return out({error:"Non autorisé"},401);const body=await req.json().catch(()=>({})),start=new Date(String(body?.start_date||"")),end=new Date(String(body?.end_date||body?.start_date||""));if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||end<start)return out({error:"Dates invalides"},400);const days=Math.floor((end.getTime()-start.getTime())/86400000)+1;if(days>31)return out({error:"Maximum 31 jours"},400);const index=await html(`${DILA}?C=M;O=D`),errors:string[]=[],missing:string[]=[];let parsed=0,upserted=0,archives=0;for(let t=start.getTime();t<=end.getTime();t+=86400000){const d=new Date(t),keyDay=ymd(d),names=[...index.matchAll(new RegExp(`href=["'](JORFSIMPLE_${keyDay}-\\d{6}\\.tar\\.gz)["']`,`gi`))].map(m=>m[1]).slice(0,4);if(!names.length){missing.push(iso(d));continue;}for(const name of names){archives++;try{const items=parseTar(await gunzip(await bytes(DILA+name)));parsed+=items.length;if(items.length){const{data,error}=await s.from("legal_catalog_fr").upsert(items,{onConflict:"document_id"}).select("document_id");if(error)throw error;upserted+=(data||[]).length;}}catch(e:any){errors.push(`${name}:${clip(e?.message||e,140)}`);}}}return out({ok:true,engine:"legal-catalog-fr-backfill-v1",start_date:iso(start),end_date:iso(end),days,archives,parsed,upserted,missing_days:missing,errors});});