import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";

type SourceItem={document_id:string;title:string;nature:string;source_url:string;source_name:string;published_at?:string;source_text:string};
type Diag={name:string;compressed_bytes?:number;tar_bytes?:number;regular_files?:number;jorf_candidates?:number;parsed?:number;error?:string};
const PATH="/functions/v1/sync-watch-catalog";
const DILA="https://echanges.dila.gouv.fr/OPENDATA/JORFSIMPLE/";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const MAX_TEXT=40000,MAX_GZ=6000000,MAX_TAR=64000000,MAX_XML=1000000;
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H});}
function clip(x:unknown,n:number){return String(x??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g,"").slice(0,n).trim();}
function key(){const m=Deno.env.get("SUPABASE_SECRET_KEYS");if(m){try{const o=JSON.parse(m),v=o?.default||Object.values(o||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function auth(req:Request,s:any){const ts0=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts0)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const ts=Number(ts0);if(Math.abs(Math.floor(Date.now()/1000)-ts)>120)return false;const{data,error}=await s.rpc("verify_veille_internal_request",{p_path:PATH,p_timestamp:ts,p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function entities(x:string){const m:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",laquo:"«",raquo:"»",eacute:"é",egrave:"è",ecirc:"ê",agrave:"à",ccedil:"ç",ocirc:"ô",ugrave:"ù"};return x.replace(/&#(x[0-9a-f]+|\d+);?/gi,(_,r)=>{const n=String(r).toLowerCase().startsWith("x")?parseInt(String(r).slice(1),16):parseInt(String(r),10);try{return Number.isFinite(n)?String.fromCodePoint(n):_;}catch{return _;}}).replace(/&([a-z][a-z0-9]+);/gi,(a,n)=>m[String(n).toLowerCase()]??a);}
function clean(x:string){return entities(x.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim();}
function tag(xml:string,name:string){const m=xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,`i`));return clean(m?.[1]||"");}
function decode(b:Uint8Array){let x=new TextDecoder("utf-8").decode(b);if(x.includes("�")){const y=new TextDecoder("windows-1252").decode(b);if((y.match(/�/g)||[]).length<(x.match(/�/g)||[]).length)x=y;}return x;}
function nature(raw:string,title:string){const x=`${raw} ${title}`.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase();if(/ORDONNANCE/.test(x))return"Ordonnance";if(/DECRET/.test(x))return"Décret";if(/ARRETE/.test(x))return"Arrêté";if(/\bLOI\b/.test(x))return"Loi";if(/DECISION|DELIBERATION/.test(x))return"Décision / jurisprudence";if(/CIRCULAIRE|INSTRUCTION/.test(x))return"Circulaire / instruction";if(/\bAVIS\b/.test(x))return"Avis";return"Texte réglementaire";}
function safeDate(raw?:string){if(!raw)return null;const t=Date.parse(raw);return Number.isFinite(t)&&t<=Date.now()+36*3600000?new Date(t).toISOString():null;}
async function text(url:string,timeout=15000){const u=new URL(url);if(u.protocol!=="https:"||u.hostname!=="echanges.dila.gouv.fr")throw new Error("Hôte DILA refusé");const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(u,{redirect:"error",signal:c.signal,headers:{"User-Agent":"Myvor-DILA-Catalog/3.2","Accept":"text/html,*/*"}});if(!r.ok)throw new Error(`DILA HTTP ${r.status}`);const x=await r.text();if(x.length>2000000)throw new Error("Index DILA trop volumineux");return x;}finally{clearTimeout(timer);}}
async function bytes(url:string,timeout=25000){const u=new URL(url);if(u.protocol!=="https:"||u.hostname!=="echanges.dila.gouv.fr")throw new Error("Hôte DILA refusé");const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(u,{redirect:"error",signal:c.signal,headers:{"User-Agent":"Myvor-DILA-Catalog/3.2","Accept":"application/gzip,application/octet-stream,*/*"}});if(!r.ok)throw new Error(`DILA HTTP ${r.status}`);const announced=Number(r.headers.get("content-length")||0);if(announced>MAX_GZ)throw new Error("Archive DILA trop volumineuse");const b=new Uint8Array(await r.arrayBuffer());if(b.length>MAX_GZ)throw new Error("Archive DILA trop volumineuse");return b;}finally{clearTimeout(timer);}}
async function gunzip(b:Uint8Array){const reader=new Blob([b]).stream().pipeThrough(new DecompressionStream("gzip")).getReader(),chunks:Uint8Array[]=[];let total=0;try{for(;;){const{value,done}=await reader.read();if(done)break;if(!value)continue;total+=value.length;if(total>MAX_TAR){await reader.cancel();throw new Error("Archive DILA décompressée trop volumineuse");}chunks.push(value);}}finally{reader.releaseLock();}const result=new Uint8Array(total);let p=0;for(const c of chunks){result.set(c,p);p+=c.length;}return result;}
function tarFiles(b:Uint8Array){const files:Uint8Array[]=[],dec=new TextDecoder("utf-8");let p=0,guard=0,regular=0;while(p+512<=b.length&&guard++<30000){const h=b.subarray(p,p+512);if(h.every(x=>x===0))break;const size=parseInt(dec.decode(h.subarray(124,136)).replace(/\0/g,"").trim()||"0",8),type=h[156],start=p+512,end=start+size;if(!Number.isFinite(size)||size<0||end>b.length)break;if(type===0||type===48){regular++;if(size>20&&size<=MAX_XML){const f=b.subarray(start,end),prefix=dec.decode(f.subarray(0,Math.min(f.length,8192)));if(/<ID(?:\s[^>]*)?>\s*JORFTEXT\d+\s*<\/ID>/i.test(prefix))files.push(f);}}p=start+Math.ceil(size/512)*512;}return{files,regular};}
function parseXml(b:Uint8Array):SourceItem|null{const xml=decode(b);const id=xml.match(/<ID(?:\s[^>]*)?>\s*(JORFTEXT\d+)\s*<\/ID>/i)?.[1]||"";if(!id)return null;let title=tag(xml,"TITREFULL")||tag(xml,"TITRE");if(!title)title=[tag(xml,"NATURE"),tag(xml,"NOR")].filter(Boolean).join(" ");if(title.length<5)return null;const body=clean(xml).slice(0,MAX_TEXT);if(body.length<80||!body.includes(id))return null;return{document_id:id,title:clip(title,800),nature:nature(tag(xml,"NATURE"),title),source_url:`https://www.legifrance.gouv.fr/jorf/id/${id}`,source_name:"Légifrance — Journal officiel",published_at:tag(xml,"DATE_PUBLI")||tag(xml,"DATE_PUBLICATION")||undefined,source_text:body};}
async function collect(){const index=await text(`${DILA}?C=M;O=D`),names:string[]=[];for(const m of index.matchAll(/href=["'](JORFSIMPLE_(20\d{6})-\d{6}\.tar\.gz)["']/gi)){if(!names.includes(m[1]))names.push(m[1]);if(names.length===4)break;}if(!names.length)throw new Error("Aucune archive DILA détectée");const map=new Map<string,SourceItem>(),diag:Diag[]=[];for(const name of names){const d:Diag={name};diag.push(d);try{const gz=await bytes(DILA+name);d.compressed_bytes=gz.length;const tar=await gunzip(gz);d.tar_bytes=tar.length;const tf=tarFiles(tar);d.regular_files=tf.regular;d.jorf_candidates=tf.files.length;let parsed=0;for(const f of tf.files){const it=parseXml(f);if(!it)continue;const old=map.get(it.source_url);if(!old||it.source_text.length>old.source_text.length)map.set(it.source_url,it);parsed++;}d.parsed=parsed;}catch(e:any){d.error=clip(e?.message||e,180);}}return{items:[...map.values()].sort((a,b)=>(Date.parse(b.published_at||"")||0)-(Date.parse(a.published_at||"")||0)).slice(0,500),diag};}
async function targets(s:any){const{data,error}=await s.rpc("get_veille_ingestion_targets");if(error)throw error;return data||[];}
async function storeCanonicalCatalog(s:any,items:SourceItem[]){let upserted=0;const now=new Date().toISOString();for(let p=0;p<items.length;p+=100){const batch=items.slice(p,p+100);const rows=batch.map(i=>({document_id:i.document_id,title:i.title,nature:i.nature,source_url:i.source_url,source_name:"DILA / Légifrance",published_at:safeDate(i.published_at),source_text:i.source_text,source_text_chars:i.source_text.length,updated_at:now}));const{data,error}=await s.from("legal_catalog_fr").upsert(rows,{onConflict:"document_id"}).select("document_id");if(error)throw error;upserted+=(data||[]).length;}return upserted;}
async function store(s:any,items:SourceItem[]){const catalogUpserts=await storeCanonicalCatalog(s,items);const ts=await targets(s);let inserted=0,contentUpserts=0;const details:any[]=[];for(const target of ts){const org=String(target.organization_id),user=String(target.user_id);for(let p=0;p<items.length;p+=60){const batch=items.slice(p,p+60);const rows=batch.map(i=>({user_id:user,organization_id:org,created_by:user,dossier_id:null,title:i.title,nature:i.nature,source_url:i.source_url,source_name:i.source_name,published_at:safeDate(i.published_at),urgency:"moyen"}));const{data:newRows,error:ins}=await s.from("watch_items").upsert(rows,{onConflict:"organization_id,source_url",ignoreDuplicates:true}).select("id");if(ins)throw ins;inserted+=(newRows||[]).length;const urls=batch.map(i=>i.source_url);const{data:known,error:rd}=await s.from("watch_items").select("id,source_url").eq("organization_id",org).in("source_url",urls);if(rd)throw rd;const byUrl=new Map((known||[]).map((r:any)=>[String(r.source_url),String(r.id)]));const now=new Date().toISOString();const cs=batch.map(i=>{const id=byUrl.get(i.source_url);return id?{watch_item_id:id,organization_id:org,source_text:i.source_text,source_text_chars:i.source_text.length,fetched_at:now,updated_at:now}:null;}).filter(Boolean);if(cs.length){const{error:ce}=await s.from("watch_item_content").upsert(cs,{onConflict:"watch_item_id"});if(ce)throw ce;contentUpserts+=cs.length;}}details.push({organization_id:org,available:items.length});}return{inserted,content_upserts:contentUpserts,catalog_upserts:catalogUpserts,organizations:ts.length,details};}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=key();if(!url||!secret)return out({error:"configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await auth(req,s))return out({error:"Non autorisé"},401);const holder=crypto.randomUUID();const{data:lease}=await s.rpc("acquire_veille_worker_lease",{p_worker:"catalog",p_holder:holder,p_seconds:180});if(lease!==true)return out({ok:true,skipped:"already_running"});try{const d=await collect();const stored=await store(s,d.items);return out({ok:true,engine:"catalog-dila-fr-canonical-v14",jurisdiction:"FR",source:"JORF/DILA",jorf_items:d.items.length,jorf_with_text:d.items.length,dila_diagnostics:d.diag,...stored});}catch(e:any){return out({ok:false,error:clip(e?.message||e,300)},500);}finally{try{await s.rpc("release_veille_worker_lease",{p_worker:"catalog",p_holder:holder});}catch{}}});