import {NextResponse} from "next/server";
import {evidenceExcerptIsGrounded,normalizeRadarText} from "@/lib/radarAudit";

export const runtime="nodejs";
export const maxDuration=20;

type Dossier={id:string;client:string;title:string;objective:string;context?:string;sector?:string|null;activity?:string|null;strategic_issues?:string[];client_position?:string|null;key_actors?:string[];watch_topics?:string[];watch_subtopics?:string[];key_deadlines?:string[]};
type WatchItem={id:string;title:string;nature:string;source_url?:string;urgency?:string;created_at?:string};
type Evidence={source_index:number;source_title:string;source_url:string;excerpt:string;confidence:number;verified:boolean};
type Actor={id:string;name:string;role:string;orbit:1|2|3;position:"favorable"|"inconnue"|"reserve"|"opposition";influence:number;why:string;window:string;action:string;certainty:"confirme"|"probable"|"a_confirmer";evidence:Evidence};
type Extraction={url:string;resolved_url?:string;content:string;status:"fetched"|"unavailable"|"unsupported";read_chars:number};

const OFFICIAL_HOSTS=["assemblee-nationale.fr","senat.fr","legifrance.gouv.fr","vie-publique.fr","gouvernement.fr","conseil-constitutionnel.fr","conseil-etat.fr","courdecassation.fr","cnil.fr","arcep.fr","economie.gouv.fr","ecologie.gouv.fr","tresor.economie.gouv.fr","eur-lex.europa.eu","europarl.europa.eu"];
const FORMAT={type:"json_schema",name:"myvor_radar_fast_v1",strict:true,schema:{type:"object",additionalProperties:false,properties:{actors:{type:"array",maxItems:4,items:{type:"object",additionalProperties:false,properties:{id:{type:"string"},name:{type:"string"},role:{type:"string"},orbit:{type:"integer",enum:[1,2,3]},position:{type:"string",enum:["favorable","inconnue","reserve","opposition"]},influence:{type:"integer",minimum:1,maximum:5},why:{type:"string"},window:{type:"string"},action:{type:"string"},certainty:{type:"string",enum:["confirme","probable","a_confirmer"]},evidence:{type:"object",additionalProperties:false,properties:{source_index:{type:"integer",minimum:0,maximum:4},source_title:{type:"string"},source_url:{type:"string"},excerpt:{type:"string"},confidence:{type:"number",minimum:0,maximum:1}},required:["source_index","source_title","source_url","excerpt","confidence"]}},required:["id","name","role","orbit","position","influence","why","window","action","certainty","evidence"]}}},required:["actors"]}} as const;

function text(value:unknown){return typeof value==="string"?value.trim():"";}
function list(value:unknown){return Array.isArray(value)?value.map(text).filter(Boolean):[];}
function decodeHtml(value:string){return value.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">");}
function htmlToText(html:string){return decodeHtml(html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<!--([\s\S]*?)-->/g," ").replace(/<br\s*\/?>/gi,"\n").replace(/<\/p>/gi,"\n").replace(/<\/li>/gi,"\n").replace(/<[^>]+>/g," ").replace(/[ \t]+/g," ").replace(/\n\s*\n+/g,"\n").trim());}
function official(raw:string){try{const url=new URL(raw);const host=url.hostname.toLowerCase();return url.protocol==="https:"&&OFFICIAL_HOSTS.some(base=>host===base||host.endsWith(`.${base}`));}catch{return false;}}
function outputText(payload:any){if(typeof payload?.output_text==="string")return payload.output_text.trim();return(payload?.output||[]).flatMap((item:any)=>item?.content||[]).filter((part:any)=>part?.type==="output_text").map((part:any)=>part?.text||"").join("").trim();}
function urgency(value:unknown){const key=text(value).toLowerCase();return key==="absolument urgent"?4:key==="fort"?3:key==="moyen"?2:1;}
function comparable(value:unknown){return normalizeRadarText(value).replace(/[^a-z0-9]+/g," ").trim();}

async function verifySession(request:Request){
  const authorization=request.headers.get("authorization")||"";
  if(!authorization.toLowerCase().startsWith("bearer "))return false;
  const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||"").replace(/\/$/,"");const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"";
  if(!url||!key)return false;
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),3500);
  try{const response=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:authorization},signal:controller.signal,cache:"no-store"});return response.ok;}catch{return false;}finally{clearTimeout(timer);}
}
async function fetchSource(rawUrl:string):Promise<Extraction>{
  if(!rawUrl||!official(rawUrl))return{url:rawUrl,content:"",status:"unsupported",read_chars:0};
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),2200);
  try{const response=await fetch(rawUrl,{headers:{"User-Agent":"Myvor/2.1 radar-fast","Accept":"text/html,text/plain;q=0.9,*/*;q=0.4"},redirect:"follow",cache:"no-store",signal:controller.signal});if(!response.ok)return{url:rawUrl,resolved_url:response.url||rawUrl,content:"",status:"unavailable",read_chars:0};const resolved=response.url||rawUrl;if(!official(resolved))return{url:rawUrl,resolved_url:resolved,content:"",status:"unsupported",read_chars:0};const contentType=(response.headers.get("content-type")||"").toLowerCase();if(!contentType.includes("text/html")&&!contentType.includes("text/plain"))return{url:rawUrl,resolved_url:resolved,content:"",status:"unsupported",read_chars:0};const raw=(await response.text()).slice(0,900_000);const content=(contentType.includes("text/html")?htmlToText(raw):raw).slice(0,4500);return{url:rawUrl,resolved_url:resolved,content,status:content?"fetched":"unavailable",read_chars:content.length};}catch{return{url:rawUrl,content:"",status:"unavailable",read_chars:0};}finally{clearTimeout(timer);}
}
function profile(dossier:Dossier){return[["Secteur",text(dossier.sector)],["Activité",text(dossier.activity)],["Enjeux",list(dossier.strategic_issues).join(" ; ")],["Position client",text(dossier.client_position)],["Acteurs suivis",list(dossier.key_actors).join(" ; ")],["Veille",[...list(dossier.watch_topics),...list(dossier.watch_subtopics)].join(" ; ")],["Échéances",list(dossier.key_deadlines).join(" ; ")]].filter(([,value])=>value).map(([label,value])=>`${label} : ${value}`).join("\n").slice(0,2800);}
function normalizeActor(raw:any,index:number):Actor{return{id:text(raw?.id)||`actor-${index+1}`,name:text(raw?.name),role:text(raw?.role),orbit:[1,2,3].includes(Number(raw?.orbit))?Number(raw.orbit) as 1|2|3:3,position:["favorable","inconnue","reserve","opposition"].includes(raw?.position)?raw.position:"inconnue",influence:Math.max(1,Math.min(5,Math.round(Number(raw?.influence)||1))),why:text(raw?.why),window:text(raw?.window),action:text(raw?.action),certainty:["confirme","probable","a_confirmer"].includes(raw?.certainty)?raw.certainty:"a_confirmer",evidence:{source_index:Math.max(0,Math.min(4,Math.round(Number(raw?.evidence?.source_index)||0))),source_title:text(raw?.evidence?.source_title),source_url:text(raw?.evidence?.source_url),excerpt:text(raw?.evidence?.excerpt).slice(0,300),confidence:Math.max(0,Math.min(1,Number(raw?.evidence?.confidence)||0)),verified:false}};}
function mentioned(actor:Actor,content:string){const source=normalizeRadarText(content);return[actor.name,actor.role].map(normalizeRadarText).filter(value=>value.length>=8).some(value=>source.includes(value));}
function ground(actor:Actor,items:WatchItem[],byUrl:Map<string,Extraction>):Actor|null{const item=actor.evidence.source_index>=1?items[actor.evidence.source_index-1]:null;const source=item?.source_url?byUrl.get(item.source_url):undefined;if(!item||!source||source.status!=="fetched")return null;if(!evidenceExcerptIsGrounded(source.content,actor.evidence.excerpt)||!mentioned(actor,source.content))return null;return{...actor,evidence:{...actor.evidence,source_title:item.title,source_url:item.source_url||"",verified:true}};}

export async function POST(request:Request){
  try{
    if(!(await verifySession(request)))return NextResponse.json({error:"Session Myvor requise."},{status:401});
    const body=await request.json().catch(()=>null);const dossier:Dossier|null=body?.dossier||null;const incoming:WatchItem[]=Array.isArray(body?.items)?body.items:[];
    if(!dossier)return NextResponse.json({error:"Sélectionne un dossier client."},{status:400});if(!incoming.length)return NextResponse.json({error:"Aucun texte n’est rattaché à ce dossier."},{status:400});
    const apiKey=text(process.env.OPENAI_API_KEY);if(!apiKey)return NextResponse.json({error:"Moteur Radar non configuré."},{status:503});const model=text(process.env.OPENAI_RADAR_FAST_MODEL)||text(process.env.OPENAI_RADAR_MODEL)||"gpt-4.1-mini";
    const items=[...incoming].sort((a,b)=>urgency(b.urgency)-urgency(a.urgency)||new Date(b.created_at||0).getTime()-new Date(a.created_at||0).getTime()).slice(0,4);
    const urls=[...new Set(items.map(item=>item.source_url||"").filter(Boolean))].slice(0,3);const extractions=await Promise.all(urls.map(fetchSource));const byUrl=new Map(extractions.map(source=>[source.url,source]));
    const sourceText=items.map((item,index)=>{const source=item.source_url?byUrl.get(item.source_url):undefined;return[`SOURCE ${index+1}`,`Titre : ${item.title}`,`Nature : ${item.nature}`,item.source_url?`URL : ${item.source_url}`:"",source?.status==="fetched"?`CONTENU :\n${source.content}`:""].filter(Boolean).join("\n");}).join("\n\n---\n\n");
    const prompt=`MYVOR — Radar d'influence rapide et vérifiable.\nCLIENT : ${dossier.client}\nDOSSIER : ${dossier.title}\nOBJECTIF : ${dossier.objective}\nCONTEXTE : ${text(dossier.context).slice(0,1200)}\n${profile(dossier)?`MÉMOIRE DOSSIER (contexte uniquement) :\n${profile(dossier)}\n`:""}\nSOURCES OFFICIELLES :\n${sourceText}\n\nIdentifie au maximum 4 acteurs institutionnels réellement nommés dans les contenus fournis. N'invente rien. Pour chaque acteur, copie un extrait exact de 18 à 220 caractères provenant d'une source numérotée. La source doit établir le rôle ou la pertinence de l'acteur. Si une position n'est pas explicitement établie, utilise inconnue. Le client n'est jamais un acteur. Les actions recommandées doivent rester prudentes et opérationnelles. Retourne uniquement le JSON du schéma.`;
    const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);
    try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:prompt,text:{format:FORMAT},max_output_tokens:1200,store:false}),signal:controller.signal});const raw=await response.text();let payload:any=null;try{payload=raw?JSON.parse(raw):null;}catch{}if(!response.ok)return NextResponse.json({error:payload?.error?.message||"Le moteur Radar rapide n’a pas répondu."},{status:502});const output=outputText(payload);if(!output)return NextResponse.json({error:"Le moteur Radar rapide n’a retourné aucun résultat."},{status:502});let parsed:any=null;try{parsed=JSON.parse(output);}catch{return NextResponse.json({error:"Réponse Radar rapide invalide."},{status:502});}const grounded=(Array.isArray(parsed?.actors)?parsed.actors:[]).slice(0,4).map(normalizeActor).map(actor=>ground(actor,items,byUrl)).filter(Boolean) as Actor[];const seen=new Set<string>();const clientKey=comparable(dossier.client);const actors=grounded.filter(actor=>{const key=comparable(actor.name);if(!key||key===clientKey||seen.has(key))return false;seen.add(key);return true;});if(!actors.length)return NextResponse.json({error:"Aucun acteur exploitable n’a été identifié."},{status:422});const fetched=extractions.filter(source=>source.status==="fetched").length;return NextResponse.json({actors,engine:"openai-radar-fast-grounded-v1",model,quality:{status:"grounded",client_excluded:true,generic_unsubstantiated_filtered:true,structured_output:true,grounded_actors:actors.length,total_actors:actors.length,grounding_rate:1,official_contact_lookup:false,verified_contact_pages:0},grounding:{official_sources_requested:urls.length,official_sources_fetched:fetched,max_official_sources:3,statuses:extractions.map(source=>({url:source.url,resolved_url:source.resolved_url||source.url,status:source.status,read_chars:source.read_chars}))}});
    }catch(error:any){if(error?.name==="AbortError")return NextResponse.json({error:"Analyse rapide indisponible."},{status:504});return NextResponse.json({error:error?.message||"Analyse rapide indisponible."},{status:502});}finally{clearTimeout(timer);}
  }catch(error:any){return NextResponse.json({error:error?.message||"Erreur interne du Radar rapide."},{status:500});}
}
