import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";

const PATH="/functions/v1/sync-watch-vie-publique";
const DATASET="https://echanges.dila.gouv.fr/OPENDATA/RAPPORTS_PUBLICS/vp_rapports.json";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const RANGE_END=4_194_303;
const MAX_ITEMS=120;
const MAX_TEXT=40_000;
type RawReport=Record<string,unknown>;
type Item={title:string;nature:string;source_url:string;source_name:string;published_at:string|null;source_text:string};
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H});}
function clip(x:unknown,n:number){return String(x??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,n).trim();}
function key(){const m=Deno.env.get("SUPABASE_SECRET_KEYS");if(m){try{const o=JSON.parse(m),v=o?.default||Object.values(o||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function auth(req:Request,s:any){const ts0=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts0)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const ts=Number(ts0);if(Math.abs(Math.floor(Date.now()/1000)-ts)>120)return false;const{data,error}=await s.rpc("verify_veille_internal_request",{p_path:PATH,p_timestamp:ts,p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function safeDate(...values:unknown[]){for(const raw of values){const v=String(raw??"").trim();if(!v)continue;const t=Date.parse(v);if(Number.isFinite(t)&&t<=Date.now()+36*3600000&&t>Date.UTC(1990,0,1))return new Date(t).toISOString();}return null;}
function arr(v:unknown){return Array.isArray(v)?v.map(x=>clip(x,500)).filter(Boolean):[];}
function canonical(raw:unknown){try{const u=new URL(String(raw||""));if(u.protocol!=="https:"||u.hostname!=="www.vie-publique.fr")return"";u.hash="";for(const k of [...u.searchParams.keys()])if(/^egn-/i.test(k)||/^utm_/i.test(k)||["fbclid","gclid"].includes(k))u.searchParams.delete(k);return u.toString();}catch{return"";}}
function extractObjects(text:string){const out:string[]=[];let depth=0,start=-1,inString=false,escape=false;for(let i=0;i<text.length;i++){const ch=text[i];if(inString){if(escape){escape=false;continue;}if(ch==="\\"){escape=true;continue;}if(ch==='"'){inString=false;}continue;}if(ch==='"'){inString=true;continue;}if(ch==='{'){if(depth===0)start=i;depth++;continue;}if(ch==='}'){if(depth>0)depth--;if(depth===0&&start>=0){out.push(text.slice(start,i+1));start=-1;if(out.length>=MAX_ITEMS)break;}}}return out;}
function natureOf(raw:RawReport){const types=arr(raw.type_rapport).join(" ").toLowerCase();if(types.includes("activite"))return"Rapport d’activité";if(types.includes("etude"))return"Rapport d’étude";if(types.includes("evaluation"))return"Rapport d’évaluation";if(types.includes("inspection"))return"Rapport d’inspection";return"Rapport public";}
function buildItem(raw:RawReport):Item|null{const title=clip(raw.titre,900),source_url=canonical(raw.url);if(title.length<8||!source_url)return null;const authors=arr(raw.auteur_moral),editor=clip(raw.editeur,300);const isCour=[editor,...authors].some(x=>/cour des comptes/i.test(x));const presentation=clip(raw.presentation,14_000),synthese=clip(raw.synthese,10_000),sommaire=clip(raw.sommaire,10_000),extrait=clip(raw.extrait,4_000),themes=arr(raw.thematique),descripteurs=arr(raw.descripteur),pdf=clip(raw.url_document,1200);const source_text=clip(["[MÉTADONNÉES OFFICIELLES DILA / VIE-PUBLIQUE]",`Titre : ${title}`,editor?`Éditeur : ${editor}`:"",authors.length?`Auteur(s) moral(aux) : ${authors.join(" ; ")}`:"",themes.length?`Thématique(s) : ${themes.join(" ; ")}`:"",descripteurs.length?`Descripteur(s) : ${descripteurs.join(" ; ")}`:"",presentation?`Présentation officielle : ${presentation}`:"",synthese?`Synthèse officielle : ${synthese}`:"",extrait?`Extrait officiel : ${extrait}`:"",sommaire?`Sommaire : ${sommaire}`:"",pdf?`Document : ${pdf}`:""].filter(Boolean).join("\n\n"),MAX_TEXT);if(source_text.length<120)return null;return{title,nature:natureOf(raw),source_url,source_name:isCour?"Cour des comptes — via DILA/Vie-publique":"Vie-publique — Rapports (DILA)",published_at:safeDate(raw.date_diffusion,raw.date_remise,raw.mise_en_ligne,raw.mise_a_jour),source_text};}
async function fetchHead(){const u=new URL(DATASET);if(u.protocol!=="https:"||u.hostname!=="echanges.dila.gouv.fr")throw new Error("Hôte DILA refusé");const c=new AbortController(),timer=setTimeout(()=>c.abort(),30000);try{const r=await fetch(u,{headers:{"User-Agent":"Myvor-DILA-Rapports/3.0","Accept":"application/json","Range":`bytes=0-${RANGE_END}`},redirect:"error",cache:"no-store",signal:c.signal});if(!(r.ok||r.status===206))throw new Error(`DILA HTTP ${r.status}`);const b=new Uint8Array(await r.arrayBuffer());if(b.length>RANGE_END+1)throw new Error("Réponse DILA trop volumineuse");return{body:new TextDecoder("utf-8").decode(b),range:r.headers.get("content-range")||"",bytes:b.length};}finally{clearTimeout(timer);}}
async function store(s:any,items:Item[]){const{data:targets,error}=await s.rpc("get_veille_ingestion_targets");if(error)throw error;let inserted=0,contentUpserts=0;for(const target of targets||[]){const org=String(target.organization_id),user=String(target.user_id);for(let p=0;p<items.length;p+=60){const batch=items.slice(p,p+60);const rows=batch.map(i=>({user_id:user,organization_id:org,created_by:user,dossier_id:null,title:i.title,nature:i.nature,source_url:i.source_url,source_name:i.source_name,published_at:i.published_at,urgency:"moyen"}));const{data:newRows,error:up}=await s.from("watch_items").upsert(rows,{onConflict:"organization_id,source_url",ignoreDuplicates:true}).select("id");if(up)throw up;inserted+=(newRows||[]).length;const urls=batch.map(i=>i.source_url);const{data:known,error:read}=await s.from("watch_items").select("id,source_url").eq("organization_id",org).in("source_url",urls);if(read)throw read;const idByUrl=new Map((known||[]).map((r:any)=>[String(r.source_url),String(r.id)]));const now=new Date().toISOString();const content=batch.map(i=>{const id=idByUrl.get(i.source_url);return id?{watch_item_id:id,organization_id:org,source_text:i.source_text,source_text_chars:i.source_text.length,fetched_at:now,updated_at:now}:null;}).filter(Boolean);if(content.length){const{error:ce}=await s.from("watch_item_content").upsert(content,{onConflict:"watch_item_id"});if(ce)throw ce;contentUpserts+=content.length;}}}return{inserted,content_upserts:contentUpserts,organizations:(targets||[]).length};}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=key();if(!url||!secret)return out({error:"configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await auth(req,s))return out({error:"Non autorisé"},401);const holder=crypto.randomUUID();const{data:lease}=await s.rpc("acquire_veille_worker_lease",{p_worker:"vie-publique",p_holder:holder,p_seconds:180});if(lease!==true)return out({ok:true,skipped:"already_running"});try{const fetched=await fetchHead();const objects=extractObjects(fetched.body);const items:Item[]=[];let parseErrors=0;for(const raw of objects){try{const item=buildItem(JSON.parse(raw));if(item)items.push(item);}catch{parseErrors++;}}const dedup=[...new Map(items.map(i=>[i.source_url,i])).values()].slice(0,MAX_ITEMS);const stored=await store(s,dedup);return out({ok:true,engine:"vie-publique-dila-v3",range:fetched.range,bytes:fetched.bytes,objects_parsed:objects.length,parse_errors:parseErrors,items_discovered:dedup.length,cour_des_comptes:dedup.filter(i=>i.source_name.startsWith("Cour des comptes")).length,newest:dedup.map(i=>i.published_at).filter(Boolean).sort().at(-1)||null,...stored});}catch(e:any){return out({ok:false,error:clip(e?.message||e,240)},500);}finally{try{await s.rpc("release_veille_worker_lease",{p_worker:"vie-publique",p_holder:holder});}catch{}}});