import { NextResponse } from "next/server";

type WatchItem={id:string;title:string;nature?:string};type Dossier={id:string;title:string;objective?:string};type Assignment={watch_id:string;dossier_id:string|null;confidence:number;reason?:string};
const STOP_WORDS=new Set(["a","au","aux","avec","ce","ces","dans","de","des","du","elle","en","et","eux","il","je","la","le","les","leur","lui","ma","mais","me","meme","mes","moi","mon","ne","nos","notre","nous","on","ou","par","pas","pour","qu","que","qui","sa","se","ses","son","sur","ta","te","tes","toi","ton","tu","un","une","vos","votre","vous","d","l","y","texte","obtenir","modification","favorable","reforme","projet","proposition"]);
function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function tokens(value:string){return normalize(value).split(/\s+/).filter(w=>w.length>2&&!STOP_WORDS.has(w));}
function stems(value:string){return tokens(value).map(w=>w.replace(/(ements?|ations?|iques?|istes?|ismes?|eurs?|euses?|ites?|ives?|ifs?|aux|ales?|es|s)$/,""));}
function localScore(item:WatchItem,dossier:Dossier){const itemTokens=new Set(stems(`${item.title} ${item.nature||""}`));const dossierTokens=stems(`${dossier.title} ${dossier.objective||""}`);if(!itemTokens.size||!dossierTokens.length)return{score:0,matches:[] as string[]};let matched=0;const matches:string[]=[];for(const word of dossierTokens){if(itemTokens.has(word)){matched+=1;matches.push(word);}else if([...itemTokens].some(x=>x.length>=5&&word.length>=5&&(x.includes(word)||word.includes(x)))){matched+=0.75;matches.push(word);}}const unique=new Set(dossierTokens).size||1;const ratio=matched/unique;let score=0;if(matched>=3)score=Math.min(0.96,0.76+ratio*0.22);else if(matched>=2)score=Math.min(0.88,0.70+ratio*0.20);else if(matched>=1)score=Math.min(0.72,0.48+ratio*0.18);return{score,matches:[...new Set(matches)].slice(0,4)};}
function localAssignments(items:WatchItem[],dossiers:Dossier[]):Assignment[]{return items.map(item=>{let best:Dossier|null=null;let bestScore=0;let bestMatches:string[]=[];for(const dossier of dossiers){const {score,matches}=localScore(item,dossier);if(score>bestScore){bestScore=score;best=dossier;bestMatches=matches;}}const reason=best&&bestScore>=0.45?(bestMatches.length?`Correspondances détectées : ${bestMatches.join(", ")}.`:`Proximité thématique avec ${best.title}.`):"Aucun lien suffisamment solide détecté.";return{watch_id:item.id,dossier_id:bestScore>=0.45&&best?best.id:null,confidence:Number(bestScore.toFixed(2)),reason};});}
function extractOutputText(payload:any){if(typeof payload?.output_text==="string")return payload.output_text;const chunks=payload?.output?.flatMap((item:any)=>item?.content||[])||[];return chunks.map((chunk:any)=>chunk?.text||"").join("");}
async function tryOpenAI(apiKey:string,items:WatchItem[],dossiers:Dossier[]):Promise<Assignment[]|null>{if(!apiKey)return null;const prompt=["Myvor: qualifie chaque évolution institutionnelle par rapport aux dossiers clients.","Pour chaque texte, propose le dossier le plus pertinent même si la confiance est moyenne. Mets dossier_id null seulement si aucun lien crédible n'existe.","confidence entre 0 et 1. reason = une phrase courte expliquant le lien métier concret avec l'objectif du dossier.","JSON uniquement: {assignments:[{watch_id,dossier_id,confidence,reason}]}","Veille:",JSON.stringify(items.slice(0,30)),"Dossiers:",JSON.stringify(dossiers.map(d=>({id:d.id,title:d.title,objective:d.objective||""})))].join("\n");const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5500);try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5-mini",input:prompt,max_output_tokens:1000,text:{format:{type:"json_object"}}}),signal:controller.signal});clearTimeout(timer);if(!response.ok)return null;const payload=await response.json();const parsed=JSON.parse(extractOutputText(payload)||"{}");return Array.isArray(parsed?.assignments)?parsed.assignments:null;}catch{clearTimeout(timer);return null;}}
export async function POST(request:Request){const body=await request.json().catch(()=>null);const items:WatchItem[]=Array.isArray(body?.items)?body.items.slice(0,40):[];const dossiers:Dossier[]=Array.isArray(body?.dossiers)?body.dossiers.slice(0,30):[];if(!items.length||!dossiers.length)return NextResponse.json({assignments:[],engine:"local"});const allowedDossierIds=new Set(dossiers.map(d=>d.id));const allowedWatchIds=new Set(items.map(i=>i.id));const apiKey=(process.env.OPENAI_API_KEY||"").trim();const aiAssignments=await tryOpenAI(apiKey,items,dossiers);const rawAssignments=aiAssignments||localAssignments(items,dossiers);const assignments=(rawAssignments||[]).filter((a:Assignment)=>allowedWatchIds.has(a.watch_id)).map((a:Assignment)=>({watch_id:a.watch_id,dossier_id:a.dossier_id&&allowedDossierIds.has(a.dossier_id)?a.dossier_id:null,confidence:Math.max(0,Math.min(1,Number(a.confidence)||0)),reason:String(a.reason||"Lien thématique détecté.").slice(0,220)}));return NextResponse.json({assignments,engine:aiAssignments?"openai":"myvor-local"});}
