import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.111.0";

type WatchRow={id:string;organization_id:string;title:string;source_url:string;source_name:string|null;published_at:string|null;dossier_id:string|null;created_at:string};
type Page={text:string;published_at:string|null};
const PATH="/functions/v1/watch-content-enricher";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const DILA="https://echanges.dila.gouv.fr/OPENDATA/JORFSIMPLE/";
const BATCH=36,MAX_RESPONSE_BYTES=2_000_000,MAX_TEXT=40_000,MAX_GZ=6_000_000,MAX_TAR=32_000_000,MAX_XML=1_000_000;
const HOSTS=["assemblee-nationale.fr","senat.fr","legifrance.gouv.fr","vie-publique.fr","economie.gouv.fr","ecologie.gouv.fr","tresor.economie.gouv.fr","conseil-etat.fr","conseil-constitutionnel.fr","ccomptes.fr","cnil.fr","arcep.fr","cre.fr","amf-france.org","autoritedelaconcurrence.fr","eur-lex.europa.eu","digital-strategy.ec.europa.eu"];
const GENERIC=new Set(["accueil","particuliers","professionnels","entreprises","associations","vie associative","etre informe","acceder a la rubrique","actualites","communiques","agenda et evenements","les publications","publications","les prises de parole","prises de parole","newsletter","s inscrire aux flux rss","acces au journal officiel","journal officiel serie l affichage par jour","journal officiel serie c affichage par jour"]);
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:H});}
function clip(value:unknown,max:number){return String(value??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,max).trim();}
function adminKey(){const modern=Deno.env.get("SUPABASE_SECRET_KEYS");if(modern){try{const parsed=JSON.parse(modern),v=parsed?.default||Object.values(parsed||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[’']/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function trusted(host:string){const h=host.toLowerCase().replace(/\.$/,"");return HOSTS.some(root=>h===root||h.endsWith(`.${root}`));}
function safeUrl(raw:string){try{const u=new URL(raw);if(u.protocol!=="https:"||!trusted(u.hostname))return null;u.hash="";for(const key of [...u.searchParams.keys()])if(/^utm_/i.test(key)||["fbclid","gclid"].includes(key))u.searchParams.delete(key);return u;}catch{return null;}}
async function authorized(req:Request,s:any){const tsRaw=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",signature=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(tsRaw)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(signature))return false;const ts=Number(tsRaw);if(Math.abs(Math.floor(Date.now()/1000)-ts)>120)return false;const{data,error}=await s.rpc("verify_veille_internal_request",{p_path:PATH,p_timestamp:ts,p_nonce:nonce,p_signature:signature});return !error&&data===true;}
function decodeEntities(value:string){const named:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",laquo:"«",raquo:"»",ndash:"–",mdash:"—",hellip:"…",eacute:"é",egrave:"è",ecirc:"ê",agrave:"à",ccedil:"ç",ocirc:"ô",ugrave:"ù",rsquo:"’",ldquo:"“",rdquo:"”"};return value.replace(/&#(x[0-9a-f]+|\d+);?/gi,(_,raw:string)=>{const n=raw.toLowerCase().startsWith("x")?parseInt(raw.slice(1),16):parseInt(raw,10);try{return Number.isFinite(n)?String.fromCodePoint(n):_;}catch{return _;}}).replace(/&([a-z][a-z0-9]+);/gi,(whole,name:string)=>named[name.toLowerCase()]??whole);}
function strip(html:string){return decodeEntities(html.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<noscript\b[\s\S]*?<\/noscript>/gi," ").replace(/<svg\b[\s\S]*?<\/svg>/gi," ").replace(/<nav\b[\s\S]*?<\/nav>/gi," ").replace(/<header\b[\s\S]*?<\/header>/gi," ").replace(/<footer\b[\s\S]*?<\/footer>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim();}
function readable(html:string){const article=html.match(/<article\b[^>]*>([\s\S]*?)<\/article>/i)?.[1];const main=html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1];const body=html.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i)?.[1];const candidates=[article,main,body,html].filter(Boolean).map(x=>strip(String(x))).filter(x=>x.length>=80).sort((a,b)=>b.length-a.length);return clip(candidates[0]||"",MAX_TEXT);}
function extractedDate(html:string){const values:string[]=[];for(const re of [/<meta[^>]+(?:property|name)=["'](?:article:published_time|datePublished|date|dc\.date|dcterms\.date)["'][^>]+content=["']([^"']+)["']/ig,/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["'](?:article:published_time|datePublished|date|dc\.date|dcterms\.date)["']/ig,/<time[^>]+datetime=["']([^"']+)["']/ig,/"datePublished"\s*:\s*"([^"]+)"/ig]){let m;while((m=re.exec(html))&&values.length<12)values.push(m[1]);}for(const raw of values){const t=Date.parse(raw);if(Number.isFinite(t)&&t<=Date.now()+36*3600000&&t>Date.UTC(1990,0,1))return new Date(t).toISOString();}return null;}
async function fetchRaw(url:URL,timeout=8500){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{redirect:"follow",cache:"no-store",signal:controller.signal,headers:{"User-Agent":"Mozilla/5.0 Myvor-Ingestion/1.2","Accept":"text/html,application/xhtml+xml,text/plain,application/xml;q=0.9,*/*;q=0.2","Accept-Language":"fr-FR,fr;q=0.9"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const type=(r.headers.get("content-type")||"").toLowerCase();if(type.includes("application/pdf")||type.includes("application/octet-stream"))throw new Error("format_binaire");const announced=Number(r.headers.get("content-length")||0);if(announced>MAX_RESPONSE_BYTES)throw new Error("page_trop_volumineuse");const bytes=new Uint8Array(await r.arrayBuffer());if(bytes.length>MAX_RESPONSE_BYTES)throw new Error("page_trop_volumineuse");let html=new TextDecoder("utf-8").decode(bytes);if((html.match(/�/g)||[]).length>3){const latin=new TextDecoder("windows-1252").decode(bytes);if((latin.match(/�/g)||[]).length<(html.match(/�/g)||[]).length)html=latin;}return{html,text:readable(html),published_at:extractedDate(html)};}finally{clearTimeout(timer);}}
function eurLexAlternate(u:URL){if(u.hostname!=="eur-lex.europa.eu"||!u.pathname.includes("/legal-content/"))return null;const parts=u.pathname.split("/").filter(Boolean);if(parts[0]!=="legal-content"||!parts[1])return null;const lang=parts[1].toUpperCase();const alt=new URL(`https://eur-lex.europa.eu/legal-content/${lang}/TXT/HTML/`);for(const [k,v] of u.searchParams)alt.searchParams.append(k,v);return alt;}
async function fetchPage(row:WatchRow):Promise<Page>{const primary=safeUrl(row.source_url);if(!primary)throw new Error("url_refusee");let firstError:unknown=null;try{const page=await fetchRaw(primary);if(page.text.length>=80)return page;firstError=new Error("contenu_insuffisant");}catch(e){firstError=e;}const alt=eurLexAlternate(primary);if(alt){try{const page=await fetchRaw(alt,12000);if(page.text.length>=80)return page;}catch(e){throw e;}}throw firstError instanceof Error?firstError:new Error("contenu_insuffisant");}
async function dilaText(url:string,timeout=15000){const u=new URL(url);if(u.protocol!=="https:"||u.hostname!=="echanges.dila.gouv.fr")throw new Error("Hôte DILA refusé");const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(u,{redirect:"error",signal:c.signal,headers:{"User-Agent":"Myvor-DILA-Repair/1.0","Accept":"text/html,*/*"}});if(!r.ok)throw new Error(`DILA HTTP ${r.status}`);const x=await r.text();if(x.length>2_000_000)throw new Error("Index DILA trop volumineux");return x;}finally{clearTimeout(timer);}}
async function dilaBytes(url:string,timeout=25000){const u=new URL(url);if(u.protocol!=="https:"||u.hostname!=="echanges.dila.gouv.fr")throw new Error("Hôte DILA refusé");const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(u,{redirect:"error",signal:c.signal,headers:{"User-Agent":"Myvor-DILA-Repair/1.0","Accept":"application/gzip,application/octet-stream,*/*"}});if(!r.ok)throw new Error(`DILA HTTP ${r.status}`);const announced=Number(r.headers.get("content-length")||0);if(announced>MAX_GZ)throw new Error("archive_trop_volumineuse");const b=new Uint8Array(await r.arrayBuffer());if(b.length>MAX_GZ)throw new Error("archive_trop_volumineuse");return b;}finally{clearTimeout(timer);}}
async function gunzip(b:Uint8Array){const reader=new Blob([b]).stream().pipeThrough(new DecompressionStream("gzip")).getReader(),chunks:Uint8Array[]=[];let total=0;try{for(;;){const{value,done}=await reader.read();if(done)break;if(!value)continue;total+=value.length;if(total>MAX_TAR){await reader.cancel();throw new Error("archive_decompressee_trop_volumineuse");}chunks.push(value);}}finally{reader.releaseLock();}const out=new Uint8Array(total);let p=0;for(const chunk of chunks){out.set(chunk,p);p+=chunk.length;}return out;}
function decode(b:Uint8Array){let x=new TextDecoder("utf-8").decode(b);if(x.includes("�")){const y=new TextDecoder("windows-1252").decode(b);if((y.match(/�/g)||[]).length<(x.match(/�/g)||[]).length)x=y;}return x;}
function findJorfInTar(tar:Uint8Array,target:string){const dec=new TextDecoder("utf-8");let p=0,guard=0;while(p+512<=tar.length&&guard++<20000){const h=tar.subarray(p,p+512);if(h.every(x=>x===0))break;const size=parseInt(dec.decode(h.subarray(124,136)).replace(/\0/g,"").trim()||"0",8),type=h[156],start=p+512,end=start+size;if(!Number.isFinite(size)||size<0||end>tar.length)break;if((type===0||type===48)&&size>20&&size<=MAX_XML){const f=tar.subarray(start,end);const xml=decode(f);if(xml.includes(target))return clip(strip(xml),MAX_TEXT);}p=start+Math.ceil(size/512)*512;}return"";}
async function repairJorf(row:WatchRow){const target=row.source_url.match(/\b(JORFTEXT\d{6,})\b/i)?.[1];if(!target||!row.published_at)return null;const t=Date.parse(row.published_at);if(!Number.isFinite(t))return null;const d=new Date(t),day=`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,"0")}${String(d.getUTCDate()).padStart(2,"0")}`;const index=await dilaText(`${DILA}?C=M;O=D`);const names=[...index.matchAll(new RegExp(`href=["'](JORFSIMPLE_${day}-\\d{6}\\.tar\\.gz)["']`,"gi"))].map(m=>m[1]).slice(0,4);for(const name of names){try{const tar=await gunzip(await dilaBytes(DILA+name));const text=findJorfInTar(tar,target);if(text.length>=80)return{text,published_at:row.published_at} as Page;}catch{}}return null;}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",key=adminKey();if(!url||!key)return json({error:"Configuration serveur incomplète"},503);const s=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});if(!await authorized(req,s))return json({error:"Non autorisé"},401);const holder=crypto.randomUUID();const{data:lease}=await s.rpc("acquire_veille_worker_lease",{p_worker:"content-enricher",p_holder:holder,p_seconds:150});if(lease!==true)return json({ok:true,skipped:"already_running"});try{const{data:reused}=await s.rpc("reuse_existing_watch_content_by_url");const{data:raw,error:missingError}=await s.rpc("get_missing_watch_items_for_enrichment",{p_limit:120});if(missingError)throw missingError;const candidates=((raw||[]) as WatchRow[]).filter(row=>!!safeUrl(row.source_url)&&!GENERIC.has(normalize(row.title))).slice(0,BATCH);let enriched=0,dateFilled=0,failed=0,dilaRepaired=0;const errors:Record<string,number>={};for(let start=0;start<candidates.length;start+=6){const group=candidates.slice(start,start+6);const settled=await Promise.allSettled(group.map(async row=>{if(/legifrance\.gouv\.fr\/jorf\/id\/JORFTEXT/i.test(row.source_url)){const dila=await repairJorf(row);if(dila)return{row,page:dila,via:"dila"};}const page=await fetchPage(row);if(page.text.length<80)throw new Error("contenu_insuffisant");return{row,page,via:"html"};}));for(let i=0;i<settled.length;i++){const outcome=settled[i],row=group[i];if(outcome.status!=="fulfilled"){failed++;const msg=clip(outcome.reason?.message||outcome.reason,80)||"erreur";errors[msg]=(errors[msg]||0)+1;continue;}const{page,via}=outcome.value,now=new Date().toISOString();const{error}=await s.from("watch_item_content").upsert({watch_item_id:row.id,organization_id:row.organization_id,source_text:page.text,source_text_chars:page.text.length,fetched_at:now,updated_at:now},{onConflict:"watch_item_id"});if(error){failed++;errors.db_upsert=(errors.db_upsert||0)+1;continue;}enriched++;if(via==="dila")dilaRepaired++;if(!row.published_at&&page.published_at){const{error:de}=await s.from("watch_items").update({published_at:page.published_at}).eq("id",row.id);if(!de)dateFilled++;}}}return json({ok:true,engine:"watch-content-enricher-v3",reused:Number(reused||0),returned_missing_rows:(raw||[]).length,candidates:candidates.length,enriched,dila_repaired:dilaRepaired,date_filled:dateFilled,failed,errors});}catch(e:any){return json({ok:false,error:clip(e?.message||e,240)},500);}finally{try{await s.rpc("release_veille_worker_lease",{p_worker:"content-enricher",p_holder:holder});}catch{}}});