import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";

const PATH="/functions/v1/sync-watch-commission-news";
const LIST="https://digital-strategy.ec.europa.eu/en/news";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
type Item={title:string;source_url:string;published_at:string;nature:string;source_text:string};
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H});}
function clip(x:unknown,n:number){return String(x??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,n).trim();}
function key(){const m=Deno.env.get("SUPABASE_SECRET_KEYS");if(m){try{const o=JSON.parse(m),v=o?.default||Object.values(o||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function auth(req:Request,s:any){const ts0=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts0)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const ts=Number(ts0);if(Math.abs(Math.floor(Date.now()/1000)-ts)>120)return false;const{data,error}=await s.rpc("verify_veille_internal_request",{p_path:PATH,p_timestamp:ts,p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function ent(x:string){const m:Record<string,string>={amp:"&",quot:'"',apos:"'",nbsp:" ",rsquo:"’",ldquo:"“",rdquo:"”",euro:"€"};return x.replace(/&#(x[0-9a-f]+|\d+);?/gi,(_,r)=>{const n=String(r).toLowerCase().startsWith("x")?parseInt(String(r).slice(1),16):parseInt(String(r),10);try{return Number.isFinite(n)?String.fromCodePoint(n):_;}catch{return _;}}).replace(/&([a-z][a-z0-9]+);/gi,(a,n)=>m[String(n).toLowerCase()]??a);}
function clean(x:string){return clip(ent(x.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")),40000);}
const MONTHS:Record<string,number>={january:0,february:1,march:2,april:3,may:4,june:5,july:6,august:7,september:8,october:9,november:10,december:11};
function dateOf(raw:string){const n=clean(raw).toLowerCase();const m=n.match(/\b(\d{1,2})\s+(january|february|march|april|may|june|july|august|september|october|november|december)\s+(20\d{2})\b/);if(!m)return null;return new Date(Date.UTC(Number(m[3]),MONTHS[m[2]],Number(m[1]),6)).toISOString();}
function parse(html:string){const items:Item[]=[];for(const seg of html.split(/<article\b/i).slice(1)){const block=seg.slice(0,15000);const meta=block.match(/<ul[^>]*primary-meta-container[^>]*>[\s\S]*?<li[^>]*>([\s\S]*?)<\/li>[\s\S]*?<li[^>]*>([\s\S]*?)<\/li>[\s\S]*?<\/ul>/i);const a=block.match(/<a[^>]+href=["'](\/en\/news\/[^"'#?]+)["'][^>]*>[\s\S]*?<span>([\s\S]*?)<\/span>/i);if(!meta||!a)continue;const published_at=dateOf(meta[2]);const title=clean(a[2]);if(!published_at||title.length<8)continue;const source_url=new URL(a[1],LIST).toString();const kind=clean(meta[1])||"News article";const desc=clean(block.match(/<div[^>]*class=["'][^"']*description[^"']*["'][^>]*>([\s\S]*?)<\/div>/i)?.[1]||"");const source_text=clip(`[MÉTADONNÉES OFFICIELLES COMMISSION EUROPÉENNE — NEWS & VIEWS]\nTitre : ${title}\nType : ${kind}\nDate : ${published_at.slice(0,10)}${desc?`\nRésumé : ${desc}`:""}`,40000);items.push({title,source_url,published_at,nature:kind,source_text});if(items.length>=60)break;}return[...new Map(items.map(i=>[i.source_url,i])).values()];}
async function fetchList(){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(LIST,{headers:{"User-Agent":"Mozilla/5.0 Myvor-Commission-News/1.0","Accept":"text/html,application/xhtml+xml","Accept-Language":"en,fr;q=0.8"},redirect:"follow",cache:"no-store",signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=new Uint8Array(await r.arrayBuffer());if(b.length>3_500_000)throw new Error("page trop volumineuse");return new TextDecoder("utf-8").decode(b);}finally{clearTimeout(timer);}}
async function store(s:any,items:Item[]){const{data:targets,error}=await s.rpc("get_veille_ingestion_targets");if(error)throw error;let inserted=0,backfilled=0,contents=0;for(const t of targets||[]){const org=String(t.organization_id),user=String(t.user_id);for(let p=0;p<items.length;p+=50){const batch=items.slice(p,p+50);const rows=batch.map(i=>({user_id:user,organization_id:org,created_by:user,title:i.title,nature:i.nature,source_url:i.source_url,source_name:"Commission européenne — Numérique (daté)",published_at:i.published_at,urgency:"moyen"}));const{data:newRows,error:ins}=await s.from("watch_items").upsert(rows,{onConflict:"organization_id,source_url",ignoreDuplicates:true}).select("id");if(ins)throw ins;inserted+=(newRows||[]).length;const urls=batch.map(i=>i.source_url);const{data:known,error:rd}=await s.from("watch_items").select("id,source_url,published_at").eq("organization_id",org).in("source_url",urls);if(rd)throw rd;const byUrl=new Map((known||[]).map((r:any)=>[String(r.source_url),r]));const now=new Date().toISOString(),cs:any[]=[];for(const i of batch){const r:any=byUrl.get(i.source_url);if(!r)continue;if(!r.published_at){const{error:u}=await s.from("watch_items").update({published_at:i.published_at,source_name:"Commission européenne — Numérique (daté)"}).eq("id",r.id).is("published_at",null);if(!u)backfilled++;}cs.push({watch_item_id:String(r.id),organization_id:org,source_text:i.source_text,source_text_chars:i.source_text.length,fetched_at:now,updated_at:now});}if(cs.length){const{error:ce}=await s.from("watch_item_content").upsert(cs,{onConflict:"watch_item_id"});if(ce)throw ce;contents+=cs.length;}}}return{inserted,date_backfills:backfilled,content_upserts:contents,organizations:(targets||[]).length};}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=key();if(!url||!secret)return out({error:"configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await auth(req,s))return out({error:"Non autorisé"},401);const holder=crypto.randomUUID();const{data:lease}=await s.rpc("acquire_veille_worker_lease",{p_worker:"commission-news",p_holder:holder,p_seconds:180});if(lease!==true)return out({ok:true,skipped:"already_running"});try{const items=parse(await fetchList());const stored=await store(s,items);return out({ok:true,engine:"commission-news-strict-v1",items_discovered:items.length,newest:items.map(i=>i.published_at).sort().at(-1)||null,...stored});}catch(e:any){return out({ok:false,error:clip(e?.message||e,240)},500);}finally{try{await s.rpc("release_veille_worker_lease",{p_worker:"commission-news",p_holder:holder});}catch{}}});