import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
type DossierInput={client:string;title:string;objective:string};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:H});}
function clip(v:unknown,n:number){return String(v??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,n).trim();}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}
function list(v:any,max=12){return Array.isArray(v)?[...new Set(v.map((x:any)=>clip(x,260)).filter(Boolean))].slice(0,max):[];}
function fallbackMarker(row:any){const notes=String(row?.internal_notes||""),issues=list(row?.strategic_issues,5).join(" ");return /pré-remplissage.*secours|pre-remplissage.*secours/i.test(notes)||/déterminer précisément le périmètre des règles applicables au dossier/i.test(issues);}
function profileFromRow(row:any){return{sector:clip(row?.sector,180),activity:clip(row?.activity,700),strategic_issues:list(row?.strategic_issues),risks_to_avoid:list(row?.risks_to_avoid),opportunities:list(row?.opportunities),client_position:clip(row?.client_position,1200),key_actors:list(row?.key_actors,8),watch_topics:list(row?.watch_topics),watch_subtopics:list(row?.watch_subtopics),reference_texts:list(row?.reference_texts,20),key_deadlines:list(row?.key_deadlines),internal_notes:clip(row?.internal_notes,1600)};}
function ready(row:any){if(!row||fallbackMarker(row))return false;const p=profileFromRow(row);return Boolean(p.sector&&p.activity&&p.strategic_issues.length&&p.risks_to_avoid.length&&p.opportunities.length&&p.client_position&&p.key_actors.length&&p.watch_topics.length);}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return json({error:"Méthode non autorisée."},405);const authorization=req.headers.get("authorization")||"";if(!authorization.toLowerCase().startsWith("bearer "))return json({error:"Session Myvor requise."},401);const url=(Deno.env.get("SUPABASE_URL")||"").replace(/\/$/,""),anon=Deno.env.get("SUPABASE_ANON_KEY")||"";if(!url||!anon)return json({error:"Configuration Supabase incomplète."},503);const body=await req.json().catch(()=>null),dossier:DossierInput|null=body?.dossier||null;if(!dossier?.title||!dossier?.objective)return json({error:"Le dossier doit avoir au moins un titre et un objectif."},400);const s=createClient(url,anon,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:authorization}}});const{data:userData,error:userError}=await s.auth.getUser();if(userError||!userData?.user?.id)return json({error:"Session Myvor invalide ou expirée."},401);async function fetchLatest(){let q=s.from("dossiers").select("*").eq("title",clip(dossier!.title,300)).order("created_at",{ascending:false}).limit(1);if(clip(dossier!.client,300))q=q.eq("client",clip(dossier!.client,300));const{data,error}=await q.maybeSingle();return error?null:data;}for(let attempt=0;attempt<24;attempt++){const row=await fetchLatest();if(ready(row))return json({profile:profileFromRow(row),engine:"dossier-profile-server-authoritative-v3"});if(attempt<23)await sleep(500);}return json({pending:true,engine:"dossier-profile-server-pending-v3"},202);});