import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";

type Item={title:string;url:string;published_at:string|null;source_text:string};
const PATH="/functions/v1/sync-watch-dgccrf",RSS="https://economie.gouv.fr/dgccrf/rss";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H});}
function clip(x:unknown,n:number){return String(x??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,n).trim();}
function key(){const m=Deno.env.get("SUPABASE_SECRET_KEYS");if(m){try{const o=JSON.parse(m),v=o?.default||Object.values(o||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function auth(req:Request,s:any){const ts0=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts0)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const ts=Number(ts0);if(Math.abs(Math.floor(Date.now()/1000)-ts)>120)return false;const{data,error}=await s.rpc("verify_veille_internal_request",{p_path:PATH,p_timestamp:ts,p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function entities(x:string){const m:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",laquo:"«",raquo:"»",eacute:"é",egrave:"è",agrave:"à",ccedil:"ç",rsquo:"’"};return x.replace(/&#(x[0-9a-f]+|\d+);?/gi,(_,r)=>{const n=String(r).toLowerCase().startsWith("x")?parseInt(String(r).slice(1),16):parseInt(String(r),10);try{return Number.isFinite(n)?String.fromCodePoint(n):_;}catch{return _;}}).replace(/&([a-z][a-z0-9]+);/gi,(a,n)=>m[String(n).toLowerCase()]??a);}
function clean(x:string){return clip(entities(x.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]+>/g," ")),5000);}
function date(raw:string){const t=Date.parse(clean(raw));return Number.isFinite(t)&&t<=Date.now()+36*3600000?new Date(t).toISOString():null;}
function canonical(raw:string){try{const u=new URL(raw);if(u.protocol!=="https:"||!/(^|\.)economie\.gouv\.fr$/i.test(u.hostname))return"";u.hash="";return u.toString();}catch{return"";}}
async function fetchRss(){const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const r=await fetch(RSS,{redirect:"follow",cache:"no-store",signal:c.signal,headers:{"User-Agent":"Mozilla/5.0 Myvor-DGCCRF/1.0","Accept":"application/rss+xml,application/xml,text/xml,*/*"}});if(!r.ok)throw new Error(`RSS HTTP ${r.status}`);const x=await r.text();if(x.length>2_000_000)throw new Error("RSS trop volumineux");return x;}finally{clearTimeout(timer);}}
function parse(xml:string){const items:Item[]=[];for(const m of xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)){const b=m[1],title=clean(b.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||""),url=canonical(clean(b.match(/<link[^>]*>([\s\S]*?)<\/link>/i)?.[1]||"")),description=clean(b.match(/<description[^>]*>([\s\S]*?)<\/description>/i)?.[1]||""),published=date(b.match(/<pubDate[^>]*>([\s\S]*?)<\/pubDate>/i)?.[1]||"");if(title.length<8||!url)continue;const source=clip([title,description].filter(Boolean).join("\n\n"),40000);items.push({title,url,published_at:published,source_text:source});if(items.length>=80)break;}return items;}
async function store(s:any,items:Item[]){const{data:targets,error}=await s.rpc("get_veille_ingestion_targets");if(error)throw error;let inserted=0,content=0;for(const target of targets||[]){const org=String(target.organization_id),user=String(target.user_id),now=new Date().toISOString();const rows=items.map(i=>({user_id:user,organization_id:org,created_by:user,dossier_id:null,title:i.title,nature:i.url.includes('/les-fiches-pratiques/')?"Fiche pratique / doctrine":"Publication DGCCRF",source_url:i.url,source_name:"DGCCRF",published_at:i.published_at,urgency:"moyen"}));const{data:newRows,error:up}=await s.from("watch_items").upsert(rows,{onConflict:"organization_id,source_url",ignoreDuplicates:true}).select("id");if(up)throw up;inserted+=(newRows||[]).length;const urls=items.map(i=>i.url),{data:known,error:read}=await s.from("watch_items").select("id,source_url").eq("organization_id",org).in("source_url",urls);if(read)throw read;const ids=new Map((known||[]).map((r:any)=>[String(r.source_url),String(r.id)]));const bodies=items.map(i=>{const id=ids.get(i.url);return id&&i.source_text.length>=40?{watch_item_id:id,organization_id:org,source_text:i.source_text,source_text_chars:i.source_text.length,fetched_at:now,updated_at:now}:null;}).filter(Boolean);if(bodies.length){const{error:ce}=await s.from("watch_item_content").upsert(bodies,{onConflict:"watch_item_id"});if(ce)throw ce;content+=bodies.length;}}return{inserted,content_upserts:content,organizations:(targets||[]).length};}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=key();if(!url||!secret)return out({error:"configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await auth(req,s))return out({error:"Non autorisé"},401);try{const items=parse(await fetchRss());const stored=await store(s,items);return out({ok:true,engine:"dgccrf-rss-v1",items_discovered:items.length,...stored});}catch(e:any){return out({ok:false,error:clip(e?.message||e,220)},500);}});