import { createClient } from "npm:@supabase/supabase-js@2";

type SourceItem={title:string;nature:string;source_url:string;source_name?:string;published_at?:string;excerpt?:string};
type Dossier={id:string;user_id:string;client:string;title:string;objective:string;context?:string;watch_keywords?:string[];watch_priority_phrases?:string[];watch_excluded_keywords?:string[]};
type WatchItem={id:string;user_id:string;title:string;nature:string;source_url:string;dossier_id:string|null;urgency:string;qualification_reason?:string|null;qualified_at?:string|null;excerpt?:string;full_text_chars?:number};
type Setting={user_id:string;enabled:boolean;auto_link_threshold:number|string;review_threshold:number|string};
type KeywordMatch={watch_id:string;dossier_id:string|null;confidence:number;matches:string[];reason:string};
type AiQualification={watch_id:string;urgency:"faible"|"moyen"|"fort"|"absolument urgent";reason:string};
type ScoreResult={score:number;matches:string[];priorityMatches:string[];blockedBy:string|null;explicitKeywords:boolean};

const JSON_HEADERS={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const VALID_URGENCIES=new Set(["faible","moyen","fort","absolument urgent"]);
const STOP_WORDS=new Set(["avec","dans","pour","sans","sous","entre","vers","chez","plus","moins","ainsi","comme","cette","celui","celle","ceux","elles","leurs","notre","votre","nous","vous","tout","tous","toute","toutes","texte","obtenir","modification","favorable","reforme","projet","proposition","objectif","client","dossier","action","impact","enjeu","enjeux","suivi","veille","mesure","mesures","nouveau","nouvelle","relatif","relative","concernant"]);
const WEAK_ANCHORS=new Set(["article","commerci","profession","entrepri","consomma","service","information","droit","regle","modal","public","activit","aout","juillet","juin","mai","avril","mars","fevrier","janvier","septembr","octobr","novembr","decembr","decret","arrete","ordonnance","code","applic","portant","journal","officiel","france","francais","entree","vigueur","publication","communiqu","actualit","autorite","minister","gouvernement","parlement"]);
const GENERIC_NAV_TITLES=new Set(["accueil","particuliers","professionnels","entreprises","actualites","communiques","agenda","publications","newsletter","accompagner et conseiller"]);
const OFFICIAL_HOSTS=["assemblee-nationale.fr","senat.fr","legifrance.gouv.fr","vie-publique.fr","economie.gouv.fr","ecologie.gouv.fr","tresor.economie.gouv.fr","conseil-etat.fr","conseil-constitutionnel.fr","qpc360.conseil-constitutionnel.fr","ccomptes.fr","cnil.fr","arcep.fr","eur-lex.europa.eu"];
const MAX_READABLE_TEXT=200_000;

function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:JSON_HEADERS});}
function clip(value:unknown,max:number){return String(value??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g,"").slice(0,max).trim();}
function extractOutputText(payload:any){if(typeof payload?.output_text==="string")return payload.output_text;const chunks=payload?.output?.flatMap((item:any)=>item?.content||[])||[];return chunks.map((chunk:any)=>chunk?.text||"").join("");}
function getAdminKey(){const modern=Deno.env.get("SUPABASE_SECRET_KEYS");if(modern){try{const keys=JSON.parse(modern);const value=keys?.default||Object.values(keys||{})[0];if(typeof value==="string"&&value)return value;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
function safeEqual(a:string,b:string){const aa=new TextEncoder().encode(a);const bb=new TextEncoder().encode(b);if(aa.length!==bb.length)return false;let diff=0;for(let i=0;i<aa.length;i++)diff|=aa[i]^bb[i];return diff===0;}
function canonicalUrl(value:string){try{const url=new URL(value);url.hash="";for(const key of [...url.searchParams.keys()]){if(/^utm_/i.test(key)||["fbclid","gclid"].includes(key))url.searchParams.delete(key);}return url.toString();}catch{return value.trim();}}
function safeTimestamp(value?:string){if(!value)return null;const time=Date.parse(value);return Number.isFinite(time)?new Date(time).toISOString():null;}
function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function stemWord(word:string){const stripped=word.replace(/(issements?|ements?|ations?|itions?|iques?|istes?|ismes?|teurs?|trices?|eurs?|euses?|ites?|ives?|ifs?|aux|ales?|elles?|ments?|es|s)$/i,"");return stripped.length>=4?stripped:word;}
function keywords(value:string){const out:string[]=[];for(const raw of normalize(value).split(/\s+/)){if(raw.length<4||STOP_WORDS.has(raw)||/^\d+$/.test(raw))continue;const word=stemWord(raw);if(word.length>=4&&!STOP_WORDS.has(word))out.push(word);}return [...new Set(out)];}
function strongKeywords(value:string){return keywords(value).filter(word=>!WEAK_ANCHORS.has(word));}
function cleanedList(value:unknown){return Array.isArray(value)?value.map(v=>String(v||"").trim()).filter(Boolean):[];}
function containsPhrase(normalizedText:string,phrase:string){const needle=normalize(phrase);return !!needle&&` ${normalizedText} `.includes(` ${needle} `);}
function phraseIsDiscriminating(phrase:string){const normalized=normalize(phrase);if(!normalized)return false;const tokens=normalized.split(/\s+/).filter(Boolean);const strong=strongKeywords(phrase);return strong.length>=1&&(tokens.length>=2||strong.length>=2||/\d/.test(normalized));}
function keywordHit(itemWords:Set<string>,word:string){if(itemWords.has(word))return 1;if(word.length<5)return 0;for(const itemWord of itemWords){if(itemWord.length>=5&&(itemWord.startsWith(word)||word.startsWith(itemWord)))return 0.8;}return 0;}
function isGenericNavigationTitle(value:string){return GENERIC_NAV_TITLES.has(normalize(value));}
function decodeEntities(value:string){const named:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",laquo:"«",raquo:"»",ndash:"–",mdash:"—",hellip:"…",eacute:"é",egrave:"è",ecirc:"ê",agrave:"à",ccedil:"ç",ocirc:"ô",ugrave:"ù",rsquo:"’",lsquo:"‘",ldquo:"“",rdquo:"”"};return value.replace(/&#(x[0-9a-f]+|\d+);?/gi,(_,raw:string)=>{const code=raw.toLowerCase().startsWith("x")?parseInt(raw.slice(1),16):parseInt(raw,10);try{return Number.isFinite(code)?String.fromCodePoint(code):_;}catch{return _;}}).replace(/&([a-z][a-z0-9]+);/gi,(whole,name:string)=>named[name.toLowerCase()]??whole);}
function stripNoise(value:string){return value.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<noscript\b[\s\S]*?<\/noscript>/gi," ").replace(/<svg\b[\s\S]*?<\/svg>/gi," ").replace(/<nav\b[\s\S]*?<\/nav>/gi," ").replace(/<footer\b[\s\S]*?<\/footer>/gi," ").replace(/<header\b[\s\S]*?<\/header>/gi," ").replace(/<aside\b[\s\S]*?<\/aside>/gi," ").replace(/<form\b[\s\S]*?<\/form>/gi," ");}
function cleanHtml(value:string){return decodeEntities(stripNoise(value)).replace(/<br\s*\/?\s*>/gi,"\n").replace(/<\/(?:p|div|section|article|li|h[1-6]|tr)>/gi,"\n").replace(/<[^>]+>/g," ").replace(/[ \t]+/g," ").replace(/\n\s*\n+/g,"\n").trim();}
function isOfficialUrl(value:string){try{const host=new URL(value).hostname.toLowerCase().replace(/^www\./,"");return OFFICIAL_HOSTS.some(allowed=>host===allowed||host.endsWith(`.${allowed}`));}catch{return false;}}
function metaDescription(html:string){const patterns=[/<meta[^>]+(?:name|property)=["'](?:description|og:description|twitter:description)["'][^>]+content=["']([^"']+)["'][^>]*>/i,/<meta[^>]+content=["']([^"']+)["'][^>]+(?:name|property)=["'](?:description|og:description|twitter:description)["'][^>]*>/i];for(const pattern of patterns){const match=html.match(pattern);if(match?.[1])return cleanHtml(match[1]);}return "";}
function readableBody(html:string){const main=html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1];if(main)return cleanHtml(main).slice(0,MAX_READABLE_TEXT);const articles=[...html.matchAll(/<article\b[^>]*>([\s\S]*?)<\/article>/gi)].map(match=>match[1]);if(articles.length)return cleanHtml(articles.join("\n")).slice(0,MAX_READABLE_TEXT);const body=html.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i)?.[1]||html;return cleanHtml(body).slice(0,MAX_READABLE_TEXT);}
async function fetchOfficialText(url:string){if(!url||!isOfficialUrl(url))return "";const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),7000);try{const response=await fetch(url,{redirect:"follow",headers:{"User-Agent":"Mozilla/5.0 Myvor-Cron/5.0","Accept":"text/html,application/xhtml+xml,*/*","Accept-Language":"fr-FR,fr;q=0.9"},signal:controller.signal});if(!response.ok)return "";const contentType=response.headers.get("content-type")||"";if(!/text\/html|application\/xhtml\+xml/i.test(contentType))return "";const html=await response.text();const meta=metaDescription(html);const body=readableBody(html);return [meta,body].filter(Boolean).join("\n").replace(/[ \t]+/g," ").replace(/\n\s*\n+/g,"\n").trim().slice(0,MAX_READABLE_TEXT);}catch{return "";}finally{clearTimeout(timer);}}
async function enrichItems(items:WatchItem[],sourceByUrl:Map<string,SourceItem>){const result:WatchItem[]=[];for(let start=0;start<items.length;start+=8){const batch=items.slice(start,start+8);const enriched=await Promise.all(batch.map(async item=>{const fallback=sourceByUrl.get(canonicalUrl(item.source_url))?.excerpt||item.excerpt||"";const full=await fetchOfficialText(item.source_url);return{...item,excerpt:[full,fallback].filter(Boolean).join("\n").slice(0,MAX_READABLE_TEXT),full_text_chars:full.length};}));result.push(...enriched);}return result;}

function scoreKeywords(item:WatchItem,dossier:Dossier):ScoreResult{
  const normalizedFull=normalize(`${item.title} ${item.nature} ${item.excerpt||""}`);
  const normalizedTitle=normalize(`${item.title} ${item.nature}`);
  const fullWords=new Set(strongKeywords(normalizedFull));
  const titleWords=new Set(strongKeywords(normalizedTitle));
  const excluded=cleanedList(dossier.watch_excluded_keywords);
  const explicitKeywords=cleanedList(dossier.watch_keywords);
  const blockedBy=excluded.find(term=>containsPhrase(normalizedFull,term))||null;
  if(blockedBy)return{score:0,matches:[],priorityMatches:[],blockedBy,explicitKeywords:explicitKeywords.length>0};

  const priorityPhrases=cleanedList(dossier.watch_priority_phrases).filter(phraseIsDiscriminating);
  const explicitPhrases=explicitKeywords.filter(phraseIsDiscriminating);
  const priorityMatches=priorityPhrases.filter(phrase=>containsPhrase(normalizedFull,phrase));
  const priorityTitleMatches=priorityPhrases.filter(phrase=>containsPhrase(normalizedTitle,phrase));
  const explicitPhraseMatches=explicitPhrases.filter(phrase=>containsPhrase(normalizedFull,phrase));
  const explicitPhraseTitleMatches=explicitPhrases.filter(phrase=>containsPhrase(normalizedTitle,phrase));
  const hasExplicitKeywords=explicitKeywords.length>0;
  const dossierWords=hasExplicitKeywords?[...new Set(explicitKeywords.flatMap(value=>strongKeywords(value)))]:strongKeywords(`${dossier.title} ${dossier.objective||""} ${dossier.context||""}`);
  const matches:string[]=[];const titleMatches:string[]=[];
  for(const word of dossierWords){if(keywordHit(fullWords,word)){matches.push(word);if(keywordHit(titleWords,word))titleMatches.push(word);}}
  const unique=[...new Set(matches)];const uniqueTitle=[...new Set(titleMatches)];

  let score=0;
  if(priorityTitleMatches.length>=1)score=.99;
  else if(priorityMatches.length>=1)score=.97;
  else if(explicitPhraseTitleMatches.length>=1)score=.97;
  else if(explicitPhraseMatches.length>=2)score=.96;
  else if(explicitPhraseMatches.length===1)score=.93;
  else if(uniqueTitle.length>=3)score=.98;
  else if(uniqueTitle.length>=2)score=.95;
  else if(uniqueTitle.length>=1&&unique.length>=3)score=.92;
  else if(unique.length>=4)score=.82;
  else if(unique.length===3)score=.76;
  else if(unique.length===2)score=.68;
  else if(unique.length===1)score=.60;
  return{score,matches:unique.slice(0,8),priorityMatches:priorityMatches.slice(0,4),blockedBy:null,explicitKeywords:hasExplicitKeywords};
}
function keywordMatch(item:WatchItem,dossiers:Dossier[]):KeywordMatch{
  if(isGenericNavigationTitle(item.title))return{watch_id:item.id,dossier_id:null,confidence:0,matches:[],reason:"Règles dossier v5 — Page générique de navigation : aucun rattachement."};
  const ranked=dossiers.map(d=>({d,...scoreKeywords(item,d)})).sort((a,b)=>b.score-a.score);const best=ranked[0];const second=ranked[1];
  if(!best||best.score<.55){const blocked=ranked.find(result=>result.blockedBy);return{watch_id:item.id,dossier_id:null,confidence:0,matches:[],reason:blocked?`Règles dossier v5 — Exclusion détectée : ${blocked.blockedBy}.`:"Règles dossier v5 — Aucun signal thématique suffisamment pertinent détecté dans le texte officiel complet."};}
  let confidence=best.score;if(second&&second.score>=.55&&(best.score-second.score)<.12)confidence=Math.min(confidence,.88);
  const parts=[best.priorityMatches.length?`Expression prioritaire : ${best.priorityMatches.join(", ")}.`:"",best.matches.length?`${best.explicitKeywords?"Mots-clés thématiques":"Signaux thématiques"} : ${best.matches.join(", ")}.`:""].filter(Boolean);
  return{watch_id:item.id,dossier_id:best.d.id,confidence:Number(confidence.toFixed(2)),matches:[...best.priorityMatches,...best.matches].slice(0,8),reason:`Règles dossier v5 — ${parts.join(" ")||`Correspondance thématique avec ${best.d.title}.`} Le score élevé exige un signal dans le titre ou une expression discriminante.`};
}

async function fetchJson(url:string,init:RequestInit={},timeoutMs=15000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(url,{...init,signal:controller.signal});const text=await response.text();let payload:any={};try{payload=text?JSON.parse(text):{};}catch{payload={raw:text};}if(!response.ok)throw new Error(`HTTP ${response.status}: ${clip(payload?.error||payload?.raw||response.statusText,240)}`);return payload;}finally{clearTimeout(timer);}}
async function qualifyUrgencyBatch(apiKey:string,items:WatchItem[],matches:KeywordMatch[],dossiers:Dossier[]):Promise<AiQualification[]>{if(!apiKey||!items.length)return[];const matchByWatch=new Map(matches.map(m=>[m.watch_id,m]));const dossierById=new Map(dossiers.map(d=>[d.id,d]));const payloadItems=items.map(item=>{const match=matchByWatch.get(item.id);const dossier=match?.dossier_id?dossierById.get(match.dossier_id):null;return{watch_id:item.id,title:clip(item.title,500),nature:clip(item.nature,120),official_text:clip(item.excerpt,6000),matched_keywords:match?.matches||[],dossier:dossier?{title:clip(dossier.title,250),objective:clip(dossier.objective,700),context:clip(dossier.context,700)}:null};});const prompt=["Tu es le moteur de qualification de la veille Myvor.","Le rattachement au dossier a déjà été déterminé de façon déterministe à partir du texte officiel complet et des règles de mots-clés. Tu ne dois pas choisir ni changer de dossier.","Évalue seulement l'urgence et explique brièvement le lien opérationnel avec l'objectif du dossier.","urgency doit être exactement: faible, moyen, fort, absolument urgent.","N'invente aucune échéance ni aucun contenu absent.","JSON uniquement: {\"qualifications\":[{\"watch_id\":\"...\",\"urgency\":\"moyen\",\"reason\":\"...\"}]}",JSON.stringify(payloadItems)].join("\n");const payload=await fetchJson("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:Deno.env.get("OPENAI_MODEL")||"gpt-5-mini",input:prompt,max_output_tokens:1800,text:{format:{type:"json_object"}}})},20000);let parsed:any={};try{parsed=JSON.parse(extractOutputText(payload)||"{}");}catch{throw new Error("Réponse IA non exploitable");}return Array.isArray(parsed?.qualifications)?parsed.qualifications:[];}

Deno.serve(async(req)=>{
  if(req.method!=="POST")return json({error:"Méthode non autorisée"},405);
  const expectedSecret=Deno.env.get("MYVOR_CRON_SECRET")||"";const suppliedSecret=req.headers.get("x-myvor-cron-secret")||"";if(!expectedSecret||!suppliedSecret||!safeEqual(expectedSecret,suppliedSecret))return json({error:"Non autorisé"},401);
  const supabaseUrl=Deno.env.get("SUPABASE_URL")||"";const adminKey=getAdminKey();if(!supabaseUrl||!adminKey)return json({error:"Configuration Supabase serveur incomplète"},500);
  const supabase=createClient(supabaseUrl,adminKey,{auth:{persistSession:false,autoRefreshToken:false}});const openAIKey=Deno.env.get("OPENAI_API_KEY")||"";const sourceEndpoint=Deno.env.get("MYVOR_SOURCES_URL")||"https://myvor.app/api/veille/sources";
  let sourcePayload:any;try{sourcePayload=await fetchJson(sourceEndpoint,{headers:{Accept:"application/json","User-Agent":"Myvor-Supabase-Veille/5.0"}},18000);}catch(error:any){return json({ok:false,error:`Collecte impossible: ${clip(error?.message,260)}`},502);}
  const sources:SourceItem[]=(Array.isArray(sourcePayload?.items)?sourcePayload.items:[]).map((item:any)=>({title:clip(item?.title,800),nature:clip(item?.nature||"Publication institutionnelle",140),source_url:canonicalUrl(clip(item?.source_url,1200)),source_name:clip(item?.source_name,180)||undefined,published_at:clip(item?.published_at,100)||undefined,excerpt:clip(item?.excerpt,12000)||undefined})).filter(item=>item.title&&item.source_url.startsWith("http")).filter((item,index,array)=>array.findIndex(x=>x.source_url===item.source_url)===index).slice(0,500);
  const sourceByUrl=new Map(sources.map(item=>[canonicalUrl(item.source_url),item]));
  const {data:settings,error:settingsError}=await supabase.from("veille_settings").select("user_id,enabled,auto_link_threshold,review_threshold").eq("enabled",true);if(settingsError)return json({ok:false,error:"Impossible de charger les réglages de veille"},500);
  const summaries:any[]=[];
  for(const setting of (settings||[]) as Setting[]){
    const userId=setting.user_id;const tenMinutesAgo=new Date(Date.now()-10*60*1000).toISOString();const {data:activeRun}=await supabase.from("veille_runs").select("id").eq("user_id",userId).eq("status","running").gte("started_at",tenMinutesAgo).limit(1).maybeSingle();if(activeRun){summaries.push({user_id:userId,status:"skipped",reason:"already_running"});continue;}
    const engine=openAIKey?"dossier-full-text-v5+openai":"dossier-full-text-v5";const {data:run,error:runError}=await supabase.from("veille_runs").insert({user_id:userId,status:"running",sources_count:Array.isArray(sourcePayload?.active_sources)?sourcePayload.active_sources.length:0,fetched_count:sources.length,engine}).select("id").single();if(runError){summaries.push({user_id:userId,status:"error",message:"run_log_failed"});continue;}const runId=run.id as string;
    try{
      const [{data:dossiers,error:dossiersError},{data:existing,error:existingError}]=await Promise.all([supabase.from("dossiers").select("id,user_id,client,title,objective,context,watch_keywords,watch_priority_phrases,watch_excluded_keywords").eq("user_id",userId),supabase.from("watch_items").select("id,user_id,title,nature,source_url,dossier_id,urgency,qualification_reason,qualified_at").eq("user_id",userId)]);if(dossiersError||existingError)throw new Error("Lecture du portefeuille impossible");
      const existingItems=(existing||[]) as WatchItem[];const existingUrls=new Set(existingItems.map(item=>canonicalUrl(String(item.source_url||""))).filter(Boolean));const fresh=sources.filter(item=>!existingUrls.has(item.source_url)).slice(0,30);let inserted:WatchItem[]=[];
      if(fresh.length){const rows=fresh.map(item=>({user_id:userId,dossier_id:null,title:item.title,nature:item.nature,source_url:item.source_url,source_name:item.source_name||null,published_at:safeTimestamp(item.published_at),urgency:"moyen"}));const {data,error}=await supabase.from("watch_items").insert(rows).select("id,user_id,title,nature,source_url,dossier_id,urgency,qualification_reason,qualified_at");if(error)throw new Error(`Insertion veille impossible: ${clip(error.message,180)}`);inserted=(data||[]) as WatchItem[];}
      const legacyUnlinked=existingItems.filter(item=>!item.dossier_id&&!String(item.qualification_reason||"").startsWith("Règles dossier v5 —")).slice(0,30);const rawProcessItems=[...inserted,...legacyUnlinked].filter((item,index,array)=>array.findIndex(candidate=>candidate.id===item.id)===index).slice(0,40);const processItems=await enrichItems(rawProcessItems,sourceByUrl);const allDossiers=(dossiers||[]) as Dossier[];const autoThreshold=Math.max(0.5,Math.min(1,Number(setting.auto_link_threshold)||0.9));const reviewThreshold=Math.max(0.3,Math.min(autoThreshold,Number(setting.review_threshold)||0.55));const matches=processItems.map(item=>keywordMatch(item,allDossiers));const candidates=matches.filter(match=>match.dossier_id&&match.confidence>=reviewThreshold);
      const aiByWatch=new Map<string,AiQualification>();let qualificationError="";if(candidates.length&&openAIKey){try{const candidateIds=new Set(candidates.map(c=>c.watch_id));const candidateItems=processItems.filter(item=>candidateIds.has(item.id));for(let start=0;start<candidateItems.length;start+=10){const batch=candidateItems.slice(start,start+10);const result=await qualifyUrgencyBatch(openAIKey,batch,candidates,allDossiers);for(const q of result){if(candidateIds.has(q.watch_id))aiByWatch.set(q.watch_id,q);}}}catch(error:any){qualificationError=clip(error?.message||"Qualification IA impossible",260);}}
      let autoLinked=0;let review=0;let actionsCreated=0;
      for(const item of processItems){const match=matches.find(candidate=>candidate.watch_id===item.id)!;const ai=aiByWatch.get(item.id);const urgency=ai&&VALID_URGENCIES.has(String(ai.urgency))?String(ai.urgency):"moyen";let dossierId:string|null=null;let suggestedId:string|null=null;if(match.dossier_id&&match.confidence>=autoThreshold){dossierId=match.dossier_id;autoLinked++;}else if(match.dossier_id&&match.confidence>=reviewThreshold){suggestedId=match.dossier_id;review++;}const reason=ai?.reason?`${match.reason} ${clip(ai.reason,320)}`:match.reason;const {error:updateError}=await supabase.from("watch_items").update({dossier_id:dossierId,suggested_dossier_id:suggestedId,urgency,qualification_confidence:match.confidence,qualification_reason:clip(reason,500),qualified_at:new Date().toISOString()}).eq("id",item.id).eq("user_id",userId);if(updateError)throw new Error(`Mise à jour qualification impossible: ${clip(updateError.message,180)}`);
        if(dossierId&&(urgency==="fort"||urgency==="absolument urgent")){const isAmendment=item.nature.toLowerCase().includes("amendement");const type=isAmendment?"amendement":"analyse";const title=isAmendment?`Préparer l’amendement — ${item.title}`:`Analyser l’impact — ${item.title}`;const {data:duplicate,error:duplicateError}=await supabase.from("actions").select("id").eq("user_id",userId).eq("dossier_id",dossierId).eq("type",type).eq("title",title).neq("status","termine").limit(1).maybeSingle();if(duplicateError)throw new Error(`Contrôle des actions impossible: ${clip(duplicateError.message,180)}`);if(!duplicate){const {error:actionError}=await supabase.from("actions").insert({user_id:userId,dossier_id:dossierId,type,title,description:`Action créée automatiquement par la veille Myvor. ${clip(reason,420)}`,actor_name:null,priority:urgency,status:"a_faire",due_date:null});if(actionError)throw new Error(`Création d’action impossible: ${clip(actionError.message,180)}`);actionsCreated++;}}
      }
      const status=qualificationError?"partial":"success";const enrichedCount=processItems.filter(item=>(item.full_text_chars||0)>0).length;const fullTextChars=processItems.reduce((sum,item)=>sum+(item.full_text_chars||0),0);const message=qualificationError?`${fresh.length} nouveau(x) texte(s), ${processItems.length} analysé(s), ${enrichedCount} texte(s) officiel(s) lu(s), ${fullTextChars} caractères analysés. Qualification IA partielle: ${qualificationError}`:`${fresh.length} nouveau(x) texte(s) · ${processItems.length} analysé(s) · ${enrichedCount} texte(s) complet(s) lu(s) · ${fullTextChars} caractères · ${autoLinked} auto-rattaché(s) · ${review} à valider · ${actionsCreated} action(s) créée(s).`;await supabase.from("veille_runs").update({status,finished_at:new Date().toISOString(),new_count:fresh.length,auto_linked_count:autoLinked,review_count:review,actions_created_count:actionsCreated,engine,message}).eq("id",runId);await supabase.from("veille_settings").update({last_run_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("user_id",userId);summaries.push({user_id:userId,status,new_items:fresh.length,processed:processItems.length,enriched:enrichedCount,full_text_chars:fullTextChars,auto_linked:autoLinked,review,actions_created:actionsCreated,engine});
    }catch(error:any){const message=clip(error?.message||"Erreur inconnue",500);await supabase.from("veille_runs").update({status:"error",finished_at:new Date().toISOString(),message}).eq("id",runId);summaries.push({user_id:userId,status:"error",message});}
  }
  return json({ok:true,synced_at:new Date().toISOString(),sources:sources.length,users:summaries});
});