export type SourceFormat="html"|"text"|"pdf";
export type SourceSegment={text:string;page?:number;section?:string;article?:string;ordinal:number};
export type StructuredEvidence={kind:"official"|"dossier";source_index?:number;source_title:string;source_url:string;excerpt:string;confidence:number;page?:number;section?:string;article?:string;fetched_at?:string};
export type EvidenceCandidate=StructuredEvidence&{tokens:string[]};
const STOPWORDS=new Set(["alors","ainsi","apres","avec","avoir","cette","comme","dans","depuis","elle","elles","entre","etre","fait","font","leur","leurs","mais","meme","moins","notamment","notre","pour","plus","peut","sans","selon","sera","sont","sous","tout","toute","toutes","tous","tres","une","vers","client","impact","texte","source","score","myvor","objectif","dossier","donnees","analyse","analysees","article"]);
export function decodeHtml(value:string){return String(value||"").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&#(\d+);/g,(_,code)=>String.fromCharCode(Number(code)||32));}
function stripTags(value:string){return decodeHtml(String(value||"").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim());}
function clean(value:string){return String(value||"").replace(/\u0000/g,"").replace(/[ \t]+/g," ").replace(/\n\s*\n\s*\n+/g,"\n\n").trim();}
export function inferArticle(value:string){const match=String(value||"").match(/\b(?:article|art\.?)[\s\u00a0]+([LDR]?\.?\s*\d+[A-Za-z0-9._-]*(?:\s*(?:bis|ter|quater))?)/i);return match?match[1].replace(/\s+/g," ").trim():undefined;}
function splitLongText(value:string,meta:Omit<SourceSegment,"text"|"ordinal">,startOrdinal:number){const cleaned=clean(value);if(!cleaned)return[];const parts=cleaned.split(/\n+|(?<=[.!?;:])\s+(?=[A-ZÀ-ÖØ-Ý0-9])/).map(item=>item.trim()).filter(item=>item.length>=24);const segments:SourceSegment[]=[];let ordinal=startOrdinal;for(const part of parts){if(part.length<=650){segments.push({...meta,text:part,article:inferArticle(part)||meta.article,ordinal:ordinal++});continue;}for(let start=0;start<part.length;start+=560){const chunk=part.slice(start,start+640).trim();if(chunk.length>=24)segments.push({...meta,text:chunk,article:inferArticle(chunk)||meta.article,ordinal:ordinal++});}}return segments;}
export function htmlToSegments(html:string):SourceSegment[]{const safe=String(html||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<!--([\s\S]*?)-->/g," ");const token=/<(h[1-6]|p|li|td|th|blockquote|article|section)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/gi;let match:RegExpExecArray|null;let heading="";let ordinal=0;const segments:SourceSegment[]=[];while((match=token.exec(safe))){const tag=match[1].toLowerCase();const text=stripTags(match[2]);if(!text)continue;if(/^h[1-6]$/.test(tag)){heading=text.slice(0,220);continue;}const article=inferArticle(text)||inferArticle(heading);segments.push(...splitLongText(text,{section:heading||undefined,article},ordinal));ordinal=segments.length;}if(!segments.length)return textToSegments(stripTags(safe));return segments.slice(0,2500);}
export function textToSegments(text:string,page?:number):SourceSegment[]{return splitLongText(text,{page},0).slice(0,2500);}
export function pdfPagesToSegments(pages:string[]):SourceSegment[]{const segments:SourceSegment[]=[];let ordinal=0;for(let index=0;index<pages.length;index++){const pageSegments=splitLongText(pages[index],{page:index+1},ordinal);segments.push(...pageSegments);ordinal=segments.length;}return segments.slice(0,4000);}
export function normalizeEvidenceText(value:string){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9%€]+/g," ").replace(/\s+/g," ").trim();}
export function evidenceTokens(value:string){const raw=normalizeEvidenceText(value).split(" ");const tokens=raw.filter(token=>(token.length>=3||/^\d+$/.test(token))&&!STOPWORDS.has(token)).map(token=>token.length>9&&!/^\d/.test(token)?token.slice(0,9):token);return[...new Set(tokens)].slice(0,80);}
function tokenOverlap(query:string[],candidate:string[]){if(!query.length||!candidate.length)return 0;const set=new Set(candidate);const matches=query.filter(token=>set.has(token));const numeric=query.filter(token=>/^\d/.test(token));if(numeric.length&&numeric.some(token=>!set.has(token)))return 0;const minMatches=query.length<=3?1:2;if(matches.length<minMatches)return 0;return matches.length/query.length+matches.length/Math.min(10,query.length);}
export function segmentRelevance(segment:SourceSegment,query:string){const queryTokens=evidenceTokens(query);const segmentTokens=evidenceTokens(`${segment.section||""} ${segment.article||""} ${segment.text}`);let score=tokenOverlap(queryTokens,segmentTokens);if(segment.article)score+=.12;if(/\b\d{1,2}[\/.]\d{1,2}[\/.]20\d{2}\b|\b20\d{2}-\d{2}-\d{2}\b/.test(segment.text))score+=.08;if(/\b(adopt|promul|amendement|commission|entrée en vigueur|reglement|directive|décret|arrete)\w*/i.test(segment.text))score+=.05;return score;}
export function selectRelevantSegments(segments:SourceSegment[],query:string,maxChars:number):SourceSegment[]{const scored=segments.map(segment=>({segment,score:segmentRelevance(segment,query)}));const positive=scored.filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.segment.ordinal-b.segment.ordinal);const fallback=scored.sort((a,b)=>a.segment.ordinal-b.segment.ordinal);const pool=positive.length?positive:fallback;const selected:SourceSegment[]=[];let used=0;for(const{segment}of pool){if(used>=maxChars)break;const remaining=maxChars-used;const text=segment.text.slice(0,remaining).trim();if(text.length<24)continue;selected.push({...segment,text});used+=text.length;}return selected.sort((a,b)=>a.ordinal-b.ordinal);}
export function formatSegment(segment:SourceSegment){const location=[segment.page?`Page ${segment.page}`:"",segment.article?`Article ${segment.article}`:"",segment.section||""].filter(Boolean).join(" · ");return location?`[${location}]\n${segment.text}`:segment.text;}
export function segmentsToText(segments:SourceSegment[]){return segments.map(formatSegment).join("\n\n");}
export function balanceAllocations(capacities:number[],totalChars:number){const allocations=capacities.map(()=>0);let remaining=Math.max(0,Math.floor(totalChars));while(remaining>0){const active=capacities.map((capacity,index)=>({capacity,index})).filter(({capacity,index})=>capacity>allocations[index]);if(!active.length)break;const share=Math.max(1,Math.floor(remaining/active.length));let consumed=0;for(const{capacity,index}of active){if(remaining<=0)break;const take=Math.min(capacity-allocations[index],share,remaining);allocations[index]+=take;remaining-=take;consumed+=take;}if(!consumed)break;}return allocations;}
export function buildOfficialEvidence(source:{index:number;title:string;url:string;fetched_at?:string;segments:SourceSegment[]}):EvidenceCandidate[]{return source.segments.map(segment=>{const tokens=evidenceTokens(`${segment.section||""} ${segment.article||""} ${segment.text}`);return{kind:"official" as const,source_index:source.index,source_title:source.title,source_url:source.url,excerpt:segment.text.slice(0,520),confidence:0,page:segment.page,section:segment.section,article:segment.article,fetched_at:source.fetched_at,tokens};}).filter(candidate=>candidate.tokens.length);}
export function buildDossierEvidence(title:string,values:{label:string;text:string}[]):EvidenceCandidate[]{return values.map(value=>{const excerpt=String(value.text||"").slice(0,520);return{kind:"dossier" as const,source_title:`${title} — ${value.label}`,source_url:"",excerpt,confidence:0,tokens:evidenceTokens(excerpt)};}).filter(candidate=>candidate.tokens.length);}
export function evidenceScore(claim:string,candidate:EvidenceCandidate){const query=evidenceTokens(claim);if(!query.length)return 0;const overlap=tokenOverlap(query,candidate.tokens);if(!overlap)return 0;const locationBoost=candidate.kind==="official"&&Boolean(candidate.page||candidate.article||candidate.section)?0.08:0;return Math.min(1,overlap*.46+locationBoost);}
export function findStructuredEvidence(claim:string,candidates:EvidenceCandidate[],minimum=.34):StructuredEvidence|null{let best:EvidenceCandidate|null=null;let bestScore=0;for(const candidate of candidates){const score=evidenceScore(claim,candidate);if(score>bestScore){best=candidate;bestScore=score;}}if(!best||bestScore<minimum)return null;const{tokens,...evidence}=best;return{...evidence,confidence:Math.round(bestScore*100)/100};}
export function evidenceLocation(evidence?:StructuredEvidence|null){if(!evidence)return"";return[evidence.source_index?`Source ${evidence.source_index}`:"",evidence.page?`page ${evidence.page}`:"",evidence.article?`article ${evidence.article}`:"",evidence.section||""].filter(Boolean).join(" · ");}
