import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";

type Candidate={celex:string;date:string|null};
type Item={celex:string;title:string;nature:string;source_url:string;published_at:string|null;source_text:string};
const PATH="/functions/v1/sync-watch-eurlex-cellar",H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const CELLAR="https://publications.europa.eu",MAX_DOC=2_500_000,MAX_TEXT=40_000,MAX_ITEMS=80;
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H});}
function clip(x:unknown,n:number){return String(x??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,n).trim();}
function key(){const m=Deno.env.get("SUPABASE_SECRET_KEYS");if(m){try{const o=JSON.parse(m),v=o?.default||Object.values(o||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function auth(req:Request,s:any){const ts0=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts0)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const ts=Number(ts0);if(Math.abs(Math.floor(Date.now()/1000)-ts)>120)return false;const{data,error}=await s.rpc("verify_veille_internal_request",{p_path:PATH,p_timestamp:ts,p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function entities(x:string){const m:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",laquo:"«",raquo:"»",ndash:"–",mdash:"—",hellip:"…",eacute:"é",egrave:"è",ecirc:"ê",agrave:"à",ccedil:"ç",ugrave:"ù",rsquo:"’",ldquo:"“",rdquo:"”"};return x.replace(/&#(x[0-9a-f]+|\d+);?/gi,(_,r)=>{const n=String(r).toLowerCase().startsWith("x")?parseInt(String(r).slice(1),16):parseInt(String(r),10);try{return Number.isFinite(n)?String.fromCodePoint(n):_;}catch{return _;}}).replace(/&([a-z][a-z0-9]+);/gi,(a,n)=>m[String(n).toLowerCase()]??a);}
function cleanHtml(x:string){return clip(entities(x.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<noscript\b[\s\S]*?<\/noscript>/gi," ").replace(/<svg\b[\s\S]*?<\/svg>/gi," ").replace(/<nav\b[\s\S]*?<\/nav>/gi," ").replace(/<header\b[\s\S]*?<\/header>/gi," ").replace(/<footer\b[\s\S]*?<\/footer>/gi," ").replace(/<[^>]+>/g," ")),MAX_TEXT);}
function safeDate(raw:string|null|undefined){if(!raw)return null;const t=Date.parse(String(raw));return Number.isFinite(t)&&t<=Date.now()+36*3600000&&t>Date.UTC(1900,0,1)?new Date(t).toISOString():null;}
function day(d:Date){return`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,"0")}-${String(d.getUTCDate()).padStart(2,"0")}`;}
async function fetchText(url:string,accept:string,timeout:number,maxBytes:number,lang=""){const u=new URL(url);if(u.protocol!=="https:"||u.hostname!=="publications.europa.eu")throw new Error("Hôte Cellar refusé");const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(u,{redirect:"follow",cache:"no-store",signal:c.signal,headers:{"User-Agent":"Myvor-EUR-Lex-Cellar/3.0","Accept":accept,...(lang?{"Accept-Language":lang}:{})}});if(!r.ok)throw new Error(`Cellar HTTP ${r.status}`);const announced=Number(r.headers.get("content-length")||0);if(announced>maxBytes)throw new Error("Réponse Cellar trop volumineuse");const b=new Uint8Array(await r.arrayBuffer());if(b.length>maxBytes)throw new Error("Réponse Cellar trop volumineuse");let x=new TextDecoder("utf-8").decode(b);if((x.match(/�/g)||[]).length>3){const alt=new TextDecoder("windows-1252").decode(b);if((alt.match(/�/g)||[]).length<(x.match(/�/g)||[]).length)x=alt;}return x;}finally{clearTimeout(timer);}}
async function recentCandidates(){const start=day(new Date(Date.now()-4*86400000));const query=`PREFIX cdm: <http://publications.europa.eu/ontology/cdm#>\nPREFIX owl: <http://www.w3.org/2002/07/owl#>\nPREFIX xsd: <http://www.w3.org/2001/XMLSchema#>\nSELECT DISTINCT ?sameAs ?date WHERE { ?w cdm:work_date_document ?date . ?w owl:sameAs ?sameAs . FILTER(?date >= "${start}"^^xsd:date) FILTER(STRSTARTS(STR(?sameAs), "http://publications.europa.eu/resource/celex/")) } ORDER BY DESC(?date) LIMIT 250`;const u=new URL(`${CELLAR}/webapi/rdf/sparql`);u.searchParams.set("query",query);const raw=await fetchText(u.toString(),"application/sparql-results+json",20000,4_000_000);const payload=JSON.parse(raw);const rows=Array.isArray(payload?.results?.bindings)?payload.results.bindings:[],found=new Map<string,Candidate>();for(const row of rows){const uri=String(row?.sameAs?.value||""),match=uri.match(/\/resource\/celex\/([^/?#]+)/i);if(!match)continue;const celex=decodeURIComponent(match[1]);if(!/^[0-9][0-9A-Z()_.-]{5,70}$/i.test(celex)||!['3','5','6'].includes(celex[0]))continue;if(!found.has(celex))found.set(celex,{celex,date:safeDate(row?.date?.value)});if(found.size>=MAX_ITEMS)break;}return[...found.values()];}
function titleFromHtml(html:string,celex:string){const xs=[html.match(/<meta[^>]+(?:name|property)=["'](?:DC\.title|dcterms\.title|og:title)["'][^>]+content=["']([^"']+)["']/i)?.[1],html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i)?.[1],html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1]].map(x=>x?clip(entities(String(x).replace(/<[^>]+>/g," ")),900):"").filter(Boolean);return xs.find(x=>x.length>=12&&!/publications office|eur-lex|access to european union law/i.test(x.toLowerCase()))||xs[0]||`Document de l’Union européenne — ${celex}`;}
function publishedFromHtml(html:string,fallback:string|null){for(const p of [/<meta[^>]+(?:name|property)=["'](?:DC\.date|dcterms\.date|date|article:published_time)["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+(?:name|property)=["'](?:DC\.date|dcterms\.date|date|article:published_time)["']/i,/"datePublished"\s*:\s*"([^"]+)"/i]){const d=safeDate(html.match(p)?.[1]);if(d)return d;}return fallback;}
function nature(celex:string,title:string){if(celex.startsWith("5"))return"Document préparatoire de l’Union européenne";if(celex.startsWith("6"))return"Jurisprudence de l’Union européenne";const t=title.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();if(t.includes("directive"))return"Directive de l’Union européenne";if(t.includes("reglement"))return"Règlement de l’Union européenne";if(t.includes("decision"))return"Décision de l’Union européenne";return"Acte de l’Union européenne";}
async function resolve(c:Candidate):Promise<Item>{const html=await fetchText(`${CELLAR}/resource/celex/${encodeURIComponent(c.celex)}`,"application/xhtml+xml",16000,MAX_DOC,"fra");const sourceText=cleanHtml(html);if(sourceText.length<120)throw new Error("contenu Cellar insuffisant");const title=titleFromHtml(html,c.celex);return{celex:c.celex,title,nature:nature(c.celex,title),source_url:`https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:${encodeURIComponent(c.celex)}`,published_at:publishedFromHtml(html,c.date),source_text:sourceText};}
async function store(s:any,items:Item[]){const{data:targets,error}=await s.rpc("get_veille_ingestion_targets");if(error)throw error;let inserted=0,contentUpserts=0;for(const target of targets||[]){const org=String(target.organization_id),user=String(target.user_id);for(let p=0;p<items.length;p+=40){const batch=items.slice(p,p+40),rows=batch.map(i=>({user_id:user,organization_id:org,created_by:user,dossier_id:null,title:i.title,nature:i.nature,source_url:i.source_url,source_name:"EUR-Lex / Cellar",published_at:i.published_at,urgency:"moyen"}));const{data:newRows,error:up}=await s.from("watch_items").upsert(rows,{onConflict:"organization_id,source_url",ignoreDuplicates:true}).select("id");if(up)throw up;inserted+=(newRows||[]).length;const urls=batch.map(i=>i.source_url),{data:known,error:read}=await s.from("watch_items").select("id,source_url").eq("organization_id",org).in("source_url",urls);if(read)throw read;const ids=new Map((known||[]).map((r:any)=>[String(r.source_url),String(r.id)])),now=new Date().toISOString(),content=batch.map(i=>{const id=ids.get(i.source_url);return id?{watch_item_id:id,organization_id:org,source_text:i.source_text,source_text_chars:i.source_text.length,fetched_at:now,updated_at:now}:null;}).filter(Boolean);if(content.length){const{error:ce}=await s.from("watch_item_content").upsert(content,{onConflict:"watch_item_id"});if(ce)throw ce;contentUpserts+=content.length;}}}return{inserted,content_upserts:contentUpserts,organizations:(targets||[]).length};}
function manualCandidates(body:any){const raw=Array.isArray(body?.celexes)?body.celexes:[];const found=new Map<string,Candidate>();for(const value of raw){const celex=clip(value,80);if(/^[0-9][0-9A-Z()_.-]{5,70}$/i.test(celex)&&['3','5','6'].includes(celex[0])&&!found.has(celex))found.set(celex,{celex,date:null});if(found.size>=20)break;}return[...found.values()];}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=key();if(!url||!secret)return out({error:"configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await auth(req,s))return out({error:"Non autorisé"},401);const holder=crypto.randomUUID();const{data:lease}=await s.rpc("acquire_veille_worker_lease",{p_worker:"eurlex",p_holder:holder,p_seconds:180});if(lease!==true)return out({ok:true,skipped:"already_running"});try{const body=await req.json().catch(()=>({}));const manual=manualCandidates(body),candidates=manual.length?manual:await recentCandidates();let items:Item[]=[];let failed=0;const errors:Record<string,number>={};for(let p=0;p<candidates.length;p+=5){const settled=await Promise.allSettled(candidates.slice(p,p+5).map(resolve));for(const r of settled){if(r.status==="fulfilled")items.push(r.value);else{failed++;const m=clip((r.reason as any)?.message||r.reason,100)||"erreur";errors[m]=(errors[m]||0)+1;}}if(!manual.length&&items.length>=40)break;}if(!manual.length)items=items.slice(0,40);const stored=await store(s,items);return out({ok:true,engine:"eurlex-cellar-v3",mode:manual.length?"manual-celex":"recent-sparql",candidates:candidates.length,documents_resolved:items.length,failed,errors,resolved_celexes:items.map(i=>i.celex),...stored});}catch(e:any){return out({ok:false,error:clip(e?.message||e,240)},500);}finally{try{await s.rpc("release_veille_worker_lease",{p_worker:"eurlex",p_holder:holder});}catch{}}});