import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";

const PATH="/functions/v1/watch-date-enricher";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const HOSTS=["cnil.fr","arcep.fr","economie.gouv.fr","digital-strategy.ec.europa.eu","conseil-constitutionnel.fr","qpc360.conseil-constitutionnel.fr","legifrance.gouv.fr","vie-publique.fr"];
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H});}
function clip(x:unknown,n:number){return String(x??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,n).trim();}
function key(){const m=Deno.env.get("SUPABASE_SECRET_KEYS");if(m){try{const o=JSON.parse(m),v=o?.default||Object.values(o||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function auth(req:Request,s:any){const ts0=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts0)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const ts=Number(ts0);if(Math.abs(Math.floor(Date.now()/1000)-ts)>120)return false;const{data,error}=await s.rpc("verify_veille_internal_request",{p_path:PATH,p_timestamp:ts,p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function trusted(host:string){const h=host.toLowerCase().replace(/\.$/,"");return HOSTS.some(x=>h===x||h.endsWith(`.${x}`));}
function entity(x:string){return x.replace(/&#(x[0-9a-f]+|\d+);?/gi,(_,r)=>{const n=String(r).toLowerCase().startsWith("x")?parseInt(String(r).slice(1),16):parseInt(String(r),10);try{return Number.isFinite(n)?String.fromCodePoint(n):_;}catch{return _;}}).replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&apos;/gi,"'");}
function clean(x:string){return entity(x.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")).replace(/\s+/g," ").trim();}
function normalizeDate(raw:string){const value=clean(raw).trim();if(!value)return null;const direct=Date.parse(value);if(Number.isFinite(direct)&&direct<=Date.now()+36*3600000&&direct>Date.UTC(1990,0,1))return new Date(direct).toISOString();const n=value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();const months:Record<string,number>={janvier:0,fevrier:1,mars:2,avril:3,mai:4,juin:5,juillet:6,aout:7,septembre:8,octobre:9,novembre:10,decembre:11};const m=n.match(/\b(\d{1,2})\s+(janvier|fevrier|mars|avril|mai|juin|juillet|aout|septembre|octobre|novembre|decembre)\s+(20\d{2})\b/);if(m)return new Date(Date.UTC(Number(m[3]),months[m[2]],Number(m[1]),6)).toISOString();const dmy=n.match(/\b(\d{1,2})[\/.\-](\d{1,2})[\/.\-](20\d{2})\b/);if(dmy)return new Date(Date.UTC(Number(dmy[3]),Number(dmy[2])-1,Number(dmy[1]),6)).toISOString();return null;}
function metaDate(html:string){const patterns=[/<meta[^>]+(?:property|name)=["'](?:article:published_time|datePublished|dcterms\.date|DC\.date|date|publication_date|publish-date)["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["'](?:article:published_time|datePublished|dcterms\.date|DC\.date|date|publication_date|publish-date)["']/i,/"datePublished"\s*:\s*"([^"]+)"/i,/"dateCreated"\s*:\s*"([^"]+)"/i,/\b(?:Publié|Publiée|Publication|Mis en ligne|Mise en ligne|Date de publication)\s*(?:le|:)\s*([^<\n]{6,40})/i];for(const p of patterns){const v=html.match(p)?.[1];const d=v?normalizeDate(v):null;if(d)return d;}const head=clean(html.slice(0,16000));const french=head.match(/\b(?:Publié|Publiée|Publication|Mis en ligne|Mise en ligne)?\s*(?:le\s*)?(\d{1,2}\s+(?:janvier|février|fevrier|mars|avril|mai|juin|juillet|août|aout|septembre|octobre|novembre|décembre|decembre)\s+20\d{2})\b/i)?.[1];return french?normalizeDate(french):null;}
async function fetchHtml(raw:string){const u=new URL(raw);if(u.protocol!=="https:"||!trusted(u.hostname)||/\.pdf(?:$|\?)/i.test(u.pathname+u.search))throw new Error("source non HTML ou hôte refusé");const c=new AbortController(),timer=setTimeout(()=>c.abort(),9000);try{const r=await fetch(u,{redirect:"follow",cache:"no-store",signal:c.signal,headers:{"User-Agent":"Mozilla/5.0 Myvor-Date-Enricher/1.0","Accept":"text/html,application/xhtml+xml,*/*","Accept-Language":"fr-FR,fr;q=0.9,en;q=0.5"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const announced=Number(r.headers.get("content-length")||0);if(announced>2_500_000)throw new Error("page trop volumineuse");const b=new Uint8Array(await r.arrayBuffer());if(b.length>2_500_000)throw new Error("page trop volumineuse");return new TextDecoder("utf-8").decode(b);}finally{clearTimeout(timer);}}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=key();if(!url||!secret)return out({error:"configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await auth(req,s))return out({error:"Non autorisé"},401);const holder=crypto.randomUUID();const{data:lease}=await s.rpc("acquire_veille_worker_lease",{p_worker:"date-enricher",p_holder:holder,p_seconds:180});if(lease!==true)return out({ok:true,skipped:"already_running"});try{const{data,error}=await s.rpc("get_watch_items_missing_dates",{p_limit:24});if(error)throw error;const rows=data||[];let filled=0,failed=0;const errors:Record<string,number>={};for(const row of rows){try{const html=await fetchHtml(String(row.source_url));const d=metaDate(html);if(!d){failed++;errors.no_date=(errors.no_date||0)+1;continue;}const{error:up}=await s.from("watch_items").update({published_at:d}).eq("id",row.id).is("published_at",null);if(up)throw up;filled++;}catch(e:any){failed++;const m=clip(e?.message||e,80)||"erreur";errors[m]=(errors[m]||0)+1;}}return out({ok:true,engine:"watch-date-enricher-v1",candidates:rows.length,filled,failed,errors});}catch(e:any){return out({ok:false,error:clip(e?.message||e,240)},500);}finally{try{await s.rpc("release_veille_worker_lease",{p_worker:"date-enricher",p_holder:holder});}catch{}}});