import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";

const PATH="/functions/v1/dossier-corpus-auto",ENGINE="dossier-corpus-auto-v21-strict-fr-eu";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const FR_AI=/^(?:(?:loi(?: organique)?|décret|decret|ordonnance)\s+n?[°o]?\s*\d{2,4}\s*[-–]\s*\d{1,5}|(?:JORFTEXT|JORFARTI|LEGITEXT|LEGIARTI|CNILTEXT)\d+)$/i;
const OMNIBUS=["32016R0679","32018R1724","32018R1725","32023R2854","32002L0058","32022L2555","32022L2557","32018R1807","32019R1150","32022R0868","32019L1024"];
const LABEL:Record<string,string>={"52025PC0837":"Digital Omnibus — Proposition COM(2025) 837","32016R0679":"RGPD — Règlement (UE) 2016/679","32023R2854":"Data Act — Règlement (UE) 2023/2854","32022L2555":"NIS2 — Directive (UE) 2022/2555","32002L0058":"ePrivacy — Directive 2002/58/CE","32024R1689":"AI Act — Règlement (UE) 2024/1689","32024L2831":"Directive (UE) 2024/2831 — travail via une plateforme","32025R0040":"Règlement (UE) 2025/40 — emballages et déchets d’emballages","32019R0943":"Règlement (UE) 2019/943 — marché intérieur de l’électricité","32019L0944":"Directive (UE) 2019/944 — marché intérieur de l’électricité","32018L1972":"Directive (UE) 2018/1972 — code européen des communications électroniques","32009R1107":"Règlement (CE) n° 1107/2009 — produits phytopharmaceutiques","32023R2405":"Règlement (UE) 2023/2405 — ReFuelEU Aviation","32011R1169":"Règlement (UE) n° 1169/2011 — information des consommateurs sur les denrées alimentaires","32020R0741":"Règlement (UE) 2020/741 — réutilisation de l’eau","32015L2366":"Directive (UE) 2015/2366 — services de paiement (PSD2)","32008L0098":"Directive 2008/98/CE — déchets","32012L0034":"Directive 2012/34/UE — espace ferroviaire unique européen"};
const CODE:Record<string,{title:string,url:string}>={
LEGITEXT000023983208:{title:"Code de l'énergie",url:"https://www.legifrance.gouv.fr/codes/texte_lc/LEGITEXT000023983208/"},
LEGITEXT000006070987:{title:"Code des postes et des communications électroniques",url:"https://www.legifrance.gouv.fr/codes/texte_lc/LEGITEXT000006070987/"},
LEGITEXT000006074220:{title:"Code de l'environnement",url:"https://www.legifrance.gouv.fr/codes/texte_lc/LEGITEXT000006074220/"},
LEGITEXT000006073189:{title:"Code de la sécurité sociale",url:"https://www.legifrance.gouv.fr/codes/texte_lc/LEGITEXT000006073189/"},
LEGITEXT000006072665:{title:"Code de la santé publique",url:"https://www.legifrance.gouv.fr/codes/texte_lc/LEGITEXT000006072665/"},
LEGITEXT000037701019:{title:"Code de la commande publique",url:"https://www.legifrance.gouv.fr/codes/texte_lc/LEGITEXT000037701019/"}
};
const EU_ALIAS:[RegExp,string,string][]=[
[/\bdigital omnibus\b/i,"52025PC0837","named"],[/\b(?:rgpd|gdpr)\b/i,"32016R0679","alias"],[/\bdata act\b/i,"32023R2854","alias"],[/\bnis\s*2\b|\bnis2\b/i,"32022L2555","alias"],[/\beprivacy\b/i,"32002L0058","alias"],[/\bai act\b|règlement européen sur l.?ia|reglement europeen sur l.?ia/i,"32024R1689","named"],[/\bdigital services act\b|\bdsa\b/i,"32022R2065","named"],[/\bdigital markets act\b|\bdma\b/i,"32022R1925","named"],
[/travailleurs? des plateformes|travail via une plateforme|platform work/i,"32024L2831","named"],[/emballages et déchets d.emballages|emballages et dechets d.emballages|règlement européen sur les emballages|reglement europeen sur les emballages|\bppwr\b/i,"32025R0040","named"],
[/emballages?.*(?:réemploi|reemploi|usage unique|plastique|déchets|dechets|\brep\b)|(?:réemploi|reemploi|usage unique|plastique|déchets|dechets|\brep\b).*emballages?/i,"32025R0040","sector"],
[/marché de l.électricité|marche de l.electricite|marché européen de l.énergie|marche europeen de l.energie/i,"32019R0943","sector"],[/marché de l.électricité|marche de l.electricite|marché européen de l.énergie|marche europeen de l.energie/i,"32019L0944","sector"],
[/réseaux de communications électroniques|reseaux de communications electroniques|fermeture du réseau cuivre|fermeture du reseau cuivre|\barcep\b/i,"32018L1972","sector"],[/produits phytopharmaceutiques|produits phytosanitaires|\bphytopharmaceutiques\b/i,"32009R1107","sector"],
[/carburants d.aviation durables|\brefueleu\b/i,"32023R2405","sector"],[/information des consommateurs.*denrées|information des consommateurs.*denrees|étiquetage.*aliment|etiquetage.*aliment/i,"32011R1169","sector"],
[/réutilisation des eaux usées|reutilisation des eaux usees/i,"32020R0741","sector"],[/services de paiement|\bpsd2\b/i,"32015L2366","sector"],[/déchets organiques|dechets organiques|déchets.*valorisation|dechets.*valorisation/i,"32008L0098","sector"],[/ferroviaire.*concurrence|espace ferroviaire unique|infrastructures ferroviaires/i,"32012L0034","sector"]
];
const FR_ALIAS:[RegExp,string,string][]=[
[/\b(?:rgpd|gdpr|informatique et libertés|informatique et libertes)\b/i,"JORFTEXT000000886460","complement"],[/\b(?:loi\s+)?sren\b|sécuriser et réguler l.espace numérique|securiser et reguler l.espace numerique/i,"JORFTEXT000049563368","alias"],[/\b(?:loi\s+)?lcen\b|confiance dans l.économie numérique|confiance dans l.economie numerique/i,"JORFTEXT000000801164","alias"],[/république numérique|republique numerique/i,"JORFTEXT000033202746","alias"],
[/\b(?:loi\s+)?agec\b|anti[- ]gaspillage.*économie circulaire|anti[- ]gaspillage.*economie circulaire|emballages?.*(?:réemploi|reemploi|usage unique|plastique|\brep\b)|(?:réemploi|reemploi|usage unique|plastique|\brep\b).*emballages?/i,"JORFTEXT000041553759","alias"],
[/orientation pour la souveraineté alimentaire|orientation pour la souverainete alimentaire|souveraineté alimentaire.*renouvellement|souverainete alimentaire.*renouvellement/i,"JORFTEXT000051368091","alias"],
[/\bélectricité\b|\belectricite\b|\barenh\b|certificats d.économies d.énergie|certificats d.economies d.energie|commission de régulation de l.énergie|commission de regulation de l.energie/i,"LEGITEXT000023983208","code"],[/\btélécoms?\b|\btelecoms?\b|fibre optique|réseaux de communications électroniques|reseaux de communications electroniques|\barcep\b|réseau cuivre|reseau cuivre/i,"LEGITEXT000006070987","code"],
[/\bpfas\b|\bicpe\b|rejets industriels|économie circulaire|economie circulaire|responsabilité élargie du producteur|responsabilite elargie du producteur|\bdéchets\b|\bdechets\b/i,"LEGITEXT000006074220","code"],[/\bmédicaments?\b|\bmedicaments?\b|accès précoce|acces precoce|\bceps\b|\bremboursement\b|\bplfss\b/i,"LEGITEXT000006073189","code"],[/\bmédicaments?\b|\bmedicaments?\b|accès précoce|acces precoce|\bhas\b|\bansm\b/i,"LEGITEXT000006072665","code"],
[/commande publique|marchés publics|marches publics/i,"LEGITEXT000037701019","code"]
];
type Seed={key:string;origin:string};type Doc={id:string;j:"FR"|"EU";title:string;nature:string;url:string;date:string|null;text:string;root:boolean;origin:string;referenceOnly?:boolean};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const clip=(v:unknown,n:number)=>String(v??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,n).trim();
const norm=(v:unknown)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();
const arr=(v:any)=>Array.isArray(v)?[...new Set(v.map((x:any)=>String(x||"").trim()).filter(Boolean))]:[];
function serviceKey(){const r=Deno.env.get("SUPABASE_SECRET_KEYS");if(r){try{const o=JSON.parse(r),v=o?.default||Object.values(o||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function authorized(req:Request,s:any){const ts=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const{data,error}=await s.rpc("verify_dossier_corpus_internal_request",{p_path:PATH,p_timestamp:Number(ts),p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function positiveText(d:any){return[d.title,d.objective,d.context,...arr(d.watch_keywords),...arr(d.watch_priority_phrases)].join(" ");}
function excludedText(d:any){return arr(d.watch_excluded_keywords).join(" ");}
const STOP=new Set(["pour","avec","dans","sans","relatif","relative","application","modalites","dispositions","nouveau","nouvelle","cadre","entreprises","entreprise","france","europeen","europeenne","projet","suivre","anticiper","donnees","data"]);
function toks(v:unknown){return[...new Set(norm(v).split(" ").filter(x=>x.length>=4&&!STOP.has(x)&&!/^[0-9]+$/.test(x)))];}
function typeScore(t:string){const n=norm(t);return /^loi\b/.test(n)||/^ordonnance\b/.test(n)?5:/^decret\b/.test(n)?4:/^arrete\b/.test(n)?2:0;}
function explicitEU(t:string){const m=new Set<string>();for(const x of t.matchAll(/\bCELEX\s*:?\s*([0-9][0-9A-Z()_.-]{5,70})\b/gi))m.add(x[1].toUpperCase());for(const x of t.matchAll(/\bCOM\s*\(\s*(20\d{2})\s*\)\s*(\d{1,4})\b/gi))m.add(`5${x[1]}PC${String(x[2]).padStart(4,"0")}`);for(const x of t.matchAll(/\b(règlement|reglement|directive)\s*(?:\(ue\))?\s*(20\d{2})\s*\/\s*(\d{1,5})\b/gi)){const l=norm(x[1]).startsWith("directive")?"L":"R";m.add(`3${x[2]}${l}${String(x[3]).padStart(4,"0")}`);}return[...m];}
function explicitFR(t:string){const m=new Set<string>();for(const x of t.matchAll(/\b(JORFTEXT\d+|JORFARTI\d+|LEGIARTI\d+|LEGITEXT\d+|CNILTEXT\d+)\b/gi))m.add(x[1].toUpperCase());for(const x of t.matchAll(/\b(loi(?:\s+organique)?|decret|décret|ordonnance)\s+(?:n(?:o|°)?\s*)?(\d{2,4})\s*[-–]\s*(\d{1,5})\b/gi)){const n=norm(x[1]),ty=n.startsWith("decret")?"décret":n.startsWith("ordonnance")?"ordonnance":n.includes("organique")?"loi organique":"loi";m.add(`${ty} n° ${x[2]}-${x[3]}`);}return[...m];}
function financeSeedsText(t:string){const n=norm(t),o:string[]=[];for(const m of n.matchAll(/loi de finances(?: rectificative)?(?: pour)? (20\d{2})/g))o.push(`LF:${m[1]}`);for(const m of n.matchAll(/loi de financement de la securite sociale(?: pour)? (20\d{2})/g))o.push(`LFSS:${m[1]}`);for(const m of n.matchAll(/\blfss\s*(20\d{2})\b/g))o.push(`LFSS:${m[1]}`);return[...new Set(o)];}
async function namedFinanceSeeds(s:any,t:string){const out:Seed[]=[];for(const x of financeSeedsText(t)){const[type,year]=x.split(":"),needle=type==="LFSS"?`%financement de la sécurité sociale pour ${year}%`:`%finances pour ${year}%`;const{data}=await s.from("legal_catalog_fr").select("document_id,title,published_at").eq("nature","Loi").ilike("title",needle).order("published_at",{ascending:false}).limit(4);if(data?.[0])out.push({key:String(data[0].document_id),origin:"named_family"});}return out;}
function candidatePhrases(d:any){const weak=new Set(["agriculture","energie","sante","medicament","emballage","recyclage","fibre optique","couverture mobile","telecom","electricite","donnees","data","cloud"]);return[...new Set([...arr(d.watch_priority_phrases),...arr(d.watch_keywords),clip(d.title,180)].map(x=>clip(x,180)).filter(x=>{const n=norm(x);return n.length>=8&&!weak.has(n)&&toks(n).length>=2;}))].slice(0,14);}
function administrativeTitle(title:string){return /(nomination|delegation de signature|organisation transitoire|admission a la retraite|cession de parts|societe civile professionnelle|extension de l accord interprofessionnel|attributions du ministre|attributions du ministre delegue|composition du gouvernement|organisation de l administration centrale|personnels? des services|transfert definitif des services|services? transferes?|conseil national de|statut general des autorites administratives)/.test(norm(title));}
function individualArrete(title:string){return /(agrement d un systeme individuel|portant agrement d une societe|nomination|delegation|admission|cession|societe civile|retraite)/.test(norm(title));}
function structuralArrete(title:string,score:number,positiveTokens:Set<string>){const n=norm(title);if(individualArrete(title)||administrativeTitle(title))return false;const structural=/(modalites|cahier des charges|conditions|seuil|fixant|prescriptions|regles|reglementation|controle|autosurveillance|redevance)/.test(n);let shared=0;for(const t of toks(title))if(positiveTokens.has(t))shared++;return structural&&((score>=.85&&shared>=3)||shared>=4);}
function excludedCandidate(title:string,excluded:string){const ex=toks(excluded);if(!ex.length)return false;const tn=new Set(toks(title));let hit=0;for(const x of ex)if(tn.has(x))hit++;return hit>=2;}
function strongCatalogCandidate(title:string,score:number,positiveTokens:Set<string>){if(administrativeTitle(title))return false;let shared=0;for(const t of toks(title))if(positiveTokens.has(t))shared++;const ts=typeScore(title);return ts>=4&&((score>=.90&&shared>=3)||(score>=.55&&shared>=4));}
function decodeHtml(h:string){return h.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g," ").trim();}
async function fetchOfficial(url:string,ms=16000){const u=new URL(url);if(u.protocol!=="https:"||!/(legifrance\.gouv\.fr|eur-lex\.europa\.eu|publications\.europa\.eu)$/.test(u.hostname))throw new Error("official host rejected");const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),ms);try{const r=await fetch(u,{signal:ctl.signal,redirect:"follow",cache:"no-store",headers:{"User-Agent":"Mozilla/5.0 Myvor-Canonical/21","Accept-Language":"fr-FR,fr;q=0.9,en;q=0.6"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text();}finally{clearTimeout(tm);}}
async function euDoc(s:any,org:string,c:string,root:boolean,origin:string):Promise<Doc>{const{data:k}=await s.from("watch_items").select("id,title,nature,source_url,published_at").eq("organization_id",org).or(`source_url.ilike.%CELEX:${c}%,source_url.ilike.%/${c}%`).limit(1).maybeSingle();if(k){const{data:ct}=await s.from("watch_item_content").select("source_text").eq("watch_item_id",k.id).maybeSingle();if(String(ct?.source_text||"").length>=100)return{id:c,j:"EU",title:k.title||LABEL[c]||`Acte UE ${c}`,nature:k.nature||"Acte de l’Union européenne",url:k.source_url,date:k.published_at||null,text:String(ct.source_text),root,origin};}let last:any;for(const u of [`https://publications.europa.eu/resource/celex/${c}`,`https://eur-lex.europa.eu/legal-content/FR/TXT/HTML/?uri=CELEX:${c}`]){try{const h=await fetchOfficial(u),text=clip(decodeHtml(h),70000);if(text.length<100)throw new Error("empty");return{id:c,j:"EU",title:LABEL[c]||`Acte UE — CELEX ${c}`,nature:c.startsWith("5")?"Document préparatoire de l’Union européenne":/L\d{4}$/.test(c)?"Directive de l’Union européenne":"Règlement de l’Union européenne",url:`https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:${c}`,date:null,text,root,origin};}catch(e){last=e;}}throw last||new Error("EU unresolved");}
async function frDoc(s:any,ref:string,root:boolean,origin:string):Promise<Doc>{const direct=ref.match(/(JORFTEXT\d+|JORFARTI\d+|LEGIARTI\d+|LEGITEXT\d+|CNILTEXT\d+)/i)?.[1]?.toUpperCase();if(direct&&CODE[direct]){const c=CODE[direct];return{id:direct,j:"FR",title:c.title,nature:"Code — référence consolidée",url:c.url,date:null,text:`Référence officielle au ${c.title} sur Légifrance. Cette entrée identifie le socle codifié du dossier ; elle ne constitue pas une extraction exhaustive des articles applicables. Les dispositions précises doivent être vérifiées dans la source officielle et dans les textes d'application rattachés.`,root,origin,referenceOnly:true};}let row:any=null;if(direct){const{data}=await s.from("legal_catalog_fr").select("document_id,title,nature,source_url,published_at,source_text").eq("document_id",direct).maybeSingle();row=data;if(!row&&direct.startsWith("JORFTEXT")){try{const url=`https://www.legifrance.gouv.fr/jorf/id/${direct}`,h=await fetchOfficial(url),text=clip(decodeHtml(h),70000);if(text.length>=100)row={document_id:direct,title:`Texte ${direct}`,nature:"Texte juridique français",source_url:url,published_at:null,source_text:text};}catch{}}}else{const m=norm(ref).match(/\b(\d{2,4})\s+(\d{1,5})\b/);if(!m)throw new Error(`FR unresolved ${ref}`);const{data}=await s.from("legal_catalog_fr").select("document_id,title,nature,source_url,published_at,source_text").or(`title.ilike.%${m[1]}-${m[2]}%,title.ilike.%${m[1]} ${m[2]}%`).limit(10);row=(data||[])[0];}if(!row||String(row.source_text||"").length<80)throw new Error(`FR unresolved ${ref}`);return{id:String(row.document_id),j:"FR",title:clip(row.title,900),nature:row.nature||"Texte juridique français",url:row.source_url,date:row.published_at||null,text:String(row.source_text),root,origin};}
function relationBefore(t:string,i:number){const b=norm(t.slice(Math.max(0,i-420),i));if(/pris pour l application|pris en application|pour l application/.test(b.slice(-300)))return"IMPLEMENTS";if(/\btranspose|transposition\b/.test(b.slice(-300)))return"TRANSPOSES";if(/\babrog/.test(b.slice(-160)))return"REPEALS";if(/\bremplac/.test(b.slice(-160)))return"REPLACES";if(/\bmodif/.test(b.slice(-160)))return"MODIFIES";return"REFERENCES";}
function frChildren(t:string){const out:any[]=[],seen=new Set<string>();for(const x of t.slice(0,16000).matchAll(/\b(loi(?:\s+organique)?|decret|décret|ordonnance)\s+(?:n(?:o|°)?\s*)?(\d{2,4})\s*[-–]\s*(\d{1,5})\b/gi)){const n=norm(x[1]),ty=n.startsWith("decret")?"décret":n.startsWith("ordonnance")?"ordonnance":n.includes("organique")?"loi organique":"loi",key=`${ty} n° ${x[2]}-${x[3]}`,relation=relationBefore(t,x.index||0),k=`${norm(key)}:${relation}`;if(relation!=="REFERENCES"&&!seen.has(k)){seen.add(k);out.push({key,relation});}}return out.slice(0,10);}
function euChildren(t:string){const out:any[]=[],seen=new Set<string>();for(const x of t.slice(0,12000).matchAll(/\b(règlement|reglement|directive)\s*(?:\(ue\)|\(ce\))?\s*(?:n[°o]?\s*)?(20\d{2})\s*\/\s*(\d{1,5})\b/gi)){const l=norm(x[1]).startsWith("directive")?"L":"R",key=`3${x[2]}${l}${String(x[3]).padStart(4,"0")}`,relation=relationBefore(t,x.index||0),k=`${key}:${relation}`;if(!seen.has(k)){seen.add(k);out.push({key,relation});}}return out.slice(0,6);}
async function aiSeeds(d:any,allowFr:boolean,allowEu:boolean){const api=Deno.env.get("OPENAI_API_KEY")||"";if(!api||(!allowFr&&!allowEu))return{eu:[] as string[],fr:[] as string[]};const schema={type:"object",additionalProperties:false,properties:{celexes:{type:"array",items:{type:"string"},maxItems:4},french_refs:{type:"array",items:{type:"string"},maxItems:4}},required:["celexes","french_refs"]};try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${api}`,"Content-Type":"application/json"},body:JSON.stringify({model:Deno.env.get("OPENAI_DOSSIER_MODEL")||"gpt-5-mini",store:false,instructions:`Identifie uniquement les textes juridiques structurants directement applicables. ${allowFr?"Références françaises exactes loi/décret/ordonnance n° année-numéro ou identifiant Légifrance.":"Aucune référence française."} ${allowEu?"CELEX exacts.":"Aucun CELEX."} N'utilise jamais les expressions exclues. Pas de texte seulement thématique, pas d'acte individuel, aucune invention.`,input:JSON.stringify({title:d.title,objective:d.objective,context:d.context,keywords:arr(d.watch_keywords),priority:arr(d.watch_priority_phrases),excluded:arr(d.watch_excluded_keywords)}),reasoning:{effort:"low"},max_output_tokens:480,text:{verbosity:"low",format:{type:"json_schema",name:"canonical_seed_v21",strict:true,schema}}})});if(!r.ok)return{eu:[],fr:[]};const p=await r.json(),txt=typeof p.output_text==="string"?p.output_text:(p.output||[]).flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||"").join(""),o=JSON.parse(txt||"{}");return{eu:arr(o.celexes).map(x=>x.toUpperCase()).filter(x=>/^[356][0-9A-Z()_.-]{5,70}$/.test(x)),fr:arr(o.french_refs).map(x=>clip(x,180)).filter(x=>FR_AI.test(x))};}catch{return{eu:[],fr:[]};}}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=serviceKey();if(!url||!secret)return out({error:"Configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await authorized(req,s))return out({error:"Non autorisé"},401);const body=await req.json().catch(()=>null),id=String(body?.dossier_id||"");if(!UUID.test(id))return out({error:"dossier_id invalide"},400);const{data:d,error}=await s.from("dossiers").select("*").eq("id",id).maybeSingle();if(error||!d)return out({error:"Dossier introuvable"},404);
const positive=positiveText(d),excluded=excludedText(d),n=norm(positive),isDigital=/\bdigital omnibus\b/i.test(n),isNamedAI=/\bai act\b|règlement\s*(?:\(ue\))?\s*2024\s*\/\s*1689|reglement\s*(?:\(ue\))?\s*2024\s*\/\s*1689/i.test(positive),strictNamedEU=isDigital||isNamedAI,eu=new Map<string,Seed>(),fr=new Map<string,Seed>(),add=(m:Map<string,Seed>,k:string,origin:string)=>{if(k&&!m.has(norm(k)))m.set(norm(k),{key:k,origin});};
for(const[r,k,origin]of EU_ALIAS)if(r.test(n))add(eu,k,origin);for(const k of explicitEU(positive))add(eu,k,"explicit");for(const[r,k,origin]of FR_ALIAS)if(r.test(n)){if(strictNamedEU)continue;if(isDigital&&origin!=="complement")continue;add(fr,k,origin);}for(const k of explicitFR(positive))add(fr,k,"explicit");if(!strictNamedEU)for(const seed of await namedFinanceSeeds(s,positive))add(fr,seed.key,seed.origin);
const searchPhrases=candidatePhrases(d),{data:candidates}=await s.rpc("search_legal_catalog_fr",{p_queries:searchPhrases,p_limit:40});const diag=(candidates||[]).slice(0,16).map((x:any)=>({id:x.document_id,title:x.title,score:Number(x.score||0)})),positiveTokens=new Set(toks([d.title,d.objective,d.context,...arr(d.watch_priority_phrases),...arr(d.watch_keywords)].join(" ")));
if(!strictNamedEU){for(const c of candidates||[]){const title=String(c.title||""),score=Number(c.score||0);if(excludedCandidate(title,excluded))continue;if(strongCatalogCandidate(title,score,positiveTokens))add(fr,String(c.document_id),"catalog");else if(typeScore(title)===2&&structuralArrete(title,score,positiveTokens))add(fr,String(c.document_id),"catalog_structural_arrete");if(fr.size>=10)break;}}
const realFr=[...fr.values()].some(x=>!['complement','code'].includes(x.origin)),ai=await aiSeeds(d,!realFr&&!strictNamedEU,eu.size===0);if(!realFr&&!strictNamedEU)for(const k of ai.fr)add(fr,k,"ai");if(eu.size===0)for(const k of ai.eu)add(eu,k,"ai");
const docs=new Map<string,Doc>(),edges:any[]=[],fail:string[]=[];
for(const seed of [...eu.values()].slice(0,14)){try{const root=await euDoc(s,d.organization_id,seed.key,true,seed.origin);docs.set(`EU:${root.id}`,root);if(root.id==="52025PC0837")for(let i=0;i<OMNIBUS.length;i++){try{const c=await euDoc(s,d.organization_id,OMNIBUS[i],false,"omnibus");docs.set(`EU:${c.id}`,c);edges.push({source:`EU:${root.id}`,target:`EU:${c.id}`,relation:i<7?"MODIFIES":"REPEALS"});}catch{fail.push(`EU:${OMNIBUS[i]}`);}}}catch{fail.push(`EU:${seed.key}`);}}
const privacyTopic=/(rgpd|gdpr|données personnelles|donnees personnelles|consentement|prospection)/i.test(positive);
for(const seed of [...fr.values()].slice(0,12)){try{const root=await frDoc(s,seed.key,true,seed.origin);docs.set(`FR:${root.id}`,root);if(['complement','code','named_family'].includes(seed.origin))continue;for(const ch of frChildren(root.text)){try{const c=await frDoc(s,ch.key,false,"child");if(c.id!==root.id){docs.set(`FR:${c.id}`,c);edges.push({source:`FR:${root.id}`,target:`FR:${c.id}`,relation:ch.relation});}}catch{fail.push(`FR:${ch.key}`);}}for(const ch of euChildren(root.text)){const already=eu.has(norm(ch.key)),allowed=ch.relation==="TRANSPOSES"||already||(ch.key==="32016R0679"&&privacyTopic);if(!allowed)continue;try{const c=await euDoc(s,d.organization_id,ch.key,false,"fr_reference");docs.set(`EU:${c.id}`,c);edges.push({source:`FR:${root.id}`,target:`EU:${c.id}`,relation:ch.relation});}catch{fail.push(`EU:${ch.key}`);}}}catch{fail.push(`FR:${seed.key}`);}}
const kept=[...docs.values()];if(!kept.length)return out({ok:false,error:"Aucun texte structurant résolu — corpus précédent préservé",engine:ENGINE,candidates:diag,failures:fail},422);
kept.sort((a,b)=>a.j===b.j?Number(b.root)-Number(a.root):a.j==="FR"?-1:1);const refs=kept.map(x=>`${x.id} — ${x.title}`),now=new Date().toISOString();await s.from("dossiers").update({reference_texts:refs}).eq("id",d.id);const ids=new Map<string,string>(),urls:string[]=[];
for(const doc of kept){urls.push(doc.url);await s.from("watch_items").upsert({user_id:d.user_id,organization_id:d.organization_id,created_by:d.created_by||d.user_id,dossier_id:null,title:doc.title,nature:doc.nature,source_url:doc.url,source_name:doc.j==="EU"?"EUR-Lex / Cellar":"Légifrance — Corpus canonique",published_at:doc.date,urgency:"moyen"},{onConflict:"organization_id,source_url",ignoreDuplicates:true});const{data:item}=await s.from("watch_items").select("id,dossier_id").eq("organization_id",d.organization_id).eq("source_url",doc.url).maybeSingle();if(!item)continue;ids.set(`${doc.j}:${doc.id}`,String(item.id));await s.from("watch_item_content").upsert({watch_item_id:item.id,organization_id:d.organization_id,source_text:doc.text,source_text_chars:doc.text.length,fetched_at:now,updated_at:now},{onConflict:"watch_item_id"});const reason=`Corpus canonique ${doc.j} : ${doc.title} est ${doc.referenceOnly?"une référence codifiée officielle":doc.root?"un texte structurant vérifié":"directement relié à un texte structurant"} du dossier.`;await s.from("watch_item_dossier_links").upsert({watch_item_id:item.id,dossier_id:d.id,organization_id:d.organization_id,score:.999,status:"linked",reason,engine:ENGINE,updated_at:now},{onConflict:"watch_item_id,dossier_id"});if(!item.dossier_id||item.dossier_id===d.id)await s.from("watch_items").update({dossier_id:d.id,qualification_confidence:.999,qualification_reason:reason,qualified_at:now}).eq("id",item.id);}
const prune=await s.rpc("prune_legacy_official_links_by_canonical_history",{p_dossier_id:d.id,p_allowed_urls:urls});for(const e of edges){const a=ids.get(e.source),b=ids.get(e.target);if(a&&b)await s.from("normative_edges").upsert({organization_id:d.organization_id,source_watch_item_id:a,target_watch_item_id:b,relation_type:e.relation,evidence:"Relation explicitement résolue depuis une source officielle.",confidence:1,resolution_method:"dossier_corpus_auto_v21",updated_at:now},{onConflict:"source_watch_item_id,target_watch_item_id,relation_type"});}
return out({ok:true,engine:ENGINE,dossier_id:d.id,resolved:kept.length,resolved_fr:kept.filter(x=>x.j==="FR").length,resolved_eu:kept.filter(x=>x.j==="EU").length,fr_seeds:[...fr.values()],eu_seeds:[...eu.values()],candidates:diag,canonical_refs:refs,relations:edges,pruned:prune.data||null,failures:fail});
});