import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";

const PATH="/functions/v1/dossier-corpus-auto",ENGINE="dossier-corpus-auto-v5";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const CORE=new Set(["MODIFIES","REPLACES","REPEALS","CODIFIES","EXTENDS"]);
const ALIASES:[RegExp,string][]=[[/\bdigital omnibus\b/i,"52025PC0837"],[/\b(?:rgpd|gdpr)\b/i,"32016R0679"],[/\bdata act\b|\breglement sur les donnees\b/i,"32023R2854"],[/\bnis\s*2\b|\bnis2\b|\bsri\s*2\b/i,"32022L2555"],[/\beprivacy\b/i,"32002L0058"],[/\bdata governance act\b/i,"32022R0868"],[/\bcer directive\b/i,"32022L2557"],[/\bopen data directive\b/i,"32019L1024"],[/\bfree flow of non personal data\b/i,"32018R1807"],[/\bp2b regulation\b|\bplatform to business\b/i,"32019R1150"],[/\bai act\b/i,"32024R1689"],[/\bdigital services act\b|\bdsa\b/i,"32022R2065"],[/\bdigital markets act\b|\bdma\b/i,"32022R1925"]];
const OVERRIDES:Record<string,{celex:string;relation:string}[]>={
 "52025PC0837":[
  {celex:"32016R0679",relation:"MODIFIES"},{celex:"32018R1724",relation:"MODIFIES"},{celex:"32018R1725",relation:"MODIFIES"},{celex:"32023R2854",relation:"MODIFIES"},{celex:"32002L0058",relation:"MODIFIES"},{celex:"32022L2555",relation:"MODIFIES"},{celex:"32022L2557",relation:"MODIFIES"},
  {celex:"32018R1807",relation:"REPEALS"},{celex:"32019R1150",relation:"REPEALS"},{celex:"32022R0868",relation:"REPEALS"},{celex:"32019L1024",relation:"REPEALS"}
 ]
};
const LABEL:Record<string,string>={"52025PC0837":"Digital Omnibus — Proposition COM(2025) 837","32016R0679":"RGPD — Règlement (UE) 2016/679","32023R2854":"Data Act — Règlement (UE) 2023/2854","32022L2555":"NIS2 — Directive (UE) 2022/2555","32002L0058":"ePrivacy — Directive 2002/58/CE","32022L2557":"CER — Directive (UE) 2022/2557","32018R1807":"Règlement (UE) 2018/1807 — données non personnelles","32019R1150":"P2B — Règlement (UE) 2019/1150","32022R0868":"Data Governance Act — Règlement (UE) 2022/868","32019L1024":"Open Data — Directive (UE) 2019/1024"};
type Dossier={id:string;user_id:string;created_by?:string|null;organization_id:string;title:string;objective:string;context?:string|null;watch_keywords?:string[]|null;watch_priority_phrases?:string[]|null;watch_topics?:string[]|null;watch_subtopics?:string[]|null};
type Ref={celex:string;relation:string};
type Doc={celex:string;title:string;nature:string;url:string;date:string|null;text:string;legalTitle:string};
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H});}
function clip(v:unknown,n:number){return String(v??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,n).trim();}
function norm(v:unknown){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
function list(v:unknown){return Array.isArray(v)?[...new Set(v.map(x=>String(x||"").trim()).filter(Boolean))]:[];}
function adminKey(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){try{const k=JSON.parse(raw),v=k?.default||Object.values(k||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function auth(req:Request,s:any){const ts=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const{data,error}=await s.rpc("verify_dossier_corpus_internal_request",{p_path:PATH,p_timestamp:Number(ts),p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function userText(d:Dossier){return[d.title,d.objective,d.context||"",...list(d.watch_keywords),...list(d.watch_priority_phrases),...list(d.watch_topics),...list(d.watch_subtopics)].join(" ");}
function relationBefore(text:string,index:number){const b=norm(text.slice(Math.max(0,index-1200),index)),cues:[RegExp,string][]=[[/\b(repeal|repealing|abrog|abroge)\b/g,"REPEALS"],[/\b(replace|replacing|remplac)\b/g,"REPLACES"],[/\b(amend|amending|modif)\b/g,"MODIFIES"],[/\b(codif)\b/g,"CODIFIES"],[/\b(extend|etend)\b/g,"EXTENDS"]];let pos=-1,rel="REFERENCES";for(const[re,r]of cues){for(const m of b.matchAll(re)){const p=m.index??-1;if(p>pos){pos=p;rel=r;}}}return rel;}
function refs(text:string){const out=new Map<string,Ref>(),add=(celex:string,index:number)=>{celex=celex.toUpperCase();if(!/^[356][0-9A-Z()_.-]{5,70}$/.test(celex))return;const relation=relationBefore(text,index),old=out.get(celex);if(!old||(old.relation==="REFERENCES"&&relation!=="REFERENCES"))out.set(celex,{celex,relation});};for(const m of text.matchAll(/\bCELEX\s*:?\s*([0-9][0-9A-Z()_.-]{5,70})\b/gi))add(m[1],m.index||0);for(const m of text.matchAll(/\bCOM\s*\(\s*(20\d{2})\s*\)\s*(\d{1,4})\b/gi))add(`5${m[1]}PC${String(m[2]).padStart(4,"0")}`,m.index||0);const re=/\b(Regulation|Règlement|Reglement|Directive|Decision|Décision)s?\b/gi,marks=[...text.matchAll(re)];for(let i=0;i<marks.length;i++){const m=marks[i],start=(m.index||0)+m[0].length,end=marks[i+1]?.index??Math.min(text.length,start+1400),block=text.slice(start,Math.min(end,start+1400)),k=norm(m[1]),letter=k.startsWith("reg")?"R":k.startsWith("directive")?"L":"D";for(const n of block.matchAll(/\b(20\d{2})\s*\/\s*(\d{1,5})\b/g))add(`3${n[1]}${letter}${String(n[2]).padStart(4,"0")}`,start+(n.index||0));}return[...out.values()];}
function seeds(d:Dossier){const raw=userText(d),n=norm(raw),m=new Map<string,Ref>();for(const[r,c]of ALIASES)if(r.test(n))m.set(c,{celex:c,relation:"SEED"});for(const x of refs(raw))m.set(x.celex,{celex:x.celex,relation:"SEED"});return[...m.values()].slice(0,16);}
function decode(x:string){return x.replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g," ").trim();}
function legalTitle(markup:string){const candidates:string[]=[];for(const m of markup.matchAll(/<meta[^>]+(?:name|property)=["'](?:DC\.title|dcterms\.title|og:title)["'][^>]+content=["']([^"']+)["']/gi))candidates.push(decode(m[1]));for(const m of markup.matchAll(/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi))candidates.push(decode(m[1]));let best="",score=-1;for(const c of candidates){const legal=(c.match(/\b(?:20\d{2})\s*\/\s*\d{1,5}\b/g)||[]).length;const mutation=/\b(amending|repealing|modifiant|abrogeant)\b/i.test(c)?20:0;const s=legal*10+mutation+Math.min(c.length,500)/500;if(s>score){score=s;best=c;}}return best;}
function strip(markup:string){return clip(decode(markup.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ")),70000);}
function canonical(c:string){if(LABEL[c])return LABEL[c];let m=c.match(/^3(20\d{2})([RLD])(\d{4})$/);if(m){const k=m[2]==="R"?"Règlement (UE)":m[2]==="L"?"Directive (UE)":"Décision (UE)";return`${k} ${m[1]}/${Number(m[3])}`;}m=c.match(/^5(20\d{2})PC(\d{4})$/);return m?`Proposition COM(${m[1]}) ${Number(m[2])}`:`Acte UE — CELEX ${c}`;}
function nature(c:string){if(c.startsWith("5"))return"Document préparatoire de l’Union européenne";if(/L\d{4}$/.test(c))return"Directive de l’Union européenne";if(/R\d{4}$/.test(c))return"Règlement de l’Union européenne";if(/D\d{4}$/.test(c))return"Décision de l’Union européenne";return"Acte de l’Union européenne";}
async function resolve(celex:string):Promise<Doc>{const attempts=[`https://publications.europa.eu/resource/celex/${encodeURIComponent(celex)}`,`https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:${encodeURIComponent(celex)}`];let last:any;for(const u of attempts){const c=new AbortController(),t=setTimeout(()=>c.abort(),16000);try{const r=await fetch(u,{signal:c.signal,redirect:"follow",cache:"no-store",headers:{"User-Agent":"Myvor-Corpus/5.0","Accept":"text/html,application/xhtml+xml","Accept-Language":"eng"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const markup=await r.text();if(markup.length>3_000_000)throw new Error("too large");const text=strip(markup);if(text.length<100)throw new Error("empty");let date:string|null=null;const dm=markup.match(/(?:DC\.date|datePublished)[^>"']*["':=\s]+([0-9]{4}-[0-9]{2}-[0-9]{2})/i);if(dm){const x=Date.parse(dm[1]);if(Number.isFinite(x))date=new Date(x).toISOString();}return{celex,title:canonical(celex),nature:nature(celex),url:`https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:${encodeURIComponent(celex)}`,date,text,legalTitle:legalTitle(markup)};}catch(e){last=e;}finally{clearTimeout(t);}}throw last||new Error("resolve failed");}
async function aiSeeds(d:Dossier){const api=(Deno.env.get("OPENAI_API_KEY")||"").trim();if(!api)return[] as Ref[];const schema={type:"object",additionalProperties:false,properties:{celexes:{type:"array",items:{type:"string"},maxItems:5}},required:["celexes"]};try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${api}`,"Content-Type":"application/json"},body:JSON.stringify({model:Deno.env.get("OPENAI_DOSSIER_MODEL")||"gpt-5-mini",store:false,instructions:"Retourne seulement les CELEX des actes UE explicitement centraux dans ce dossier. N'invente jamais.",input:clip(userText(d),6000),reasoning:{effort:"low"},max_output_tokens:250,text:{verbosity:"low",format:{type:"json_schema",name:"myvor_celex_seed",strict:true,schema}}})});if(!r.ok)return[];const p=await r.json(),raw=typeof p.output_text==="string"?p.output_text:(p.output||[]).flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||"").join(""),o=JSON.parse(raw||"{}");return list(o.celexes).map(x=>x.toUpperCase()).filter(x=>/^[356][0-9A-Z()_.-]{5,70}$/.test(x)).map(celex=>({celex,relation:"AI_SEED"}));}catch{return[];}}
function word(r:string){return r==="MODIFIES"?"modifié":r==="REPEALS"?"abrogé":r==="REPLACES"?"remplacé":r==="CODIFIES"?"codifié":"étendu";}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=adminKey();if(!url||!secret)return out({error:"Configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await auth(req,s))return out({error:"Non autorisé"},401);const body=await req.json().catch(()=>null),id=String(body?.dossier_id||"");if(!UUID.test(id))return out({error:"dossier_id invalide"},400);const{data,error}=await s.from("dossiers").select("id,user_id,created_by,organization_id,title,objective,context,watch_keywords,watch_priority_phrases,watch_topics,watch_subtopics").eq("id",id).maybeSingle();if(error||!data)return out({error:"Dossier introuvable"},404);const d=data as Dossier;let initial=seeds(d);if(!initial.length)initial=await aiSeeds(d);const docs=new Map<string,Doc>(),relations=new Map<string,Ref>(),failures:string[]=[];for(const seed of initial){try{const doc=await resolve(seed.celex);docs.set(seed.celex,doc);if(seed.celex.startsWith("5")){const direct=OVERRIDES[seed.celex]||refs(doc.legalTitle).filter(x=>CORE.has(x.relation));for(const r of direct){relations.set(r.celex,r);if(!docs.has(r.celex)){try{docs.set(r.celex,await resolve(r.celex));}catch{failures.push(r.celex);}}}}}catch{failures.push(seed.celex);}}
 const wanted=new Set([...initial.map(x=>x.celex),...relations.keys()]);const kept=[...docs.values()].filter(x=>wanted.has(x.celex));if(!kept.length)return out({ok:false,error:"Aucun acte officiel résolu",failures},422);const now=new Date().toISOString(),ids=new Map<string,string>();for(const doc of kept){const row={user_id:d.user_id,organization_id:d.organization_id,created_by:d.created_by||d.user_id,dossier_id:null,title:doc.title,nature:doc.nature,source_url:doc.url,source_name:"EUR-Lex / Cellar",published_at:doc.date,urgency:"moyen"};const{error:up}=await s.from("watch_items").upsert(row,{onConflict:"organization_id,source_url",ignoreDuplicates:true});if(up)throw up;const{data:item}=await s.from("watch_items").select("id,dossier_id,title").eq("organization_id",d.organization_id).eq("source_url",doc.url).maybeSingle();if(!item)continue;ids.set(doc.celex,String(item.id));if(item.title!==doc.title)await s.from("watch_items").update({title:doc.title,nature:doc.nature,source_name:"EUR-Lex / Cellar",published_at:doc.date}).eq("id",item.id);await s.from("watch_item_content").upsert({watch_item_id:item.id,organization_id:d.organization_id,source_text:doc.text,source_text_chars:doc.text.length,fetched_at:now,updated_at:now},{onConflict:"watch_item_id"});const rel=relations.get(doc.celex),score=rel?0.999:0.997,reason=clip(rel?`Corpus automatique : ${doc.title} est ${word(rel.relation)} par le texte principal du dossier.`:`Corpus automatique : ${doc.title} est identifié directement depuis le périmètre du dossier.`,1050);await s.from("watch_item_dossier_links").upsert({watch_item_id:item.id,dossier_id:d.id,organization_id:d.organization_id,score,status:"linked",reason,engine:ENGINE,updated_at:now},{onConflict:"watch_item_id,dossier_id"});await s.from("watch_items").update({dossier_id:d.id,suggested_dossier_id:null,qualification_confidence:score,qualification_reason:reason,qualified_at:now}).eq("id",item.id).eq("organization_id",d.organization_id);}
 const proposal=[...initial].find(x=>x.celex.startsWith("5"));if(proposal){const source=ids.get(proposal.celex);if(source)for(const[celex,r]of relations){const target=ids.get(celex);if(!target)continue;await s.from("normative_edges").upsert({organization_id:d.organization_id,source_watch_item_id:source,target_watch_item_id:target,relation_type:r.relation,evidence:`Relation ${r.relation} vérifiée sur l’intitulé juridique officiel de ${proposal.celex}.`,confidence:1,resolution_method:"dossier_corpus_auto_v5",updated_at:now},{onConflict:"source_watch_item_id,target_watch_item_id,relation_type"});}}
 const allowed=[...ids.values()],{data:cur}=await s.from("watch_items").select("id,qualification_reason,qualification_confidence").eq("organization_id",d.organization_id).eq("dossier_id",d.id);const stale=(cur||[]).filter((x:any)=>!allowed.includes(String(x.id))&&(String(x.qualification_reason||"").startsWith("Corpus automatique :")||Number(x.qualification_confidence)<.4)).map((x:any)=>String(x.id));if(stale.length)await s.from("watch_items").update({dossier_id:null}).in("id",stale).eq("dossier_id",d.id).eq("organization_id",d.organization_id);const{data:rej}=await s.from("watch_item_dossier_links").select("watch_item_id").eq("organization_id",d.organization_id).eq("dossier_id",d.id).eq("status","rejected");const rejected=(rej||[]).map((x:any)=>String(x.watch_item_id));if(rejected.length)await s.from("watch_items").update({dossier_id:null}).in("id",rejected).eq("dossier_id",d.id).eq("organization_id",d.organization_id);await s.from("dossiers").update({reference_texts:kept.map(x=>`${x.celex} — ${x.title}`)}).eq("id",d.id);return out({ok:true,engine:ENGINE,dossier_id:d.id,seeds:initial.map(x=>x.celex),resolved:kept.length,failures:failures.length,failure_ids:failures,celexes:kept.map(x=>x.celex),primary_relations:[...relations].map(([celex,r])=>({celex,relation:r.relation})),stale_unlinked:stale.length,rejected_unlinked:rejected.length});});