import "jsr:@supabase/functions-js@2/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";

const PATH="/functions/v1/dossier-corpus-auto", ENGINE="dossier-corpus-auto-v7-fr-eu";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const CORE=new Set(["MODIFIES","REPEALS","REPLACES","CODIFIES","EXTENDS"]);
const EU_ALIAS:[RegExp,string][]=[[/\bdigital omnibus\b/i,"52025PC0837"],[/\b(?:rgpd|gdpr)\b/i,"32016R0679"],[/\bdata act\b/i,"32023R2854"],[/\bnis\s*2\b|\bnis2\b/i,"32022L2555"],[/\beprivacy\b/i,"32002L0058"],[/\bdata governance act\b/i,"32022R0868"],[/\bcer directive\b/i,"32022L2557"],[/\bopen data directive\b/i,"32019L1024"],[/\bfree flow of non personal data\b/i,"32018R1807"],[/\bp2b regulation\b|\bplatform to business\b/i,"32019R1150"],[/\bai act\b/i,"32024R1689"],[/\bdigital services act\b|\bdsa\b/i,"32022R2065"],[/\bdigital markets act\b|\bdma\b/i,"32022R1925"]];
const FR_ALIAS:[RegExp,string][]=[[/\b(?:loi )?informatique et libertes\b/i,"loi n° 78-17"],[/\b(?:loi )?sren\b|\bsecuriser et reguler l espace numerique\b/i,"loi n° 2024-449"],[/\b(?:loi )?lcen\b|\bconfiance dans l economie numerique\b/i,"loi n° 2004-575"],[/\brepublique numerique\b/i,"loi n° 2016-1321"],[/\bsapin\s*2\b/i,"loi n° 2016-1691"]];
const OVERRIDE:Record<string,{key:string;relation:string}[]>={"52025PC0837":[{key:"32016R0679",relation:"MODIFIES"},{key:"32018R1724",relation:"MODIFIES"},{key:"32018R1725",relation:"MODIFIES"},{key:"32023R2854",relation:"MODIFIES"},{key:"32002L0058",relation:"MODIFIES"},{key:"32022L2555",relation:"MODIFIES"},{key:"32022L2557",relation:"MODIFIES"},{key:"32018R1807",relation:"REPEALS"},{key:"32019R1150",relation:"REPEALS"},{key:"32022R0868",relation:"REPEALS"},{key:"32019L1024",relation:"REPEALS"}]};
const LABEL:Record<string,string>={"52025PC0837":"Digital Omnibus — Proposition COM(2025) 837","32016R0679":"RGPD — Règlement (UE) 2016/679","32023R2854":"Data Act — Règlement (UE) 2023/2854","32022L2555":"NIS2 — Directive (UE) 2022/2555","32002L0058":"ePrivacy — Directive 2002/58/CE","32022L2557":"CER — Directive (UE) 2022/2557","32018R1807":"Règlement (UE) 2018/1807 — données non personnelles","32019R1150":"P2B — Règlement (UE) 2019/1150","32022R0868":"Data Governance Act — Règlement (UE) 2022/868","32019L1024":"Open Data — Directive (UE) 2019/1024"};

type Dossier={id:string;user_id:string;created_by?:string|null;organization_id:string;title:string;objective:string;context:string;watch_keywords:string[];watch_priority_phrases:string[];watch_topics:string[];watch_subtopics:string[]};
type R={key:string;relation:string};
type Doc={id:string;j:"EU"|"FR";title:string;nature:string;url:string;date:string|null;text:string;root:boolean;relation:string;legalTitle:string};
const out=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const clip=(v:unknown,n:number)=>String(v??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,n).trim();
const norm=(v:unknown)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();
const arr=(v:unknown)=>Array.isArray(v)?[...new Set(v.map(x=>String(x||"").trim()).filter(Boolean))]:[];
function key(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){try{const o=JSON.parse(raw),v=o?.default||Object.values(o||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function auth(req:Request,s:any){const ts=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const{data,error}=await s.rpc("verify_dossier_corpus_internal_request",{p_path:PATH,p_timestamp:Number(ts),p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function txt(d:Dossier){return[d.title,d.objective,d.context,...arr(d.watch_keywords),...arr(d.watch_priority_phrases),...arr(d.watch_topics),...arr(d.watch_subtopics)].join(" ");}
function relBefore(t:string,i:number){const b=norm(t.slice(Math.max(0,i-800),i)),c:[RegExp,string][]=[[/\b(repeal|repealing|abrog|abrogeant)\b/g,"REPEALS"],[/\b(replace|remplac)\b/g,"REPLACES"],[/\b(amend|amending|modif|modifiant)\b/g,"MODIFIES"],[/\bcodif\b/g,"CODIFIES"],[/\bextend|etend\b/g,"EXTENDS"]];let p=-1,r="REFERENCES";for(const[x,y]of c)for(const m of b.matchAll(x))if((m.index??-1)>p){p=m.index??-1;r=y;}return r;}
function euRefs(t:string){const m=new Map<string,R>(),add=(k:string,i:number)=>{k=k.toUpperCase();if(!/^[356][0-9A-Z()_.-]{5,70}$/.test(k))return;const r=relBefore(t,i),o=m.get(k);if(!o||(o.relation==="REFERENCES"&&r!=="REFERENCES"))m.set(k,{key:k,relation:r});};for(const x of t.matchAll(/\bCELEX\s*:?\s*([0-9][0-9A-Z()_.-]{5,70})\b/gi))add(x[1],x.index||0);for(const x of t.matchAll(/\bCOM\s*\(\s*(20\d{2})\s*\)\s*(\d{1,4})\b/gi))add(`5${x[1]}PC${String(x[2]).padStart(4,"0")}`,x.index||0);const marks=[...t.matchAll(/\b(Regulation|Règlement|Reglement|Directive|Decision|Décision)s?\b/gi)];for(let i=0;i<marks.length;i++){const x=marks[i],start=(x.index||0)+x[0].length,end=marks[i+1]?.index??Math.min(t.length,start+1200),block=t.slice(start,Math.min(end,start+1200)),n=norm(x[1]),letter=n.startsWith("reg")?"R":n.startsWith("directive")?"L":"D";for(const y of block.matchAll(/\b(20\d{2})\s*\/\s*(\d{1,5})\b/g))add(`3${y[1]}${letter}${String(y[2]).padStart(4,"0")}`,start+(y.index||0));}return[...m.values()];}
function frRefs(t:string){const m=new Map<string,R>(),add=(k:string,i:number)=>{const r=relBefore(t,i),nk=norm(k),o=m.get(nk);if(!o||(o.relation==="REFERENCES"&&r!=="REFERENCES"))m.set(nk,{key:clip(k,120),relation:r});};for(const x of t.matchAll(/\b(JORFTEXT\d+|JORFARTI\d+|JORFSCTA\d+|LEGIARTI\d+|LEGITEXT\d+|LEGISCTA\d+|CNILTEXT\d+)\b/gi))add(x[1].toUpperCase(),x.index||0);for(const x of t.matchAll(/\b(loi(?:\s+organique)?|decret|décret|ordonnance)\s+(?:n(?:o|°)?\s*)?(\d{2,4})\s*[-–]\s*(\d{1,5})\b/gi)){const n=norm(x[1]),type=n.startsWith("decret")?"décret":n.startsWith("ordonnance")?"ordonnance":n.includes("organique")?"loi organique":"loi";add(`${type} n° ${x[2]}-${x[3]}`,x.index||0);}return[...m.values()];}
function seeds(d:Dossier){const raw=txt(d),n=norm(raw),em=new Map<string,R>(),fm=new Map<string,R>();for(const[r,k]of EU_ALIAS)if(r.test(n))em.set(k,{key:k,relation:"SEED"});for(const x of euRefs(raw))em.set(x.key,{key:x.key,relation:"SEED"});for(const[r,k]of FR_ALIAS)if(r.test(n))fm.set(norm(k),{key:k,relation:"SEED"});for(const x of frRefs(raw))fm.set(norm(x.key),{key:x.key,relation:"SEED"});return{eu:[...em.values()].slice(0,16),fr:[...fm.values()].slice(0,10)};}
function decode(x:string){return x.replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g," ").trim();}
const strip=(h:string)=>clip(decode(h.replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ")),70000);
function pageTitle(h:string){const a:string[]=[];for(const m of h.matchAll(/<meta[^>]+(?:name|property)=["'](?:DC\.title|dcterms\.title|og:title)["'][^>]+content=["']([^"']+)["']/gi))a.push(decode(m[1]));for(const m of h.matchAll(/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi))a.push(decode(m[1]));return a.sort((x,y)=>y.length-x.length)[0]||"";}
function euLabel(c:string){if(LABEL[c])return LABEL[c];let m=c.match(/^3(20\d{2})([RLD])(\d{4})$/);if(m)return`${m[2]==="R"?"Règlement (UE)":m[2]==="L"?"Directive (UE)":"Décision (UE)"} ${m[1]}/${Number(m[3])}`;m=c.match(/^5(20\d{2})PC(\d{4})$/);return m?`Proposition COM(${m[1]}) ${Number(m[2])}`:`Acte UE — CELEX ${c}`;}
function euNature(c:string){return c.startsWith("5")?"Document préparatoire de l’Union européenne":/L\d{4}$/.test(c)?"Directive de l’Union européenne":/R\d{4}$/.test(c)?"Règlement de l’Union européenne":/D\d{4}$/.test(c)?"Décision de l’Union européenne":"Acte de l’Union européenne";}
async function euDoc(c:string,root:boolean,relation="SEED"):Promise<Doc>{let last:any;for(const u of [`https://publications.europa.eu/resource/celex/${encodeURIComponent(c)}`,`https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:${encodeURIComponent(c)}`]){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),15000);try{const r=await fetch(u,{signal:ctl.signal,redirect:"follow",cache:"no-store",headers:{"User-Agent":"Myvor-Corpus/7.0","Accept-Language":"eng"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const h=await r.text(),text=strip(h);if(text.length<100)throw new Error("empty");return{id:c,j:"EU",title:euLabel(c),nature:euNature(c),url:`https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=CELEX:${c}`,date:null,text,root,relation,legalTitle:pageTitle(h)};}catch(e){last=e;}finally{clearTimeout(tm);}}throw last||new Error("EU unresolved");}
const frId=(u:string)=>(u.match(/(JORFTEXT\d+|JORFARTI\d+|JORFSCTA\d+|LEGIARTI\d+|LEGITEXT\d+|LEGISCTA\d+|CNILTEXT\d+)/i)?.[1]||"").toUpperCase();
function frNature(t:string){const n=norm(t);return n.startsWith("loi organique")?"Loi organique":n.startsWith("loi")?"Loi":n.startsWith("decret")?"Décret":n.startsWith("ordonnance")?"Ordonnance":n.startsWith("arrete")?"Arrêté":n.includes("deliberation")?"Délibération":"Texte juridique français";}
async function fetchFr(u:string){const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),12000);try{const r=await fetch(u,{signal:ctl.signal,redirect:"follow",cache:"no-store",headers:{"User-Agent":"Mozilla/5.0 Myvor-Canonical-France/2.0","Accept-Language":"fr-FR,fr;q=0.9"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text();}finally{clearTimeout(tm);}}
function exactTitle(ref:string,title:string,url:string){const direct=ref.match(/(JORFTEXT\d+|JORFARTI\d+|JORFSCTA\d+|LEGIARTI\d+|LEGITEXT\d+|LEGISCTA\d+|CNILTEXT\d+)/i)?.[1]?.toUpperCase();if(direct)return frId(url)===direct;const m=norm(ref).match(/\b(\d{2,4})\s+(\d{1,5})\b/);if(!m)return false;const t=norm(title),type=norm(ref).startsWith("decret")?"decret":norm(ref).startsWith("ordonnance")?"ordonnance":norm(ref).startsWith("loi")?"loi":"";return t.includes(`${m[1]} ${m[2]}`)&&(!type||t.startsWith(type)||t.includes(` ${type} `));}
async function frFromDb(s:any,org:string,ref:string){const direct=ref.match(/(JORFTEXT\d+|JORFARTI\d+|JORFSCTA\d+|LEGIARTI\d+|LEGITEXT\d+|LEGISCTA\d+|CNILTEXT\d+)/i)?.[1];let q=s.from("watch_items").select("id,title,nature,source_url,published_at").eq("organization_id",org).ilike("source_url","%legifrance.gouv.fr%");if(direct)q=q.ilike("source_url",`%${direct}%`);else{const m=norm(ref).match(/\b(\d{2,4})\s+(\d{1,5})\b/);if(!m)return null;q=q.or(`title.ilike.%${m[1]}-${m[2]}%,title.ilike.%${m[1]} ${m[2]}%`);}const{data}=await q.limit(20);const hit=(data||[]).find((x:any)=>exactTitle(ref,String(x.title||""),String(x.source_url||"")));if(!hit)return null;const{data:c}=await s.from("watch_item_content").select("source_text").eq("watch_item_id",hit.id).maybeSingle();return{...hit,text:String(c?.source_text||"")};}
async function frSearch(ref:string){const u=`https://www.legifrance.gouv.fr/search/all?query=${encodeURIComponent(ref)}&searchField=ALL&tab_selection=all&page=1`,h=await fetchFr(u);for(const m of h.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const url=new URL(m[1],"https://www.legifrance.gouv.fr").toString(),title=decode(m[2]);if(/(JORFTEXT|JORFARTI|LEGIARTI|LEGITEXT|CNILTEXT)/i.test(url)&&title.length>7&&exactTitle(ref,title,url))return{url,title};}return null;}
async function frDoc(s:any,org:string,ref:string,root:boolean,relation="SEED"):Promise<Doc>{let hit=await frFromDb(s,org,ref),url="",title="",text="",date:string|null=null;if(hit){url=hit.source_url;title=hit.title;text=hit.text;date=hit.published_at||null;}else{const h=await frSearch(ref);if(!h)throw new Error(`FR unresolved ${ref}`);url=h.url;title=h.title;}if(!text){const h=await fetchFr(url);text=strip(h);const pt=pageTitle(h);if(pt&&pt.length<950)title=pt;}const id=frId(url);if(!id||text.length<80)throw new Error(`FR invalid ${ref}`);return{id,j:"FR",title:clip(title,900),nature:frNature(title),url,date,text,root,relation,legalTitle:title};}
async function ai(d:Dossier,wEU:boolean,wFR:boolean){const api=Deno.env.get("OPENAI_API_KEY")||"";if(!api)return{eu:[] as R[],fr:[] as R[]};const schema={type:"object",additionalProperties:false,properties:{celexes:{type:"array",items:{type:"string"},maxItems:4},french_refs:{type:"array",items:{type:"string"},maxItems:4}},required:["celexes","french_refs"]};try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${api}`,"Content-Type":"application/json"},body:JSON.stringify({model:Deno.env.get("OPENAI_DOSSIER_MODEL")||"gpt-5-mini",store:false,instructions:`Retourne uniquement des actes juridiques directement centraux et précisément identifiables. ${wEU?"CELEX UE exacts autorisés.":"Aucun CELEX."} ${wFR?"Références françaises exactes seulement: loi/décret/ordonnance n° année-numéro ou identifiant Légifrance.":"Aucune référence française."} Aucun texte seulement thématique. N'invente jamais.`,input:clip(txt(d),6000),reasoning:{effort:"low"},max_output_tokens:350,text:{verbosity:"low",format:{type:"json_schema",name:"legal_seed_v7",strict:true,schema}}})});if(!r.ok)return{eu:[],fr:[]};const p=await r.json(),raw=typeof p.output_text==="string"?p.output_text:(p.output||[]).flatMap((x:any)=>x.content||[]).map((x:any)=>x.text||"").join(""),o=JSON.parse(raw||"{}");return{eu:arr(o.celexes).map(x=>x.toUpperCase()).filter(x=>/^[356][0-9A-Z()_.-]{5,70}$/.test(x)).map(key=>({key,relation:"AI_SEED"})),fr:arr(o.french_refs).filter(x=>/^(?:loi(?: organique)?|décret|decret|ordonnance)\s+n?[°o]?\s*\d{2,4}[-–]\d{1,5}$|^(?:JORFTEXT|JORFARTI|JORFSCTA|LEGIARTI|LEGITEXT|LEGISCTA|CNILTEXT)\d+$/i.test(x.replace(/\s+/g," "))).map(key=>({key,relation:"AI_SEED"}))};}catch{return{eu:[],fr:[]};}}
const verb=(r:string)=>r==="MODIFIES"?"modifié":r==="REPEALS"?"abrogé":r==="REPLACES"?"remplacé":r==="CODIFIES"?"codifié":"étendu";
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=key();if(!url||!secret)return out({error:"Configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await auth(req,s))return out({error:"Non autorisé"},401);const body=await req.json().catch(()=>null),id=String(body?.dossier_id||"");if(!UUID.test(id))return out({error:"dossier_id invalide"},400);const{data,error}=await s.from("dossiers").select("id,user_id,created_by,organization_id,title,objective,context,watch_keywords,watch_priority_phrases,watch_topics,watch_subtopics").eq("id",id).maybeSingle();if(error||!data)return out({error:"Dossier introuvable"},404);const d=data as Dossier,raw=txt(d);let{eu,fr}=seeds(d);const frCtx=/\b(france|francais|français|legifrance|cnil|loi|decret|décret|ordonnance|code)\b/i.test(raw);if(!eu.length||(!fr.length&&frCtx)){const a=await ai(d,!eu.length,!fr.length&&frCtx);if(!eu.length)eu=a.eu;if(!fr.length&&frCtx)fr=a.fr;}
 const docs=new Map<string,Doc>(),edges:{source:string;target:string;relation:string;j:string}[]=[],fail:string[]=[];
 for(const seed of eu){try{const root=await euDoc(seed.key,true,seed.relation);docs.set(`EU:${root.id}`,root);const rs=OVERRIDE[seed.key]||(seed.key.startsWith("5")?euRefs(root.legalTitle).filter(x=>CORE.has(x.relation)):[]);for(const x of rs.slice(0,16)){if(x.key===root.id)continue;try{const c=await euDoc(x.key,false,x.relation);docs.set(`EU:${c.id}`,c);edges.push({source:`EU:${root.id}`,target:`EU:${c.id}`,relation:x.relation,j:"EU"});}catch{fail.push(`EU:${x.key}`);}}}catch{fail.push(`EU:${seed.key}`);}}
 for(const seed of fr){try{const root=await frDoc(s,d.organization_id,seed.key,true,seed.relation);docs.set(`FR:${root.id}`,root);for(const x of frRefs(root.text).filter(x=>CORE.has(x.relation)).slice(0,12)){try{const c=await frDoc(s,d.organization_id,x.key,false,x.relation);if(c.id===root.id)continue;docs.set(`FR:${c.id}`,c);edges.push({source:`FR:${root.id}`,target:`FR:${c.id}`,relation:x.relation,j:"FR"});}catch{fail.push(`FR:${x.key}`);}}}catch{fail.push(`FR:${seed.key}`);}}
 const kept=[...docs.values()];if(!kept.length)return out({ok:false,error:"Aucun acte officiel résolu",failures:fail},422);const refs=kept.map(x=>`${x.id} — ${x.title}`);await s.from("dossiers").update({reference_texts:refs}).eq("id",d.id);const now=new Date().toISOString(),ids=new Map<string,string>();for(const doc of kept){const row={user_id:d.user_id,organization_id:d.organization_id,created_by:d.created_by||d.user_id,dossier_id:null,title:doc.title,nature:doc.nature,source_url:doc.url,source_name:doc.j==="EU"?"EUR-Lex / Cellar":"Légifrance — Corpus canonique",published_at:doc.date,urgency:"moyen"};const{error:up}=await s.from("watch_items").upsert(row,{onConflict:"organization_id,source_url",ignoreDuplicates:true});if(up)throw up;const{data:item}=await s.from("watch_items").select("id,title").eq("organization_id",d.organization_id).eq("source_url",doc.url).maybeSingle();if(!item)continue;ids.set(`${doc.j}:${doc.id}`,String(item.id));await s.from("watch_item_content").upsert({watch_item_id:item.id,organization_id:d.organization_id,source_text:doc.text,source_text_chars:doc.text.length,fetched_at:now,updated_at:now},{onConflict:"watch_item_id"});const score=doc.root?.997:.999,reason=clip(doc.root?`Corpus canonique ${doc.j} : ${doc.title} est identifié directement depuis le périmètre du dossier.`:`Corpus canonique ${doc.j} : ${doc.title} est ${verb(doc.relation)} par un texte principal du dossier.`,1050);await s.from("watch_item_dossier_links").upsert({watch_item_id:item.id,dossier_id:d.id,organization_id:d.organization_id,score,status:"linked",reason,engine:ENGINE,updated_at:now},{onConflict:"watch_item_id,dossier_id"});await s.from("watch_items").update({dossier_id:d.id,suggested_dossier_id:null,qualification_confidence:score,qualification_reason:reason,qualified_at:now}).eq("id",item.id).eq("organization_id",d.organization_id);}
 for(const e of edges){const a=ids.get(e.source),b=ids.get(e.target);if(a&&b)await s.from("normative_edges").upsert({organization_id:d.organization_id,source_watch_item_id:a,target_watch_item_id:b,relation_type:e.relation,evidence:`Relation ${e.relation} résolue depuis la source officielle ${e.j}.`,confidence:1,resolution_method:"dossier_corpus_auto_v7_fr_eu",updated_at:now},{onConflict:"source_watch_item_id,target_watch_item_id,relation_type"});}
 const allowed=[...ids.values()],{data:cur}=await s.from("watch_items").select("id,qualification_reason,qualification_confidence").eq("organization_id",d.organization_id).eq("dossier_id",d.id);const stale=(cur||[]).filter((x:any)=>!allowed.includes(String(x.id))&&(/Corpus (automatique|canonique)/i.test(String(x.qualification_reason||""))||Number(x.qualification_confidence)<.4)).map((x:any)=>String(x.id));if(stale.length)await s.from("watch_items").update({dossier_id:null}).in("id",stale).eq("dossier_id",d.id).eq("organization_id",d.organization_id);return out({ok:true,engine:ENGINE,dossier_id:d.id,eu_seeds:eu.map(x=>x.key),fr_seeds:fr.map(x=>x.key),resolved:kept.length,resolved_eu:kept.filter(x=>x.j==="EU").length,resolved_fr:kept.filter(x=>x.j==="FR").length,failures:fail,canonical_refs:refs,primary_relations:edges,stale_unlinked:stale.length});});