"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowRight,ChevronDown,ChevronUp,ExternalLink,RefreshCw} from "lucide-react";

type Dossier={id:string;client:string;title:string};
type LinkJustification={objective_link?:string|null;evidence?:string[]|null;consequence?:string|null};
type Watch={id:string;title:string;nature:string;source_url:string;dossier_id:string|null;created_at:string;source_name?:string|null;published_at?:string|null;change_type?:string|null;change_summary?:string|null;change_baseline_ids?:string[]|null;link_justification?:LinkJustification|null};
type Filter="all"|"nouveau"|"modification"|"precision"|"application"|"abrogation"|"aucun_changement"|"socle_initial";
const FILTERS:[Filter,string][]=[["all","Tous"],["nouveau","Nouveau"],["modification","Modification"],["precision","Précision"],["application","Application"],["abrogation","Abrogation"],["aucun_changement","Aucun changement"],["socle_initial","Socle initial"]];
const BADGES:Record<string,[string,string]>={nouveau:["Nouveau","#7fe0b4"],modification:["Modification","#ffd466"],precision:["Précision","#8bc5ff"],application:["Application","#cfb2ff"],abrogation:["Abrogation","#ff9da3"],aucun_changement:["Aucun changement","#b8c6d9"],socle_initial:["Socle initial","#b9cdea"],pending:["Analyse en cours","#c2cee0"]};
const MONTHS:Record<string,string>={janvier:"janvier",fevrier:"février","février":"février",mars:"mars",avril:"avril",mai:"mai",juin:"juin",juillet:"juillet",aout:"août","août":"août",septembre:"septembre",octobre:"octobre",novembre:"novembre",decembre:"décembre","décembre":"décembre"};
function clean(v?:string|null){return String(v||"").replace(/\s+/g," ").trim()}
function cut(v?:string|null,n=120){const s=clean(v);return s.length>n?s.slice(0,n).trim()+"…":s}
function date(raw?:string|null){if(!raw)return"";const d=new Date(raw);return Number.isFinite(d.getTime())?d.toLocaleDateString("fr-FR",{day:"2-digit",month:"short",year:"numeric"}):""}
function time(w:Watch){const t=Date.parse(w.published_at||w.created_at||"");return Number.isFinite(t)?t:0}
function kind(w:Watch){const s=`${w.nature} ${w.title}`.toLowerCase();for(const [r,n] of [[/projet de loi/,"Projet de loi"],[/proposition de loi/,"Proposition de loi"],[/\bloi\b/,"Loi"],[/décret|decret/,"Décret"],[/arrêté|arrete/,"Arrêté"],[/ordonnance/,"Ordonnance"],[/règlement|reglement/,"Règlement"],[/directive/,"Directive"],[/décision|decision/,"Décision"],[/amendement/,"Amendement"],[/rapport/,"Rapport"]] as [RegExp,string][])if(r.test(s))return n;return clean(w.nature)||"Texte"}
function shortTitle(w:Watch){const m=clean(w.title).match(/\b(\d{1,2})\s+(janvier|février|fevrier|mars|avril|mai|juin|juillet|août|aout|septembre|octobre|novembre|décembre|decembre)\s+(\d{4})\b/i);let d="";if(m)d=`${Number(m[1])} ${MONTHS[m[2].toLowerCase()]||m[2]} ${m[3]}`;else{const x=new Date(w.published_at||w.created_at||"");if(Number.isFinite(x.getTime()))d=x.toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"})}return d?`${kind(w)} du ${d}…`:`${kind(w)}…`}
function dispositionLabel(t:string,i:number){const a=t.match(/\b(?:article|art\.)\s+([A-Z0-9LRC°\.\-]+)/i);if(a)return`Article ${a[1]}`;for(const [r,n] of [[/délai|échéance/i,"Délai"],[/seuil|montant|plafond/i,"Seuil / montant"],[/obligation|tenu de/i,"Obligation"],[/dérogation|exception/i,"Dérogation"],[/procédure|formalités/i,"Procédure"],[/agrément|autorisation/i,"Agrément / autorisation"]] as [RegExp,string][])if(r.test(t))return n;return`Disposition ${i+1}`}
function dispositions(w:Watch){const e=(Array.isArray(w.link_justification?.evidence)?w.link_justification!.evidence!:[]).map(clean).filter(Boolean).slice(0,5);const src=e.length?e:(clean(w.change_summary)?[clean(w.change_summary)]:[]);return src.map((detail,i)=>({label:dispositionLabel(detail,i),detail}))}

export default function ChangesModuleV2({dossiers,watch}:{dossiers:Dossier[];watch:Watch[];onOpenImpact?:(dossierId:string,watchIds:string[])=>void}){
 const[selectedDossierId,setSelectedDossierId]=useState(dossiers[0]?.id||"");const[filter,setFilter]=useState<Filter>("all");const[refreshing,setRefreshing]=useState(false);const[selected,setSelected]=useState<Record<string,number>>({});const[opened,setOpened]=useState<Record<string,boolean>>({});
 useEffect(()=>{if(!selectedDossierId||!dossiers.some(d=>d.id===selectedDossierId))setSelectedDossierId(dossiers[0]?.id||"")},[dossiers,selectedDossierId]);
 const dossier=dossiers.find(d=>d.id===selectedDossierId)||dossiers[0]||null;const linked=useMemo(()=>watch.filter(w=>w.dossier_id===selectedDossierId).sort((a,b)=>time(b)-time(a)),[watch,selectedDossierId]);const visible=filter==="all"?linked:linked.filter(w=>(w.change_type||"pending")===filter);
 const baseline=(w:Watch)=>(Array.isArray(w.change_baseline_ids)?w.change_baseline_ids:[]).map(id=>watch.find(x=>x.id===id)).filter(Boolean) as Watch[];
 const refresh=()=>{setRefreshing(true);window.dispatchEvent(new Event("pageshow"));window.setTimeout(()=>setRefreshing(false),700)};
 if(!dossiers.length)return <section className="emptyPage"><h1>Ce qui change</h1><p>Créez d’abord un dossier client.</p></section>;
 return <div className="page"><style jsx>{`
 .page{display:grid;gap:18px;background:linear-gradient(180deg,#07162d,#081b36);color:#fff;border-radius:22px;padding:22px;min-height:calc(100vh - 130px)}.head{display:flex;justify-content:space-between;gap:18px}.kicker{color:#f3bd3e;font-size:10px;font-weight:900;letter-spacing:.14em;text-transform:uppercase}.head h1{font-size:32px;margin:6px 0}.head p{margin:0;color:#b8c7d9;font-size:13px}.actions{display:flex;gap:8px}.actions select,.refresh{height:42px;border:1px solid rgba(255,255,255,.13);background:#0d284d;color:#fff;border-radius:11px;padding:0 12px;font-weight:750}.refresh{display:flex;align-items:center;gap:7px}.refreshing svg{transform:rotate(180deg)}
 .context{display:flex;justify-content:space-between;align-items:center;background:#0b2447;border:1px solid rgba(255,255,255,.09);border-radius:16px;padding:16px 18px}.context span{font-size:9px;color:#91a5bd;text-transform:uppercase;font-weight:900}.context h2{margin:4px 0 2px;font-size:18px}.context p{margin:0;color:#aebfd3;font-size:11px}.filters{display:flex;gap:7px;flex-wrap:wrap}.filters button{border:1px solid rgba(255,255,255,.1);background:#0d284a;color:#aebed2;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:800}.filters button.active{background:#f3bd3e;color:#102541;border-color:#f3bd3e}
 .list{display:grid;gap:13px}.row{overflow:hidden;border:1px solid rgba(255,255,255,.09);border-radius:16px;background:#0a203e}.rowHead{display:flex;justify-content:space-between;gap:12px;padding:15px 17px;background:#0b2344;border-bottom:1px solid rgba(255,255,255,.08)}.meta{font-size:9px;color:#8298b4}.short{margin:6px 0 0;font-size:18px;line-height:1.25}.badge{font-size:8px;font-weight:900;text-transform:uppercase;border:1px solid currentColor;border-radius:999px;padding:6px 9px;height:max-content}
 .cols{display:grid;grid-template-columns:repeat(3,minmax(0,1fr))}.col{padding:18px;display:grid;align-content:start;gap:10px;position:relative}.col+.col{border-left:1px solid rgba(255,255,255,.08)}.col:before{content:"";position:absolute;top:0;left:0;right:0;height:3px}.before{background:linear-gradient(180deg,rgba(176,54,67,.22),rgba(176,54,67,.10))}.before:before{background:#ff858d}.now{background:linear-gradient(180deg,rgba(42,172,116,.22),rgba(42,172,116,.10))}.now:before{background:#6ce0ad}.case{background:linear-gradient(180deg,rgba(243,189,62,.22),rgba(243,189,62,.10))}.case:before{background:#f3bd3e}.label{font-size:9px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}.col h4{font-size:16px;margin:0}.col p{font-size:11px;line-height:1.6;color:#d4dde7;margin:0}.muted{color:#9aadc0!important;font-style:italic}.tiny{font-size:9px;color:#9aadc3}
 .dispTitle{font-size:8px;color:#9fe0bf;text-transform:uppercase;font-weight:900;letter-spacing:.08em}.disp{display:grid;gap:7px}.disp button{display:grid;grid-template-columns:1fr auto;gap:8px;text-align:left;border:1px solid rgba(108,224,173,.22);background:rgba(5,32,27,.25);color:#fff;border-radius:10px;padding:9px 10px}.disp button.active{background:rgba(38,132,94,.28);border-color:#6ce0ad}.disp strong{display:block;font-size:10px}.disp small{display:block;color:#a8cdbb;font-size:9px;margin-top:3px}
 .detail{display:flex;justify-content:space-between;gap:18px;padding:14px 17px;background:#091d38;border-top:1px solid rgba(255,255,255,.08)}.detail span{font-size:8px;color:#6ce0ad;text-transform:uppercase;font-weight:900}.detail h5{margin:5px 0 6px;font-size:13px}.detail p{margin:0;color:#c4d0de;font-size:11px;line-height:1.6}.detail a,.links a{color:#ffd466;text-decoration:none;font-size:9px;font-weight:850;display:inline-flex;gap:6px;align-items:center}
 .schema{padding:15px 17px 17px;background:#081b34;border-top:1px solid rgba(255,255,255,.08)}.schemaTitle{font-size:8px;color:#91a5bd;text-transform:uppercase;font-weight:900;letter-spacing:.08em;margin-bottom:9px}.track{display:grid;grid-template-columns:1fr 26px 1fr 26px 1fr 26px 1fr;gap:7px;align-items:stretch}.node{border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:10px}.node span{font-size:8px;font-weight:900;text-transform:uppercase}.node p{font-size:9px;line-height:1.45;margin:5px 0 0;color:#e6edf5}.red{background:rgba(176,54,67,.16)}.red span{color:#ff9ca3}.neutral{background:#0d2949}.neutral span{color:#bdcad9}.green{background:rgba(42,172,116,.16)}.green span{color:#82e6ba}.yellow{background:rgba(243,189,62,.16)}.yellow span{color:#ffd466}.arrow{display:grid;place-items:center;color:#7288a4}.links{display:flex;gap:12px;padding:10px 15px;background:#091d38;border-top:1px solid rgba(255,255,255,.08)}.empty{padding:30px;text-align:center;color:#8fa3bb}.emptyPage{padding:30px;background:#071936;color:#fff;border-radius:16px}
 @media(max-width:1100px){.cols,.track{grid-template-columns:1fr}.col+.col{border-left:0;border-top:1px solid rgba(255,255,255,.08)}.arrow{transform:rotate(90deg);height:18px}}@media(max-width:700px){.page{padding:15px}.head{display:grid}.actions{display:grid;grid-template-columns:1fr auto}.rowHead,.detail{display:grid}}
 `}</style>
 <header className="head"><div><div className="kicker">Comparaison normative du dossier</div><h1>Ce qui change</h1><p>Avant → Maintenant → Impact sur mon dossier.</p></div><div className="actions"><select value={selectedDossierId} onChange={e=>{setSelectedDossierId(e.target.value);setFilter("all")}}>{dossiers.map(d=><option value={d.id} key={d.id}>{d.client} · {d.title}</option>)}</select><button className={`refresh ${refreshing?"refreshing":""}`} onClick={refresh}><RefreshCw size={15}/>Actualiser</button></div></header>
 {dossier&&<section className="context"><div><span>Dossier actif</span><h2>{dossier.title}</h2><p>{dossier.client}</p></div><span>{linked.length} texte(s) rattaché(s)</span></section>}
 <div className="filters">{FILTERS.map(([id,label])=><button key={id} className={filter===id?"active":""} onClick={()=>setFilter(id)}>{label}</button>)}</div>
 <div className="list">{visible.length?visible.map(item=>{const type=item.change_type||"pending";const badge=BADGES[type]||BADGES.pending;const base=baseline(item);const prev=base[0]||null;const prevSummary=clean(prev?.change_summary);const current=clean(item.change_summary);const impact=clean(item.link_justification?.consequence);const objective=clean(item.link_justification?.objective_link);const ds=dispositions(item);const idx=Math.min(selected[item.id]??0,Math.max(0,ds.length-1));const chosen=ds[idx]||null;const open=Boolean(opened[item.id])&&Boolean(chosen);return <article className="row" key={item.id}>
  <div className="rowHead"><div><div className="meta">{item.nature} · {date(item.published_at||item.created_at)}{item.source_name?` · ${item.source_name}`:""}</div><h3 className="short" title={item.title}>{shortTitle(item)}</h3></div><span className="badge" style={{color:badge[1]}}>{badge[0]}</span></div>
  <div className="cols">
   <section className="col before"><div className="label">1 · Règles précédemment applicables</div>{prev?<><h4 title={prev.title}>{shortTitle(prev)}</h4><p>{prevSummary||"État antérieur identifié comme base de comparaison."}</p><div className="tiny">{date(prev.published_at||prev.created_at)}</div></>:<><h4>Règle antérieure non documentée</h4><p className="muted">Le corpus ne permet pas encore d’isoler une norme antérieure précise.</p></>}</section>
   <section className="col now"><div className="label">2 · Normes désormais applicables</div><h4 title={item.title}>{shortTitle(item)}</h4><p>{current||"Comparaison normative en cours."}</p>{ds.length>0&&<><div className="dispTitle">Dispositions qui changent · cliquer pour le détail</div><div className="disp">{ds.map((d,i)=>{const active=open&&idx===i;return <button key={i} className={active?"active":""} onClick={()=>{const same=(selected[item.id]??0)===i;setSelected(s=>({...s,[item.id]:i}));setOpened(o=>({...o,[item.id]:same?!o[item.id]:true}))}}><span><strong>{d.label}</strong><small>{cut(d.detail,78)}</small></span>{active?<ChevronUp size={14}/>:<ChevronDown size={14}/>}</button>})}</div></>}</section>
   <section className="col case"><div className="label">3 · Qu’est-ce que ça change pour mon dossier ?</div><p>{impact||"L’effet concret sur ce dossier n’a pas encore été qualifié."}</p>{objective&&<><div className="tiny">Point du dossier concerné</div><p>{objective}</p></>}</section>
  </div>
  {open&&chosen&&<div className="detail"><div><span>Détail de la disposition</span><h5>{chosen.label}</h5><p>{chosen.detail}</p></div>{item.source_url&&<a href={item.source_url} target="_blank" rel="noreferrer">Ouvrir la source <ExternalLink size={12}/></a>}</div>}
  <div className="schema"><div className="schemaTitle">Schéma du changement</div><div className="track"><div className="node red"><span>Avant</span><p>{cut(prevSummary||"Règle antérieure de référence.")}</p></div><div className="arrow"><ArrowRight size={16}/></div><div className="node neutral"><span>Disposition modifiée</span><p>{cut(chosen?.detail||current||badge[0])}</p></div><div className="arrow"><ArrowRight size={16}/></div><div className="node green"><span>Maintenant</span><p>{cut(current||chosen?.detail||"Nouvelle norme identifiée.")}</p></div><div className="arrow"><ArrowRight size={16}/></div><div className="node yellow"><span>Mon dossier</span><p>{cut(impact||"Effet dossier à qualifier.")}</p></div></div></div>
  <div className="links">{prev?.source_url&&<a href={prev.source_url} target="_blank" rel="noreferrer">Règle précédente <ExternalLink size={12}/></a>}{item.source_url&&<a href={item.source_url} target="_blank" rel="noreferrer">Norme actuelle <ExternalLink size={12}/></a>}</div>
 </article>}):<div className="empty">Aucune évolution correspondant à ce filtre.</div>}</div>
 </div>
}
