"use client";

import {useMemo,useState} from "react";
import {Activity,AlertTriangle,ArrowRight,Bell,BriefcaseBusiness,CalendarDays,Clock3,Database,FileText,FolderPlus,Home,RefreshCw,Search,ShieldCheck,Sparkles,Target,TrendingUp} from "lucide-react";

type Tab="dashboard"|"dossiers"|"veille"|"impact"|"radar"|"builder";
type Dossier={id:string;client:string;title:string;objective:string;context:string;status:string;created_at:string};
type Watch={id:string;title:string;nature:string;source_url:string;dossier_id:string|null;urgency:string;created_at:string;source_name?:string|null;published_at?:string|null};
export type Action={id:string;dossier_id:string|null;type:string;title:string;description:string|null;actor_name:string|null;priority:string;status:string;due_date:string|null;created_at:string;updated_at:string};
type SearchResult={key:string;kind:"Dossier"|"Veille"|"Action";title:string;meta:string;target:"dossier"|"watch"|"action";id:string};
type ActivityItem={key:string;title:string;meta:string;kind:"watch"|"action"|"dossier";id:string;date:number};

const DAY=24*60*60*1000;
function rank(value:string){return value==="absolument urgent"?4:value==="fort"?3:value==="moyen"?2:1;}
function urgencyClass(value:string){return value==="absolument urgent"?"critical":value==="fort"?"high":value==="moyen"?"medium":"low";}
function actionDestination(type:string):Tab{return type==="contact"?"radar":type==="note_client"||type==="amendement"?"builder":type==="analyse"?"impact":"dossiers";}
function startOfToday(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime();}
function safeTime(value:string|null|undefined){const n=value?new Date(value).getTime():0;return Number.isFinite(n)?n:0;}
function searchable(...values:(string|null|undefined)[]){return values.filter(Boolean).join(" ").toLocaleLowerCase("fr");}
function shortDate(value:number|string){const d=new Date(value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit"}).format(d):"—";}
function agendaDate(value:string|null){if(!value)return {day:"—",month:"",time:""};const d=new Date(value);if(!Number.isFinite(d.getTime()))return {day:"—",month:"",time:""};return {day:new Intl.DateTimeFormat("fr-FR",{day:"2-digit"}).format(d),month:new Intl.DateTimeFormat("fr-FR",{month:"short"}).format(d).replace(".","").toUpperCase(),time:new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit"}).format(d)};}
function relativeTime(value:string|number){const t=typeof value==="number"?value:safeTime(value);if(!t)return "";const diff=Math.max(0,Date.now()-t);if(diff<60*60*1000)return `il y a ${Math.max(1,Math.round(diff/(60*1000)))} min`;if(diff<DAY)return `il y a ${Math.max(1,Math.round(diff/(60*60*1000)))} h`;return `il y a ${Math.max(1,Math.round(diff/DAY))} j`;}
function hostOf(url:string){try{return new URL(url).hostname.replace(/^www\./,"");}catch{return "";}}

export default function DashboardCorporate({dossiers,watch,actions,actionsLoading,actionsError,go}:{dossiers:Dossier[];watch:Watch[];actions:Action[];actionsLoading:boolean;actionsError:string;go:(tab:Tab)=>void}){
  const[searchOpen,setSearchOpen]=useState(false);
  const[searchQuery,setSearchQuery]=useState("");
  const today=startOfToday();
  const openActions=useMemo(()=>actions.filter(action=>action.status!=="termine"),[actions]);
  const urgentWatch=useMemo(()=>[...watch].filter(item=>rank(item.urgency)>=3).sort((a,b)=>rank(b.urgency)-rank(a.urgency)||safeTime(b.created_at)-safeTime(a.created_at)),[watch]);
  const recentDossiers=useMemo(()=>[...dossiers].sort((a,b)=>safeTime(b.created_at)-safeTime(a.created_at)).slice(0,5),[dossiers]);
  const todayWatch=useMemo(()=>watch.filter(item=>safeTime(item.created_at)>=today),[watch,today]);
  const impactNotes=useMemo(()=>openActions.filter(action=>action.type==="analyse").length,[openActions]);
  const sourceCount=useMemo(()=>new Set(watch.map(item=>hostOf(item.source_url)).filter(Boolean)).size,[watch]);
  const lastSync=useMemo(()=>Math.max(0,...watch.map(item=>safeTime(item.created_at))),[watch]);
  const highCount=watch.filter(item=>rank(item.urgency)>=3).length;
  const mediumCount=watch.filter(item=>item.urgency==="moyen").length;
  const lowCount=Math.max(0,watch.length-highCount-mediumCount);
  const impactTotal=Math.max(1,highCount+mediumCount+lowCount);
  const highPct=Math.round(highCount/impactTotal*100);
  const mediumPct=Math.round(mediumCount/impactTotal*100);
  const lowPct=Math.max(0,100-highPct-mediumPct);
  const donut=`conic-gradient(#ef4444 0 ${highPct}%,#f3b51b ${highPct}% ${highPct+mediumPct}%,#22a66f ${highPct+mediumPct}% 100%)`;
  const dossierName=(id:string|null)=>id?dossiers.find(item=>item.id===id)?.title||"Dossier lié":"Sans dossier";

  const trend=useMemo(()=>Array.from({length:7},(_,index)=>{const start=today-(6-index)*DAY,end=start+DAY;return {date:start,count:watch.filter(item=>{const t=safeTime(item.created_at);return t>=start&&t<end;}).length};}),[watch,today]);
  const maxTrend=Math.max(1,...trend.map(item=>item.count));
  const chartPoints=trend.map((item,index)=>`${index*(100/6)},${76-(item.count/maxTrend)*58}`).join(" ");
  const areaPath=`M 0 76 L ${chartPoints.split(" ").join(" L ")} L 100 76 Z`;

  const deadlines=useMemo(()=>openActions.filter(action=>action.due_date&&safeTime(action.due_date)>=today).sort((a,b)=>safeTime(a.due_date)-safeTime(b.due_date)).slice(0,4),[openActions,today]);
  const activities=useMemo<ActivityItem[]>(()=>{
    const rows:ActivityItem[]=[
      ...watch.slice(0,8).map(item=>({key:`w-${item.id}`,title:`Nouvelle veille : ${item.title}`,meta:item.nature,kind:"watch" as const,id:item.id,date:safeTime(item.created_at)})),
      ...openActions.slice(0,8).map(item=>({key:`a-${item.id}`,title:item.title,meta:[dossierName(item.dossier_id),item.actor_name].filter(Boolean).join(" · "),kind:"action" as const,id:item.id,date:safeTime(item.updated_at||item.created_at)})),
      ...dossiers.slice(0,5).map(item=>({key:`d-${item.id}`,title:`Dossier : ${item.title}`,meta:item.client||"Dossier client",kind:"dossier" as const,id:item.id,date:safeTime(item.created_at)})),
    ];
    return rows.sort((a,b)=>b.date-a.date).slice(0,5);
  },[watch,openActions,dossiers]);

  const openExactDossier=(id:string)=>{sessionStorage.setItem("myvor:open-dossier",id);go("dossiers");};
  const openExactWatch=(id:string)=>{sessionStorage.setItem("myvor:open-watch",id);go("veille");};
  const openExactAction=(action:Action)=>{if(action.dossier_id){sessionStorage.setItem("myvor:open-dossier",action.dossier_id);sessionStorage.setItem("myvor:focus-action",JSON.stringify({id:action.id,type:action.type,title:action.title,actor_name:action.actor_name||""}));go("dossiers");return;}go(actionDestination(action.type));};
  const openActivity=(item:ActivityItem)=>{if(item.kind==="watch"){openExactWatch(item.id);return;}if(item.kind==="dossier"){openExactDossier(item.id);return;}const action=actions.find(row=>row.id===item.id);if(action)openExactAction(action);};

  const searchResults=useMemo<SearchResult[]>(()=>{const query=searchQuery.trim().toLocaleLowerCase("fr");if(!query)return [];const dossierResults=dossiers.filter(d=>searchable(d.title,d.client,d.objective,d.context,d.status).includes(query)).slice(0,5).map(d=>({key:`d-${d.id}`,kind:"Dossier" as const,title:d.title,meta:[d.client,d.objective].filter(Boolean).join(" · ")||"Dossier client",target:"dossier" as const,id:d.id}));const watchResults=watch.filter(item=>searchable(item.title,item.nature,item.urgency,item.source_name).includes(query)).slice(0,5).map(item=>({key:`w-${item.id}`,kind:"Veille" as const,title:item.title,meta:[item.nature,item.urgency].filter(Boolean).join(" · "),target:"watch" as const,id:item.id}));const actionResults=actions.filter(action=>searchable(action.title,action.description,action.actor_name,action.priority,dossierName(action.dossier_id)).includes(query)).slice(0,5).map(action=>({key:`a-${action.id}`,kind:"Action" as const,title:action.title,meta:[dossierName(action.dossier_id),action.priority].filter(Boolean).join(" · "),target:"action" as const,id:action.id}));return [...dossierResults,...watchResults,...actionResults].slice(0,12);},[searchQuery,dossiers,watch,actions]);
  const closeSearch=()=>{setSearchOpen(false);setSearchQuery("");};
  const openSearchResult=(result:SearchResult)=>{closeSearch();if(result.target==="dossier"){openExactDossier(result.id);return;}if(result.target==="watch"){openExactWatch(result.id);return;}const action=actions.find(item=>item.id===result.id);if(action)openExactAction(action);};

  const dateLabel=new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());

  return <div className="cockpit-dashboard">
    <style jsx global>{`
      body:has(.cockpit-dashboard),.app:has(.cockpit-dashboard){background:#031126}
      .app:has(.cockpit-dashboard) .topbar{background:#031126;border-bottom:1px solid #18304c;box-shadow:none}
      .app:has(.cockpit-dashboard) .sidebar{background:linear-gradient(180deg,#031126 0%,#061a33 100%);border-right:1px solid #18304c;color:#d4deeb}
      .app:has(.cockpit-dashboard) .logo{background:transparent;color:#f5b51b;border:1px solid rgba(245,181,27,.35);box-shadow:0 0 24px rgba(245,181,27,.12)}
      .app:has(.cockpit-dashboard) .navbtn{color:#d2dbea;border:1px solid transparent;border-radius:10px}.app:has(.cockpit-dashboard) .navbtn:hover{background:#0b213d;border-color:#1b3a5a;color:#fff}.app:has(.cockpit-dashboard) .navbtn.active{background:#102b4d;color:#ffc62a;border-color:#1c3b5c;box-shadow:inset 3px 0 0 #ffc62a}
      .app:has(.cockpit-dashboard) .main{max-width:none;margin:0;padding:22px 24px 30px;background:radial-gradient(circle at 50% -20%,rgba(26,73,124,.18),transparent 38%),linear-gradient(180deg,#031126,#04172b);min-height:calc(100vh - 68px)}
      .app:has(.cockpit-dashboard) .logout{background:#071c35;border-color:#23425f;color:#d9e4f1}
      .cockpit-dashboard{max-width:1560px;margin:0 auto;color:#f7f9fc;display:grid;gap:15px;font-size:13px}
      .cockpit-dashboard button{font:inherit}.cockpit-dashboard button:focus-visible{outline:2px solid #ffc62a;outline-offset:2px}
      .cockpit-top{display:grid;grid-template-columns:minmax(240px,1fr) minmax(330px,430px);align-items:center;gap:24px;padding:0 2px 3px}.cockpit-greeting h1{font-size:28px;line-height:1.1;margin:0 0 7px;color:#fff;letter-spacing:-.025em}.cockpit-greeting p{margin:0;color:#a8b7c9;text-transform:none}.cockpit-search{height:42px;border:1px solid #29435f;background:#07182e;border-radius:9px;color:#94a6ba;display:flex;align-items:center;justify-content:space-between;padding:0 13px;cursor:pointer}.cockpit-search:hover{border-color:#3d6287;background:#0a203b}.cockpit-search span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
      .metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.metric-card{border:1px solid #173552;background:linear-gradient(135deg,#071a31,#0a213d);border-radius:11px;padding:17px 18px;display:grid;grid-template-columns:48px 1fr;gap:14px;align-items:center;text-align:left;color:#fff;cursor:pointer;min-height:92px;transition:.15s ease}.metric-card:hover{transform:translateY(-2px);border-color:#2b5379;background:linear-gradient(135deg,#08203c,#0d294a)}.metric-icon{width:48px;height:48px;border-radius:50%;display:grid;place-items:center}.metric-icon.blue{background:#0e54ad}.metric-icon.green{background:#0b804f}.metric-icon.gold{background:#d99500}.metric-icon.red{background:#b92430}.metric-copy{display:grid;gap:2px}.metric-label{color:#d9e2ed;font-size:12px}.metric-value{font-size:27px;font-weight:850;line-height:1}.metric-delta{font-size:11px;color:#7fb7ff;margin-top:5px}.metric-delta.green{color:#3bd88a}.metric-delta.gold{color:#ffc62a}.metric-delta.red{color:#ff636e}
      .cockpit-layout{display:grid;grid-template-columns:minmax(0,1fr) 306px;gap:14px}.cockpit-main{display:grid;gap:14px}.cockpit-row{display:grid;grid-template-columns:1.22fr 1fr 1.03fr;gap:14px}.cockpit-bottom{display:grid;grid-template-columns:.95fr 1.72fr;gap:14px}.cockpit-side{display:grid;gap:14px;align-content:start}
      .cockpit-panel{background:linear-gradient(145deg,#06172c,#081e38);border:1px solid #173552;border-radius:11px;overflow:hidden;min-width:0}.panel-head{height:50px;padding:0 14px;display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid #16324d}.panel-head h2{font-size:14px;margin:0;color:#f5f8fc}.panel-link{border:0;background:transparent;color:#ffc62a;display:flex;align-items:center;gap:5px;cursor:pointer;padding:6px}.panel-link:hover{color:#ffe08a}.panel-body{padding:11px 14px}.empty-cockpit{padding:22px 12px;text-align:center;color:#7f93aa;font-size:12px}
      .dossier-list,.alert-list,.activity-list,.agenda-list{display:grid}.dossier-row,.alert-row,.activity-row,.agenda-row{border:0;border-bottom:1px solid #17324d;background:transparent;color:#eef3f9;text-align:left;cursor:pointer}.dossier-row:last-child,.alert-row:last-child,.activity-row:last-child,.agenda-row:last-child{border-bottom:0}.dossier-row:hover,.alert-row:hover,.activity-row:hover,.agenda-row:hover{background:#0a213d}.dossier-row{display:grid;grid-template-columns:10px minmax(0,1fr) auto;gap:10px;align-items:center;padding:11px 4px}.status-dot{width:8px;height:8px;border-radius:50%;background:#2bb879}.status-dot.high{background:#ef4444}.status-dot.medium{background:#f3b51b}.dossier-copy,.alert-copy,.activity-copy{min-width:0}.dossier-copy b,.alert-copy b,.activity-copy b{display:block;color:#f4f7fb;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dossier-copy small,.alert-copy small,.activity-copy small{display:block;color:#8fa2b8;font-size:10px;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.score-pill{min-width:34px;height:34px;border:2px solid #f3b51b;border-radius:50%;display:grid;place-items:center;font-size:10px;font-weight:850;color:#fff}.score-pill.high{border-color:#ef4444}.score-pill.low{border-color:#22a66f}
      .impact-wrap{display:grid;grid-template-columns:128px 1fr;gap:14px;align-items:center;padding:17px 5px 19px}.impact-donut{width:118px;height:118px;border-radius:50%;display:grid;place-items:center;position:relative}.impact-donut:after{content:"";position:absolute;width:72px;height:72px;background:#071a31;border-radius:50%;box-shadow:0 0 0 1px #15334f}.impact-center{position:relative;z-index:1;text-align:center}.impact-center strong{display:block;font-size:24px}.impact-center span{font-size:9px;color:#8fa2b8}.impact-legend{display:grid;gap:11px}.legend-row{display:grid;grid-template-columns:8px 1fr auto;gap:7px;align-items:center;color:#dce5ef;font-size:10px}.legend-dot{width:7px;height:7px;border-radius:50%}.legend-dot.red{background:#ef4444}.legend-dot.gold{background:#f3b51b}.legend-dot.green{background:#22a66f}.legend-row b{font-size:10px;color:#fff}
      .trend-panel .panel-body{padding-top:16px}.trend-chart{height:155px;position:relative}.trend-chart svg{width:100%;height:118px;overflow:visible}.grid-line{stroke:#17334f;stroke-width:.6}.trend-area{fill:rgba(243,181,27,.14)}.trend-line{fill:none;stroke:#f3b51b;stroke-width:2.2;vector-effect:non-scaling-stroke}.trend-dot{fill:#f3b51b}.trend-labels{display:grid;grid-template-columns:repeat(7,1fr);gap:2px;color:#71869d;font-size:8px;text-align:center}.trend-legend{display:flex;align-items:center;justify-content:center;gap:7px;color:#b0bdcc;font-size:9px;margin-top:10px}.trend-legend i{width:17px;height:3px;border-radius:99px;background:#f3b51b;display:block}
      .alert-row{display:grid;grid-template-columns:9px minmax(0,1fr) auto;gap:9px;align-items:center;padding:11px 3px}.alert-badge{font-size:9px;border-radius:5px;padding:5px 7px;background:#3a1f18;color:#ffc62a}.alert-badge.high,.alert-badge.critical{background:#3b1820;color:#ff626c}.alert-age{display:block;color:#8799ad;font-size:9px;margin-top:5px;text-align:right}
      .quick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;padding:6px 0}.quick-btn{border:1px solid #1d3c5a;background:#071b33;border-radius:8px;min-height:95px;color:#eef4fa;display:grid;place-items:center;align-content:center;gap:10px;cursor:pointer;padding:10px 5px;font-size:10px;text-align:center}.quick-btn svg{color:#ffc62a}.quick-btn:hover{background:#0b2747;border-color:#31597e;transform:translateY(-1px)}
      .activity-row{display:grid;grid-template-columns:28px minmax(0,1fr) auto;gap:10px;align-items:center;padding:10px 3px}.activity-icon{width:27px;height:27px;border-radius:6px;background:#0c2848;color:#ffc62a;display:grid;place-items:center}.activity-age{color:#8ea0b4;font-size:9px;white-space:nowrap}
      .agenda-row{display:grid;grid-template-columns:41px minmax(0,1fr) auto;gap:10px;align-items:center;padding:12px 3px}.agenda-date{text-align:center}.agenda-date strong{display:block;font-size:18px;line-height:1;color:#fff}.agenda-date span{display:block;font-size:8px;color:#b6c3d1;margin-top:4px}.agenda-copy b{display:block;font-size:11px;color:#edf3f9}.agenda-copy small{display:block;color:#8ea0b4;font-size:9px;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agenda-time{background:#122b47;border:1px solid #244461;border-radius:5px;padding:6px 7px;color:#dbe5ef;font-size:9px}
      .cockpit-footer{border:1px solid #173552;background:#06172c;border-radius:10px;display:grid;grid-template-columns:1fr 1fr 1fr;min-height:55px;align-items:center}.footer-item{display:flex;align-items:center;justify-content:center;gap:9px;color:#c5d1de;font-size:10px;border-right:1px solid #17324d;height:100%}.footer-item:last-child{border-right:0}.footer-item svg{color:#79a6d6}.footer-item.secure svg,.footer-item.secure b{color:#35d284}.footer-item b{color:#fff}
      .dash-search-backdrop{position:fixed;inset:0;z-index:10000;background:rgba(1,8,19,.76);backdrop-filter:blur(7px);display:flex;justify-content:center;align-items:flex-start;padding:92px 18px 24px;overflow:auto}.dash-search-modal{width:min(720px,100%);background:#06162c;border:1px solid #274563;border-radius:16px;box-shadow:0 28px 70px rgba(0,0,0,.45);overflow:hidden}.dash-search-head{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:10px;padding:14px 16px;border-bottom:1px solid #173653;color:#8fa4bc}.dash-search-head input{width:100%;border:0;outline:0;background:transparent;color:#f6f8fb;font:inherit;font-size:16px}.dash-search-head input::placeholder{color:#72869f}.dash-search-close{border:1px solid #274563;background:#0a213d;color:#d9e4f2;border-radius:8px;padding:8px 10px;cursor:pointer}.dash-search-results{max-height:min(62vh,520px);overflow:auto;padding:8px}.dash-search-result{width:100%;border:0;background:transparent;border-radius:10px;padding:12px;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:12px;align-items:center;text-align:left;color:#eef4fb;cursor:pointer}.dash-search-result:hover{background:#0a213d}.dash-search-kind{min-width:62px;padding:5px 8px;border-radius:999px;background:#0c2b59;color:#73aafc;font-size:10px;font-weight:850;text-align:center}.dash-search-copy{display:grid;gap:3px;min-width:0}.dash-search-copy b{font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dash-search-copy small{font-size:10px;color:#8fa4bc;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dash-search-empty{padding:28px 18px;text-align:center;color:#8fa4bc;font-size:12px}.dash-search-empty b{display:block;color:#e8eef7;margin-bottom:5px}
      @media(max-width:1180px){.metric-grid{grid-template-columns:repeat(2,1fr)}.cockpit-layout{grid-template-columns:1fr}.cockpit-side{grid-template-columns:1fr 1fr}.cockpit-row{grid-template-columns:1fr 1fr}.cockpit-row .trend-panel{grid-column:1/-1}.cockpit-bottom{grid-template-columns:1fr 1.5fr}}
      @media(max-width:850px){.app:has(.cockpit-dashboard) .main{padding:16px 14px 96px}.cockpit-top{grid-template-columns:1fr}.cockpit-greeting h1{font-size:24px}.cockpit-row,.cockpit-bottom,.cockpit-side{grid-template-columns:1fr}.cockpit-row .trend-panel{grid-column:auto}.cockpit-footer{grid-template-columns:1fr}.footer-item{border-right:0;border-bottom:1px solid #17324d;padding:13px}.footer-item:last-child{border-bottom:0}}
      @media(max-width:560px){.metric-grid{grid-template-columns:1fr 1fr;gap:9px}.metric-card{grid-template-columns:39px 1fr;gap:9px;padding:12px;min-height:78px}.metric-icon{width:39px;height:39px}.metric-value{font-size:22px}.metric-delta{display:none}.cockpit-top{gap:12px}.impact-wrap{grid-template-columns:110px 1fr}.impact-donut{width:104px;height:104px}.impact-donut:after{width:64px;height:64px}.quick-grid{grid-template-columns:repeat(2,1fr)}.panel-head{height:48px}.cockpit-dashboard{gap:11px}.cockpit-layout,.cockpit-main,.cockpit-side{gap:11px}.dash-search-backdrop{padding:72px 10px 12px}}
    `}</style>

    <header className="cockpit-top"><div className="cockpit-greeting"><h1>Bonjour,</h1><p>Voici les informations clés de ce {dateLabel}.</p></div><button type="button" className="cockpit-search" onClick={()=>setSearchOpen(true)}><span>Rechercher un dossier, une veille, une action…</span><Search size={17}/></button></header>

    {searchOpen&&<div className="dash-search-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)closeSearch();}}><div className="dash-search-modal" role="dialog" aria-modal="true" aria-label="Recherche Myvor"><div className="dash-search-head"><Search size={19}/><input autoFocus value={searchQuery} onChange={event=>setSearchQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Escape")closeSearch();if(event.key==="Enter"&&searchResults[0])openSearchResult(searchResults[0]);}} placeholder="Rechercher un dossier, un texte, une action…"/><button type="button" className="dash-search-close" onClick={closeSearch}>Fermer</button></div><div className="dash-search-results">{searchQuery.trim()?searchResults.length?searchResults.map(result=><button type="button" className="dash-search-result" key={result.key} onClick={()=>openSearchResult(result)}><span className="dash-search-kind">{result.kind}</span><span className="dash-search-copy"><b>{result.title}</b><small>{result.meta}</small></span><ArrowRight size={15}/></button>):<div className="dash-search-empty"><b>Aucun résultat</b>Essayez un nom de client, un texte ou un mot-clé.</div>:<div className="dash-search-empty"><b>Recherche globale</b>Recherchez dans vos dossiers, votre veille et vos actions.</div>}</div></div></div>}

    <section className="metric-grid">
      <button className="metric-card" onClick={()=>go("dossiers")}><span className="metric-icon blue"><BriefcaseBusiness size={22}/></span><span className="metric-copy"><span className="metric-label">Dossiers actifs</span><strong className="metric-value">{dossiers.length}</strong><span className="metric-delta">Portefeuille client</span></span></button>
      <button className="metric-card" onClick={()=>go("veille")}><span className="metric-icon green"><FileText size={22}/></span><span className="metric-copy"><span className="metric-label">Veilles aujourd’hui</span><strong className="metric-value">{todayWatch.length}</strong><span className="metric-delta green">{watch.length} au total</span></span></button>
      <button className="metric-card" onClick={()=>go("impact")}><span className="metric-icon gold"><TrendingUp size={22}/></span><span className="metric-copy"><span className="metric-label">Notes d’impact</span><strong className="metric-value">{impactNotes}</strong><span className="metric-delta gold">Analyses ouvertes</span></span></button>
      <button className="metric-card" onClick={()=>go("veille")}><span className="metric-icon red"><Bell size={22}/></span><span className="metric-copy"><span className="metric-label">Alertes actives</span><strong className="metric-value">{urgentWatch.length}</strong><span className="metric-delta red">{urgentWatch.filter(item=>item.urgency==="absolument urgent").length} urgences</span></span></button>
    </section>

    <div className="cockpit-layout"><main className="cockpit-main">
      <div className="cockpit-row">
        <section className="cockpit-panel"><div className="panel-head"><h2>Dossiers récents</h2><button className="panel-link" onClick={()=>go("dossiers")}>Voir tous <ArrowRight size={13}/></button></div><div className="panel-body dossier-list">{recentDossiers.length?recentDossiers.map((d,index)=>{const linked=watch.filter(item=>item.dossier_id===d.id);const level=linked.length?Math.max(...linked.map(item=>rank(item.urgency))):1;const score=Math.min(99,Math.max(22,Math.round((linked.length*11)+(level*17)+(index?0:4))));return <button key={d.id} className="dossier-row" onClick={()=>openExactDossier(d.id)}><span className={`status-dot ${level>=3?"high":level==2?"medium":""}`}/><span className="dossier-copy"><b>{d.title}</b><small>{d.client||"Client"} · {relativeTime(d.created_at)}</small></span><span className={`score-pill ${level>=3?"high":level<=1?"low":""}`}>{score}</span></button>}):<div className="empty-cockpit">Aucun dossier pour le moment.</div>}</div></section>

        <section className="cockpit-panel"><div className="panel-head"><h2>Répartition des notes d’impact</h2><button className="panel-link" onClick={()=>go("impact")}>Ouvrir <ArrowRight size={13}/></button></div><div className="panel-body impact-wrap"><button type="button" className="impact-donut" style={{background:donut}} onClick={()=>go("impact")} aria-label="Ouvrir les notes d’impact"><span className="impact-center"><strong>{watch.length}</strong><span>Total suivi</span></span></button><div className="impact-legend"><div className="legend-row"><i className="legend-dot red"/><span>Impact élevé</span><b>{highCount} ({highPct}%)</b></div><div className="legend-row"><i className="legend-dot gold"/><span>Impact moyen</span><b>{mediumCount} ({mediumPct}%)</b></div><div className="legend-row"><i className="legend-dot green"/><span>Impact faible</span><b>{lowCount} ({lowPct}%)</b></div></div></div></section>

        <section className="cockpit-panel trend-panel"><div className="panel-head"><h2>Tendance des veilles</h2><button className="panel-link" onClick={()=>go("veille")}>7 derniers jours <ArrowRight size={13}/></button></div><div className="panel-body"><button type="button" onClick={()=>go("veille")} style={{border:0,background:"transparent",padding:0,width:"100%",cursor:"pointer"}} aria-label="Ouvrir la veille"><div className="trend-chart"><svg viewBox="0 0 100 80" preserveAspectRatio="none" aria-hidden="true"><line className="grid-line" x1="0" y1="18" x2="100" y2="18"/><line className="grid-line" x1="0" y1="47" x2="100" y2="47"/><line className="grid-line" x1="0" y1="76" x2="100" y2="76"/><path className="trend-area" d={areaPath}/><polyline className="trend-line" points={chartPoints}/>{trend.map((item,index)=><circle key={item.date} className="trend-dot" cx={index*(100/6)} cy={76-(item.count/maxTrend)*58} r="1.5"/>)}</svg><div className="trend-labels">{trend.map(item=><span key={item.date}>{shortDate(item.date)}</span>)}</div></div></button><div className="trend-legend"><i/> Nombre de veilles</div></div></section>
      </div>

      <div className="cockpit-bottom">
        <section className="cockpit-panel"><div className="panel-head"><h2>Accès rapides</h2><span style={{color:"#8094aa",fontSize:10}}>Modules Myvor</span></div><div className="panel-body quick-grid"><button className="quick-btn" onClick={()=>go("dossiers")}><FolderPlus size={24}/>Nouveau dossier</button><button className="quick-btn" onClick={()=>go("impact")}><TrendingUp size={24}/>Note d’impact</button><button className="quick-btn" onClick={()=>go("builder")}><Sparkles size={24}/>Note Builder</button><button className="quick-btn" onClick={()=>go("veille")}><Search size={24}/>Veille</button><button className="quick-btn" onClick={()=>go("radar")}><Target size={24}/>Radar d’influence</button><button className="quick-btn" onClick={()=>go("veille")}><Bell size={24}/>Alertes</button></div></section>

        <section className="cockpit-panel"><div className="panel-head"><h2>Activité récente</h2><button className="panel-link" onClick={()=>go("dossiers")}>Voir l’activité <ArrowRight size={13}/></button></div><div className="panel-body activity-list">{activities.length?activities.map(item=><button key={item.key} className="activity-row" onClick={()=>openActivity(item)}><span className="activity-icon">{item.kind==="watch"?<Activity size={14}/>:item.kind==="dossier"?<BriefcaseBusiness size={14}/>:<Sparkles size={14}/>}</span><span className="activity-copy"><b>{item.title}</b><small>{item.meta}</small></span><span className="activity-age">{relativeTime(item.date)}</span></button>):<div className="empty-cockpit">Aucune activité récente.</div>}</div></section>
      </div>
    </main>

    <aside className="cockpit-side">
      <section className="cockpit-panel"><div className="panel-head"><h2>Alertes prioritaires</h2><button className="panel-link" onClick={()=>go("veille")}>Voir toutes</button></div><div className="panel-body alert-list">{urgentWatch.slice(0,4).length?urgentWatch.slice(0,4).map(item=><button key={item.id} className="alert-row" onClick={()=>openExactWatch(item.id)}><span className={`status-dot ${urgencyClass(item.urgency)}`}/><span className="alert-copy"><b>{item.title}</b><small>{item.nature}</small></span><span><span className={`alert-badge ${urgencyClass(item.urgency)}`}>{item.urgency==="absolument urgent"?"Urgent":item.urgency}</span><span className="alert-age">{relativeTime(item.created_at)}</span></span></button>):<div className="empty-cockpit">Aucune alerte prioritaire.</div>}</div><div style={{padding:"0 14px 13px"}}><button className="panel-link" onClick={()=>go("veille")}>Voir toutes les alertes <ArrowRight size={13}/></button></div></section>

      <section className="cockpit-panel"><div className="panel-head"><h2>Agenda institutionnel</h2><button className="panel-link" onClick={()=>go("dossiers")}>Voir l’agenda</button></div><div className="panel-body agenda-list">{deadlines.length?deadlines.map(action=>{const date=agendaDate(action.due_date);return <button key={action.id} className="agenda-row" onClick={()=>openExactAction(action)}><span className="agenda-date"><strong>{date.day}</strong><span>{date.month}</span></span><span className="agenda-copy"><b>{action.title}</b><small>{dossierName(action.dossier_id)}</small></span><span className="agenda-time">{date.time}</span></button>}):<div className="empty-cockpit">Aucune échéance à venir.</div>}</div></section>
    </aside></div>

    <footer className="cockpit-footer"><div className="footer-item secure"><ShieldCheck size={18}/><span><b>Sécurité :</b> session authentifiée</span></div><div className="footer-item"><Database size={18}/><span>Sources connectées : <b>{sourceCount}</b></span></div><div className="footer-item"><RefreshCw size={18}/><span>Dernière synchronisation : <b>{lastSync?relativeTime(lastSync):"aucune"}</b></span></div></footer>

    {actionsLoading&&<div style={{color:"#8499b0",fontSize:10,textAlign:"right"}}><Clock3 size={11} style={{verticalAlign:"middle",marginRight:5}}/>Actualisation des actions…</div>}
    {actionsError&&<div style={{color:"#ff9d8f",fontSize:10,textAlign:"right"}}><AlertTriangle size={11} style={{verticalAlign:"middle",marginRight:5}}/>{actionsError}</div>}
  </div>;
}
