"use client";

import {useMemo,useState} from "react";
import {Activity,AlertTriangle,ArrowRight,Bell,BriefcaseBusiness,CalendarDays,Clock3,Database,FileText,FolderPlus,RefreshCw,Search,ShieldCheck,Sparkles,Target,TrendingUp} from "lucide-react";

type Tab="dashboard"|"dossiers"|"veille"|"impact"|"radar"|"builder";
type Dossier={id:string;client:string;title:string;objective:string;context:string;status:string;created_at:string};
type Watch={id:string;title:string;nature:string;source_url:string;dossier_id:string|null;urgency:string;created_at:string;source_name?:string|null;published_at?:string|null};
export type Action={id:string;dossier_id:string|null;type:string;title:string;description:string|null;actor_name:string|null;priority:string;status:string;due_date:string|null;created_at:string;updated_at:string};
type SearchResult={key:string;kind:"Dossier"|"Veille"|"Action";title:string;meta:string;target:"dossier"|"watch"|"action";id:string};
type ActivityItem={key:string;title:string;meta:string;kind:"watch"|"action"|"dossier";id:string;date:number};

const DAY=24*60*60*1000;
function rank(value:string){return value==="absolument urgent"?4:value==="fort"?3:value==="moyen"?2:1;}
function urgencyClass(value:string){return value==="absolument urgent"?"critical":value==="fort"?"high":value==="moyen"?"medium":"low";}
function actionDestination(type:string):Tab{return type==="contact"?"radar":type==="note_client"||type==="amendement"?"builder":type==="analyse"?"impact":"dossiers";}
function actionCta(type:string){return type==="contact"?"Ouvrir le radar":type==="note_client"?"Rédiger la note":type==="amendement"?"Préparer l’amendement":type==="analyse"?"Analyser l’impact":"Ouvrir l’action";}
function startOfToday(){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime();}
function safeTime(value:string|null|undefined){const n=value?new Date(value).getTime():0;return Number.isFinite(n)?n:0;}
function searchable(...values:(string|null|undefined)[]){return values.filter(Boolean).join(" ").toLocaleLowerCase("fr");}
function shortDate(value:number|string){const d=new Date(value);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"2-digit"}).format(d):"—";}
function agendaDate(value:string|null){if(!value)return {day:"—",month:"",time:""};const d=new Date(value);if(!Number.isFinite(d.getTime()))return {day:"—",month:"",time:""};return {day:new Intl.DateTimeFormat("fr-FR",{day:"2-digit"}).format(d),month:new Intl.DateTimeFormat("fr-FR",{month:"short"}).format(d).replace(".","").toUpperCase(),time:new Intl.DateTimeFormat("fr-FR",{hour:"2-digit",minute:"2-digit"}).format(d)};}
function relativeTime(value:string|number){const t=typeof value==="number"?value:safeTime(value);if(!t)return "";const diff=Math.max(0,Date.now()-t);if(diff<60*60*1000)return `il y a ${Math.max(1,Math.round(diff/(60*1000)))} min`;if(diff<DAY)return `il y a ${Math.max(1,Math.round(diff/(60*60*1000)))} h`;return `il y a ${Math.max(1,Math.round(diff/DAY))} j`;}
function hostOf(url:string){try{return new URL(url).hostname.replace(/^www\./,"");}catch{return "";}}
function scoreFromUrgency(value:string){return value==="absolument urgent"?91:value==="fort"?78:value==="moyen"?61:34;}

export default function DashboardCorporate({dossiers,watch,actions,actionsLoading,actionsError,go}:{dossiers:Dossier[];watch:Watch[];actions:Action[];actionsLoading:boolean;actionsError:string;go:(tab:Tab)=>void}){
  const[searchOpen,setSearchOpen]=useState(false);
  const[searchQuery,setSearchQuery]=useState("");
  const today=startOfToday();
  const dossierName=(id:string|null)=>id?dossiers.find(item=>item.id===id)?.title||"Dossier lié":"Sans dossier";
  const openActions=actions.filter(action=>action.status!=="termine");
  const sortedActions=[...openActions].sort((a,b)=>rank(b.priority)-rank(a.priority)||(safeTime(a.due_date)||Number.MAX_SAFE_INTEGER)-(safeTime(b.due_date)||Number.MAX_SAFE_INTEGER)||safeTime(b.updated_at)-safeTime(a.updated_at));
  const urgentWatch=[...watch].filter(item=>rank(item.urgency)>=3).sort((a,b)=>rank(b.urgency)-rank(a.urgency)||safeTime(b.created_at)-safeTime(a.created_at));
  const recentDossiers=[...dossiers].sort((a,b)=>safeTime(b.created_at)-safeTime(a.created_at)).slice(0,5);
  const todayWatch=watch.filter(item=>safeTime(item.created_at)>=today);
  const impactNotes=openActions.filter(action=>action.type==="analyse").length;
  const sourceCount=new Set(watch.map(item=>hostOf(item.source_url)).filter(Boolean)).size;
  const lastSync=Math.max(0,...watch.map(item=>safeTime(item.created_at)));
  const highCount=watch.filter(item=>rank(item.urgency)>=3).length;
  const mediumCount=watch.filter(item=>item.urgency==="moyen").length;
  const lowCount=Math.max(0,watch.length-highCount-mediumCount);
  const impactTotal=Math.max(1,highCount+mediumCount+lowCount);
  const highPct=Math.round(highCount/impactTotal*100),mediumPct=Math.round(mediumCount/impactTotal*100),lowPct=Math.max(0,100-highPct-mediumPct);
  const donut=`conic-gradient(#ef4444 0 ${highPct}%,#f3b51b ${highPct}% ${highPct+mediumPct}%,#22a66f ${highPct+mediumPct}% 100%)`;
  const trend=Array.from({length:7},(_,index)=>{const start=today-(6-index)*DAY,end=start+DAY;return {date:start,count:watch.filter(item=>{const t=safeTime(item.created_at);return t>=start&&t<end;}).length};});
  const maxTrend=Math.max(1,...trend.map(item=>item.count));
  const points=trend.map((item,index)=>`${index*(100/6)},${76-(item.count/maxTrend)*58}`).join(" ");
  const deadlines=openActions.filter(action=>action.due_date&&safeTime(action.due_date)>=today).sort((a,b)=>safeTime(a.due_date)-safeTime(b.due_date)).slice(0,4);
  const urgentAction=sortedActions.find(action=>action.priority==="absolument urgent")||sortedActions.find(action=>action.priority==="fort")||null;
  const nextDeadline=deadlines[0]||null;
  const nextStepAction=urgentAction||nextDeadline;
  const nextStepWatch=!nextStepAction?(urgentWatch[0]||null):null;

  const activities:ActivityItem[]=[
    ...watch.slice(0,8).map(item=>({key:`w-${item.id}`,title:`Nouvelle veille : ${item.title}`,meta:item.nature,kind:"watch" as const,id:item.id,date:safeTime(item.created_at)})),
    ...openActions.slice(0,8).map(item=>({key:`a-${item.id}`,title:item.title,meta:[dossierName(item.dossier_id),item.actor_name].filter(Boolean).join(" · "),kind:"action" as const,id:item.id,date:safeTime(item.updated_at||item.created_at)})),
    ...dossiers.slice(0,5).map(item=>({key:`d-${item.id}`,title:`Dossier : ${item.title}`,meta:item.client||"Dossier client",kind:"dossier" as const,id:item.id,date:safeTime(item.created_at)})),
  ].sort((a,b)=>b.date-a.date).slice(0,5);

  const openExactDossier=(id:string)=>{sessionStorage.setItem("myvor:open-dossier",id);go("dossiers");};
  const openExactWatch=(id:string)=>{sessionStorage.setItem("myvor:open-watch",id);go("veille");};
  const openExactAction=(action:Action)=>{if(action.dossier_id){sessionStorage.setItem("myvor:open-dossier",action.dossier_id);sessionStorage.setItem("myvor:focus-action",JSON.stringify({id:action.id,type:action.type,title:action.title,actor_name:action.actor_name||""}));go("dossiers");return;}go(actionDestination(action.type));};
  const openActivity=(item:ActivityItem)=>{if(item.kind==="watch"){openExactWatch(item.id);return;}if(item.kind==="dossier"){openExactDossier(item.id);return;}const action=actions.find(row=>row.id===item.id);if(action)openExactAction(action);};

  const searchResults=useMemo<SearchResult[]>(()=>{const query=searchQuery.trim().toLocaleLowerCase("fr");if(!query)return [];const dossierResults=dossiers.filter(d=>searchable(d.title,d.client,d.objective,d.context,d.status).includes(query)).slice(0,5).map(d=>({key:`d-${d.id}`,kind:"Dossier" as const,title:d.title,meta:[d.client,d.objective].filter(Boolean).join(" · ")||"Dossier client",target:"dossier" as const,id:d.id}));const watchResults=watch.filter(item=>searchable(item.title,item.nature,item.urgency,item.source_name).includes(query)).slice(0,5).map(item=>({key:`w-${item.id}`,kind:"Veille" as const,title:item.title,meta:[item.nature,item.urgency].filter(Boolean).join(" · "),target:"watch" as const,id:item.id}));const actionResults=actions.filter(action=>searchable(action.title,action.description,action.actor_name,action.priority,dossierName(action.dossier_id)).includes(query)).slice(0,5).map(action=>({key:`a-${action.id}`,kind:"Action" as const,title:action.title,meta:[dossierName(action.dossier_id),action.priority].filter(Boolean).join(" · "),target:"action" as const,id:action.id}));return [...dossierResults,...watchResults,...actionResults].slice(0,12);},[searchQuery,dossiers,watch,actions]);
  const closeSearch=()=>{setSearchOpen(false);setSearchQuery("");};
  const openSearchResult=(result:SearchResult)=>{closeSearch();if(result.target==="dossier"){openExactDossier(result.id);return;}if(result.target==="watch"){openExactWatch(result.id);return;}const action=actions.find(item=>item.id===result.id);if(action)openExactAction(action);};
  const dateLabel=new Intl.DateTimeFormat("fr-FR",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());

  return <div className="cockpit-dashboard">
    <style jsx global>{`
      body:has(.cockpit-dashboard),.app:has(.cockpit-dashboard){background:#031126}.app:has(.cockpit-dashboard) .topbar{background:#031126;border-bottom:1px solid #18304c;box-shadow:none}.app:has(.cockpit-dashboard) .sidebar{background:linear-gradient(180deg,#031126 0%,#061a33 100%);border-right:1px solid #18304c;color:#d4deeb}.app:has(.cockpit-dashboard) .logo{background:transparent;color:#f5b51b;border:1px solid rgba(245,181,27,.35);box-shadow:0 0 24px rgba(245,181,27,.12)}.app:has(.cockpit-dashboard) .navbtn{color:#d2dbea;border:1px solid transparent;border-radius:10px}.app:has(.cockpit-dashboard) .navbtn:hover{background:#0b213d;border-color:#1b3a5a;color:#fff}.app:has(.cockpit-dashboard) .navbtn.active{background:#102b4d;color:#ffc62a;border-color:#1c3b5c;box-shadow:inset 3px 0 0 #ffc62a}.app:has(.cockpit-dashboard) .main{max-width:none;margin:0;padding:22px 24px 30px;background:radial-gradient(circle at 50% -20%,rgba(26,73,124,.18),transparent 38%),linear-gradient(180deg,#031126,#04172b);min-height:calc(100vh - 68px)}.app:has(.cockpit-dashboard) .logout{background:#071c35;border-color:#23425f;color:#d9e4f1}
      .cockpit-dashboard{max-width:1560px;margin:0 auto;color:#f7f9fc;display:grid;gap:15px;font-size:13px}.cockpit-dashboard button{font:inherit}.cockpit-dashboard button:focus-visible{outline:2px solid #ffc62a;outline-offset:2px}.cockpit-top{display:grid;grid-template-columns:minmax(240px,1fr) minmax(330px,430px);align-items:center;gap:24px;padding:0 2px 3px}.cockpit-greeting h1{font-size:28px;line-height:1.1;margin:0 0 7px;color:#fff;letter-spacing:-.025em}.cockpit-greeting p{margin:0;color:#a8b7c9}.cockpit-search{height:42px;border:1px solid #29435f;background:#07182e;border-radius:9px;color:#94a6ba;display:flex;align-items:center;justify-content:space-between;padding:0 13px;cursor:pointer}.cockpit-search:hover{border-color:#3d6287;background:#0a203b}
      .metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.metric-card{border:1px solid #173552;background:linear-gradient(135deg,#071a31,#0a213d);border-radius:11px;padding:17px 18px;display:grid;grid-template-columns:48px 1fr;gap:14px;align-items:center;text-align:left;color:#fff;cursor:pointer;min-height:92px;transition:.15s ease}.metric-card:hover{transform:translateY(-2px);border-color:#2b5379}.metric-icon{width:48px;height:48px;border-radius:50%;display:grid;place-items:center}.metric-icon.blue{background:#0e54ad}.metric-icon.green{background:#0b804f}.metric-icon.gold{background:#d99500}.metric-icon.red{background:#b92430}.metric-copy{display:grid;gap:2px}.metric-label{color:#d9e2ed;font-size:12px}.metric-value{font-size:27px;font-weight:850;line-height:1}.metric-delta{font-size:11px;color:#7fb7ff;margin-top:5px}.metric-delta.green{color:#3bd88a}.metric-delta.gold{color:#ffc62a}.metric-delta.red{color:#ff636e}
      .cockpit-layout{display:grid;grid-template-columns:minmax(0,1fr) 306px;gap:14px}.cockpit-main{display:grid;gap:14px}.cockpit-row{display:grid;grid-template-columns:1.22fr 1fr 1.03fr;gap:14px}.cockpit-bottom{display:grid;grid-template-columns:.95fr 1.72fr;gap:14px}.cockpit-side{display:grid;gap:14px;align-content:start}.cockpit-panel{background:linear-gradient(145deg,#06172c,#081e38);border:1px solid #173552;border-radius:11px;overflow:hidden;min-width:0}.panel-head{height:50px;padding:0 14px;display:flex;align-items:center;justify-content:space-between;gap:12px;border-bottom:1px solid #16324d}.panel-head h2{font-size:14px;margin:0;color:#f5f8fc}.panel-link{border:0;background:transparent;color:#ffc62a;display:flex;align-items:center;gap:5px;cursor:pointer;padding:6px}.panel-body{padding:11px 14px}.empty-cockpit{padding:22px 12px;text-align:center;color:#7f93aa;font-size:12px}
      .dossier-list,.alert-list,.activity-list,.agenda-list{display:grid}.dossier-row,.alert-row,.activity-row,.agenda-row{border:0;border-bottom:1px solid #17324d;background:transparent;color:#eef3f9;text-align:left;cursor:pointer}.dossier-row:last-child,.alert-row:last-child,.activity-row:last-child,.agenda-row:last-child{border-bottom:0}.dossier-row:hover,.alert-row:hover,.activity-row:hover,.agenda-row:hover{background:#0a213d}.dossier-row{display:grid;grid-template-columns:10px minmax(0,1fr) auto;gap:10px;align-items:center;padding:11px 4px}.status-dot{width:8px;height:8px;border-radius:50%;background:#2bb879}.status-dot.high,.status-dot.critical{background:#ef4444}.status-dot.medium{background:#f3b51b}.dossier-copy,.alert-copy,.activity-copy{min-width:0}.dossier-copy b,.alert-copy b,.activity-copy b{display:block;color:#f4f7fb;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dossier-copy small,.alert-copy small,.activity-copy small{display:block;color:#8fa2b8;font-size:10px;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.score-pill{min-width:34px;height:34px;border:2px solid #f3b51b;border-radius:50%;display:grid;place-items:center;font-size:10px;font-weight:850;color:#fff}.score-pill.high,.score-pill.critical{border-color:#ef4444}.score-pill.low{border-color:#22a66f}
      .impact-wrap{display:grid;grid-template-columns:128px 1fr;gap:14px;align-items:center;padding:17px 5px 19px}.impact-donut{width:118px;height:118px;border-radius:50%;display:grid;place-items:center;position:relative}.impact-donut:after{content:"";position:absolute;width:72px;height:72px;background:#071a31;border-radius:50%;box-shadow:0 0 0 1px #15334f}.impact-center{position:relative;z-index:1;text-align:center}.impact-center strong{display:block;font-size:24px}.impact-center span{font-size:9px;color:#8fa2b8}.impact-legend{display:grid;gap:11px}.legend-row{display:grid;grid-template-columns:8px 1fr auto;gap:7px;align-items:center;color:#dce5ef;font-size:10px}.legend-dot{width:7px;height:7px;border-radius:50%}.legend-dot.red{background:#ef4444}.legend-dot.gold{background:#f3b51b}.legend-dot.green{background:#22a66f}
      .trend-chart{padding:11px 14px 7px}.trend-chart svg{width:100%;height:142px;overflow:visible}.trend-grid{stroke:#16324d;stroke-width:.6}.trend-line{fill:none;stroke:#f3b51b;stroke-width:2.4}.trend-area{fill:rgba(243,181,27,.13)}.trend-labels{display:grid;grid-template-columns:repeat(7,1fr);color:#788da5;font-size:9px;text-align:center;margin-top:-2px}.trend-legend{display:flex;justify-content:center;gap:6px;align-items:center;color:#97a9bd;font-size:9px;padding:0 0 12px}.trend-legend:before{content:"";width:16px;height:3px;border-radius:3px;background:#f3b51b}
      .quick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.quick-btn{min-height:84px;background:#071b34;border:1px solid #1a3a58;border-radius:9px;color:#eef3fa;display:grid;place-items:center;align-content:center;gap:8px;cursor:pointer;font-size:10px}.quick-btn svg{color:#f3b51b}.quick-btn:hover{background:#0b2747;border-color:#315575}.activity-row{padding:10px 2px;display:grid;grid-template-columns:28px minmax(0,1fr) auto;align-items:center;gap:10px}.activity-icon{width:26px;height:26px;border:1px solid #1a3b5c;background:#071a31;border-radius:6px;display:grid;place-items:center;color:#f3b51b}.activity-age,.alert-age{color:#8195ab;font-size:9px}.alert-row{padding:11px 2px;display:grid;grid-template-columns:9px minmax(0,1fr) auto;gap:9px;align-items:center}.alert-badge{display:block;border-radius:5px;padding:5px 6px;font-size:9px;text-align:center;margin-bottom:4px}.alert-badge.high,.alert-badge.critical{background:#3b1820;color:#ff737e}.alert-badge.medium{background:#3a2b09;color:#ffc62a}.agenda-row{padding:10px 1px;display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:10px;align-items:center}.agenda-date{display:grid;text-align:center;color:#fff}.agenda-date strong{font-size:17px;line-height:1}.agenda-date span{font-size:8px;color:#a4b5c8;margin-top:3px}.agenda-copy b{display:block;font-size:11px;color:#f3f6fa}.agenda-copy small{display:block;font-size:9px;color:#8398ae;margin-top:3px}.agenda-time{background:#102a45;border:1px solid #1d3d5c;border-radius:6px;padding:6px;color:#dce6ef;font-size:9px}
      .next-key{background:linear-gradient(135deg,#ffd04c 0%,#f3b51b 55%,#d99500 100%);border:1px solid #ffdf75;border-radius:14px;padding:18px;color:#07162c;box-shadow:0 18px 38px rgba(217,149,0,.20),0 0 28px rgba(243,181,27,.12);display:grid;gap:13px;position:relative;overflow:hidden}.next-key:after{content:"";position:absolute;width:130px;height:130px;border-radius:50%;right:-50px;top:-58px;background:rgba(255,255,255,.18)}.next-key-head{display:flex;align-items:center;gap:9px;font-weight:900;position:relative;z-index:1}.next-key-icon{width:34px;height:34px;border-radius:10px;background:#07162c;color:#ffc62a;display:grid;place-items:center}.next-key-copy{position:relative;z-index:1}.next-key-copy h3{font-size:16px;line-height:1.25;margin:0 0 8px;color:#07162c}.next-key-copy p{margin:0;color:#29384b;font-size:10px;line-height:1.55}.next-key-badges{display:flex;flex-wrap:wrap;gap:6px;margin-top:10px}.next-key-badge{background:rgba(7,22,44,.10);border:1px solid rgba(7,22,44,.16);border-radius:999px;padding:5px 8px;font-size:9px;font-weight:800}.next-key-cta{position:relative;z-index:1;width:100%;border:1px solid #07162c;background:#07162c;color:#ffd04c;border-radius:9px;padding:10px 12px;display:flex;justify-content:center;align-items:center;gap:7px;font-weight:850;cursor:pointer}.next-key-cta:hover{background:#0b2444}
      .cockpit-footer{border:1px solid #173552;background:#071a31;border-radius:10px;display:grid;grid-template-columns:repeat(3,1fr);min-height:54px}.footer-item{display:flex;align-items:center;justify-content:center;gap:9px;color:#a8b8ca;border-right:1px solid #173552;font-size:10px}.footer-item:last-child{border-right:0}.footer-item svg{color:#8da6c0}.footer-item.secure svg,.footer-item.secure b{color:#38d58c}.dash-search-backdrop{position:fixed;inset:0;z-index:10000;background:rgba(1,8,19,.72);backdrop-filter:blur(7px);display:flex;justify-content:center;align-items:flex-start;padding:90px 18px}.dash-search-modal{width:min(720px,100%);background:#06162c;border:1px solid #173653;border-radius:18px;overflow:hidden;box-shadow:0 28px 70px rgba(0,0,0,.45)}.dash-search-head{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:10px;padding:14px 16px;border-bottom:1px solid #173653;color:#8fa4bc}.dash-search-head input{width:100%;border:0;outline:0;background:transparent;color:#f6f8fb;font:inherit;font-size:16px}.dash-search-close{border:1px solid #173653;background:#0a213d;color:#d9e4f2;border-radius:9px;padding:8px 10px;font-weight:800;cursor:pointer}.dash-search-results{max-height:520px;overflow:auto;padding:8px}.dash-search-result{width:100%;border:0;background:transparent;border-radius:12px;padding:12px;display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:12px;align-items:center;text-align:left;color:#eef4fb;cursor:pointer}.dash-search-result:hover{background:#0a213d}.dash-search-kind{min-width:62px;padding:5px 8px;border-radius:999px;background:#0c2b59;color:#73aafc;font-size:11px;font-weight:850;text-align:center}.dash-search-copy{display:grid;gap:3px;min-width:0}.dash-search-copy b,.dash-search-copy small{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dash-search-copy small{font-size:11px;color:#8fa4bc}.dash-search-empty{padding:28px 18px;text-align:center;color:#8fa4bc;font-size:13px}
      @media(max-width:1180px){.cockpit-layout{grid-template-columns:1fr}.cockpit-side{grid-template-columns:repeat(3,1fr)}.cockpit-row{grid-template-columns:1fr 1fr}.cockpit-row>.cockpit-panel:last-child{grid-column:1/-1}}
      @media(max-width:850px){.app:has(.cockpit-dashboard) .main{padding:17px 14px 96px}.cockpit-top{grid-template-columns:1fr}.metric-grid{grid-template-columns:repeat(2,1fr)}.cockpit-row,.cockpit-bottom,.cockpit-side{grid-template-columns:1fr}.cockpit-row>.cockpit-panel:last-child{grid-column:auto}.cockpit-footer{grid-template-columns:1fr}.footer-item{border-right:0;border-bottom:1px solid #173552;justify-content:flex-start;padding:0 15px}.footer-item:last-child{border-bottom:0}}
      @media(max-width:520px){.cockpit-greeting h1{font-size:24px}.metric-grid{gap:9px}.metric-card{grid-template-columns:38px 1fr;padding:13px 11px}.metric-icon{width:38px;height:38px}.metric-value{font-size:22px}.impact-wrap{grid-template-columns:1fr;justify-items:center}.quick-grid{grid-template-columns:repeat(2,1fr)}}
    `}</style>

    <div className="cockpit-top"><div className="cockpit-greeting"><h1>Bonjour,</h1><p>Voici les informations clés de ce {dateLabel}.</p></div><button className="cockpit-search" onClick={()=>setSearchOpen(true)}><span>Rechercher un dossier, une veille, un acteur…</span><Search size={17}/></button></div>

    <section className="metric-grid">
      <button className="metric-card" onClick={()=>go("dossiers")}><span className="metric-icon blue"><BriefcaseBusiness size={23}/></span><span className="metric-copy"><span className="metric-label">Dossiers actifs</span><strong className="metric-value">{dossiers.length}</strong><span className="metric-delta">Portefeuille client</span></span></button>
      <button className="metric-card" onClick={()=>go("veille")}><span className="metric-icon green"><FileText size={23}/></span><span className="metric-copy"><span className="metric-label">Veilles aujourd’hui</span><strong className="metric-value">{todayWatch.length}</strong><span className="metric-delta green">{watch.length} au total</span></span></button>
      <button className="metric-card" onClick={()=>go("impact")}><span className="metric-icon gold"><TrendingUp size={23}/></span><span className="metric-copy"><span className="metric-label">Notes d’impact</span><strong className="metric-value">{impactNotes}</strong><span className="metric-delta gold">Analyses ouvertes</span></span></button>
      <button className="metric-card" onClick={()=>go("veille")}><span className="metric-icon red"><Bell size={23}/></span><span className="metric-copy"><span className="metric-label">Alertes actives</span><strong className="metric-value">{urgentWatch.length}</strong><span className="metric-delta red">{urgentWatch.filter(item=>item.urgency==="absolument urgent").length} urgence(s)</span></span></button>
    </section>

    <div className="cockpit-layout"><main className="cockpit-main">
      <div className="cockpit-row">
        <section className="cockpit-panel"><div className="panel-head"><h2>Dossiers récents</h2><button className="panel-link" onClick={()=>go("dossiers")}>Voir tous</button></div><div className="panel-body dossier-list">{recentDossiers.length?recentDossiers.map(dossier=>{const dossierWatch=watch.filter(item=>item.dossier_id===dossier.id);const urgency=[...dossierWatch].sort((a,b)=>rank(b.urgency)-rank(a.urgency))[0]?.urgency||"faible";return <button key={dossier.id} className="dossier-row" onClick={()=>openExactDossier(dossier.id)}><span className={`status-dot ${urgencyClass(urgency)}`}/><span className="dossier-copy"><b>{dossier.title}</b><small>{dossier.client||"Dossier client"}</small></span><span className={`score-pill ${urgencyClass(urgency)}`}>{scoreFromUrgency(urgency)}</span></button>}):<div className="empty-cockpit">Aucun dossier actif.</div>}</div></section>
        <section className="cockpit-panel"><div className="panel-head"><h2>Répartition des impacts</h2><button className="panel-link" onClick={()=>go("impact")}>Voir les notes</button></div><div className="panel-body impact-wrap"><div className="impact-donut" style={{background:donut}}><div className="impact-center"><strong>{watch.length}</strong><span>Total</span></div></div><div className="impact-legend"><div className="legend-row"><span className="legend-dot red"/><span>Impact élevé</span><b>{highCount} ({highPct}%)</b></div><div className="legend-row"><span className="legend-dot gold"/><span>Impact moyen</span><b>{mediumCount} ({mediumPct}%)</b></div><div className="legend-row"><span className="legend-dot green"/><span>Impact faible</span><b>{lowCount} ({lowPct}%)</b></div></div></div></section>
        <section className="cockpit-panel"><div className="panel-head"><h2>Tendance des veilles</h2><span style={{color:"#8398ae",fontSize:10}}>7 derniers jours</span></div><div className="trend-chart"><svg viewBox="0 0 100 80" preserveAspectRatio="none" aria-label="Tendance des veilles"><line className="trend-grid" x1="0" y1="20" x2="100" y2="20"/><line className="trend-grid" x1="0" y1="40" x2="100" y2="40"/><line className="trend-grid" x1="0" y1="60" x2="100" y2="60"/><polygon className="trend-area" points={`0,76 ${points} 100,76`}/><polyline className="trend-line" points={points}/>{trend.map((item,index)=><circle key={item.date} cx={index*(100/6)} cy={76-(item.count/maxTrend)*58} r="1.6" fill="#f3b51b"/>)}</svg><div className="trend-labels">{trend.map(item=><span key={item.date}>{shortDate(item.date)}</span>)}</div></div><div className="trend-legend">Nombre de veilles</div></section>
      </div>

      <div className="cockpit-bottom">
        <section className="cockpit-panel"><div className="panel-head"><h2>Accès rapides</h2><span style={{color:"#8094aa",fontSize:10}}>Modules Myvor</span></div><div className="panel-body quick-grid"><button className="quick-btn" onClick={()=>go("dossiers")}><FolderPlus size={24}/>Nouveau dossier</button><button className="quick-btn" onClick={()=>go("impact")}><TrendingUp size={24}/>Note d’impact</button><button className="quick-btn" onClick={()=>go("builder")}><Sparkles size={24}/>Note Builder</button><button className="quick-btn" onClick={()=>go("veille")}><Search size={24}/>Veille</button><button className="quick-btn" onClick={()=>go("radar")}><Target size={24}/>Radar d’influence</button><button className="quick-btn" onClick={()=>go("veille")}><Bell size={24}/>Alertes</button></div></section>
        <section className="cockpit-panel"><div className="panel-head"><h2>Activité récente</h2><button className="panel-link" onClick={()=>go("dossiers")}>Voir l’activité <ArrowRight size={13}/></button></div><div className="panel-body activity-list">{activities.length?activities.map(item=><button key={item.key} className="activity-row" onClick={()=>openActivity(item)}><span className="activity-icon">{item.kind==="watch"?<Activity size={14}/>:item.kind==="dossier"?<BriefcaseBusiness size={14}/>:<Sparkles size={14}/>}</span><span className="activity-copy"><b>{item.title}</b><small>{item.meta}</small></span><span className="activity-age">{relativeTime(item.date)}</span></button>):<div className="empty-cockpit">Aucune activité récente.</div>}</div></section>
      </div>
    </main>

    <aside className="cockpit-side">
      <section className="cockpit-panel"><div className="panel-head"><h2>Alertes prioritaires</h2><button className="panel-link" onClick={()=>go("veille")}>Voir toutes</button></div><div className="panel-body alert-list">{urgentWatch.slice(0,4).length?urgentWatch.slice(0,4).map(item=><button key={item.id} className="alert-row" onClick={()=>openExactWatch(item.id)}><span className={`status-dot ${urgencyClass(item.urgency)}`}/><span className="alert-copy"><b>{item.title}</b><small>{item.nature}</small></span><span><span className={`alert-badge ${urgencyClass(item.urgency)}`}>{item.urgency==="absolument urgent"?"Urgent":item.urgency}</span><span className="alert-age">{relativeTime(item.created_at)}</span></span></button>):<div className="empty-cockpit">Aucune alerte prioritaire.</div>}</div><div style={{padding:"0 14px 13px"}}><button className="panel-link" onClick={()=>go("veille")}>Voir toutes les alertes <ArrowRight size={13}/></button></div></section>
      <section className="cockpit-panel"><div className="panel-head"><h2>Agenda institutionnel</h2><button className="panel-link" onClick={()=>go("dossiers")}>Voir l’agenda</button></div><div className="panel-body agenda-list">{deadlines.length?deadlines.map(action=>{const date=agendaDate(action.due_date);return <button key={action.id} className="agenda-row" onClick={()=>openExactAction(action)}><span className="agenda-date"><strong>{date.day}</strong><span>{date.month}</span></span><span className="agenda-copy"><b>{action.title}</b><small>{dossierName(action.dossier_id)}</small></span><span className="agenda-time">{date.time}</span></button>}):<div className="empty-cockpit">Aucune échéance à venir.</div>}</div></section>

      <section className="next-key" aria-label="Prochaine étape clé"><div className="next-key-head"><span className="next-key-icon"><Target size={18}/></span><span>Prochaine étape clé</span></div><div className="next-key-copy">{nextStepAction?<><h3>{nextStepAction.title}</h3><p>{nextStepAction.actor_name?`Acteur : ${nextStepAction.actor_name}`:dossierName(nextStepAction.dossier_id)}</p><div className="next-key-badges"><span className="next-key-badge">{nextStepAction.priority||"À traiter"}</span>{nextStepAction.due_date&&<span className="next-key-badge">Échéance : {agendaDate(nextStepAction.due_date).day} {agendaDate(nextStepAction.due_date).month} · {agendaDate(nextStepAction.due_date).time}</span>}</div></>:nextStepWatch?<><h3>{nextStepWatch.title}</h3><p>{nextStepWatch.nature}{nextStepWatch.dossier_id?` · ${dossierName(nextStepWatch.dossier_id)}`:" · Veille à qualifier"}</p><div className="next-key-badges"><span className="next-key-badge">{nextStepWatch.urgency}</span><span className="next-key-badge">{relativeTime(nextStepWatch.created_at)}</span></div></>:<><h3>Aucune action critique détectée</h3><p>Votre portefeuille est à jour pour le moment.</p></>}</div><button className="next-key-cta" onClick={()=>nextStepAction?openExactAction(nextStepAction):nextStepWatch?openExactWatch(nextStepWatch.id):go("dossiers")}>{nextStepAction?actionCta(nextStepAction.type):nextStepWatch?"Ouvrir l’alerte":"Ouvrir les dossiers"}<ArrowRight size={15}/></button></section>
    </aside></div>

    <footer className="cockpit-footer"><div className="footer-item secure"><ShieldCheck size={18}/><span><b>Sécurité :</b> session authentifiée</span></div><div className="footer-item"><Database size={18}/><span>Sources connectées : <b>{sourceCount}</b></span></div><div className="footer-item"><RefreshCw size={18}/><span>Dernière synchronisation : <b>{lastSync?relativeTime(lastSync):"aucune"}</b></span></div></footer>
    {actionsLoading&&<div style={{color:"#8499b0",fontSize:10,textAlign:"right"}}><Clock3 size={11} style={{verticalAlign:"middle",marginRight:5}}/>Actualisation des actions…</div>}
    {actionsError&&<div style={{color:"#ff9d8f",fontSize:10,textAlign:"right"}}><AlertTriangle size={11} style={{verticalAlign:"middle",marginRight:5}}/>{actionsError}</div>}

    {searchOpen&&<div className="dash-search-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)closeSearch();}}><div className="dash-search-modal" role="dialog" aria-modal="true" aria-label="Recherche Myvor"><div className="dash-search-head"><Search size={19}/><input autoFocus value={searchQuery} onChange={event=>setSearchQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Escape")closeSearch();if(event.key==="Enter"&&searchResults[0])openSearchResult(searchResults[0]);}} placeholder="Rechercher un dossier, un texte, une action…"/><button type="button" className="dash-search-close" onClick={closeSearch}>Fermer</button></div><div className="dash-search-results">{searchQuery.trim()?searchResults.length?searchResults.map(result=><button type="button" className="dash-search-result" key={result.key} onClick={()=>openSearchResult(result)}><span className="dash-search-kind">{result.kind}</span><span className="dash-search-copy"><b>{result.title}</b><small>{result.meta}</small></span><ArrowRight size={16}/></button>):<div className="dash-search-empty">Aucun résultat.</div>:<div className="dash-search-empty">Recherchez dans vos dossiers, votre veille et vos actions.</div>}</div></div></div>}
  </div>;
}
