"use client";

import { useEffect,useState } from "react";
import { ArrowLeft,FileText,Target,AlertTriangle,CalendarDays,Sparkles } from "lucide-react";
import type { Action } from "./DashboardCorporate";
import { listProductions,type Production } from "@/lib/productions";

type Dossier={id:string;client:string;title:string;objective:string;context:string;status:string;created_at:string};
type Watch={id:string;title:string;nature:string;source_url:string;dossier_id:string|null;urgency:string;created_at:string};
type Tab="dashboard"|"dossiers"|"veille"|"impact"|"radar"|"builder";

export default function DossierDetail({dossier,watch,actions,back,go}:{dossier:Dossier;watch:Watch[];actions:Action[];back:()=>void;go:(tab:Tab)=>void}){
  const related=watch.filter(w=>w.dossier_id===dossier.id);
  const openActions=actions.filter(a=>a.dossier_id===dossier.id&&a.status!=="termine");
  const urgent=related.filter(w=>["fort","absolument urgent"].includes(w.urgency));
  const [productions,setProductions]=useState<Production[]>([]);const [productionError,setProductionError]=useState("");const [selectedProduction,setSelectedProduction]=useState<Production|null>(null);const [focusActionId,setFocusActionId]=useState<string|null>(null);
  useEffect(()=>{let active=true;listProductions(dossier.id).then(({data,error})=>{if(!active)return;setProductions(data);setProductionError(error?error.message:"");});return()=>{active=false;};},[dossier.id]);
  useEffect(()=>{const raw=sessionStorage.getItem("myvor:focus-action");if(!raw)return;try{const action=JSON.parse(raw);if(action?.id&&openActions.some(item=>item.id===action.id)){setFocusActionId(action.id);sessionStorage.removeItem("myvor:focus-action");setTimeout(()=>document.getElementById(`action-${action.id}`)?.scrollIntoView({behavior:"smooth",block:"center"}),100);setTimeout(()=>setFocusActionId(null),2600);}}catch{sessionStorage.removeItem("myvor:focus-action");}},[dossier.id,actions.length]);
  return <div className="corp-dashboard">
    <style jsx global>{`.myvor-action-focus{outline:3px solid #f3bd3e!important;outline-offset:3px;box-shadow:0 0 0 8px rgba(243,189,62,.14)!important;background:#fff9e8!important}`}</style>
    <button className="corp-primary" style={{marginBottom:18}} onClick={back}><ArrowLeft size={16}/> Retour aux dossiers</button>
    <div className="corp-head"><div><div className="corp-kicker">Dossier client</div><h1>{dossier.title}</h1><p>{dossier.client}</p></div><span className="corp-status">{dossier.status}</span></div>
    <section className="corp-panel" style={{marginBottom:16}}><div className="corp-panel-head"><div><span>Objectif stratégique</span><h2>{dossier.objective}</h2></div><Target size={20}/></div>{dossier.context&&<p>{dossier.context}</p>}</section>
    <div className="corp-kpis"><div className="corp-kpi"><span>Textes liés</span><strong>{related.length}</strong><small><FileText size={15}/> Corpus du dossier</small></div><div className="corp-kpi alert"><span>Risques forts</span><strong>{urgent.length}</strong><small><AlertTriangle size={15}/> À surveiller</small></div><div className="corp-kpi"><span>Actions ouvertes</span><strong>{openActions.length}</strong><small><CalendarDays size={15}/> À exécuter</small></div><div className="corp-kpi"><span>Productions IA</span><strong>{productions.length}</strong><small><Sparkles size={15}/> Historique du dossier</small></div></div>
    <div className="corp-dashboard-grid"><section className="corp-panel"><div className="corp-panel-head"><div><span>Veille liée</span><h2>Textes du dossier</h2></div><button onClick={()=>go("veille")}>Ouvrir la veille</button></div><div className="corp-list">{related.length?related.map(item=><a className="corp-list-row" key={item.id} href={item.source_url||undefined} target={item.source_url?"_blank":undefined} rel="noreferrer"><span className="corp-doc"><FileText size={18}/></span><span className="corp-list-copy"><b>{item.title}</b><small>{item.nature}</small></span><span className={`corp-impact ${item.urgency.replaceAll(" ","-")}`}>{item.urgency}</span></a>):<div className="corp-empty">Aucun texte rattaché.</div>}</div></section>
    <section className="corp-panel"><div className="corp-panel-head"><div><span>Plan d’action</span><h2>Actions ouvertes</h2></div></div><div className="corp-list">{openActions.length?openActions.map(a=><button id={`action-${a.id}`} className={`corp-list-row ${focusActionId===a.id?"myvor-action-focus":""}`} key={a.id} onClick={()=>go(a.type==="contact"?"radar":a.type==="note_client"||a.type==="amendement"?"builder":"impact")}><span className="corp-list-copy"><b>{a.title}</b><small>{[a.actor_name,a.priority,a.due_date?new Date(a.due_date).toLocaleDateString("fr-FR"):null].filter(Boolean).join(" · ")}</small></span></button>):<div className="corp-empty">Aucune action ouverte.</div>}</div></section>
    <aside className="corp-side-stack"><section className="corp-panel corp-score-card"><span>Outils du dossier</span><button onClick={()=>go("impact")}><Sparkles size={15}/> Note d’impact</button><button onClick={()=>go("radar")}><Sparkles size={15}/> Radar d’influence</button><button onClick={()=>go("builder")}><Sparkles size={15}/> Note Builder</button></section></aside></div>
    <section className="corp-panel" style={{marginTop:16}}><div className="corp-panel-head"><div><span>Mémoire du dossier</span><h2>Productions IA</h2></div><Sparkles size={19}/></div>{productionError?<div className="corp-empty">Historique indisponible : {productionError}</div>:productions.length?<div className="corp-list">{productions.map(p=><button className="corp-list-row" key={p.id} onClick={()=>setSelectedProduction(selectedProduction?.id===p.id?null:p)}><span className="corp-doc"><Sparkles size={18}/></span><span className="corp-list-copy"><b>{p.title}</b><small>{labelType(p.type)} · {new Date(p.created_at).toLocaleString("fr-FR",{dateStyle:"medium",timeStyle:"short"})}</small></span></button>)}</div>:<div className="corp-empty">Aucune production enregistrée pour ce dossier.</div>}{selectedProduction&&<ProductionPreview production={selectedProduction}/>}</section>
  </div>;
}

function labelType(type:Production["type"]){return type==="impact"?"Note d’impact":type==="radar"?"Radar d’influence":"Note Builder";}
function ProductionPreview({production}:{production:Production}){const content:any=production.content||{};if(production.type==="impact"){const note=content.note||{};return <div style={{marginTop:16,padding:16,border:"1px solid #e1e8f2",borderRadius:14,background:"#f9fbfe"}}><b>{note.executive_summary||production.title}</b>{note.score!=null&&<p>Score d’impact : {note.score}/100 · {note.level||""}</p>}{Array.isArray(note.recommendations)&&note.recommendations.length>0&&<ul>{note.recommendations.map((x:string,i:number)=><li key={i}>{x}</li>)}</ul>}</div>;}if(production.type==="radar"){const actors=Array.isArray(content.actors)?content.actors:[];return <div style={{marginTop:16,padding:16,border:"1px solid #e1e8f2",borderRadius:14,background:"#f9fbfe"}}><b>{actors.length} acteur(s) cartographié(s)</b><ul>{actors.slice(0,8).map((a:any,i:number)=><li key={a.id||i}>{a.name} — influence {a.influence}/5 — {a.position}</li>)}</ul></div>;}const doc=content.document||{};return <div style={{marginTop:16,padding:16,border:"1px solid #e1e8f2",borderRadius:14,background:"#f9fbfe"}}><b>{doc.subject?`Objet : ${doc.subject}`:production.title}</b><p style={{whiteSpace:"pre-wrap",lineHeight:1.6}}>{doc.content||"Document enregistré."}</p></div>;}
