"use client";

import { useEffect,useMemo,useState } from "react";
import { Bell,BriefcaseBusiness,CalendarDays,FileText,Folder,MoreHorizontal,Search,Sparkles,Trash2 } from "lucide-react";
import { isTransientError,withRetry } from "@/lib/reliability";
import { supabase } from "@/lib/supabase";
import styles from "./DossiersCorporate.module.css";

type Dossier={id:string;client:string;title:string;objective:string;context:string;status:string;created_at:string};
type Watch={id:string;title:string;nature:string;source_url:string;dossier_id:string|null;urgency:string;created_at:string};
type EditDraft={client:string;title:string;objective:string;context:string;status:string};
type ImpactProductionRow={dossier_id:string;content:any;created_at:string};
type ImpactTone="critical"|"strong"|"medium"|"low";

function impactTone(score:number):ImpactTone{if(score>=80)return"critical";if(score>=65)return"strong";if(score>=45)return"medium";return"low";}
function asRetryable(error:any,status?:number){const wrapped:any=new Error(error?.message||"Opération Supabase impossible.");wrapped.status=status||error?.status||0;return wrapped;}
async function reliableSupabase<T extends {error:any;status?:number}>(operation:()=>PromiseLike<T>){return withRetry(async()=>{const result=await operation();if(result.error)throw asRetryable(result.error,result.status);return result;},{attempts:3,baseDelayMs:220,shouldRetry:error=>isTransientError(error)});}

export default function DossiersCorporate({items,watch,add,search,searching,messages,open}:{items:Dossier[];watch:Watch[];add:()=>void;search:(d:Dossier)=>void;searching:string|null;messages:Record<string,string>;open:(d:Dossier)=>void}){
  const [query,setQuery]=useState("");const [filter,setFilter]=useState<"all"|"active"|"urgent">("all");const [menuId,setMenuId]=useState<string|null>(null);const [deleting,setDeleting]=useState<string|null>(null);const [deleteMessage,setDeleteMessage]=useState("");const [editing,setEditing]=useState<Dossier|null>(null);const [saving,setSaving]=useState(false);const [editMessage,setEditMessage]=useState("");const [revision,setRevision]=useState(0);const [impactScores,setImpactScores]=useState<Record<string,number>>({});const [draft,setDraft]=useState<EditDraft>({client:"",title:"",objective:"",context:"",status:"Actif"});

  useEffect(()=>{const target=sessionStorage.getItem("myvor:open-dossier");if(!target)return;const dossier=items.find(item=>item.id===target);if(dossier){sessionStorage.removeItem("myvor:open-dossier");open(dossier);}},[items,open]);
  useEffect(()=>{let active=true;async function loadValidatedScores(){if(!supabase||!items.length){if(active)setImpactScores({});return;}try{const dossierIds=items.map(item=>item.id);const {data}=await reliableSupabase(()=>supabase.from("productions").select("dossier_id,content,created_at").eq("type","impact").in("dossier_id",dossierIds).order("created_at",{ascending:false}));if(!active)return;const scores:Record<string,number>={};for(const row of (data||[]) as ImpactProductionRow[]){if(scores[row.dossier_id]!=null)continue;const note=row.content?.note;const score=Number(note?.score);if(note?.quality?.status!=="validated"||note?.score_available===false||!Number.isFinite(score))continue;scores[row.dossier_id]=Math.max(0,Math.min(100,Math.round(score)));}if(active)setImpactScores(scores);}catch{}}void loadValidatedScores();return()=>{active=false;};},[items,revision]);

  function related(dossierId:string){return watch.filter(item=>item.dossier_id===dossierId);}function rank(dossierId:string){return impactScores[dossierId]??-1;}
  const filtered=useMemo(()=>items.filter(dossier=>{const q=query.trim().toLocaleLowerCase("fr");const matches=!q||[dossier.client,dossier.title,dossier.objective,dossier.context].join(" ").toLocaleLowerCase("fr").includes(q);const rel=watch.filter(item=>item.dossier_id===dossier.id);const urgent=rel.some(item=>["fort","absolument urgent"].includes(item.urgency));const status=filter==="all"||(filter==="active"&&dossier.status.toLowerCase()==="actif")||(filter==="urgent"&&urgent);return matches&&status;}).sort((a,b)=>rank(b.id)-rank(a.id)||new Date(b.created_at).getTime()-new Date(a.created_at).getTime()),[items,watch,query,filter,revision,impactScores]);
  const activeCount=items.filter(d=>d.status.toLowerCase()==="actif").length;const linkedCount=items.filter(d=>watch.some(w=>w.dossier_id===d.id)).length;const urgentCount=items.filter(d=>watch.some(w=>w.dossier_id===d.id&&["fort","absolument urgent"].includes(w.urgency))).length;

  function beginEdit(dossier:Dossier){setMenuId(null);setEditMessage("");setEditing(dossier);setDraft({client:dossier.client,title:dossier.title,objective:dossier.objective,context:dossier.context||"",status:dossier.status||"Actif"});}
  async function saveDossier(e:React.FormEvent){e.preventDefault();if(!supabase||!editing||saving)return;const payload={client:draft.client.trim(),title:draft.title.trim(),objective:draft.objective.trim(),context:draft.context.trim(),status:draft.status};if(!payload.client||!payload.title||!payload.objective){setEditMessage("Client, intitulé et objectif sont obligatoires.");return;}setSaving(true);setEditMessage("");try{const {data}=await reliableSupabase(()=>supabase.from("dossiers").update(payload).eq("id",editing.id).select("*").single());Object.assign(editing,data as Dossier);setEditing(null);setRevision(v=>v+1);if(typeof window!=="undefined")window.dispatchEvent(new Event("pageshow"));}catch(error:any){setEditMessage(`Impossible d’enregistrer : ${error?.message||"erreur réseau"}`);}finally{setSaving(false);}}
  async function removeDossier(dossier:Dossier){if(!supabase||deleting)return;const confirmed=window.confirm(`Supprimer définitivement le dossier « ${dossier.title} » pour ${dossier.client} ?\n\nCette action supprimera aussi ses actions et productions enregistrées.`);if(!confirmed)return;setDeleting(dossier.id);setDeleteMessage("");setMenuId(null);try{await reliableSupabase(()=>supabase.from("actions").delete().eq("dossier_id",dossier.id));await reliableSupabase(()=>supabase.from("dossiers").delete().eq("id",dossier.id));window.location.reload();}catch(error:any){setDeleteMessage(`Impossible de supprimer le dossier : ${error?.message||"erreur inconnue"}`);setDeleting(null);}}

  return <div className={styles.page}><div className={styles.head}><div><h1>Dossiers clients</h1><p>Gérez et suivez l’ensemble de vos dossiers clients.</p></div><button className={styles.primary} onClick={add}>+ Nouveau dossier</button></div>{deleteMessage&&<div className={styles.message}>{deleteMessage}</div>}<div className={styles.kpis}><button onClick={()=>setFilter("active")} className={styles.kpi}><span className={styles.kpiIcon}><Folder size={22}/></span><span><strong>{activeCount}</strong><small>Dossiers actifs</small><em>Portefeuille client</em></span></button><button onClick={()=>setFilter("all")} className={styles.kpi}><span className={styles.kpiIcon}><FileText size={22}/></span><span><strong>{watch.length}</strong><small>Textes suivis</small><em>{linkedCount} dossier(s) liés</em></span></button><button onClick={()=>setFilter("urgent")} className={styles.kpi}><span className={`${styles.kpiIcon} ${styles.alertIcon}`}><Bell size={22}/></span><span><strong>{urgentCount}</strong><small>Alertes critiques</small><em>À traiter</em></span></button><button onClick={()=>setFilter("all")} className={styles.kpi}><span className={styles.kpiIcon}><BriefcaseBusiness size={22}/></span><span><strong>{items.length}</strong><small>Dossiers au total</small><em>Base active</em></span></button></div><div className={styles.toolbar}><label className={styles.search}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un dossier, un client…"/></label><div className={styles.filters}><button className={filter==="all"?styles.active:""} onClick={()=>setFilter("all")}>Tous les statuts</button><button className={filter==="active"?styles.active:""} onClick={()=>setFilter("active")}>Actifs</button><button className={filter==="urgent"?styles.active:""} onClick={()=>setFilter("urgent")}>Prioritaires</button></div></div>
    {filtered.length?<div className={styles.tableWrap}><div className={styles.tableHeader}><span>Dossier</span><span>Client</span><span>Statut</span><span>Score validé</span><span>Dernière évolution</span><span>Alertes</span><span/></div><div className={styles.tableBody}>{filtered.map(dossier=>{const rel=related(dossier.id);const urgent=rel.filter(w=>["fort","absolument urgent"].includes(w.urgency)).length;const score=impactScores[dossier.id];const tone=score!=null?impactTone(score):null;const latest=rel.reduce((max,item)=>Math.max(max,new Date(item.created_at).getTime()||0),0);const impactStyle=tone?({"--impact":`${score*3.6}deg`} as React.CSSProperties):undefined;return <div className={styles.tableRow} key={dossier.id} onDoubleClick={()=>open(dossier)}><button className={styles.dossierCell} onClick={()=>open(dossier)}><span className={styles.star}>☆</span><span><b>{dossier.title}</b><small>{dossier.objective||"Objectif à préciser"}</small></span></button><div className={styles.clientCell}><b>{dossier.client}</b><small>Client</small></div><div><span className={`${styles.status} ${dossier.status.toLowerCase()==="actif"?styles.statusActive:styles.statusIdle}`}>{dossier.status}<i/></span></div><div><span className={`${styles.impact} ${tone?styles[tone]:""}`} style={impactStyle} title={score!=null?"Dernière Note d’impact validée":"Aucune Note d’impact validée"}><b>{score!=null?`${score}%`:"—"}</b></span></div><div className={styles.dateCell}><CalendarDays size={17}/><span><b>{latest?new Date(latest).toLocaleDateString("fr-FR",{day:"2-digit",month:"short",year:"numeric"}):"—"}</b><small>{latest?"Veille rattachée":"Aucune évolution"}</small></span></div><div className={styles.alertCell}><Bell size={17}/><span className={urgent?styles.alertCount:styles.alertZero}>{urgent}</span></div><div className={styles.menuCell}><button className={styles.menuButton} onClick={()=>setMenuId(menuId===dossier.id?null:dossier.id)} aria-label="Actions du dossier"><MoreHorizontal size={19}/></button>{menuId===dossier.id&&<div className={styles.menu}><button onClick={()=>open(dossier)}>Ouvrir le dossier</button><button disabled={!!searching} onClick={()=>{setMenuId(null);search(dossier);}}><Sparkles size={14}/>{searching===dossier.id?"Analyse en cours…":"Chercher les évolutions"}</button><button onClick={()=>beginEdit(dossier)}>Modifier le dossier</button><button className={styles.danger} disabled={deleting===dossier.id} onClick={()=>void removeDossier(dossier)}><Trash2 size={14}/>{deleting===dossier.id?"Suppression…":"Supprimer"}</button></div>}</div>{messages[dossier.id]&&<div className={styles.rowMessage}>{messages[dossier.id]}</div>}</div>;})}</div><div className={styles.tableFooter}><span>{filtered.length} dossier(s) affiché(s)</span><span>Triés par score validé</span></div></div>:<div className={styles.empty}><BriefcaseBusiness size={34}/><h2>Aucun dossier trouvé</h2><p>Créez un nouveau dossier ou modifiez vos filtres.</p></div>}
    {editing&&<div className={styles.modalBackdrop} onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setEditing(null);}}><form className={styles.modal} onSubmit={saveDossier}><div className={styles.modalHead}><div><small>Modifier le dossier</small><h2>{editing.title}</h2></div><button type="button" onClick={()=>setEditing(null)}>×</button></div>{editMessage&&<div className={styles.message}>{editMessage}</div>}<label>Client<input required value={draft.client} onChange={e=>setDraft({...draft,client:e.target.value})}/></label><label>Intitulé du dossier<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Objectif du client<textarea required value={draft.objective} onChange={e=>setDraft({...draft,objective:e.target.value})}/></label><label>Contexte<textarea value={draft.context} onChange={e=>setDraft({...draft,context:e.target.value})}/></label><label>Statut<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}><option>Actif</option><option>En pause</option><option>Terminé</option><option>Archivé</option></select></label><div className={styles.modalActions}><button type="button" onClick={()=>setEditing(null)} disabled={saving}>Annuler</button><button className={styles.save} disabled={saving}>{saving?"Enregistrement…":"Enregistrer"}</button></div></form></div>}
  </div>;
}
