"use client";
import {useState} from "react";
import {Download,Link2,ShieldCheck} from "lucide-react";
import type {Production} from "@/lib/productions";
import {updateProductionContent} from "@/lib/productions";
import {downloadImpactPdf} from "@/lib/impactPdf";
import {qualityLabel,requireAccessToken,type ScoreKey} from "@/lib/impactAudit";
import {supabase} from "@/lib/supabase";
import type {ImpactEvidence,ImpactNote,ImpactProductionContent} from "@/lib/impactTypes";
const scoreLabels:{key:ScoreKey;label:string;max:number}[]=[{key:"juridique",label:"Juridique et réglementaire",max:20},{key:"economique_operationnel",label:"Économique et opérationnel",max:20},{key:"urgence",label:"Urgence institutionnelle",max:15},{key:"probabilite",label:"Probabilité d’évolution ou d’adoption",max:15},{key:"politique_reputation",label:"Politique et réputation",max:15},{key:"capacite_action",label:"Capacité d’action du client",max:15}];
const box={border:"1px solid #e1e8f2",borderRadius:12,padding:14,background:"white"} as const,heading={margin:"0 0 9px",fontSize:13,color:"#17365f"} as const,button={border:"1px solid #cfdbea",background:"white",borderRadius:10,padding:"9px 11px",display:"inline-flex",alignItems:"center",gap:6,fontWeight:800,color:"#17365f"} as const;
function location(evidence?:ImpactEvidence|null){if(!evidence)return"";return[evidence.source_index?`Source ${evidence.source_index}`:"",evidence.page?`page ${evidence.page}`:"",evidence.article?`article ${evidence.article}`:"",evidence.section||""].filter(Boolean).join(" · ");}
function scoreIsAvailable(note?:ImpactNote|null){return !!note&&note.score_available!==false&&!note.continuity_mode&&Number.isFinite(Number(note.score));}
function ListSection({title,items}:{title:string;items?:string[]}){if(!items?.length)return null;return<section style={box}><h4 style={heading}>{title}</h4><ul style={{margin:0,paddingLeft:18,lineHeight:1.6}}>{items.map((item,index)=><li key={index}>{item}</li>)}</ul></section>}
export default function ImpactProductionDetail({production,previous,onUpdated}:{production:Production;previous?:Production|null;onUpdated?:(production:Production)=>void}){
  const[current,setCurrent]=useState(production),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const content=(current.content||{}) as unknown as ImpactProductionContent,note=content.note||{},audit=content.audit,previousNote=((previous?.content||{}) as unknown as ImpactProductionContent)?.note,dossier=(audit?.dossier_snapshot||{}) as any;
  async function validate(){if(!note.quality?.can_validate||!supabase)return;setBusy(true);setMessage("");try{const{data}=await supabase.auth.getSession();requireAccessToken(data.session);const validatedAt=new Date().toISOString();const nextNote:ImpactNote={...note,quality:{...note.quality,status:"validated",label:qualityLabel("validated"),validated_at:validatedAt,validated_by:data.session?.user?.id||"user"}};const nextContent:ImpactProductionContent={...content,note:nextNote,audit:{...(audit||{} as any),validated_at:validatedAt,validated_by:data.session?.user?.id||"user"} as any};const result=await updateProductionContent(current.id,nextContent as unknown as Record<string,unknown>);if(result.error)throw result.error;const updated=result.data||{...current,content:nextContent as unknown as Record<string,unknown>};setCurrent(updated);onUpdated?.(updated);setMessage("Note validée et version d’historique mise à jour.");}catch(error:any){setMessage(error?.message||"Validation impossible.");}finally{setBusy(false);}}
  function exportPdf(){downloadImpactPdf(note as any,{client:dossier.client||"Client",title:dossier.title||current.title},String(content.depth||note.depth||"Standard"));}
  const hasScore=scoreIsAvailable(note),previousHasScore=scoreIsAvailable(previousNote),delta=hasScore&&previousHasScore?Number(note.score)-Number(previousNote?.score):null,status=note.quality?.status||"draft";
  return <div style={{marginTop:16,padding:18,border:"1px solid #d9e4f1",borderRadius:16,background:"#f8fbff",display:"grid",gap:14}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",flexWrap:"wrap"}}><div><small style={{fontWeight:850,color:"#0b57d0",textTransform:"uppercase",letterSpacing:".08em"}}>Version {audit?.analysis_id?.slice(0,8)||current.id.slice(0,8)}</small><h3 style={{margin:"5px 0"}}>{note.title||current.title}</h3><div style={{fontSize:12,color:"#68758a"}}>{audit?.generated_at?new Date(audit.generated_at).toLocaleString("fr-FR"):new Date(current.created_at).toLocaleString("fr-FR")}</div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{note.quality?.can_validate&&status!=="validated"&&<button onClick={validate} disabled={busy} style={button}><ShieldCheck size={15}/>{busy?"Validation…":"Valider"}</button>}<button onClick={exportPdf} disabled={status==="insufficient_sources"} style={button}><Download size={15}/>PDF</button></div></div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:8}}><div style={box}><small>Score d’impact</small><strong style={{display:"block",fontSize:25,color:"#0b244a"}}>{hasScore?`${Math.round(Number(note.score))}/100`:"—"}</strong>{!hasScore&&<small style={{display:"block",marginTop:4,color:"#a52436",fontWeight:800}}>Score non calculé</small>}</div><div style={box}><small>Niveau d’impact</small><strong style={{display:"block",marginTop:5}}>{note.impact_level||note.level||"—"}</strong></div><div style={box}><small>Urgence</small><strong style={{display:"block",marginTop:5}}>{String(note.urgency_level||"—").replaceAll("_"," ")}</strong></div><div style={box}><small>Couverture</small><strong style={{display:"block",marginTop:5}}>{Math.round((note.quality?.overall_coverage||0)*100)} %</strong></div></div>
    <div style={{padding:"10px 12px",borderRadius:10,background:status==="validated"?"#eaf8f1":"#fff8e5",color:status==="validated"?"#126845":"#865d00",fontWeight:800,fontSize:12}}>{note.quality?.label||qualityLabel(status as any)}</div>{message&&<div style={{fontSize:12,color:"#34506f"}}>{message}</div>}
    {delta!==null&&<section style={box}><h4 style={heading}>Évolution depuis la note précédente</h4><p style={{margin:0}}>Score : <b>{delta>0?`+${delta}`:delta}</b> point(s) · impact {previousNote?.impact_level||previousNote?.level||"—"} → {note.impact_level||note.level||"—"} · urgence {String(previousNote?.urgency_level||"—").replaceAll("_"," ")} → {String(note.urgency_level||"—").replaceAll("_"," ")}</p></section>}
    <section style={box}><h4 style={heading}>Synthèse exécutive</h4><p style={{margin:0,lineHeight:1.65}}>{note.executive_summary||"Synthèse indisponible."}</p></section>
    {!!note.score_detail&&<section style={box}><h4 style={heading}>Grille de score et preuves</h4><div style={{display:"grid",gap:9}}>{scoreLabels.map(metric=>{const evidence=note.score_evidence?.[metric.key];return<div key={metric.key} style={{borderTop:"1px solid #edf1f6",paddingTop:9}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><b>{metric.label}</b><strong>{Math.round(Number(note.score_detail?.[metric.key])||0)}/{metric.max}</strong></div><p style={{margin:"5px 0",color:"#526278"}}>{note.score_justifications?.[metric.key]}</p>{evidence?<div style={{borderLeft:"3px solid #16714e",paddingLeft:9,fontSize:12}}><b><Link2 size={12} style={{verticalAlign:"middle"}}/> {evidence.source_title}</b>{location(evidence)&&<div style={{color:"#16714e",fontWeight:800}}>{location(evidence)}</div>}<div style={{marginTop:4}}>« {evidence.excerpt} »</div></div>:<div style={{fontSize:12,color:"#9a6500"}}>Preuve précise non retrouvée.</div>}</div>})}</div></section>}
    {!!note.dispositions_concernees?.length&&<section style={box}><h4 style={heading}>Dispositions concernées</h4>{note.dispositions_concernees.map((item,index)=><div key={index} style={{borderTop:index?"1px solid #edf1f6":"none",padding:"9px 0"}}><b>{item.disposition}</b><p style={{margin:"4px 0"}}>{item.impact_client}</p>{item.evidence&&<small style={{color:"#16714e",fontWeight:800}}>{location(item.evidence)} · {item.evidence.source_title}</small>}</div>)}</section>}
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:10}}><ListSection title="Risques — inférences Myvor" items={note.risks}/><ListSection title="Opportunités — inférences Myvor" items={note.opportunities}/><ListSection title="Échéances" items={note.deadlines}/><ListSection title="Recommandations" items={note.recommendations}/></div>
    {!!note.sources_used?.length&&<section style={box}><h4 style={heading}>Sources et empreintes</h4>{note.sources_used.map((source,index)=><div key={index} style={{padding:"7px 0",borderTop:index?"1px solid #edf1f6":"none"}}><b>Source {index+1} · {source.title}</b><div style={{fontSize:12,color:"#526278"}}>{source.status} · {source.read_chars||0} caractères · {source.format||"format inconnu"}</div>{source.content_hash&&<code style={{fontSize:10}}>{source.content_hash}</code>}</div>)}</section>}
    <section style={box}><h4 style={heading}>Version du moteur</h4><div style={{fontSize:12,lineHeight:1.7,color:"#526278"}}>Modèle : {audit?.model||"inconnu"}<br/>Moteur : {audit?.engine_version||"inconnu"}<br/>Prompt : {audit?.prompt_version||"inconnu"}<br/>Scoring : {audit?.scoring_version||"inconnu"}<br/>Preuves : {audit?.evidence_version||"inconnu"}<br/>Hash du corpus : <code>{audit?.corpus_hash||"indisponible"}</code></div></section>
  </div>;
}
