"use client";

import { useEffect,useRef,useState } from "react";
import { AlertTriangle,BarChart3,BriefcaseBusiness,LogOut,Radar,Search,Sparkles,X } from "lucide-react";
import { isSupabaseConfigured,supabase } from "@/lib/supabase";
import DashboardCorporate,{type Action} from "./DashboardCorporate";
import DossiersCorporate from "./DossiersCorporate";
import VeilleCorporate from "./VeilleCorporate";
import ImpactModule from "./ImpactModule";
import RadarModule from "./RadarModule";
import BuilderModule from "./BuilderModule";
import DossierDetail from "./DossierDetail";

type Tab="dashboard"|"dossiers"|"veille"|"impact"|"radar"|"builder";
type Dossier={id:string;client:string;title:string;objective:string;context:string;status:string;created_at:string;watch_keywords?:string[];watch_priority_phrases?:string[];watch_excluded_keywords?:string[]};
type Watch={id:string;title:string;nature:string;source_url:string;dossier_id:string|null;urgency:string;created_at:string};
type SourceItem={title:string;nature:string;source_url:string;source_name:string;published_at?:string};
type ActionDraft={dossier_id:string;type:string;title:string;description?:string;actor_name?:string;priority:string;due_date?:string|null};
const nav=[["dashboard","Tableau de bord",BarChart3],["dossiers","Dossiers clients",BriefcaseBusiness],["veille","Veille",Search],["impact","Note d’impact",AlertTriangle],["radar","Radar d’influence",Radar],["builder","Note Builder",Sparkles]] as const;
const AUTO_LINK_THRESHOLD=0.75;

function parseWatchList(value:string){return [...new Set(value.split(/[\n,;]+/).map(item=>item.trim()).filter(Boolean))].slice(0,60);}

export default function Home(){
  const [session,setSession]=useState<any>(null);const [loading,setLoading]=useState(true);const [tab,setTab]=useState<Tab>("dashboard");const [dossiers,setDossiers]=useState<Dossier[]>([]);const [watch,setWatch]=useState<Watch[]>([]);const [actions,setActions]=useState<Action[]>([]);const [actionsLoading,setActionsLoading]=useState(false);const [actionsError,setActionsError]=useState("");const [selectedDossier,setSelectedDossier]=useState<Dossier|null>(null);const [modal,setModal]=useState<"dossier"|"watch"|null>(null);const [authMode,setAuthMode]=useState<"login"|"signup">("login");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [syncing,setSyncing]=useState(false);const [syncMessage,setSyncMessage]=useState("");const [searchingDossier,setSearchingDossier]=useState<string|null>(null);const [dossierMessages,setDossierMessages]=useState<Record<string,string>>({});const [mobileMenuOpen,setMobileMenuOpen]=useState(false);const lastResumeRefreshAt=useRef(0);

  useEffect(()=>{if(!supabase){setLoading(false);return;}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false);});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe();},[]);
  useEffect(()=>{if(session)loadData();else{setDossiers([]);setWatch([]);setActions([]);}},[session]);
  useEffect(()=>{
    if(!session||!supabase)return;
    let cancelled=false;
    const refreshOnResume=async()=>{
      const now=Date.now();
      if(now-lastResumeRefreshAt.current<1500)return;
      lastResumeRefreshAt.current=now;
      const [dRes,wRes,aRes]=await Promise.all([
        supabase.from("dossiers").select("*").order("created_at",{ascending:false}),
        supabase.from("watch_items").select("*").order("created_at",{ascending:false}),
        supabase.from("actions").select("id,dossier_id,type,title,description,actor_name,priority,status,due_date,created_at,updated_at").order("created_at",{ascending:false}),
      ]);
      if(cancelled)return;
      const nextDossiers=(dRes.data||[]) as Dossier[];
      setDossiers(nextDossiers);
      setWatch((wRes.data||[]) as Watch[]);
      setActions((aRes.data||[]) as Action[]);
      setActionsError(aRes.error?aRes.error.message:"");
      setSelectedDossier(current=>current?(nextDossiers.find(dossier=>dossier.id===current.id)||null):null);
    };
    const requestRefresh=()=>{void refreshOnResume();};
    const onVisibility=()=>{if(document.visibilityState==="visible")requestRefresh();};
    window.addEventListener("focus",requestRefresh);
    window.addEventListener("pageshow",requestRefresh);
    window.addEventListener("online",requestRefresh);
    document.addEventListener("visibilitychange",onVisibility);
    return()=>{
      cancelled=true;
      window.removeEventListener("focus",requestRefresh);
      window.removeEventListener("pageshow",requestRefresh);
      window.removeEventListener("online",requestRefresh);
      document.removeEventListener("visibilitychange",onVisibility);
    };
  },[session]);

  async function loadData(){
    if(!supabase)return;setActionsLoading(true);
    const [dRes,wRes,aRes]=await Promise.all([supabase.from("dossiers").select("*").order("created_at",{ascending:false}),supabase.from("watch_items").select("*").order("created_at",{ascending:false}),supabase.from("actions").select("id,dossier_id,type,title,description,actor_name,priority,status,due_date,created_at,updated_at").order("created_at",{ascending:false})]);
    setDossiers((dRes.data||[]) as Dossier[]);setWatch((wRes.data||[]) as Watch[]);setActions((aRes.data||[]) as Action[]);setActionsError(aRes.error?aRes.error.message:"");setActionsLoading(false);
    if(!aRes.error)await deriveActionsFromWatch((wRes.data||[]) as Watch[],(aRes.data||[]) as Action[]);
  }

  async function deriveActionsFromWatch(items:Watch[],existing:Action[]){
    if(!supabase)return;const drafts:ActionDraft[]=[];for(const item of items){if(!item.dossier_id||!["fort","absolument urgent"].includes(item.urgency))continue;const isAmendement=item.nature.toLowerCase().includes("amendement");drafts.push({dossier_id:item.dossier_id,type:isAmendement?"amendement":"analyse",title:isAmendement?`Préparer l’amendement — ${item.title}`:`Analyser l’impact — ${item.title}`,description:`Action générée automatiquement depuis la veille (${item.nature}).`,priority:item.urgency});}await persistActions(drafts,existing,false);
  }

  async function persistActions(drafts:ActionDraft[],existing=actions,reload=true){
    if(!supabase||!drafts.length)return;const keys=new Set(existing.filter(a=>a.status!=="termine").map(a=>`${a.dossier_id}|${a.type}|${a.title}`));const rows=drafts.filter(d=>{const key=`${d.dossier_id}|${d.type}|${d.title}`;if(keys.has(key))return false;keys.add(key);return true;}).map(d=>({...d,status:"a_faire",due_date:d.due_date||null,actor_name:d.actor_name||null,description:d.description||null}));if(!rows.length)return;const {error}=await supabase.from("actions").insert(rows);if(error){setActionsError(error.message);return;}if(reload){const {data,error:readError}=await supabase.from("actions").select("id,dossier_id,type,title,description,actor_name,priority,status,due_date,created_at,updated_at").order("created_at",{ascending:false});if(!readError)setActions((data||[]) as Action[]);}}

  async function linkWatchToDossier(watchId:string,dossierId:string|null){if(!supabase)return;const previous=watch;setWatch(items=>items.map(item=>item.id===watchId?{...item,dossier_id:dossierId}:item));const {error}=await supabase.from("watch_items").update({dossier_id:dossierId}).eq("id",watchId);if(error){setWatch(previous);setSyncMessage(`Impossible de rattacher le texte : ${error.message}`);}else await loadData();}
  async function findRelevantForDossier(dossier:Dossier){if(!supabase||searchingDossier)return;setSearchingDossier(dossier.id);setDossierMessages(m=>({...m,[dossier.id]:"Analyse de la veille en cours…"}));try{const candidates=watch.filter(w=>!w.dossier_id||w.dossier_id===dossier.id).slice(0,40);if(!candidates.length){setDossierMessages(m=>({...m,[dossier.id]:"Aucune évolution à analyser pour le moment."}));return;}const endpoint=new URL("/api/veille/assign",window.location.origin).toString();const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:candidates.map(w=>({id:w.id,title:w.title,nature:w.nature,source_url:w.source_url})),dossiers:[{id:dossier.id,title:dossier.title,objective:dossier.objective,context:dossier.context,watch_keywords:dossier.watch_keywords||[],watch_priority_phrases:dossier.watch_priority_phrases||[],watch_excluded_keywords:dossier.watch_excluded_keywords||[]}]})});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||"Analyse impossible");const relevant=(payload.assignments||[]).filter((a:any)=>a.dossier_id===dossier.id&&Number(a.confidence)>=AUTO_LINK_THRESHOLD);let linked=0;for(const a of relevant){const {error}=await supabase.from("watch_items").update({dossier_id:dossier.id}).eq("id",a.watch_id);if(error)throw error;linked++;}await loadData();setDossierMessages(m=>({...m,[dossier.id]:linked?`${linked} évolution(s) à 75 % ou plus trouvée(s) et rattachée(s).`:"Aucune évolution n’atteint le seuil automatique de 75 %."}));}catch(error:any){setDossierMessages(m=>({...m,[dossier.id]:error?.message||"Analyse impossible"}));}finally{setSearchingDossier(null);}}
  async function syncSources(){if(!supabase||syncing)return;setSyncing(true);setSyncMessage("");try{const endpoint=new URL("/api/veille/sources",window.location.origin).toString();const response=await fetch(endpoint,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload?.error||"Synchronisation impossible");const incoming:SourceItem[]=payload.items||[];const byUrl=new Map(watch.map(item=>[item.source_url,item]));const fresh=incoming.filter(item=>!byUrl.has(item.source_url));const existing=incoming.filter(item=>byUrl.has(item.source_url));if(fresh.length){const rows=fresh.map(item=>({title:item.title,nature:item.nature,source_url:item.source_url,dossier_id:null,urgency:"moyen"}));const {error}=await supabase.from("watch_items").insert(rows);if(error)throw error;}let repaired=0;for(const item of existing){const current=byUrl.get(item.source_url);if(current&&(current.title!==item.title||current.nature!==item.nature)){const {error}=await supabase.from("watch_items").update({title:item.title,nature:item.nature}).eq("id",current.id);if(error)throw error;repaired++;}}await loadData();setSyncMessage(`${fresh.length} nouveau(x) élément(s), ${repaired} corrigé(s). Sources actives : ${(payload.active_sources||[]).join(", ")||"aucune"}.`);}catch(error:any){setSyncMessage(`Erreur de synchronisation : ${error?.message||"inconnue"}`);}finally{setSyncing(false);}}
  async function auth(e:React.FormEvent){e.preventDefault();setMessage("");if(!supabase)return;const result=authMode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error)setMessage(result.error.message);else if(authMode==="signup")setMessage("Compte créé. Vérifie ton e-mail si la confirmation est activée.");}

  function updateDossier(updated:Dossier){setSelectedDossier(updated);setDossiers(current=>current.map(dossier=>dossier.id===updated.id?updated:dossier));}

  if(loading)return <div className="auth"><div style={{color:"white"}}>Chargement de Myvor…</div></div>;if(!isSupabaseConfigured)return <SetupScreen/>;if(!session)return <div className="auth"><form className="authbox" onSubmit={auth}><div className="brand" style={{color:"var(--navy)"}}><div className="logo">M</div>Myvor</div><h1>Anticipez l’impact.</h1><p className="muted">Votre cockpit opérationnel d’affaires publiques.</p><div className="tabs"><button type="button" className={authMode==="login"?"active":""} onClick={()=>setAuthMode("login")}>Connexion</button><button type="button" className={authMode==="signup"?"active":""} onClick={()=>setAuthMode("signup")}>Créer un compte</button></div><div className="form"><div className="field"><label>E-mail</label><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label>Mot de passe</label><input type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)}/></div>{message&&<div className="notice">{message}</div>}<button className="btn primary">{authMode==="login"?"Se connecter":"Créer mon espace"}</button></div></form></div>;

  const content=selectedDossier?<DossierDetail dossier={selectedDossier} watch={watch} actions={actions} onUpdate={updateDossier} back={()=>setSelectedDossier(null)} go={t=>{setSelectedDossier(null);setTab(t);}}/>:tab==="dashboard"?<DashboardCorporate dossiers={dossiers} watch={watch} actions={actions} actionsLoading={actionsLoading} actionsError={actionsError} go={setTab}/>:tab==="dossiers"?<DossiersCorporate items={dossiers} watch={watch} add={()=>setModal("dossier")} search={findRelevantForDossier} searching={searchingDossier} messages={dossierMessages} open={setSelectedDossier}/>:tab==="veille"?<VeilleCorporate items={watch} dossiers={dossiers} add={()=>setModal("watch")} sync={syncSources} syncing={syncing} syncMessage={syncMessage} link={linkWatchToDossier}/>:tab==="impact"?<ImpactModule dossiers={dossiers} watch={watch} onActions={drafts=>persistActions(drafts)}/>:tab==="radar"?<RadarModule dossiers={dossiers} watch={watch} onActions={drafts=>persistActions(drafts)}/>:<BuilderModule dossiers={dossiers} watch={watch}/>;
  return <div className="app"><style jsx global>{`
    .brand-menu-trigger{border:0;background:transparent;color:inherit;padding:0;text-align:left}
    .mobile-menu-backdrop{display:none}
    @media(max-width:850px){
      .brand-menu-trigger{cursor:pointer;touch-action:manipulation;-webkit-tap-highlight-color:transparent}
      .brand-menu-trigger:focus-visible{outline:2px solid var(--gold);outline-offset:5px;border-radius:12px}
      .mobile-menu-backdrop{display:block;position:fixed;inset:0;z-index:80;background:rgba(3,11,24,.62);backdrop-filter:blur(3px)}
      .mobile-menu-sheet{position:absolute;top:0;left:0;width:min(86vw,340px);height:100%;background:linear-gradient(180deg,#07162c 0%,#0b2448 100%);color:white;padding:calc(18px + env(safe-area-inset-top)) 14px calc(18px + env(safe-area-inset-bottom));box-shadow:18px 0 50px rgba(1,10,24,.28);display:flex;flex-direction:column;gap:18px;overflow:auto}
      .mobile-menu-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:0 4px 10px;border-bottom:1px solid rgba(255,255,255,.12)}
      .mobile-menu-brand{display:flex;align-items:center;gap:10px;font-weight:850;font-size:20px}.mobile-menu-brand small{display:block;color:#93a8c4;font-size:10px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;margin-top:2px}
      .mobile-menu-close{width:40px;height:40px;border:1px solid rgba(255,255,255,.16);border-radius:11px;background:rgba(255,255,255,.06);color:white;display:grid;place-items:center}
      .mobile-menu-nav{display:grid;gap:7px}.mobile-menu-nav button{width:100%;border:1px solid transparent;background:transparent;color:#c8d3e3;text-align:left;border-radius:13px;padding:13px 14px;display:flex;align-items:center;gap:11px;font-weight:760}.mobile-menu-nav button.active{background:#143761;border-color:#214a7a;color:white}.mobile-menu-nav button:active{transform:scale(.985)}
      .mobile-menu-foot{margin-top:auto;color:#8fa4c2;font-size:11px;padding:0 6px}
    }
  `}</style><header className="topbar"><button type="button" className="brand brand-menu-trigger" aria-label="Ouvrir le menu Myvor" aria-expanded={mobileMenuOpen} onClick={()=>{if(window.matchMedia("(max-width:850px)").matches)setMobileMenuOpen(true);}}><div className="logo">M</div>Myvor</button><button className="logout" onClick={()=>supabase?.auth.signOut()}><LogOut size={16}/></button></header>{mobileMenuOpen&&<div className="mobile-menu-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setMobileMenuOpen(false);}}><aside className="mobile-menu-sheet" role="dialog" aria-modal="true" aria-label="Menu Myvor" onMouseDown={event=>event.stopPropagation()}><div className="mobile-menu-head"><div className="mobile-menu-brand"><div className="logo">M</div><div>Myvor<small>Navigation</small></div></div><button type="button" className="mobile-menu-close" onClick={()=>setMobileMenuOpen(false)} aria-label="Fermer le menu"><X size={20}/></button></div><nav className="mobile-menu-nav">{nav.map(([id,label,Icon])=><button type="button" key={id} className={tab===id&&!selectedDossier?"active":""} onClick={()=>{setSelectedDossier(null);setTab(id);setMobileMenuOpen(false);}}><Icon size={19}/>{label}</button>)}</nav><div className="mobile-menu-foot">Anticipez l’impact.</div></aside></div>}<div className="shell"><aside className="sidebar">{nav.map(([id,label,Icon])=><button key={id} className={`navbtn ${tab===id&&!selectedDossier?"active":""}`} onClick={()=>{setSelectedDossier(null);setTab(id);}}><Icon size={18}/>{label}</button>)}</aside><main className="main">{content}</main></div><nav className="mobile-nav">{nav.slice(0,5).map(([id,label,Icon])=><button key={id} className={tab===id&&!selectedDossier?"active":""} onClick={()=>{setSelectedDossier(null);setTab(id);setMobileMenuOpen(false);}}><Icon size={19}/>{label.split(" ")[0]}</button>)}</nav>{modal==="dossier"&&<DossierModal close={()=>setModal(null)} done={()=>{setModal(null);loadData();}}/>}{modal==="watch"&&<WatchModal dossiers={dossiers} close={()=>setModal(null)} done={()=>{setModal(null);loadData();}}/>}</div>;
}
function SetupScreen(){return <div className="auth"><div className="authbox"><div className="brand" style={{color:"var(--navy)"}}><div className="logo">M</div>Myvor</div><h1>Configuration requise</h1><p className="muted">Ajoute les variables Supabase dans Netlify.</p></div></div>;}
function DossierModal({close,done}:{close:()=>void;done:()=>void}){const [f,setF]=useState({client:"",title:"",objective:"",context:"",watch_keywords:"",watch_priority_phrases:"",watch_excluded_keywords:""});const [err,setErr]=useState("");async function save(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from("dossiers").insert({client:f.client,title:f.title,objective:f.objective,context:f.context,watch_keywords:parseWatchList(f.watch_keywords),watch_priority_phrases:parseWatchList(f.watch_priority_phrases),watch_excluded_keywords:parseWatchList(f.watch_excluded_keywords),status:"Actif"});if(error)setErr(error.message);else done();}return <Modal title="Nouveau dossier" close={close}><form className="form" onSubmit={save}>{[["client","Client"],["title","Intitulé du dossier"],["objective","Objectif du client"]].map(([k,l])=><div className="field" key={k}><label>{l}</label><input required value={(f as any)[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></div>)}<div className="field"><label>Contexte</label><textarea value={f.context} onChange={e=>setF({...f,context:e.target.value})}/></div><div className="field"><label>Mots-clés de veille</label><textarea placeholder={"mobilité\ntransport\nVTC"} value={f.watch_keywords} onChange={e=>setF({...f,watch_keywords:e.target.value})}/></div><div className="field"><label>Expressions prioritaires</label><textarea placeholder={"plateformes de mobilité"} value={f.watch_priority_phrases} onChange={e=>setF({...f,watch_priority_phrases:e.target.value})}/></div><div className="field"><label>Mots ou expressions à exclure</label><textarea placeholder={"sport automobile"} value={f.watch_excluded_keywords} onChange={e=>setF({...f,watch_excluded_keywords:e.target.value})}/></div>{err&&<div className="notice">{err}</div>}<div className="actions"><button type="button" className="btn ghost" onClick={close}>Annuler</button><button className="btn primary">Créer le dossier</button></div></form></Modal>;}
function WatchModal({dossiers,close,done}:{dossiers:Dossier[];close:()=>void;done:()=>void}){const [f,setF]=useState({title:"",nature:"Projet de loi",source_url:"",dossier_id:"",urgency:"moyen"});const [err,setErr]=useState("");async function save(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.from("watch_items").insert({...f,dossier_id:f.dossier_id||null});if(error)setErr(error.message);else done();}return <Modal title="Ajouter un texte" close={close}><form className="form" onSubmit={save}><div className="field"><label>Titre</label><input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></div><div className="field"><label>Nature juridique</label><select value={f.nature} onChange={e=>setF({...f,nature:e.target.value})}>{["Projet de loi","Proposition de loi","Amendement","Décret","Arrêté","Ordonnance","Résolution","Rapport","Question parlementaire","Audition","Communiqué institutionnel","Décision / jurisprudence"].map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label>Lien officiel</label><input type="url" required value={f.source_url} onChange={e=>setF({...f,source_url:e.target.value})}/></div><div className="field"><label>Dossier lié</label><select value={f.dossier_id} onChange={e=>setF({...f,dossier_id:e.target.value})}><option value="">Non rattaché</option>{dossiers.map(d=><option value={d.id} key={d.id}>{d.title}</option>)}</select></div><div className="field"><label>Niveau d’impact</label><select value={f.urgency} onChange={e=>setF({...f,urgency:e.target.value})}>{["faible","moyen","fort","absolument urgent"].map(x=><option key={x}>{x}</option>)}</select></div>{err&&<div className="notice">{err}</div>}<div className="actions"><button type="button" className="btn ghost" onClick={close}>Annuler</button><button className="btn primary">Ajouter</button></div></form></Modal>;}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal"><div className="modalbox"><div className="toolbar" style={{marginTop:0}}><h2>{title}</h2><button className="btn ghost" onClick={close}><X size={18}/></button></div>{children}</div></div>;}
