"use client";

import { useMemo,useState } from "react";
import { ExternalLink,Orbit,Sparkles,X } from "lucide-react";
import styles from "./RadarCorporate.module.css";

type Dossier={id:string;client:string;title:string;objective:string;context:string;status:string;created_at:string};
type Watch={id:string;title:string;nature:string;source_url:string;dossier_id:string|null;urgency:string;created_at:string};
type Actor={id:string;name:string;role:string;orbit:1|2|3;position:"favorable"|"inconnue"|"reserve"|"opposition";influence:number;why:string;window:string;action:string};
type ActionDraft={dossier_id:string;type:string;title:string;description?:string;actor_name?:string;priority:string;due_date?:string|null};
const COLORS={favorable:"#2f8f5b",inconnue:"#d9a514",reserve:"#d97706",opposition:"#b42318"};const ORBIT_RADII={1:112,2:190,3:268};
function postJson<T>(url:string,body:unknown):Promise<T>{return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open("POST",url,true);xhr.setRequestHeader("Content-Type","application/json;charset=UTF-8");xhr.responseType="text";xhr.onload=()=>{let payload:any={};try{payload=xhr.responseText?JSON.parse(xhr.responseText):{};}catch{}if(xhr.status>=200&&xhr.status<300)resolve(payload as T);else reject(new Error(payload?.error||`Erreur réseau (${xhr.status})`));};xhr.onerror=()=>reject(new Error("Impossible de contacter le moteur Radar."));xhr.ontimeout=()=>reject(new Error("Le moteur Radar a mis trop de temps à répondre."));xhr.timeout=15000;xhr.send(JSON.stringify(body));});}

export default function RadarModule({dossiers,watch,onActions}:{dossiers:Dossier[];watch:Watch[];onActions?:(drafts:ActionDraft[])=>Promise<void>|void}){
  const [dossierId,setDossierId]=useState(dossiers[0]?.id||"");const [actors,setActors]=useState<Actor[]>([]);const [selected,setSelected]=useState<Actor|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const dossier=dossiers.find(d=>d.id===dossierId)||null;const related=useMemo(()=>watch.filter(w=>w.dossier_id===dossierId),[watch,dossierId]);const source=related[0]||null;
  async function generate(){if(!dossier){setError("Sélectionne un dossier client.");return;}if(!related.length){setError("Aucun texte n’est rattaché à ce dossier.");return;}setLoading(true);setError("");setActors([]);setSelected(null);try{const payload=await postJson<{actors?:Actor[]}>("/api/radar",{dossier,items:related});const nextActors=payload.actors||[];setActors(nextActors);if(onActions&&nextActors.length){const priority=(a:Actor)=>a.influence>=5||a.position==="opposition"?"fort":"moyen";const drafts=nextActors.filter(a=>a.influence>=4||a.orbit===1).sort((a,b)=>b.influence-a.influence).slice(0,4).map(a=>({dossier_id:dossier.id,type:"contact",title:`Contacter ${a.name}`,description:a.action||a.why,actor_name:a.name,priority:priority(a),due_date:null}));await onActions(drafts);}}catch(err:any){setError(err?.message||"Génération impossible");}finally{setLoading(false);}}
  return <div className={styles.page}><div className={styles.head}><div><div className={styles.kicker}>Cartographie stratégique</div><h1>Radar d’influence</h1><p>Visualisez les acteurs, leur proximité avec la décision, leur influence et leur position face à l’objectif client.</p></div></div>
    <div className={styles.setup}><section className={styles.panel}><h2>Dossier analysé</h2><div className={styles.field}><label>Dossier client</label><select value={dossierId} onChange={e=>{setDossierId(e.target.value);setActors([]);setSelected(null);setError("");}}><option value="">Sélectionner un dossier</option>{dossiers.map(d=><option key={d.id} value={d.id}>{d.client} — {d.title}</option>)}</select></div>{dossier&&<div className={styles.objective}><b>Objectif client :</b><br/>{dossier.objective}</div>}</section><section className={styles.panel}><h2>Lecture des orbites</h2><div className={styles.orbitList}><div className={styles.orbitRow}><b>1re orbite</b><span>Décision directe</span></div><div className={styles.orbitRow}><b>2e orbite</b><span>Influence forte</span></div><div className={styles.orbitRow}><b>3e orbite</b><span>Influence indirecte</span></div></div></section></div>
    <div className={styles.generate}><div><h3>Prêt à cartographier</h3><p>{related.length} texte(s) lié(s) au dossier sélectionné.</p></div><button onClick={generate} disabled={loading||!dossier||!related.length}><Sparkles size={17}/>{loading?"Cartographie en cours…":"Générer le radar d’influence"}</button></div>{error&&<div className={styles.error}>{error}</div>}
    <section className={styles.radarCard}><div className={styles.legend}><Legend color={COLORS.favorable} label="Favorable"/><Legend color={COLORS.inconnue} label="Neutre ou inconnue"/><Legend color={COLORS.reserve} label="Réserves"/><Legend color={COLORS.opposition} label="Opposition forte"/></div>{actors.length?<div className={styles.canvas}>{[3,2,1].map(orbit=><div key={orbit} className={styles.orbit} style={{width:ORBIT_RADII[orbit as 1|2|3]*2,height:ORBIT_RADII[orbit as 1|2|3]*2}}><span className={styles.orbitLabel}>Orbite {orbit}</span></div>)}<svg viewBox="0 0 720 720" style={{position:"absolute",inset:0,width:"100%",height:"100%",pointerEvents:"none"}}>{actors.map((actor,index)=>{const p=positionFor(actor,index,actors);return <line key={actor.id} x1="360" y1="360" x2={p.x} y2={p.y} stroke="#9fb2ca" strokeWidth="1.4" strokeDasharray={actor.orbit===3?"5 5":"0"}/>;})}</svg><button className={styles.center} onClick={()=>source?.source_url&&window.open(source.source_url,"_blank")} style={{cursor:source?.source_url?"pointer":"default"}}><span><Orbit size={24}/><b>{dossier?.title||"Dossier"}</b>{source?.source_url&&<small>Lire le texte original</small>}</span></button>{actors.map((actor,index)=>{const p=positionFor(actor,index,actors);const size=52+actor.influence*8;return <button key={actor.id} className={styles.actor} onClick={()=>setSelected(actor)} title={actor.name} style={{left:`${p.x/7.2}%`,top:`${p.y/7.2}%`,width:size,height:size,background:COLORS[actor.position]}}>{actor.name}</button>;})}</div>:<div className={styles.empty}><Orbit size={36}/><h3>Le radar est prêt</h3><p>Sélectionnez un dossier puis générez la cartographie des acteurs.</p></div>}</section>
    {selected&&<div className={styles.modal} onClick={()=>setSelected(null)}><div className={styles.modalBox} onClick={e=>e.stopPropagation()}><div className={styles.modalHead}><div><div className={styles.eyebrow}>Acteur — orbite {selected.orbit}</div><h2>{selected.name}</h2><p>{selected.role}</p></div><button className={styles.close} onClick={()=>setSelected(null)}><X size={18}/></button></div><div className={styles.infoGrid}><Info title="Pourquoi il compte" text={selected.why}/><Info title="Fenêtre d’action" text={selected.window}/><Info title="Action recommandée" text={selected.action}/><div className={styles.info}><h3>Lecture stratégique</h3><p><b>Influence :</b> {selected.influence}/5<br/><b>Proximité décisionnelle :</b> orbite {selected.orbit}<br/><b>Position :</b> {labelPosition(selected.position)}</p></div></div>{source?.source_url&&<a className={styles.source} href={source.source_url} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Lire le texte original</a>}</div></div>}
  </div>;
}
function positionFor(actor:Actor,index:number,actors:Actor[]){const same=actors.filter(a=>a.orbit===actor.orbit);const rank=same.findIndex(a=>a.id===actor.id);const angle=((Math.PI*2)/Math.max(1,same.length))*rank-(Math.PI/2)+(actor.orbit*0.22);const radius=ORBIT_RADII[actor.orbit];return{x:360+Math.cos(angle)*radius,y:360+Math.sin(angle)*radius};}function Legend({color,label}:{color:string;label:string}){return <span className={styles.legendItem}><i className={styles.legendDot} style={{background:color}}/>{label}</span>;}function Info({title,text}:{title:string;text:string}){return <div className={styles.info}><h3>{title}</h3><p>{text||"À préciser."}</p></div>;}function labelPosition(value:Actor["position"]){return value==="favorable"?"Favorable":value==="inconnue"?"Neutre ou inconnue":value==="reserve"?"Réserves ou opposition probable":"Opposition forte ou capacité de blocage";}
