"use client";

import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,ArrowRight,Building2,CheckCircle2,Eye,FileText,Radar,RefreshCw,Search,Sparkles,X} from "lucide-react";
import {supabase} from "@/lib/supabase";
import {belongsToDossier,primaryDossierId} from "@/lib/watchMembership";
import VeilleStatusMessage from "./VeilleStatusMessage";
import styles from "./VeilleCorporate.module.css";

type Dossier={id:string;client:string;title:string;objective:string;context:string;status:string;created_at:string};
type LinkJustification={summary?:string;objective_link?:string;evidence?:string[];consequence?:string;status?:string};
type Watch={id:string;title:string;nature:string;source_url:string;dossier_id:string|null;dossier_ids?:string[]|null;urgency:string;created_at:string;source_name?:string|null;published_at?:string|null;suggested_dossier_id?:string|null;qualification_confidence?:number|null;qualification_reason?:string|null;link_justification?:LinkJustification|null;link_justification_engine?:string|null;change_type?:string|null;change_summary?:string|null;change_baseline_ids?:string[]|null};
type View="todo"|"watch"|"all";
const REVIEW=.60,IGNORED="Ignoré manuellement",STORAGE="myvor:veille:selected-dossier";

function date(item:Watch){const d=new Date(item.published_at||item.created_at);return Number.isFinite(d.getTime())?d.toLocaleDateString("fr-FR"):"";}
function time(item:Watch){const d=Date.parse(item.published_at||item.created_at);return Number.isFinite(d)?d:0;}
function urgent(item:Watch){const u=(item.urgency||"").toLowerCase();return u==="fort"||u.includes("urgent")||!!(item.change_summary||item.change_type||(item.change_baseline_ids||[]).length);}
function source(item:Watch){try{return item.source_name||new URL(item.source_url).hostname.replace(/^www\./,"");}catch{return item.source_name||"Source officielle";}}

export default function VeilleCorporate({items,dossiers,add,refresh,refreshing,refreshMessage,link,onOpenDossier,onOpenImpact,onOpenRadar,onOpenBuilder}:{items:Watch[];dossiers:Dossier[];add:()=>void;refresh:()=>void;refreshing:boolean;refreshMessage:string;link:(watchId:string,dossierId:string|null)=>Promise<void>|void;onOpenDossier?:(dossierId:string)=>void;onOpenImpact?:(dossierId:string,watchIds:string[])=>void;onOpenRadar?:(dossierId:string,watchIds:string[])=>void;onOpenBuilder?:(dossierId:string,watchIds:string[])=>void}){
  const[view,setView]=useState<View>("todo"),[dossierId,setDossierId]=useState(""),[query,setQuery]=useState(""),[nature,setNature]=useState("all"),[urgency,setUrgency]=useState("all"),[dateRange,setDateRange]=useState("all"),[detail,setDetail]=useState<string|null>(null),[message,setMessage]=useState(""),[technical,setTechnical]=useState("");

  useEffect(()=>{try{const saved=sessionStorage.getItem(STORAGE)||"";if(dossiers.some(d=>d.id===saved))setDossierId(saved);}catch{}},[dossiers]);
  useEffect(()=>{try{dossierId?sessionStorage.setItem(STORAGE,dossierId):sessionStorage.removeItem(STORAGE);}catch{}},[dossierId]);
  useEffect(()=>{const target=sessionStorage.getItem("myvor:open-watch");if(!target)return;const item=items.find(i=>i.id===target);if(!item)return;sessionStorage.removeItem("myvor:open-watch");setDossierId(primaryDossierId(item)||item.suggested_dossier_id||"");setView("all");setQuery(item.title);},[items]);

  const dossier=useMemo(()=>dossiers.find(d=>d.id===dossierId)||null,[dossiers,dossierId]);
  const relevant=useMemo(()=>dossierId?items.filter(item=>!String(item.qualification_reason||"").startsWith(IGNORED)&&(belongsToDossier(item,dossierId)||(item.suggested_dossier_id===dossierId&&Number(item.qualification_confidence)>=REVIEW))).sort((a,b)=>time(b)-time(a)):[],[items,dossierId]);
  const pending=(item:Watch)=>item.suggested_dossier_id===dossierId&&!belongsToDossier(item,dossierId);
  const todo=useMemo(()=>relevant.filter(item=>pending(item)||urgent(item)),[relevant,dossierId]);
  const todoIds=useMemo(()=>new Set(todo.map(item=>item.id)),[todo]);
  const watching=useMemo(()=>relevant.filter(item=>!todoIds.has(item.id)),[relevant,todoIds]);
  const natures=useMemo(()=>Array.from(new Set(relevant.map(i=>i.nature).filter(Boolean))).sort(),[relevant]);
  const filtered=useMemo(()=>{const now=Date.now(),days=dateRange==="7d"?7:dateRange==="30d"?30:dateRange==="90d"?90:0,cutoff=dateRange==="today"?new Date(new Date().setHours(0,0,0,0)).getTime():days?now-days*86400000:0,q=query.trim().toLowerCase();return relevant.filter(item=>(!q||[item.title,item.nature,item.source_name||"",item.change_summary||"",item.qualification_reason||""].join(" ").toLowerCase().includes(q))&&(!cutoff||time(item)>=cutoff)&&(nature==="all"||item.nature===nature)&&(urgency==="all"||(item.urgency||"").toLowerCase()===urgency));},[relevant,query,nature,urgency,dateRange]);

  async function accept(item:Watch){if(!dossierId)return;setMessage("");setTechnical("");if(supabase){const existing=item.link_justification||null;const{error}=await supabase.from("watch_items").update({suggested_dossier_id:null,link_justification:existing?{...existing,status:"confirmed"}:{summary:"Rattachement confirmé.",objective_link:"Le texte est pertinent pour le dossier sélectionné.",consequence:"Le texte est intégré au suivi du dossier.",status:"confirmed"},link_justification_engine:item.link_justification_engine||"accepted-suggestion",link_justified_at:new Date().toISOString()}).eq("id",item.id);if(error){setMessage("Le rattachement n’a pas pu être enregistré.");setTechnical(error.message);return;}}await link(item.id,dossierId);}
  async function ignore(item:Watch){if(!supabase)return;const{error}=await supabase.from("watch_items").update({suggested_dossier_id:null,qualification_confidence:null,qualification_reason:`${IGNORED}.`,link_justification:null}).eq("id",item.id);if(error){setMessage("Le texte n’a pas pu être ignoré.");setTechnical(error.message);return;}await refresh();}
  function why(item:Watch){return item.link_justification?.summary||item.link_justification?.objective_link||item.qualification_reason||"Rattaché au périmètre du dossier sélectionné.";}
  function change(item:Watch){return item.change_summary||item.link_justification?.consequence||"Aucun changement consolidé à ce stade.";}
  function card(item:Watch){const isPending=pending(item),score=Number(item.qualification_confidence);return <article className={styles.card} key={item.id}><div className={styles.top}><span className={styles.nature}>{item.nature}</span><span className={`${styles.urgency} ${styles[(item.urgency||"").replaceAll(" ","-") as keyof typeof styles]||""}`}>{item.urgency}</span>{isPending&&Number.isFinite(score)&&<span className="vd-confidence">À valider · {Math.round(score*100)} %</span>}</div><h3 className={styles.title}>{item.title}</h3><div className="vd-meta">{source(item)} · {date(item)}</div><div className="vd-why"><b>Pourquoi ce texte ?</b><p>{why(item)}</p></div><div className="vd-change"><b>Ce qui change</b><p>{change(item)}</p></div><div className={styles.footer}><div className="vd-actions">{isPending&&<button className={styles.accept} onClick={()=>void accept(item)}><CheckCircle2 size={14}/>Rattacher</button>}{isPending&&<button className={styles.ignore} onClick={()=>void ignore(item)}>Ignorer</button>}{item.source_url&&<a className={styles.source} href={item.source_url} target="_blank" rel="noreferrer">Lire la source <ArrowRight size={13}/></a>}<button className="vd-link" onClick={()=>onOpenDossier?.(dossierId)}><Building2 size={13}/>Dossier</button><button className="vd-link" onClick={()=>onOpenImpact?.(dossierId,[item.id])}><AlertTriangle size={13}/>Urgence</button><button className="vd-link" onClick={()=>onOpenRadar?.(dossierId,[item.id])}><Radar size={13}/>Radar</button><button className="vd-link" onClick={()=>onOpenBuilder?.(dossierId,[item.id])}><Sparkles size={13}/>Note Builder</button><button className="vd-link" onClick={()=>setDetail(detail===item.id?null:item.id)}><Eye size={13}/>{detail===item.id?"Fermer":"Détails"}</button></div></div>{detail===item.id&&<div className="vd-detail"><div><b>{dossier?.client} — {dossier?.title}</b><button onClick={()=>setDetail(null)}><X size={14}/></button></div><p><strong>Rattachement.</strong> {why(item)}</p><p><strong>Évolution.</strong> {change(item)}</p><p><strong>Chaîne normative.</strong> {(item.change_baseline_ids||[]).length?`${item.change_baseline_ids?.length} texte(s) antérieur(s) relié(s).`:"Aucun antécédent consolidé."}</p></div>}</article>;}

  const tabs:[View,string,number][]=[["todo","À traiter",todo.length],["watch","À surveiller",watching.length],["all","Tous les éléments pertinents",relevant.length]];
  const shown=view==="todo"?todo:view==="watch"?watching:filtered;
  const refreshText=refreshMessage.startsWith("Impossible")?refreshMessage:refreshMessage?"Veille actualisée.":"";

  return <div className={styles.page}><style jsx global>{`.vd-selector{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;align-items:end;padding:15px;border:1px solid #21415f;border-radius:14px;background:#07192f}.vd-selector label{display:grid;gap:7px}.vd-selector label>span{font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.07em;color:#8fa4bb}.vd-selector select{min-height:44px;border:1px solid #365671;border-radius:10px;background:#06172b;color:#f5f8fc;padding:0 12px;font-weight:800}.vd-counts{display:flex;gap:7px;flex-wrap:wrap}.vd-counts span{border:1px solid #29445f;border-radius:999px;padding:7px 9px;color:#9eb0c4;font-size:9px}.vd-counts strong{color:#f3bd3e}.vd-tabs{display:flex;gap:22px;border-bottom:1px solid #173653;overflow:auto}.vd-tabs button{border:0;background:transparent;color:#8fa4bb;padding:5px 2px 12px;font-weight:850;white-space:nowrap}.vd-tabs button.active{color:#f3bd3e;border-bottom:2px solid #f3bd3e}.vd-tabs em{font-style:normal;margin-left:7px;font-size:9px;background:#0a213a;border:1px solid #173653;border-radius:999px;padding:2px 6px}.vd-view{display:grid;gap:11px}.vd-head{display:flex;justify-content:space-between;align-items:end}.vd-head h2{margin:0;color:#f7f9fc;font-size:17px}.vd-head p,.vd-meta{margin:4px 0 0;color:#91a5bc;font-size:10px}.vd-why,.vd-change{border:1px solid #183853;background:#071c33;border-radius:10px;padding:11px}.vd-why{border-left:3px solid #f3bd3e}.vd-why b,.vd-change b{color:#8196ac;font-size:9px;text-transform:uppercase}.vd-why p,.vd-change p{margin:5px 0 0;color:#c1cedb;font-size:11px;line-height:1.5}.vd-actions{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.vd-link{min-height:32px;border:1px solid #29445f;background:#081f38;color:#d7e5f2;border-radius:8px;padding:6px 8px;font-size:9px;font-weight:800;display:inline-flex;gap:5px;align-items:center}.vd-confidence{margin-left:auto;border:1px solid #725d16;background:#2c250d;color:#f3bd3e;border-radius:999px;padding:5px 8px;font-size:9px;font-weight:850}.vd-detail{border:1px solid #29445f;background:#06172b;border-radius:10px;padding:11px;color:#b6c5d4;font-size:10px}.vd-detail>div{display:flex;justify-content:space-between;color:#eef4fb}.vd-detail button{border:0;background:transparent;color:#c6d3e1}.vd-placeholder{border:1px dashed #29445f;border-radius:14px;padding:38px;text-align:center;color:#91a5bc}.vd-placeholder svg{color:#f3bd3e}.vd-placeholder h2{color:#f7f9fc}.vd-grid{display:grid;gap:10px}@media(max-width:850px){.vd-selector{grid-template-columns:1fr}.vd-head{align-items:start;flex-direction:column;gap:5px}}`}</style>
    <div className={styles.head}><div><div className={styles.kicker}>Veille opérationnelle</div><h1>Veille</h1><p>Sélectionnez un dossier : Myvor masque le flux global et n’affiche que les textes pertinents pour ce périmètre.</p></div><div className={styles.actions}><button className={styles.secondary} onClick={refresh} disabled={refreshing}><RefreshCw size={16}/>{refreshing?"Actualisation…":"Actualiser"}</button><button className={styles.primary} onClick={add}>+ Ajouter un texte</button></div></div>
    <section className="vd-selector"><label><span>Dossier analysé</span><select value={dossierId} onChange={e=>{setDossierId(e.target.value);setView("todo");setQuery("");setNature("all");setUrgency("all");setDateRange("all");}}><option value="">Sélectionner le dossier…</option>{dossiers.map(d=><option key={d.id} value={d.id}>{d.client} — {d.title}</option>)}</select></label>{dossier&&<div className="vd-counts"><span><strong>{todo.length}</strong> à traiter</span><span><strong>{watching.length}</strong> à surveiller</span><span><strong>{relevant.length}</strong> pertinents</span></div>}</section>
    {(message||refreshText)&&<VeilleStatusMessage summary={message||refreshText} technical={technical}/>} 
    {!dossier?<div className="vd-placeholder"><Building2 size={34}/><h2>Sélectionnez un dossier</h2><p>La veille globale reste masquée pour éviter d’afficher des centaines de textes sans contexte.</p></div>:<><div className="vd-tabs">{tabs.map(([id,label,count])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}<em>{count}</em></button>)}</div><section className="vd-view"><div className="vd-head"><div><h2>{view==="todo"?"À traiter":view==="watch"?"À surveiller":"Tous les éléments pertinents"}</h2><p>{view==="todo"?"Rattachements à valider et évolutions prioritaires.":view==="watch"?"Signaux pertinents sans action immédiate.":"Le corpus utile de ce dossier uniquement."}</p></div><span className={styles.count}>{shown.length} élément(s)</span></div>{view==="all"&&<div className={styles.toolbar}><label className={styles.search}><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher dans ce dossier…"/></label><select className={styles.select} value={nature} onChange={e=>setNature(e.target.value)}><option value="all">Toutes les natures</option>{natures.map(v=><option key={v} value={v}>{v}</option>)}</select><select className={styles.select} value={urgency} onChange={e=>setUrgency(e.target.value)}><option value="all">Tous les impacts</option>{["faible","moyen","fort","absolument urgent"].map(v=><option key={v} value={v}>{v}</option>)}</select><select className={styles.select} value={dateRange} onChange={e=>setDateRange(e.target.value)}><option value="all">Toutes les dates</option><option value="today">Aujourd’hui</option><option value="7d">7 derniers jours</option><option value="30d">30 derniers jours</option><option value="90d">90 derniers jours</option></select></div>}{shown.length?<div className="vd-grid">{shown.map(card)}</div>:<div className={styles.empty}><FileText size={34}/><h2>Aucun élément</h2><p>Rien ne correspond à cette vue pour le dossier sélectionné.</p></div>}</section></>}
  </div>;
}
