"use client";

import {useMemo,useState} from "react";
import {ArrowRight,CheckCircle2,CircleDot,FileSearch,Flag,Layers3,Plus,ShieldCheck,Sparkles,Target,Users} from "lucide-react";
import styles from "./WarZoneView.module.css";

export type WarZoneActor={id:string;name:string;role:string;institution?:string;orbit:1|2|3;position?:string;influence:number;influence_score?:number;why:string;window:string;action:string;certainty?:string};
export type WarZoneDossier={id:string;client:string;title:string;objective:string;context:string;key_deadlines?:string[]};
export type WarZoneWatch={id:string;title:string;nature:string;urgency:string;created_at:string;published_at?:string|null};
export type WarZoneActionDraft={dossier_id:string;type:string;title:string;description?:string;actor_name?:string;priority:string;due_date?:string|null};

type ScenarioId="institutionnel"|"coalition"|"contribution";
type Scenario={id:ScenarioId;name:string;tagline:string;impact:number;feasibility:number;speed:number;risk:number;summary:string;lever:string;whyNow:string;hypothesis:string;preconditions:string[];risks:string[];success:string[];evidence:string[]};
type PlanStep={id:string;order:number;title:string;actor?:WarZoneActor;purpose:string;deliverable:string;timing:string;priority:"high"|"medium"|"low";expected:string;dependency:string;success:string;evidence:string};
type Props={dossier:WarZoneDossier|null;actors:WarZoneActor[];watch:WarZoneWatch[];onOpenActor:(actor:WarZoneActor)=>void;onActions?:(drafts:WarZoneActionDraft[])=>Promise<void>|void};

function score(actor:WarZoneActor){const raw=Number(actor.influence_score);return Number.isFinite(raw)?Math.max(0,Math.min(100,Math.round(raw))):Math.max(20,Math.min(100,Math.round((actor.influence||1)*20)));}
function positionWeight(position?:string){if(position==="favorable")return 1;if(position==="reserve")return .35;if(position==="opposition")return -.7;return 0;}
function urgencyWeight(value?:string){const key=String(value||"").toLowerCase();if(key.includes("absolument"))return 4;if(key.includes("fort"))return 3;if(key.includes("moyen"))return 2;return 1;}
function strategicIndex(actors:WarZoneActor[],watch:WarZoneWatch[]){if(!actors.length)return 20;const actorBase=actors.reduce((sum,actor)=>sum+score(actor)*(1+positionWeight(actor.position)*.2),0)/actors.length;const urgency=watch.reduce((sum,item)=>sum+urgencyWeight(item.urgency),0);const evidence=Math.min(15,watch.length*1.2+urgency*.35);return Math.max(18,Math.min(90,Math.round(actorBase*.72+evidence)));}
function topActors(actors:WarZoneActor[]){return [...actors].sort((a,b)=>score(b)-score(a)).slice(0,4);}
function firstDeadline(dossier:WarZoneDossier|null){return dossier?.key_deadlines?.find(Boolean)||"la prochaine échéance du dossier";}
function clip(value:string,max=120){const clean=String(value||"").trim();return clean.length>max?`${clean.slice(0,max-1)}…`:clean;}
function actorLabel(actor?:WarZoneActor){return actor?`${actor.name}${actor.institution?` — ${actor.institution}`:""}`:"acteur institutionnel à confirmer";}
function positionLabel(value?:string){if(value==="favorable")return "favorable";if(value==="reserve")return "réservée";if(value==="opposition")return "en opposition";return "non documentée";}
function priorityWatch(watch:WarZoneWatch[]){return [...watch].sort((a,b)=>urgencyWeight(b.urgency)-urgencyWeight(a.urgency)||new Date(b.published_at||b.created_at||0).getTime()-new Date(a.published_at||a.created_at||0).getTime()).slice(0,4);}
function watchLabel(item?:WarZoneWatch){return item?`${item.nature} — ${clip(item.title,86)}`:"source de veille à consolider";}
function dominantNature(watch:WarZoneWatch[]){const counts=new Map<string,number>();watch.forEach(item=>counts.set(item.nature,(counts.get(item.nature)||0)+1));return [...counts.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]||"évolution institutionnelle";}

function buildScenarios(index:number,dossier:WarZoneDossier,actors:WarZoneActor[],watch:WarZoneWatch[]):Scenario[]{
  const targets=topActors(actors),first=targets[0],second=targets[1],deadline=firstDeadline(dossier),evidence=priorityWatch(watch),nature=dominantNature(watch),objective=clip(dossier.objective||dossier.title,150),context=clip(dossier.context||dossier.title,150);
  const institutionalFit=Math.min(95,index+Math.round(((first?.orbit===1?12:6)+(second?.orbit===1?5:0))));
  const coalitionFit=Math.min(92,index+Math.min(16,actors.filter(a=>a.orbit>=2).length*4));
  const contributionFit=Math.min(96,index+Math.min(18,watch.length*2)+(nature.toLowerCase().includes("amend")?6:0));
  return[
    {id:"institutionnel",name:"Trajectoire institutionnelle",tagline:`Structurer le chemin de décision jusqu’à ${deadline}`,impact:institutionalFit,feasibility:first?82:56,speed:watch.some(w=>urgencyWeight(w.urgency)>=3)?88:72,risk:first?.position==="opposition"?48:28,summary:`Prioriser ${actorLabel(first)} puis ${actorLabel(second)} comme points d’entrée formels autour de l’objectif « ${objective} ».`,lever:`Brief décisionnel sourcé → échange institutionnel → suivi de l’arbitrage`,whyNow:`Le Radar place ${first?.name||"un acteur prioritaire"} parmi les acteurs les plus influents et sa position est ${positionLabel(first?.position)}. ${evidence[0]?`Le signal le plus prioritaire est « ${clip(evidence[0].title,95)} ».`:"La veille doit encore être consolidée."}`,hypothesis:`Si le chemin de décision, les contraintes institutionnelles et la demande formelle sont clarifiés avant ${deadline}, Myvor peut réduire l’incertitude sur l’arbitrage sans dépendre d’un seul interlocuteur.`,preconditions:[`Valider précisément la demande liée à « ${objective} »`,`Confirmer le rôle réel de ${actorLabel(first)}`,`Préparer une base factuelle issue d’au moins ${Math.max(1,Math.min(3,evidence.length))} source(s) liée(s)`],risks:[first?.position==="opposition"?`${first.name} est actuellement qualifié ${positionLabel(first.position)} : ne pas supposer d’adhésion.`:"La position du premier acteur peut rester incomplètement documentée.",`Dépendance excessive à un seul canal si ${second?.name||"un second relais"} n’est pas activé.`,`Fenêtre d’action susceptible de se réduire avant ${deadline}.`],success:[`Rôle et marge de décision des 2 premiers acteurs confirmés`,`Demande institutionnelle formulée en une phrase et reliée au dossier`,`Retour ou signal institutionnel enregistré avant ${deadline}`],evidence:evidence.map(watchLabel)},
    {id:"coalition",name:"Trajectoire de coalition",tagline:"Construire une position convergente et publiquement défendable",impact:coalitionFit,feasibility:actors.length>=4?78:62,speed:61,risk:36,summary:`Transformer le contexte « ${context} » en socle commun avec des relais sectoriels ou institutionnels déjà présents dans le Radar.`,lever:"Socle factuel commun → convergence des acteurs → contribution coordonnée",whyNow:`Le Radar contient ${actors.length} acteur(s), dont ${actors.filter(a=>a.orbit>=2).length} dans les orbites Influence/Écosystème. Cela permet de tester une stratégie multi-acteurs plutôt qu’un canal unique.`,hypothesis:`Une convergence limitée à des faits, impacts documentés et demandes institutionnelles communes peut renforcer la robustesse d’une contribution sans fabriquer artificiellement un consensus.`,preconditions:[`Identifier au moins 2 acteurs ayant un intérêt institutionnel objectivement convergent`,`Distinguer les faits partagés des positions propres à chaque organisation`,`Fixer un périmètre commun limité à l’objectif « ${objective} »`],risks:["Convergence de façade si les intérêts réels divergent.","Dilution de l’objectif si le socle commun devient trop large.","Confusion entre coordination factuelle et alignement politique : conserver des positions autonomes."],success:["Deux acteurs ou organisations valident un socle factuel commun","Une contribution commune ou parallèle est prête avant l’échéance","Les divergences restantes sont explicitement documentées"],evidence:evidence.map(watchLabel)},
    {id:"contribution",name:"Trajectoire expertise & texte",tagline:`Transformer la veille ${nature.toLowerCase()} en contribution exploitable`,impact:contributionFit,feasibility:88,speed:86,risk:20,summary:`Partir des ${watch.length} évolution(s) rattachée(s) pour isoler le point de décision, construire la preuve et produire une contribution formelle directement reliée à « ${objective} ».`,lever:"Matrice de preuve → note technique → proposition formelle → suivi de prise en compte",whyNow:`La veille contient ${watch.length} élément(s) et le type dominant est « ${nature} ». ${evidence[0]?`Le premier support à exploiter est « ${clip(evidence[0].title,95)} ».`:"Il faut d’abord renforcer les sources."}`,hypothesis:`Une demande précise accompagnée d’une justification sourcée et d’une rédaction opérationnelle est plus facilement intégrable dans un processus institutionnel qu’un argumentaire général.`,preconditions:[`Identifier le point exact du texte, de la consultation ou de l’arbitrage à faire évoluer`,`Relier chaque affirmation importante à une source du dossier`,`Séparer clairement faits, analyse Myvor et position du client`],risks:["Contribution trop générale pour être exploitable par l’institution.","Source insuffisante ou obsolète sur un élément central.",`Décalage temporel si la production n’est pas finalisée avant ${deadline}.`],success:["Un point de modification ou de décision est identifié sans ambiguïté","Chaque recommandation est reliée à une source ou marquée comme analyse","La contribution est prête à être transmise par un canal institutionnel approprié"],evidence:evidence.map(watchLabel)},
  ];
}

function buildPlan(scenario:ScenarioId,dossier:WarZoneDossier,actors:WarZoneActor[],watch:WarZoneWatch[]):PlanStep[]{
  const targets=topActors(actors),deadline=firstDeadline(dossier),first=targets[0],second=targets[1],third=targets[2],evidence=priorityWatch(watch),objective=clip(dossier.objective||dossier.title,135),source1=watchLabel(evidence[0]),source2=watchLabel(evidence[1]);
  if(scenario==="coalition")return[
    {id:"c1",order:1,title:"Définir le périmètre de convergence",purpose:`Isoler, dans « ${objective} », les 2 ou 3 points pouvant être défendus sur une base factuelle commune.`,deliverable:"Matrice convergences / divergences",timing:"Immédiat",priority:"high",expected:"Un socle commun limité et crédible",dependency:"Objectif du dossier validé",success:"Les points communs et les divergences sont séparés explicitement",evidence:source1},
    {id:"c2",order:2,title:"Qualifier les relais compatibles",actor:second||first,purpose:`Vérifier quels acteurs du Radar peuvent légitimement porter ou relayer ce socle au regard de leur rôle public et de leur institution.`,deliverable:"Short-list de 2 à 4 relais",timing:"Sous 48 h",priority:"high",expected:"Coalition construite sur des rôles réels, pas sur des suppositions",dependency:"Fiches acteurs enrichies",success:"Chaque relais a un rôle, une position et une source de qualification",evidence:source2},
    {id:"c3",order:3,title:"Consolider le dossier factuel",purpose:`Produire un paquet de preuve commun à partir de ${Math.max(1,evidence.length)} source(s) prioritaire(s), sans harmoniser artificiellement les positions.`,deliverable:"Note factuelle commune",timing:"Sous 72 h",priority:"high",expected:"Base documentaire partagée et vérifiable",dependency:"Sources liées au dossier",success:"Toutes les affirmations centrales sont sourcées",evidence:`${source1}${evidence[1]?` ; ${source2}`:""}`},
    {id:"c4",order:4,title:"Formaliser les contributions",actor:third||second||first,purpose:"Préparer une contribution commune lorsque c’est légitime, ou des contributions parallèles cohérentes lorsque les positions diffèrent.",deliverable:"Contribution(s) finalisée(s)",timing:`Avant ${deadline}`,priority:"high",expected:"Expression coordonnée sans effacer les divergences",dependency:"Socle factuel validé",success:"Chaque organisation conserve une position explicitement attribuée",evidence:source1},
    {id:"c5",order:5,title:"Mesurer les signaux de reprise",purpose:"Suivre les réponses institutionnelles, nouvelles publications et évolutions du Radar afin d’actualiser la stratégie.",deliverable:"Revue stratégique post-action",timing:`À ${deadline}`,priority:"medium",expected:"Décision de poursuivre, ajuster ou arrêter la coalition",dependency:"Veille active",success:"Au moins un signal objectivable de reprise, réponse ou non-prise en compte est enregistré",evidence:"Veille Myvor actualisée"},
  ];
  if(scenario==="contribution")return[
    {id:"e1",order:1,title:"Isoler le point de décision",purpose:`Transformer « ${objective} » en une demande institutionnelle précise : disposition, arbitrage, consultation ou mesure clairement identifiable.`,deliverable:"Fiche point de décision",timing:"Immédiat",priority:"high",expected:"Une demande compréhensible sans contexte oral supplémentaire",dependency:"Objectif client validé",success:"Le point visé est formulé en une phrase",evidence:source1},
    {id:"e2",order:2,title:"Construire la matrice de preuve",purpose:`Associer chaque effet attendu, risque ou justification aux sources de veille les plus pertinentes, dont ${source1}.`,deliverable:"Matrice affirmation → source → niveau de confiance",timing:"Sous 24 h",priority:"high",expected:"Argumentation vérifiable et audit-able",dependency:"Sources accessibles",success:"Aucune affirmation centrale sans source ou étiquette « analyse »",evidence:`${source1}${evidence[1]?` ; ${source2}`:""}`},
    {id:"e3",order:3,title:"Rédiger la contribution opérationnelle",purpose:"Produire une note courte, une proposition de rédaction ou une contribution formelle adaptée au type de procédure observé dans la veille.",deliverable:"Note technique + proposition opérationnelle",timing:"Sous 48 h",priority:"high",expected:"Document directement exploitable par un interlocuteur institutionnel",dependency:"Matrice de preuve terminée",success:"Le document distingue faits, analyse et demande",evidence:source1},
    {id:"e4",order:4,title:"Choisir le canal institutionnel",actor:first,purpose:`Transmettre la contribution via un canal cohérent avec le rôle de ${actorLabel(first)}, sans présumer de sa position ni personnaliser le message sur des caractéristiques privées.`,deliverable:"Transmission / rendez-vous / dépôt formel",timing:`Avant ${deadline}`,priority:"high",expected:"Contribution reçue dans le bon circuit",dependency:"Rôle de la cible confirmé",success:"Canal, destinataire institutionnel et date de transmission enregistrés",evidence:first?.why||"Fiche acteur à confirmer"},
    {id:"e5",order:5,title:"Contrôler la prise en compte",purpose:"Comparer la version, décision ou signal institutionnel suivant avec la demande formulée et documenter les écarts.",deliverable:"Note d’écart et prochaine décision",timing:`À ${deadline}`,priority:"medium",expected:"Boucle d’apprentissage mesurable",dependency:"Nouvelle évolution disponible",success:"La prise en compte est classée : reprise / partielle / absente / indéterminée",evidence:"Nouvelle veille rattachée au dossier"},
  ];
  return[
    {id:"i1",order:1,title:"Cartographier le chemin de décision",purpose:`Identifier qui décide, qui instruit et qui peut formaliser l’arbitrage autour de « ${objective} ».`,deliverable:"Chaîne de décision en 1 page",timing:"Immédiat",priority:"high",expected:"Aucune confusion entre influence, instruction et décision",dependency:"Radar généré",success:"Chaque rôle institutionnel est attribué et sourcé",evidence:first?.why||source1},
    {id:"i2",order:2,title:"Sécuriser le premier point d’entrée",actor:first,purpose:`Préparer un échange institutionnel avec ${actorLabel(first)} centré sur le dossier, son rôle public et les éléments vérifiables disponibles.`,deliverable:"Brief décisionnel 1 page",timing:"Sous 48 h",priority:"high",expected:"Premier canal institutionnel qualifié",dependency:"Fiche acteur enrichie",success:`Rôle, position (${positionLabel(first?.position)}) et fenêtre d’action confirmés`,evidence:source1},
    {id:"i3",order:3,title:"Ouvrir un second canal",actor:second,purpose:`Créer une voie complémentaire avec ${actorLabel(second)} pour éviter une stratégie mono-acteur et tester la cohérence du diagnostic institutionnel.`,deliverable:"Brief adapté au second rôle",timing:"Sous 72 h",priority:"high",expected:"Deux lectures institutionnelles du dossier",dependency:"Premier brief finalisé",success:"Le second canal apporte une information ou un signal distinct",evidence:source2},
    {id:"i4",order:4,title:"Consolider avant arbitrage",actor:third,purpose:`Actualiser la demande avec les nouvelles évolutions, notamment ${source1}, puis vérifier si l’ordre des priorités du Radar doit changer.`,deliverable:"Brief d’arbitrage actualisé",timing:`Avant ${deadline}`,priority:"high",expected:"Stratégie alignée sur la situation la plus récente",dependency:"Veille synchronisée",success:"Aucune source prioritaire non intégrée au brief",evidence:`${source1}${evidence[1]?` ; ${source2}`:""}`},
    {id:"i5",order:5,title:"Décider de la suite",purpose:"Après le prochain signal institutionnel, comparer le résultat obtenu à l’objectif et choisir : maintenir, élargir, basculer vers expertise ou arrêter la séquence.",deliverable:"Décision stratégique documentée",timing:`À ${deadline}`,priority:"medium",expected:"Pas de poursuite automatique d’une stratégie devenue obsolète",dependency:"Signal post-arbitrage disponible",success:"Une décision de continuation est justifiée par des faits nouveaux",evidence:"Radar + veille recalculés"},
  ];
}

export default function WarZoneView({dossier,actors,watch,onOpenActor,onActions}:Props){
  const[generated,setGenerated]=useState(false),[scenarioId,setScenarioId]=useState<ScenarioId>("institutionnel"),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
  const index=useMemo(()=>strategicIndex(actors,watch),[actors,watch]);
  const targets=useMemo(()=>topActors(actors),[actors]);
  const evidence=useMemo(()=>priorityWatch(watch),[watch]);
  const scenarios=useMemo(()=>dossier?buildScenarios(index,dossier,actors,watch):[],[index,dossier,actors,watch]);
  const active=scenarios.find(item=>item.id===scenarioId)||scenarios[0];
  const plan=useMemo(()=>dossier?buildPlan(scenarioId,dossier,actors,watch):[],[scenarioId,dossier,actors,watch]);
  async function addPlan(){if(!dossier||!onActions)return;setSaving(true);setSaved(false);try{await onActions(plan.map(step=>({dossier_id:dossier.id,type:"influence",title:step.title,description:`${step.purpose} Livrable : ${step.deliverable}. Dépendance : ${step.dependency}. Critère de réussite : ${step.success}. Preuve : ${step.evidence}.`,actor_name:step.actor?.name,priority:step.priority,due_date:null})));setSaved(true);}finally{setSaving(false);}}
  if(!dossier)return <div className={styles.empty}><Target size={38}/><h3>Sélectionnez un dossier</h3><p>La War Zone construit la stratégie à partir de l’objectif, du Radar et de la veille.</p></div>;
  if(!actors.length)return <div className={styles.empty}><Users size={38}/><h3>Générez d’abord le Radar</h3><p>La War Zone utilise les acteurs qualifiés du Radar pour construire une stratégie exploitable.</p></div>;
  const target=Math.min(95,index+18);
  return <div className={styles.page}>
    <section className={styles.objectiveCard}><div><span className={styles.eyebrow}>Objectif stratégique</span><h2>{dossier.objective||dossier.title}</h2><p>{dossier.context||"La stratégie est construite à partir des acteurs, échéances et évolutions rattachés au dossier."}</p></div><div className={styles.indexBox}><span>Indice stratégique</span><div><strong>{index}</strong><em>/100</em><ArrowRight size={18}/><strong>{target}</strong><em>cible</em></div><small>Indice de configuration, pas une probabilité de succès.</small></div></section>

    {!generated?<section className={styles.launchCard}><Sparkles size={30}/><h3>Construire une stratégie contextualisée</h3><p>Myvor va relier l’objectif, les acteurs, leurs positions connues, les échéances et les signaux de veille pour produire plusieurs trajectoires argumentées.</p><button onClick={()=>setGenerated(true)}><Sparkles size={16}/>Générer la stratégie</button></section>:<>
      <section className={styles.section}><div className={styles.sectionTitle}><div><span>01</span><div><h3>Diagnostic stratégique</h3><p>Ce que Myvor utilise réellement pour construire les trajectoires.</p></div></div></div><div className={styles.diagnosticGrid}><Diagnostic label="Échéance" value={firstDeadline(dossier)}/><Diagnostic label="Acteur prioritaire" value={actorLabel(targets[0])}/><Diagnostic label="Position connue" value={positionLabel(targets[0]?.position)}/><Diagnostic label="Veille dominante" value={dominantNature(watch)}/><Diagnostic label="Sources prioritaires" value={`${evidence.length} retenue(s) sur ${watch.length}`}/><Diagnostic label="Contexte" value={clip(dossier.context||dossier.title,105)}/></div></section>

      <section className={styles.section}><div className={styles.sectionTitle}><div><span>02</span><div><h3>Cibles prioritaires</h3><p>Leur rôle est utilisé comme contrainte de stratégie, pas comme prétexte à personnaliser un message politique.</p></div></div></div><div className={styles.targetGrid}>{targets.map((actor,indexTarget)=><button key={actor.id} className={styles.targetCard} onClick={()=>onOpenActor(actor)}><div className={styles.targetRank}>0{indexTarget+1}</div><div className={styles.targetMain}><b>{actor.name}</b><span>{actor.role}</span><small>{actor.institution||"Institution à préciser"} · position {positionLabel(actor.position)}</small></div><div className={styles.targetScore}><strong>{score(actor)}</strong><span>/100</span></div></button>)}</div></section>

      <section className={styles.section}><div className={styles.sectionTitle}><div><span>03</span><div><h3>Trajectoires stratégiques</h3><p>Chaque scénario est recalculé à partir du dossier actif.</p></div></div></div><div className={styles.scenarioGrid}>{scenarios.map(item=><button key={item.id} onClick={()=>setScenarioId(item.id)} className={`${styles.scenarioCard} ${scenarioId===item.id?styles.scenarioActive:""}`}><div className={styles.scenarioTop}><span>{item.name}</span>{scenarioId===item.id&&<CheckCircle2 size={17}/>}</div><h4>{item.tagline}</h4><p>{item.summary}</p><div className={styles.metrics}><Metric label="Impact" value={item.impact}/><Metric label="Faisabilité" value={item.feasibility}/><Metric label="Vitesse" value={item.speed}/><Metric label="Risque" value={item.risk} inverse/></div><div className={styles.lever}><Layers3 size={14}/>{item.lever}</div></button>)}</div></section>

      {active&&<section className={styles.section}><div className={styles.sectionTitle}><div><span>04</span><div><h3>Lecture détaillée — {active.name}</h3><p>Hypothèse, conditions de réussite, risques et preuves à mobiliser.</p></div></div></div><div className={styles.strategyDetail}><article><span>Pourquoi maintenant</span><p>{active.whyNow}</p></article><article><span>Hypothèse stratégique</span><p>{active.hypothesis}</p></article><article><span>Préconditions</span><ul>{active.preconditions.map(item=><li key={item}>{item}</li>)}</ul></article><article><span>Risques à contrôler</span><ul>{active.risks.map(item=><li key={item}>{item}</li>)}</ul></article><article><span>Critères de réussite</span><ul>{active.success.map(item=><li key={item}>{item}</li>)}</ul></article><article><span>Preuves mobilisées</span><ul>{active.evidence.length?active.evidence.map(item=><li key={item}>{item}</li>):<li>Aucune source prioritaire disponible : renforcer la veille avant exécution.</li>}</ul></article></div></section>}

      <section className={styles.section}><div className={styles.sectionTitle}><div><span>05</span><div><h3>Plan d’action — {active?.name||"stratégie"}</h3><p>Une séquence de cinq mouvements avec dépendance et critère de sortie.</p></div></div><button className={styles.addPlan} onClick={()=>void addPlan()} disabled={!onActions||saving}>{saved?<CheckCircle2 size={15}/>:<Plus size={15}/>} {saving?"Ajout…":saved?"Plan ajouté":"Ajouter aux actions"}</button></div><div className={styles.plan}>{plan.map(step=><article key={step.id} className={styles.step}><div className={styles.stepOrder}>{step.order}</div><div className={styles.stepBody}><div className={styles.stepHead}><div><b>{step.title}</b>{step.actor&&<button onClick={()=>onOpenActor(step.actor!)}>{step.actor.name}</button>}</div><span className={styles[step.priority]}>{step.timing}</span></div><p>{step.purpose}</p><div className={styles.stepMeta}><span><Flag size={13}/>Livrable : {step.deliverable}</span><span><CircleDot size={13}/>Effet attendu : {step.expected}</span><span><Layers3 size={13}/>Dépendance : {step.dependency}</span><span><CheckCircle2 size={13}/>Réussite : {step.success}</span><span><FileSearch size={13}/>Preuve : {step.evidence}</span></div></div></article>)}</div></section>

      <section className={styles.guardrail}><ShieldCheck size={17}/><div><b>Cadre Myvor</b><span>La War Zone structure des démarches transparentes d’affaires publiques à partir de rôles institutionnels, sources publiques et enjeux du dossier. Elle ne produit pas de ciblage psychologique, d’exploitation de données privées ni de persuasion politique personnalisée.</span></div></section>
    </>}
  </div>;
}

function Diagnostic({label,value}:{label:string;value:string}){return <div className={styles.diagnostic}><span>{label}</span><b>{value}</b></div>;}
function Metric({label,value,inverse=false}:{label:string;value:number;inverse?:boolean}){const display=inverse?100-value:value;return <div className={styles.metric}><div><span>{label}</span><b>{value}</b></div><div><i style={{width:`${Math.max(4,Math.min(100,display))}%`}}/></div></div>;}
