import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
type Mode="express"|"standard"|"deep";
type CriterionKey="juridique"|"reglementaire"|"operationnel"|"reputationnel"|"fenetre_action"|"risque_inaction";
const ENGINE="myvor-urgency-score-v1";
const PROMPT_VERSION="urgency-score-prompt-v1";
const MAX:Record<CriterionKey,number>={juridique:15,reglementaire:15,operationnel:20,reputationnel:15,fenetre_action:20,risque_inaction:15};
const KEYS=Object.keys(MAX) as CriterionKey[];
const MODE_CONFIG:Record<Mode,{sourceLimit:number;sourceChars:number;fetchTimeout:number;modelTimeout:number;tokens:number}>={express:{sourceLimit:4,sourceChars:2600,fetchTimeout:2500,modelTimeout:16000,tokens:1200},standard:{sourceLimit:8,sourceChars:3500,fetchTimeout:3500,modelTimeout:33000,tokens:2600},deep:{sourceLimit:16,sourceChars:5000,fetchTimeout:4500,modelTimeout:60000,tokens:4600}};
const OFFICIAL_HOSTS=["assemblee-nationale.fr","senat.fr","legifrance.gouv.fr","vie-publique.fr","gouvernement.fr","economie.gouv.fr","ecologie.gouv.fr","travail-emploi.gouv.fr","interieur.gouv.fr","justice.gouv.fr","sante.gouv.fr","conseil-constitutionnel.fr","conseil-etat.fr","courdecassation.fr","ccomptes.fr","cnil.fr","arcep.fr","cre.fr","amf-france.org","autoritedelaconcurrence.fr","eur-lex.europa.eu","ec.europa.eu","commission.europa.eu","digital-strategy.ec.europa.eu","europarl.europa.eu","consilium.europa.eu"];

const criterionSchema=(max:number)=>({type:"object",additionalProperties:false,properties:{score:{type:"number",minimum:0,maximum:max},justification:{type:"string"},evidence:{type:"array",items:{type:"string"}}},required:["score","justification","evidence"]});
const OUTPUT_SCHEMA={type:"object",additionalProperties:false,properties:{summary:{type:"string"},criteria:{type:"object",additionalProperties:false,properties:{juridique:criterionSchema(15),reglementaire:criterionSchema(15),operationnel:criterionSchema(20),reputationnel:criterionSchema(15),fenetre_action:criterionSchema(20),risque_inaction:criterionSchema(15)},required:[...KEYS]},workstreams:{type:"array",items:{type:"string"}},next_actions:{type:"array",items:{type:"string"}},uncertainties:{type:"array",items:{type:"string"}}},required:["summary","criteria","workstreams","next_actions","uncertainties"]};

function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});}
function clip(value:unknown,max:number){return String(value??"").normalize("NFKC").replace(/[\u0000-\u001F\u007F]/g," ").replace(/\s+/g," ").slice(0,max).trim();}
function clamp(value:unknown,max:number){const number=Number(value);return Number.isFinite(number)?Math.max(0,Math.min(max,Math.round(number))):0;}
function allowedUrl(raw:string){try{const url=new URL(raw);const host=url.hostname.toLowerCase();return url.protocol==="https:"&&OFFICIAL_HOSTS.some(base=>host===base||host.endsWith(`.${base}`));}catch{return false;}}
function htmlText(raw:string){return raw.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/\s+/g," ").trim();}
function outputText(payload:any){if(typeof payload?.output_text==="string")return payload.output_text;return (payload?.output||[]).flatMap((item:any)=>item?.content||[]).map((item:any)=>item?.text||"").join("");}

async function requireQuota(req:Request){const authorization=req.headers.get("authorization")||"";if(!authorization.toLowerCase().startsWith("bearer "))return json({error:"Session Myvor requise."},401);const supabaseUrl=(Deno.env.get("SUPABASE_URL")||"").replace(/\/$/,"");const anonKey=Deno.env.get("SUPABASE_ANON_KEY")||"";if(!supabaseUrl||!anonKey)return json({error:"Configuration Supabase incomplète."},503);try{const user=await fetch(`${supabaseUrl}/auth/v1/user`,{headers:{apikey:anonKey,Authorization:authorization}});if(!user.ok)return json({error:"Session Myvor invalide ou expirée."},401);const quota=await fetch(`${supabaseUrl}/rest/v1/rpc/consume_ai_quota`,{method:"POST",headers:{apikey:anonKey,Authorization:authorization,"Content-Type":"application/json"},body:JSON.stringify({p_feature:"urgency_score"})});if(!quota.ok)return json({error:"Impossible de vérifier le quota IA Myvor."},503);const allowed=await quota.json().catch(()=>false);if(allowed!==true)return json({error:"Trop de Scores d’urgence générés en peu de temps. Réessaie dans quelques minutes."},429);return null;}catch{return json({error:"Impossible de vérifier la session Myvor."},503);}}

async function fetchSource(item:any,config:(typeof MODE_CONFIG)[Mode]){const url=clip(item?.source_url,1200),title=clip(item?.title,500);if(!url||!allowedUrl(url))return{title,url,status:url?"unsupported":"missing_url",read_chars:0,text:""};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),config.fetchTimeout);try{const response=await fetch(url,{headers:{"User-Agent":"Myvor/1.0 urgency-score","Accept":"text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.4"},redirect:"follow",signal:controller.signal});if(!response.ok||!allowedUrl(response.url||url))return{title,url,status:"unavailable",read_chars:0,text:""};const type=(response.headers.get("content-type")||"").toLowerCase();if(!type.includes("text/html")&&!type.includes("application/xhtml+xml")&&!type.includes("text/plain"))return{title,url:response.url||url,status:"unsupported",read_chars:0,text:""};const raw=(await response.text()).slice(0,650000);const text=clip(type.includes("html")||type.includes("xhtml")?htmlText(raw):raw,config.sourceChars);return{title,url:response.url||url,status:text.length>=100?"fetched":"unavailable",read_chars:text.length,text};}catch{return{title,url,status:"unavailable",read_chars:0,text:""};}finally{clearTimeout(timer);}}

function dossierContext(dossier:any){const lines=[`Client : ${clip(dossier?.client,300)}`,`Dossier : ${clip(dossier?.title,500)}`,`Objectif client : ${clip(dossier?.objective,1800)}`,`Contexte : ${clip(dossier?.context,2500)}`,`Secteur : ${clip(dossier?.sector,500)}`,`Activité : ${clip(dossier?.activity,900)}`,`Enjeux : ${(Array.isArray(dossier?.strategic_issues)?dossier.strategic_issues:[]).map((v:any)=>clip(v,300)).filter(Boolean).join(" ; ")}`,`Risques à éviter : ${(Array.isArray(dossier?.risks_to_avoid)?dossier.risks_to_avoid:[]).map((v:any)=>clip(v,300)).filter(Boolean).join(" ; ")}`,`Opportunités recherchées : ${(Array.isArray(dossier?.opportunities)?dossier.opportunities:[]).map((v:any)=>clip(v,300)).filter(Boolean).join(" ; ")}`,`Position client : ${clip(dossier?.client_position,1000)}`,`Échéances client : ${(Array.isArray(dossier?.key_deadlines)?dossier.key_deadlines:[]).map((v:any)=>clip(v,250)).filter(Boolean).join(" ; ")}`,`Notes internes : ${clip(dossier?.internal_notes,1200)}`];return lines.filter(line=>!line.endsWith(": ")).join("\n");}

function buildPrompt(mode:Mode,dossier:any,items:any[],sources:any[]){const modeRule=mode==="express"?"MODE EXPRESS. Réponds de manière extrêmement compacte. Une à deux phrases maximum par justification. Donne au plus 3 actions immédiates. workstreams peut être vide.":mode==="standard"?"MODE STANDARD. Justifie chaque critère en 2 à 4 phrases et fournis 3 à 6 pistes de travail concrètes, sans construire une stratégie d'influence détaillée.":"MODE APPROFONDI. Justifie chaque chiffre de façon détaillée et causale. Pour chaque critère, explique les faits retenus, leur lien avec l'objectif client, les incertitudes et pourquoi la note n'est ni plus haute ni plus basse. Cite dans evidence les titres des éléments ou faits réellement présents dans le corpus.";const itemMeta=items.map((item,index)=>`VEILLE ${index+1}\nTitre : ${clip(item?.title,500)}\nNature : ${clip(item?.nature,180)}\nUrgence de veille : ${clip(item?.urgency,100)}\nSource : ${clip(item?.source_name,240)}\nRaison de rattachement : ${clip(item?.qualification_reason,650)}\nURL : ${clip(item?.source_url,1000)}`).join("\n\n");const sourceText=sources.map((source,index)=>`SOURCE LUE ${index+1}\nTitre : ${source.title}\nURL : ${source.url}\nContenu : ${source.text}`).join("\n\n---\n\n");return `Tu es le moteur Score d'urgence de Myvor, un outil d'aide à la décision pour les affaires publiques.\n\nQUESTION UNIQUE : une action est-elle nécessaire maintenant pour atteindre l'objectif du client, et pourquoi ?\n\n${modeRule}\n\nBARÈME FIXE SUR 100 :\n- juridique : 0 à 15\n- reglementaire : 0 à 15\n- operationnel : 0 à 20\n- reputationnel : 0 à 15\n- fenetre_action : 0 à 20\n- risque_inaction : 0 à 15\n\nRÈGLES :\n1. Le score mesure l'urgence d'agir par rapport à l'objectif précis du client, jamais l'importance générale du sujet.\n2. Chaque note doit être justifiée par les données fournies. N'invente aucun texte, date, sanction, position d'acteur ou conséquence certaine.\n3. Si une information manque, réduis la certitude de la note et inscris le point dans uncertainties.\n4. fenetre_action mesure la marge temporelle et la capacité à intervenir utilement avant un point de bascule. Un score élevé signifie une fenêtre courte ou décisive.\n5. risque_inaction mesure ce que le client risque de perdre ou subir s'il ne fait rien.\n6. Ne produis PAS de cartographie d'acteurs ni de stratégie de lobbying : cela appartient au Radar et à la War Zone.\n7. Les recommandations doivent rester des pistes de travail internes ou des étapes de préparation.\n8. evidence contient uniquement des titres ou faits présents dans le corpus ; jamais de références inventées.\n9. Réponds exactement selon le schéma JSON imposé.\n\nDOSSIER CLIENT\n${dossierContext(dossier)}\n\nÉLÉMENTS DE VEILLE RATTACHÉS\n${itemMeta}\n\nCONTENU OFFICIEL RÉCUPÉRÉ\n${sourceText||"Aucun contenu officiel n'a pu être lu. Base tes notes uniquement sur les métadonnées de veille et signale les limites dans uncertainties."}`;}

function normalize(raw:any,mode:Mode,sources:any[]){const criteria={} as Record<CriterionKey,any>;for(const key of KEYS){const value=raw?.criteria?.[key]||{};criteria[key]={score:clamp(value.score,MAX[key]),max:MAX[key],justification:clip(value.justification,mode==="deep"?2200:mode==="standard"?1200:650),evidence:(Array.isArray(value.evidence)?value.evidence:[]).slice(0,mode==="deep"?8:4).map((item:any)=>clip(item,500)).filter(Boolean)};}const score=KEYS.reduce((sum,key)=>sum+criteria[key].score,0);const level=score>=85?"critique":score>=70?"urgent":score>=50?"action_necessaire":score>=25?"a_surveiller":"faible";const decision=score>=70?"AGIR_MAINTENANT":score>=50?"AGIR":score>=25?"SURVEILLER_ET_PREPARER":"NE_PAS_AGIR_IMMEDIATEMENT";return{score,level,decision,action_needed:score>=50,summary:clip(raw?.summary,mode==="deep"?2600:mode==="standard"?1500:850),criteria,workstreams:(Array.isArray(raw?.workstreams)?raw.workstreams:[]).slice(0,mode==="express"?0:mode==="standard"?6:8).map((v:any)=>clip(v,900)).filter(Boolean),next_actions:(Array.isArray(raw?.next_actions)?raw.next_actions:[]).slice(0,mode==="express"?3:mode==="standard"?5:7).map((v:any)=>clip(v,900)).filter(Boolean),uncertainties:(Array.isArray(raw?.uncertainties)?raw.uncertainties:[]).slice(0,mode==="express"?3:mode==="standard"?6:10).map((v:any)=>clip(v,900)).filter(Boolean),sources:sources.map(source=>({title:source.title,url:source.url,status:source.status})),mode};}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Méthode non autorisée."},405);const authError=await requireQuota(req);if(authError)return authError;const body=await req.json().catch(()=>null);const mode:Mode=["express","standard","deep"].includes(String(body?.mode))?body.mode:"standard";const dossier=body?.dossier||null;const items=Array.isArray(body?.items)?body.items:[];if(!dossier?.objective||!items.length)return json({error:"Dossier et veille rattachée sont obligatoires."},400);const config=MODE_CONFIG[mode];const selected=items.slice(0,mode==="express"?6:mode==="standard"?12:24);const sourceItems=selected.filter((item:any)=>item?.source_url).slice(0,config.sourceLimit);const sources=await Promise.all(sourceItems.map((item:any)=>fetchSource(item,config)));const apiKey=clip(Deno.env.get("OPENAI_API_KEY")||"",400);if(!apiKey.startsWith("sk-"))return json({error:"OPENAI_API_KEY n'est pas configurée dans Supabase."},503);const model=clip(Deno.env.get("OPENAI_URGENCY_MODEL")||"gpt-5-mini",120);const prompt=buildPrompt(mode,dossier,selected,sources);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),config.modelTimeout);const started=Date.now();try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json","X-Client-Request-Id":crypto.randomUUID()},body:JSON.stringify({model,input:prompt,max_output_tokens:config.tokens,text:{verbosity:mode==="deep"?"medium":"low",format:{type:"json_schema",name:"myvor_urgency_score",schema:OUTPUT_SCHEMA,strict:true}},store:false}),signal:controller.signal});if(!response.ok){const raw=await response.text();let message="";try{message=clip(JSON.parse(raw)?.error?.message,260);}catch{}return json({error:message||`Le service IA a renvoyé une erreur (${response.status}).`},response.status===429?429:502);}const payload=await response.json();if(payload?.status==="incomplete")return json({error:"Le moteur IA n'a pas terminé le Score d'urgence dans le temps disponible."},504);const text=outputText(payload);let parsed:any=null;try{parsed=JSON.parse(text);}catch{return json({error:"Le moteur IA a renvoyé un Score d'urgence inexploitable."},502);}const normalized=normalize(parsed,mode,sources);return json({result:{...normalized,engine:ENGINE,model,execution_ms:Date.now()-started},engine:ENGINE,model,prompt_version:PROMPT_VERSION,execution_ms:Date.now()-started});}catch(error:any){if(error?.name==="AbortError")return json({error:mode==="express"?"Le Score Express n'a pas été calculé dans la fenêtre cible.":mode==="standard"?"Le Score Standard n'a pas été calculé dans la fenêtre cible.":"Le Score approfondi a dépassé le temps disponible."},504);return json({error:`Erreur moteur Score d'urgence : ${clip(error?.message||"inconnue",220)}`},502);}finally{clearTimeout(timer);}});
