-- Myvor — autonomous institutional monitoring foundation.
-- Stores the global institutional feed once, then creates user watch items only
-- after dossier relevance qualification.

begin;

create table if not exists public.institutional_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  nature text not null,
  source_url text not null,
  source_name text not null default 'Source institutionnelle',
  published_at timestamptz,
  excerpt text,
  discovered_at timestamptz not null default now(),
  processed_at timestamptz
);

create unique index if not exists institutional_items_source_url_uidx
  on public.institutional_items (source_url);
create index if not exists institutional_items_discovered_at_idx
  on public.institutional_items (discovered_at desc);
create index if not exists institutional_items_processing_idx
  on public.institutional_items (processed_at, discovered_at)
  where processed_at is null;

alter table public.institutional_items enable row level security;
revoke all on table public.institutional_items from anon, authenticated;

alter table public.watch_items
  add column if not exists institutional_item_id uuid references public.institutional_items(id) on delete set null,
  add column if not exists source_name text,
  add column if not exists published_at timestamptz,
  add column if not exists excerpt text,
  add column if not exists suggested_dossier_id uuid references public.dossiers(id) on delete set null,
  add column if not exists qualification_confidence double precision,
  add column if not exists qualification_reason text,
  add column if not exists qualified_at timestamptz;

create unique index if not exists watch_items_user_institutional_uidx
  on public.watch_items (user_id, institutional_item_id)
  where institutional_item_id is not null;
create index if not exists watch_items_published_at_idx
  on public.watch_items (user_id, published_at desc nulls last);

create table if not exists public.veille_sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running','success','error')),
  discovered_count integer not null default 0,
  backlog_count integer not null default 0,
  matched_count integer not null default 0,
  auto_linked_count integer not null default 0,
  review_count integer not null default 0,
  message text
);

create index if not exists veille_sync_runs_started_at_idx
  on public.veille_sync_runs (started_at desc);

alter table public.veille_sync_runs enable row level security;
revoke all on table public.veille_sync_runs from anon, authenticated;

commit;
