const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const MAX_CONTEXT_ITEMS=24;
const DEFAULT_MODEL="gpt-5-mini";
type Dossier={id:string;client:string;title:string;objective:string;context?:string;key_deadlines?:string[]};
type WatchItem={id:string;title:string;nature:string;source_url?:string;source_name?:string|null;urgency?:string;created_at?:string;published_at?:string|null};
type Position="favorable"|"inconnue"|"reserve"|"opposition";
type Actor={id:string;name:string;role:string;institution?:string;orbit:1|2|3;position?:Position;position_reason?:string;influence:number;influence_score?:number;why:string;window:string;action:string;certainty?:"confirme"|"probable"|"a_confirmer";evidence?:Record<string,unknown>};

const OUTPUT_SCHEMA={type:"object",additionalProperties:false,properties:{actor:{type:"object",additionalProperties:false,properties:{role:{type:"string"},institution:{type:"string"},orbit:{type:"integer",enum:[1,2,3]},influence_score:{type:"integer"},score_breakdown:{type:"object",additionalProperties:false,properties:{institutional_power:{type:"integer"},dossier_relevance:{type:"integer"},timing:{type:"integer"},accessibility:{type:"integer"}},required:["institutional_power","dossier_relevance","timing","accessibility"]},position:{type:"string",enum:["favorable","inconnue","reserve","opposition"]},position_reason:{type:"string"},certainty:{type:"string",enum:["confirme","probable","a_confirmer"]},why:{type:"string"},window:{type:"string"},action:{type:"string"},source_indexes:{type:"array",items:{type:"integer"}},evidence_summary:{type:"string"}},required:["role","institution","orbit","influence_score","score_breakdown","position","position_reason","certainty","why","window","action","source_indexes","evidence_summary"]}},required:["actor"]};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function text(value:unknown,max=1000){return String(value??"").normalize("NFKC").replace(/[\u0000-\u001F\u007F]/g,"").slice(0,max).trim()}
function clamp(value:unknown,min:number,max:number){const n=Number(value);return Math.max(min,Math.min(max,Number.isFinite(n)?n:min))}
function cleanApiKey(raw:string){const normalized=String(raw||"").normalize("NFKC");const match=normalized.match(/sk-[A-Za-z0-9_-]+/);return match?.[0]||""}
function outputText(payload:any){if(typeof payload?.output_text==="string")return payload.output_text.trim();return(payload?.output||[]).flatMap((item:any)=>item?.content||[]).filter((part:any)=>part?.type==="output_text").map((part:any)=>part?.text||"").join("").trim()}
function modelName(){return text(Deno.env.get("OPENAI_RADAR_ENRICH_MODEL")||DEFAULT_MODEL,120)||DEFAULT_MODEL}
async function requireAuthenticatedQuota(req:Request){const authorization=req.headers.get("authorization")||"";if(!authorization.toLowerCase().startsWith("bearer "))return json({error:"Session Myvor requise."},401);const supabaseUrl=(Deno.env.get("SUPABASE_URL")||"").replace(/\/$/,""),anonKey=Deno.env.get("SUPABASE_ANON_KEY")||"";if(!supabaseUrl||!anonKey)return json({error:"La sécurité Supabase de Myvor n’est pas configurée."},503);try{const[userResponse,quotaResponse]=await Promise.all([fetch(`${supabaseUrl}/auth/v1/user`,{method:"GET",headers:{apikey:anonKey,Authorization:authorization}}),fetch(`${supabaseUrl}/rest/v1/rpc/consume_ai_quota`,{method:"POST",headers:{apikey:anonKey,Authorization:authorization,"Content-Type":"application/json"},body:JSON.stringify({p_feature:"radar-enrich"})})]);if(!userResponse.ok)return json({error:"Session Myvor invalide ou expirée."},401);const user=await userResponse.json().catch(()=>null);if(!user?.id)return json({error:"Session Myvor invalide ou expirée."},401);if(!quotaResponse.ok)return json({error:"Impossible de vérifier le quota IA du Radar."},503);const allowed=await quotaResponse.json().catch(()=>false);if(allowed!==true)return json({error:"Trop d’enrichissements Radar en peu de temps. Réessaie dans quelques minutes."},429);return null}catch{return json({error:"Impossible de vérifier la session Myvor."},503)}}

type OpenAIResult={detail:any|null;model:string;webSearch:boolean;error:string};
async function requestActorDetail(apiKey:string,model:string,prompt:string,webSearch:boolean,maxOutputTokens:number):Promise<OpenAIResult>{
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),webSearch?26000:18000);
  try{
    const body:any={model,input:prompt,max_output_tokens:maxOutputTokens,store:false,text:{format:{type:"json_schema",name:"myvor_actor_detail_v3",strict:true,schema:OUTPUT_SCHEMA}}};
    if(webSearch)body.tools=[{type:"web_search"}];
    const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify(body),signal:controller.signal});
    const raw=await response.text();let payload:any=null;try{payload=raw?JSON.parse(raw):null}catch{}
    if(!response.ok){const message=text(payload?.error?.message||raw||`OpenAI ${response.status}`,320);console.error("radar-enrich-openai",response.status,model,webSearch?"web":"context",message);return{detail:null,model,webSearch,error:`OpenAI ${response.status}: ${message}`};}
    if(payload?.status==="failed"||payload?.status==="incomplete"){const reason=text(payload?.error?.message||payload?.incomplete_details?.reason||payload?.status,240);console.error("radar-enrich-status",payload?.status,model,reason);return{detail:null,model,webSearch,error:`OpenAI ${payload?.status}: ${reason}`};}
    let parsed:any=null;try{parsed=JSON.parse(outputText(payload))}catch{}
    if(!parsed?.actor){const reason="Le moteur n’a pas retourné de fiche structurée exploitable.";console.error("radar-enrich-output",model,webSearch?"web":"context",reason);return{detail:null,model,webSearch,error:reason};}
    return{detail:parsed.actor,model,webSearch,error:""};
  }catch(error:any){const reason=error?.name==="AbortError"?"Délai OpenAI dépassé.":text(error?.message||error,260);console.error("radar-enrich-fetch",model,webSearch?"web":"context",reason);return{detail:null,model,webSearch,error:reason};}
  finally{clearTimeout(timer);}
}

function buildSignals(items:WatchItem[],rawIndexes:unknown){const indexes=(Array.isArray(rawIndexes)?rawIndexes:[]).map((n:any)=>Math.round(Number(n))).filter((n:number)=>n>=1&&n<=items.length).slice(0,3);const signals=indexes.map((n:number)=>{const item=items[n-1];return{title:text(item.title,420),nature:text(item.nature,120),date:text(item.published_at||item.created_at,80),url:text(item.source_url,700),source_name:text(item.source_name,180),urgency:text(item.urgency,80)}});return{indexes,signals};}
function buildEnrichedActor(actor:Actor,detail:any,items:WatchItem[]){const breakdown=detail?.score_breakdown||{};const scoreBreakdown={institutional_power:clamp(breakdown.institutional_power,0,35),dossier_relevance:clamp(breakdown.dossier_relevance,0,30),timing:clamp(breakdown.timing,0,20),accessibility:clamp(breakdown.accessibility,0,15)};const sum=clamp(scoreBreakdown.institutional_power+scoreBreakdown.dossier_relevance+scoreBreakdown.timing+scoreBreakdown.accessibility,0,100);const{indexes,signals}=buildSignals(items,detail?.source_indexes);const firstSignal=signals[0];const allowedPositions:Position[]=["favorable","inconnue","reserve","opposition"];const position=allowedPositions.includes(detail?.position as Position)?detail.position as Position:"inconnue";return{...actor,role:text(detail?.role,300)||actor.role,institution:text(detail?.institution,300)||text(actor.institution,300),orbit:[1,2,3].includes(Number(detail?.orbit))?Number(detail.orbit):actor.orbit,position,position_reason:text(detail?.position_reason,700)||text(actor.position_reason,700),influence:Math.max(1,Math.min(5,Math.ceil(sum/20))),influence_score:sum,score_breakdown:scoreBreakdown,why:text(detail?.why,900)||actor.why,window:text(detail?.window,500)||actor.window,action:text(detail?.action,700)||actor.action,certainty:["confirme","probable","a_confirmer"].includes(detail?.certainty)?detail.certainty:"a_confirmer",signals,source_count:signals.length,evidence:{source_index:indexes[0]||0,source_title:firstSignal?.title||"Recherche institutionnelle ciblée",source_url:firstSignal?.url||"",excerpt:text(detail?.evidence_summary,600),confidence:signals.length?.9:.7,verified:signals.length>0},detail_status:"enriched"};}
function buildFallbackActor(actor:Actor,dossier:Dossier,items:WatchItem[],reason:string){const score=clamp(actor.influence_score??Number(actor.influence||1)*20,0,100);const signals=items.slice(0,3).map(item=>({title:text(item.title,420),nature:text(item.nature,120),date:text(item.published_at||item.created_at,80),url:text(item.source_url,700),source_name:text(item.source_name,180),urgency:text(item.urgency,80)}));const firstSignal=signals[0];const deadline=text((dossier.key_deadlines||[])[0],240);return{...actor,influence_score:score,position:actor.position||"inconnue",position_reason:text(actor.position_reason,700)||"La position publique de cet acteur n’a pas pu être vérifiée automatiquement ; elle doit rester à confirmer avant toute action d’influence.",why:text(actor.why,900)||`Cet acteur figure dans la cartographie du dossier « ${text(dossier.title,220)} » et doit être vérifié à partir des sources institutionnelles disponibles.`,window:text(actor.window,500)||(deadline?`La prochaine fenêtre d’action doit être appréciée avant l’échéance suivante : ${deadline}.`:"La prochaine échéance institutionnelle du dossier doit être confirmée avant d’engager une action ciblée."),action:text(actor.action,700)||`Vérifier le rôle actuel de ${text(actor.name,160)}, documenter sa position publique sur le dossier puis qualifier l’opportunité d’un contact.`,certainty:"a_confirmer",signals,source_count:signals.length,evidence:{source_index:signals.length?1:0,source_title:firstSignal?.title||"Contexte du Radar",source_url:firstSignal?.url||"",excerpt:`Enrichissement automatique dégradé : ${text(reason,260)}`,confidence:signals.length?.55:.35,verified:false},detail_status:"degraded"};}

Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Méthode non autorisée."},405);const authError=await requireAuthenticatedQuota(req);if(authError)return authError;const body=await req.json().catch(()=>null);const dossier=(body?.dossier||null) as Dossier|null;const items=(Array.isArray(body?.items)?body.items:[]).slice(0,MAX_CONTEXT_ITEMS) as WatchItem[];const actor=(Array.isArray(body?.actors)?body.actors[0]:body?.actor||null) as Actor|null;if(!dossier||!actor)return json({error:"Sélectionne un acteur du Radar avant de demander le détail."},400);const apiKey=cleanApiKey(Deno.env.get("OPENAI_API_KEY")||"");if(!apiKey)return json({error:"Le secret OPENAI_API_KEY n’est pas configuré dans Supabase."},503);
const sourceInput=items.map((item,index)=>({index:index+1,title:text(item.title,420),nature:text(item.nature,120),urgency:text(item.urgency,80),date:text(item.published_at||item.created_at,80),source:text(item.source_name,180),url:text(item.source_url,700)}));
const prompt=["MYVOR — fiche acteur détaillée et vérifiable.","Tu enrichis UNIQUEMENT l’acteur fourni. N’ajoute ni ne remplace son identité.","RÈGLE DE RÉDACTION OBLIGATOIRE : position_reason, why, window, action et evidence_summary doivent être des phrases complètes, concrètes et autonomes.","Chaque phrase doit expliquer le fait observé, son lien avec le dossier et, lorsqu’il s’agit d’une action, ce qui doit être fait et dans quel but.","N’écris jamais des fragments vagues comme 'acteur clé', 'fenêtre favorable', 'à surveiller', 'prendre contact', 'forte influence' ou 'action prioritaire' sans expliquer concrètement pourquoi, quand et pour quel objectif.","Le champ action doit indiquer une action précise, son objet et le résultat attendu.","Le champ window doit expliquer la condition ou l’échéance qui rend l’action pertinente ; si aucune fenêtre vérifiable n’est disponible, indique quelle échéance doit être confirmée.","Si une recherche web est disponible, utilise-la uniquement pour vérifier cet acteur, son rôle/institution et sa pertinence pour le dossier. Privilégie les sources institutionnelles et les URL officielles fournies.","N’invente jamais une fonction, une position, une date ou un fait. Si une position favorable/réservée/opposition n’est pas étayée par une source publique suffisamment claire, retourne position=inconnue.","Le score /100 doit être la somme exacte de : pouvoir institutionnel /35, pertinence dossier /30, temporalité /20, accessibilité /15.","source_indexes doit contenir uniquement les numéros des évolutions fournies réellement pertinentes pour cet acteur. Si aucune évolution ne le concerne directement, retourne [].","evidence_summary est une paraphrase factuelle rédigée en phrase complète, jamais une citation inventée.",`CLIENT: ${text(dossier.client,240)}`,`DOSSIER: ${text(dossier.title,320)}`,`OBJECTIF: ${text(dossier.objective,1200)}`,`CONTEXTE: ${text(dossier.context,2200)||"Non renseigné"}`,`ÉCHÉANCES: ${JSON.stringify((dossier.key_deadlines||[]).slice(0,5).map(v=>text(v,220)))}`,`ACTEUR: ${JSON.stringify({name:text(actor.name,180),current_role:text(actor.role,260),current_institution:text(actor.institution,260),current_orbit:actor.orbit,current_score:actor.influence_score??actor.influence*20,current_position:actor.position||"inconnue"})}`,`ÉVOLUTIONS LIÉES: ${JSON.stringify(sourceInput)}`].join("\n");

const configuredModel=modelName();let result=await requestActorDetail(apiKey,configuredModel,prompt,true,2200);let fallbackUsed=false;if(!result.detail){fallbackUsed=true;result=await requestActorDetail(apiKey,DEFAULT_MODEL,prompt,false,2400);}if(result.detail){const enriched=buildEnrichedActor(actor,result.detail,items);return json({actor:enriched,enrichment:{status:fallbackUsed?"actor_detail_enriched_context_fallback":"actor_detail_enriched",grounded:true,source_content_read:true,web_search:result.webSearch,watch_items_used:items.length,complete_sentence_style:true,fallback_used:fallbackUsed},engine:"supabase-radar-actor-detail-v4-resilient",model:result.model});}
const degraded=buildFallbackActor(actor,dossier,items,result.error||"Enrichissement IA indisponible.");return json({actor:degraded,enrichment:{status:"actor_detail_degraded",grounded:items.length>0,source_content_read:true,web_search:false,watch_items_used:items.length,complete_sentence_style:true,fallback_used:true,degraded:true},engine:"supabase-radar-actor-detail-v4-resilient",model:DEFAULT_MODEL,warning:"La vérification IA complète n’a pas abouti ; Myvor affiche une fiche de continuité à confirmer."});
});