import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.111.0";

const PATH="/functions/v1/sync-watch-institutional";
const H={"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const MAX_TEXT=40000;
type Source={name:string,url:string,nature:string};
type Item={title:string;nature:string;source_url:string;source_name:string;published_at:string|null;source_text:string};
const SOURCES:Source[]=[
{name:"Assemblée nationale",url:"http://www2.assemblee-nationale.fr/feeds/detail/documents-parlementaires",nature:"Texte parlementaire"},
{name:"Sénat — Textes",url:"https://www.senat.fr/rss/textes.rss",nature:"Texte parlementaire"},
{name:"Sénat — Rapports",url:"https://www.senat.fr/rss/rapports.rss",nature:"Rapport"},
{name:"Économie — Actualités",url:"https://www.economie.gouv.fr/rss/toutesactualites",nature:"Communiqué institutionnel"},
{name:"Transition écologique — Actualités",url:"https://www.ecologie.gouv.fr/rss-actualites.xml",nature:"Communiqué institutionnel"},
{name:"Transition écologique — Presse",url:"https://www.ecologie.gouv.fr/rss-presse.xml",nature:"Communiqué institutionnel"},
{name:"Direction générale du Trésor",url:"https://www.tresor.economie.gouv.fr/Flux/Atom/Articles/Home",nature:"Publication institutionnelle"},
{name:"Conseil d’État — Avis",url:"https://conseil-etat.fr/outils/flux-rss/avis-rss",nature:"Avis consultatif"},
{name:"Conseil d’État — Jurisprudence",url:"https://conseil-etat.fr/outils/flux-rss/analyses-de-jurisprudence-rss",nature:"Décision / jurisprudence"}
];
function out(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H});}
function clip(x:unknown,n:number){return String(x??"").normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").slice(0,n).trim();}
function key(){const m=Deno.env.get("SUPABASE_SECRET_KEYS");if(m){try{const o=JSON.parse(m),v=o?.default||Object.values(o||{})[0];if(typeof v==="string"&&v)return v;}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";}
async function auth(req:Request,s:any){const ts0=req.headers.get("x-myvor-timestamp")||"",nonce=req.headers.get("x-myvor-nonce")||"",sig=(req.headers.get("x-myvor-signature")||"").toLowerCase();if(!/^\d{10}$/.test(ts0)||!/^[0-9a-f-]{36}$/i.test(nonce)||!/^[0-9a-f]{64}$/.test(sig))return false;const ts=Number(ts0);if(Math.abs(Math.floor(Date.now()/1000)-ts)>120)return false;const{data,error}=await s.rpc("verify_veille_internal_request",{p_path:PATH,p_timestamp:ts,p_nonce:nonce,p_signature:sig});return !error&&data===true;}
function entities(x:string){const named:Record<string,string>={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:" ",laquo:"«",raquo:"»",ndash:"–",mdash:"—",hellip:"…",eacute:"é",egrave:"è",ecirc:"ê",agrave:"à",ccedil:"ç",ocirc:"ô",ugrave:"ù",rsquo:"’",ldquo:"“",rdquo:"”"};return x.replace(/&#(x[0-9a-f]+|\d+);?/gi,(_,r)=>{const n=String(r).toLowerCase().startsWith("x")?parseInt(String(r).slice(1),16):parseInt(String(r),10);try{return Number.isFinite(n)?String.fromCodePoint(n):_;}catch{return _;}}).replace(/&([a-z][a-z0-9]+);/gi,(a,n)=>named[String(n).toLowerCase()]??a);}
function clean(x:string,n=MAX_TEXT){return clip(entities(x.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<script\b[\s\S]*?<\/script>/gi," ").replace(/<style\b[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ")),n);}
function tag(block:string,names:string[]){for(const name of names){const m=block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,`i`));if(m?.[1])return clean(m[1],5000);}return"";}
function link(block:string){const simple=tag(block,["link"]);if(/^https?:\/\//i.test(simple))return simple;const h=block.match(/<link[^>]+href=["']([^"']+)["']/i)?.[1];return h?entities(h):"";}
function date(raw:string){const t=Date.parse(clean(raw,200));return Number.isFinite(t)&&t<=Date.now()+36*3600000&&t>Date.UTC(1990,0,1)?new Date(t).toISOString():null;}
function canonical(raw:string){try{const u=new URL(raw);if(!/^https?:$/.test(u.protocol))return"";if(u.protocol==="http:"&&/(assemblee-nationale\.fr)$/i.test(u.hostname))u.protocol="https:";u.hash="";for(const k of [...u.searchParams.keys()])if(/^utm_/i.test(k)||["fbclid","gclid"].includes(k))u.searchParams.delete(k);return u.toString();}catch{return"";}}
function infer(title:string,fallback:string){const t=title.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();if(t.includes("proposition de loi"))return"Proposition de loi";if(t.includes("projet de loi"))return"Projet de loi";if(/\bamendement\b/.test(t))return"Amendement";if(/\bdecret\b/.test(t))return"Décret";if(/\barrete\b/.test(t))return"Arrêté";if(/\bavis\b/.test(t))return"Avis";return fallback;}
async function fetchFeed(src:Source){const c=new AbortController(),timer=setTimeout(()=>c.abort(),9000);try{const r=await fetch(src.url,{headers:{"User-Agent":"Mozilla/5.0 Myvor-Institutional-Feeds/4.0","Accept":"application/rss+xml,application/atom+xml,application/xml,text/xml,*/*","Accept-Language":"fr-FR,fr;q=0.9"},redirect:"follow",cache:"no-store",signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=new Uint8Array(await r.arrayBuffer());if(b.length>3_000_000)throw new Error("flux trop volumineux");const xml=new TextDecoder("utf-8").decode(b);const blocks=[...xml.matchAll(/<(item|entry)\b[^>]*>([\s\S]*?)<\/\1>/gi)].map(m=>m[2]).slice(0,60);const items:Item[]=[];for(const block of blocks){const title=tag(block,["title"]),source_url=canonical(link(block));if(title.length<8||!source_url)continue;const published_at=date(tag(block,["pubDate","published","updated","dc:date","date"]));const desc=tag(block,["content:encoded","content","description","summary"]);const source_text=clip(`[MÉTADONNÉES OFFICIELLES — ${src.name}]\nTitre : ${title}${published_at?`\nDate : ${published_at.slice(0,10)}`:""}${desc?`\nRésumé / contenu du flux : ${desc}`:""}`,MAX_TEXT);if(source_text.length<80)continue;items.push({title,nature:infer(title,src.nature),source_url,source_name:src.name,published_at,source_text});}return items;}finally{clearTimeout(timer);}}
async function store(s:any,items:Item[]){const dedup=[...new Map(items.map(i=>[i.source_url,i])).values()];const{data:targets,error}=await s.rpc("get_veille_ingestion_targets");if(error)throw error;let inserted=0,contentUpserts=0,dateBackfills=0;for(const target of targets||[]){const org=String(target.organization_id),user=String(target.user_id);for(let p=0;p<dedup.length;p+=60){const batch=dedup.slice(p,p+60);const rows=batch.map(i=>({user_id:user,organization_id:org,created_by:user,title:i.title,nature:i.nature,source_url:i.source_url,source_name:i.source_name,published_at:i.published_at,urgency:"moyen"}));const{data:newRows,error:ins}=await s.from("watch_items").upsert(rows,{onConflict:"organization_id,source_url",ignoreDuplicates:true}).select("id");if(ins)throw ins;inserted+=(newRows||[]).length;const urls=batch.map(i=>i.source_url);const{data:known,error:read}=await s.from("watch_items").select("id,source_url,published_at").eq("organization_id",org).in("source_url",urls);if(read)throw read;const byUrl=new Map((known||[]).map((r:any)=>[String(r.source_url),r]));const now=new Date().toISOString(),contents:any[]=[];for(const i of batch){const r:any=byUrl.get(i.source_url);if(!r)continue;if(!r.published_at&&i.published_at){const{error:u}=await s.from("watch_items").update({published_at:i.published_at,source_name:i.source_name}).eq("id",r.id).is("published_at",null);if(!u)dateBackfills++;}contents.push({watch_item_id:String(r.id),organization_id:org,source_text:i.source_text,source_text_chars:i.source_text.length,fetched_at:now,updated_at:now});}if(contents.length){const{error:ce}=await s.from("watch_item_content").upsert(contents,{onConflict:"watch_item_id"});if(ce)throw ce;contentUpserts+=contents.length;}}}return{inserted,content_upserts:contentUpserts,date_backfills:dateBackfills,organizations:(targets||[]).length};}
Deno.serve(async req=>{if(req.method!=="POST")return out({error:"Méthode non autorisée"},405);const url=Deno.env.get("SUPABASE_URL")||"",secret=key();if(!url||!secret)return out({error:"configuration incomplète"},503);const s=createClient(url,secret,{auth:{persistSession:false,autoRefreshToken:false}});if(!await auth(req,s))return out({error:"Non autorisé"},401);const holder=crypto.randomUUID();const{data:lease}=await s.rpc("acquire_veille_worker_lease",{p_worker:"institutional",p_holder:holder,p_seconds:180});if(lease!==true)return out({ok:true,skipped:"already_running"});try{const results=await Promise.allSettled(SOURCES.map(async src=>({src,items:await fetchFeed(src)})));const items:Item[]=[];const health:any[]=[];for(const r of results){if(r.status==="fulfilled"){items.push(...r.value.items);health.push({name:r.value.src.name,count:r.value.items.length,error:null});}else health.push({name:"source",count:0,error:clip((r.reason as any)?.message||r.reason,100)});}const stored=await store(s,items);return out({ok:true,engine:"institutional-feeds-only-v4",sources:SOURCES.length,items_discovered:items.length,health,...stored});}catch(e:any){return out({ok:false,error:clip(e?.message||e,300)},500);}finally{try{await s.rpc("release_veille_worker_lease",{p_worker:"institutional",p_holder:holder});}catch{}}});